### ISSUE TITLE
无法链接电脑， Usb调试一点击就闪退。

### ISSUE THREAD

**Issue by aboucide** [kkevsekk1/AutoX#1005]
1. Autox.js 版本：6.6.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：红米K60
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：VSCODE扩展商店 Ext的最新版
7. 问题描述： App无法连接电脑，无论是无线连接还是数据线连接。手机上面已经开启了 usb调试，也都在一个局域网内。
无线连接没有反应。
数据线连接只要我一点usb调试，app就直接卡死闪退。
所有权限都给了。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by gaomanyi** [comment]
同样的问题。

**Comment by killerddd3** [comment]
同样也碰到了这个问题

**Comment by aboucide** [comment]
没办法使用。

**Comment by remember-5** [comment]
我也是

**Comment by NOWorEVER** [comment]
➕1

**Comment by heyingjiee** [comment]
你好，请问怎么解决的啊
