### ISSUE TITLE
提交代码

### ISSUE THREAD

**Issue by gaomanyi** [kkevsekk1/AutoX#1022]
1. Autox.js version: 6.2.9
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 10
4. Android model: xiaomi 10
5. Android system category: MIUI 11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:
8. Error log (optional):
9. Screenshot (optional):

@kkevsekk1 给我开一下代码上传权限，vscode 连接wifi连接错误已经找到了，android14项目目录识别问题， 布局分析不起作用问题。

**Comment by Dream-668** [comment]
提pr不就好了
