### ISSUE TITLE
保存后文件末尾仍然有多出代码，导致语法错误

### ISSUE THREAD

**Issue by yezie** [kkevsekk1/AutoX#103]
编辑器文中删除字符后，保存时结尾字符异常，文档末尾的原字符仍存在，导致语法错误

**Comment by kkevsekk1** [comment]
手机编辑器，还是vscode 插件？

**Comment by yezie** [comment]
手机编辑器

**Comment by SJ2050cn** [comment]
遇到了同样的问题。

**Comment by rasso1** [comment]
老安卓没事,新版安卓机,
保存时,文档末尾自动随机添加文档内部分代码,造成错误.
临时解决办法,保存时,末尾多加几个//
