### ISSUE TITLE
Autox安装位置

### ISSUE THREAD

**Issue by zaqai** [kkevsekk1/AutoX#1036]
3. Android 版本：Android 14
4. Android 机型：荣耀magic6
5. Android 系统类别：magicos8
7. 问题描述：荣耀这系统真的找不到在哪给文件访问权限，只有照片和视频访问权限，给了也没用，还是读不了根目录下的“脚本”文件夹，创建新文件也创建不了，软件也没有要读取文件的权限，可能是因为荣耀给他报毒了被限制了，所以想问问Autox安装位置，把脚本文件夹改到那里，android/data下没找到autox

**Comment by LYS86** [comment]
importClass(android.net.Uri);
importClass(android.content.Intent);

function test() {
    var intent = new Intent();
    intent.setAction('android.settings.MANAGE_ALL_FILES_ACCESS_PERMISSION');
    intent.putExtra('android.provider.extra.PACKAGE_NAME', context.getPackageName()); 
    app.startActivity(intent);
}

test();

**Comment by zaqai** [comment]
别这么极客，现在新建文件都建
