### ISSUE TITLE
截屏不会根据屏幕旋转

### ISSUE THREAD

**Issue by nfh994** [kkevsekk1/AutoX#1064]
1. Autox.js 版本：665
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：三星S10
5. Android 系统类别：OneUI

问题描述：
如果在竖屏时申请权限images.requestScreenCapture(); 
屏幕旋转为横屏时截图,分辨率仍然是竖屏的分辨率 空白部分是透明的
images.requestScreenCapture()无参数时应该是按照截图时屏幕方向截图 autojs9是这样的

**Comment by Liberations** [comment]
问题是旋转了横屏此时坐标点击又该如何处理呢 原先的图色逻辑也就失效了吧？

**Comment by nfh994** [comment]
> 问题是旋转了横屏此时坐标点击又该如何处理呢 原先的图色逻辑也就失效了吧？

正常应该是根据屏幕方向编写不同逻辑吧
