### ISSUE TITLE
Auto.js-VSCode-Extension 连接不上电脑（app是用的原版，原版extension可以连上）

### ISSUE THREAD

**Issue by freemedom** [kkevsekk1/AutoX#108]
![image](https://user-images.githubusercontent.com/57294686/141603371-65aedc27-a2ec-45c7-bac5-c71365659b40.png)
总是显示这个ip地址，连不上这个地址
原版的是192.168的地址，可以连上

**Comment by freemedom** [comment]
查了查，是不是有问题？，169不是局域网地址啊

**Comment by kkevsekk1** [comment]
你是不是安装了两个插件？

**Comment by kkevsekk1** [comment]
禁用掉以一个插件
