### ISSUE TITLE
如何获取指针位置，并实时记录并输出

### ISSUE THREAD

**Issue by Alanwti** [kkevsekk1/AutoX#1119]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：当我们要截图时每次都要手动点点位置找出指针位置（点两次后再手动输入坐标耗时截图），想封装一个函数，能直接截图（执行函数后，点击截图第一个点执行点击确认后保存第一个截图点位置信息，当第二个截图点搞定后截图返回image），但没有找到能实时获取指针位置的方法。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by xxl-cc** [comment]
在touch事件内，把坐标信息打印出来
   events.on("touch", function (point) {
                let c = colors.toString(images.pixel(captureScreen(), point.x, point.y));
                log("(" + point.x + ", " + point.y + "): " + c);
            });

**Comment by Alanwti** [comment]
收到我的哥
