### ISSUE TITLE
悬浮窗布局范围分析和层次分析失效无法有效识别控件

### ISSUE THREAD

**Issue by Alanwti** [kkevsekk1/AutoX#1120]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：布局范围，和层次分析总是不能有效识别并显示控件，但使用textContains().exists()又有控件，如果用id判断的话（无des），id从何得知。就导致必须使用图片匹配来确定却控件位置，非常耗费手机资源。希望有大佬能解决这个问题。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
找控件的话，推荐使用 https://github.com/gkd-kit/gkd
授权后开启HTTP服务，打开要分析的界面 后保存快照，你可以在网页端刷新看到，鼠标点一下基本就能找到，非常方便

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
找控件的话，推荐使用 https://github.com/gkd-kit/gkd
授权后开启HTTP服务，打开要分析的界面 后保存快照，你可以在网页端刷新看到，鼠标点一下基本就能找到，非常方便

**Comment by Alanwti** [comment]
老哥他是可以快照保存页面页面节点信息，但是怎么可视化显示这些节点控件，是不是还需要第三方然得软件去识别，app的布局页面信息不像浏览器可以直接查看页面代码，真麻烦。官方快照审查也是通过auto.js识别被快照的节点信息啊，问题是auto.js识别不出来所有布局控件。

**Comment by Alanwti** [comment]
看懂了兄弟要将快照文件上传github通过网页才能看
