### ISSUE TITLE
控件使用导致模块方方法不可用

### ISSUE THREAD

**Issue by Alanwti** [kkevsekk1/AutoX#1122]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：控件的使可能导致不可预见的错误
8. 报错日志（可选）：16:53:52.670/E: TypeError: Cannot find function picIsOK in object 3. ([remote]XXXX#111)
TypeError: Cannot find function picIsOK in object 3.
    at searchAndSeeAdNew ([remote]XXXX:111:0)
    at [remote]XXXX:25:0
9. 屏幕截图（可选）：
![捕获](https://github.com/user-attachments/assets/e02ed518-7b4d-456c-8c30-bdf9aa253801)
此处u是导入的工具类模块对象，for循环内部执行的是控件相关代码操作，目的是确定返回有”综合“控件的页面，如果没有注释掉for循环后面的u相关的方法就会报错TypeError: Cannot find function picIsOK in object 3.。for循环以上的u模块对象的方法不受影响。注释掉后，后面u对象的方法可以成功执行。希望了解源码的大佬能解决一下。

**Comment by vtrayy** [comment]
你循环里的u覆盖了u

**Comment by Alanwti** [comment]
收到我靠，写的时候没注意到，排错排了好久难绷。
