### ISSUE TITLE
运行v6的 截屏并保存 的示例代码,软件崩溃无法截图

### ISSUE THREAD

**Issue by xvyanzhen** [kkevsekk1/AutoX#1140]
1. Autox.js 版本：7.0.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：红米k30s
5. Android 系统类别：HyperOS
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：运行v6的截屏并保存的示例代码,软件崩溃无法截图
8. 报错日志（可选）：
[Log_20240816_111814.txt](https://github.com/user-attachments/files/16632520/Log_20240816_111814.txt)

9. 屏幕截图（可选）：
![Screenshot_2024-08-16-11-18-16-383_org autojs aut](https://github.com/user-attachments/assets/ad17c386-e734-407e-9904-221c01b60e6d)

**Comment by aiselp** [comment]
少了个权限

**Comment by duguanfeng** [comment]
> 少了个权限

要如何解决呢, 我们使用者可以手动给这个权限吗
