### ISSUE TITLE
运行一段时间以后引擎自动退出，并没有任何提示

### ISSUE THREAD

**Issue by Lumitx** [kkevsekk1/AutoX#1146]
Autox.js 版本：[6.6.6](https://github.com/kkevsekk1/AutoX/releases/tag/6.6.6)
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 14
Android 机型：小米6
Android 系统类别：lineageos 20
VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
问题描述：
报错日志（可选）：
屏幕截图（可选）：

之前在直播页面看广告也会有这个问题，后来把sleep调高了一些就好了。

今天这个是在主流程加了一个回调的代码，但是运行一段时间以后就程序自动退出，连悬浮窗都没有了。退出以后又弹提示 [autoxjs获取了root权限]

这个程序退出在检索慢的页面做逻辑会大概率发生，例如直播。找一个元素要1秒。

这里的定时任务是切换页面检索一个组件并点击并计算时间再次添加任务。正常运行肯定是没bug的。

```
let claimRewards = function (adTask, timerTask) {
    adTask = adTask || new AdTask()
    timerTask = timerTask || new util.TimerTask();
    // 这里做一个代理机制，将#watchAdIfMatch代理
    print("claimRewards 对watchAdIfMatch 进行代理")
    let _watchAdIfMatch = adTask.watchAdIfMatch
    adTask.watchAdIfMatch = function (block, timeout, context) {
        _watchAdIfMatch.apply(adTask, [block, timeout, context])
        sleep(1000)
        // 加入定时任务检测
        G.info("检测定时任务 ..")
        timerTask.run()
        sleep(1000)
    }

    claimRewards = function (adTask, timerTask) {
        print("claimRewards start")
        // .....
        G.info("doClaim 剩余时间 #", t, " ==> 添加任务")
          timerTask.addTask("doClaim#" + t, () => {
              claimRewards(adTask, timerTask)
          }, t)
    }

    claimRewards(adTask, timerTask)
}
```

**Comment by panghuahua2017** [comment]
> 找到原因了，开了前台服务也因为内存不足被杀掉了。

是因为内存不足吗？我监测了脚本最开始运行，和运行几个小时后，占用内存100M左右，剩余内存500左右。但经常闪退，并且没有任何报错。不知道什么原因。

**Comment by Lumitx** [comment]
> > 找到原因了，开了前台服务也因为内存不足被杀掉了。
> 
> 是因为内存不足吗？我监测了脚本最开始运行，和运行几个小时后，占用内存100M左右，剩余内存500左右。但经常闪退，并且没有任何报错。不知道什么原因。

我的是因为内存不足。
我的运行周期也很久，一次也要几个小时。脚本重复做直播任务，而直播又比较吃内存。内存不足导致程序被杀，开启zram以后再也没碰到了。
