### ISSUE TITLE
7.0.2版本中获取应用列表只能拿到系统预装应用，第三方安装应用找不到，导致launchApp不生效

### ISSUE THREAD

**Issue by vikiea** [kkevsekk1/AutoX#1147]
1. Autox.js 版本：702
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米11 ultra
5. Android 系统类别：hyperOS
6. 问题描述：获取应用列表只能拿到系统预装应用，第三方安装应用找不到，导致launchApp不生效。
launchApp("应用商店")可以正常跳转
launchApp("猫眼")无法跳转
通过pm.getInstalledApplications(0);打印应用列表，找不到“猫眼”程序

**Comment by lining1209** [comment]
您好 找到解决方法了吗 我也遇到了同样的问题

**Comment by aiselp** [comment]
使用包名应该没有这个限制

**Comment by XcantloadX** [comment]
> 使用包名应该没有这个限制

用包名貌似也不行
```js
console.show(true)
console.log(app.launchApp('浏览器'))
console.log(app.launch('com.android.browser'))

console.log(app.launchApp('微信'))
console.log(app.launch('com.tencent.mm'))
console.log(app.launchPackage('com.tencent.mm'))
```
结果：
```
true
true
false
false
false
```

Autox.js 6.6.4，红米 Note 12 Turbo，MIUI 14.0.23，Android 13

**Comment by QC2168** [comment]
我也遇到了这个问题

**Comment by QC2168** [comment]
autoXjs [7.0.2 ](https://github.com/kkevsekk1/AutoX/releases/tag/7.0.2)有效
```js
app.startActivity({
  packageName: "com.taobao.idlefish",
  className: "com.taobao.fleamarket.home.activity.InitActivity"
});
```
