### ISSUE TITLE
Google ML kit OCR PaddleOcr TesseractOCR 代码例子可以在 autoxjs里运行，但是打包后运行直接闪退

### ISSUE THREAD

**Issue by real-cool** [kkevsekk1/AutoX#1148]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14 android 12
4. Android 机型：红米 k60 ultra,blueStacks（蓝叠） 模拟器
5. Android 系统类别：
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：代码例子可以在 autoxjs里运行，但是打包后运行直接闪退
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by real-cool** [comment]
autox 版本 667 658及 702版本都试过了都不行，

**Comment by real-cool** [comment]
上面写错了的点是 paddle ocr 不过是在 autox app里 还是打包后 都无法运行，

**Comment by real-cool** [comment]
找到问题了，通过 engine.execScriptFile()方式才能打包运行。

**Comment by richer0718** [comment]
> 找到问题了，通过 engine.execScriptFile()方式才能打包运行。

请问可以说的详细一点吗，我也遇到了这个问题
