### ISSUE TITLE
7.02无法使用adb shell 通过广播运行脚本

### ISSUE THREAD

**Issue by poweryu** [kkevsekk1/AutoX#1149]
1. Autox.js 版本：7.02
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：鸿蒙2.0
4. Android 机型：荣耀20 PRO
5. Android 系统类别：鸿蒙
6. 问题描述：
* 在app端正常运行的脚本，在电脑端使用adb shell 调用autox运行脚本时报错提示：“无法处理文件”。而autoxV6版本使用adb shell 调用autox正常运行脚本。

```
 adb shell am start -n org.autojs.autoxjs.v7/org.autojs.autojs.external.open.RunIntentActivity file:///storage/emulated/0/脚本/test.js
```
*  说明：已经在app设置中打开“允许使用广播运行脚本“。
7. 报错日志（可选）：
8. 屏幕截图（可选）：
![SVID_20240821_233626 00_00_04 20240821-233752](https://github.com/user-attachments/assets/e3999656-6894-41ca-9ee3-667fe58483c9)

**Comment by aiselp** [comment]
命令有错，uri需要作为data传入

**Comment by poweryu** [comment]
命令是改成这样吗？运行还是报同样的错误
```
adb shell am start -n org.autojs.autoxjs.v7/org.autojs.autojs.external.open.RunIntentActivity -d file:///storage/emulated/0/脚本/test.js -t text/javascript
```
在autox.js 中调用也报同样的错误，同样的代码在v6版本中正常
```
app.startActivity({
    packageName:"org.autojs.autoxjs.v7",
    data:"file:///storage/emulated/0/脚本/demo.js",
   className:"org.autojs.autojs.external.open.RunIntentActivity"
})
```

**Comment by aiselp** [comment]
测试了一下确实会弹出一个错误提示，下次更新会尝试修复
