### ISSUE TITLE
无障碍服务events.on事件响应存在问题

### ISSUE THREAD

**Issue by yuiru64** [kkevsekk1/AutoX#115]
如图，按下按键随后松开按键，存在key_down事件重复了两遍，key_down/key_up事件响应顺序不对的情况。经测试，按下和松开按键的时间间隔足够长时才没有这个问题。
```
events.on("key_up", (keyCode, event) => {
    console.log(event)
});
events.on("key_down", (keyCode, event) => {
    console.log(event)
});
```
![Screenshot_20211205_121428](https://user-images.githubusercontent.com/18999026/144733519-a72c9fd3-d30b-4b04-b2c7-8e428183d324.jpg)
![Screenshot_20211205_121619](https://user-images.githubusercontent.com/18999026/144733524-5f9ee609-0dfe-46d4-a93a-806f4430d2dd.jpg)

**Comment by kkevsekk1** [comment]
没时间测试，是不是和事件分发冲突
