### ISSUE TITLE
在"ui";定义组件，如何不使用ui.${id}的情况下获取组件

### ISSUE THREAD

**Issue by xchd** [kkevsekk1/AutoX#1151]
1. Autox.js 版本：6.6.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：MuMu
5. Android 系统类别：MuMu
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：在`"ui";<linear  id="container"></linear >`**动态**添加了`<input id="i1"> <input id="i2">,<input id="i.....">`，使用`id("container").findOnce();`方法获取是null，我想获取动态添加的input的text，应该如何实现。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by fanlushuai** [comment]
重新加载一遍？
