### ISSUE TITLE
app部分需求点击处，click(）等手势模拟点击失效，adb 投屏的鼠标点击和物理点击依然生效

### ISSUE THREAD

**Issue by Alanwti** [kkevsekk1/AutoX#1165]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：app部分需求点击处，click(）等手势模拟点击失效，adb 投屏的鼠标点击和物理点击依然生效。autox.js的点击原理和adb加scrcpy的鼠标点击原理有何不同，都不是真实的物理点击。猜测app可能添加了，脚本点击的检测，但是adb 鼠标点击依然生效证明是可以代码模拟的，有没有懂Android和autox.js源码的大佬解决一下这个问题，十分感谢。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by 1195343015** [comment]
老哥是不是在搞大麦，我大麦点击就出现了这个问题。我感觉是app为了防止脚本点击，可能会判断用户点击按钮时的touchdown,touchmove,touchup操作，而单纯调用`click()`是可以被app过滤掉的。

**Comment by Tie-Tie** [comment]
在无障碍中设置点击时长，短、中、长，一个个尝试过去就行了，我就是这样的
