### ISSUE TITLE
在循环中使用random生成随机数，每次都是第一次生成的数据

### ISSUE THREAD

**Issue by sudot** [kkevsekk1/AutoX#1166]
1. Autox.js 版本：702
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K30S Ultra
5. Android 系统类别：MIUI14.0.5
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：

在循环中调用 `random` 函数，虽然每个 `random` 函数生成的值是不同的，但是第二次循环开始，后面的每次循环生成的随机数都是第一次生成的随机数结果，代码如下：
```
let xx = 0;
while (true) {
  const index = random(0, coordinates.length);
  const duration = random(100, 300);

  const coordinate = coordinates[index];
  gesture(duration, coordinate);

  const time = random(3, 8);
  console.log(duration, index, time, new Date().getTime());
  sleep(time * 1000);
  xx++;
  if (xx > 3) break;
}
```

生成的随机数如下，可以看到4次循环，每一次生成的都一样：
```
17:55:28.974/D: 239 0 7 1724925328973（这是第一次循环生成的随机数）
17:55:36.229/D: 239 0 7 1724925336219（这是第二次循环生成的随机数）
17:55:43.494/D: 239 0 7 1724925343482（这是第三次循环生成的随机数）
17:55:50.755/D: 239 0 7 1724925350741（这是第四次循环生成的随机数）
```
![image](https://github.com/user-attachments/assets/1956b900-0eb5-4182-96de-632860db9e58)

自己用时间戳的方式生成随机数，然后发现方法每次都会执行，方法内的生成数据也正常，但是返回值却又变成一模一样了。
```

function getRandomInt(min, max) {
  const num = new Date().getTime() % (max - min);
  console.log("getRandomInt", num, min + num, new Date().getTime());
  return min + num;
}

let xx = 0;
while (true) {
  const index = getRandomInt(0, coordinates.length);
  const duration = getRandomInt(100, 300);

  const coordinate = coordinates[index];
  gesture(duration, coordinate);

  const time = getRandomInt(3, 8);
  console.log(duration, index, time, new Date().getTime());
  sleep(time * 1000);
  xx++;
  if (xx > 3) break;
}
```

![image](https://github.com/user-attachments/assets/73e4a4f3-a8f2-4ffc-b4c9-d20428733f99)

9. 报错日志（可选）：
10. 屏幕截图（可选）：
![image](https://github.com/user-attachments/assets/1956b900-0eb5-4182-96de-632860db9e58)

![image](https://github.com/user-attachments/assets/76d1c80f-0364-4480-be74-165ad0655665)

**Comment by sudot** [comment]
卧槽，把定义变量的关键字 `const` 改成 `let` 就行了，这骚操作很不符合直觉啊。这个 ISSUE 留着给大家当 FAQ 吧。

```
let xx = 0;
while (true) {
  let index = random(0, coordinates.length);
  let duration = random(100, 300);

  let coordinate = coordinates[index];
  gesture(duration, coordinate);

  let time = random(3, 8);
  console.log(duration, index, time, new Date().getTime());
  sleep(time * 1000);
  xx++;
  if (xx > 3) break;
}
```

![image](https://github.com/user-attachments/assets/172b6f68-30be-48c6-9d3e-b2d31380fd27)

**Comment by sunboye** [comment]
哈哈  我开始也是const  出现一些奇怪的问题，最后全换成let了
