### ISSUE TITLE
v7版本开定时任务闪退崩溃

### ISSUE THREAD

**Issue by ruoerxi** [kkevsekk1/AutoX#1169]
1. Autox.js 版本：[7.0.2](https://github.com/kkevsekk1/AutoX/releases/tag/7.0.2)
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：redmi k40
5. Android 系统类别：MIUI
6. 问题描述：点击定时任务 autox.js 闪退 创建不了定时任务

**Comment by Lvbey** [comment]
xiaomi 14 pro + 1
