### ISSUE TITLE
[功能请求]申请为AutoX添加一个 android.permission.READ_LOGS 的权限

### ISSUE THREAD

**Issue by PianCat** [kkevsekk1/AutoX#1172]
1. Autox.js 版本：702
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：华为MatePad 11
5. Android 系统类别：HarmonyOS4.2
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：
    在使用 AutoX 运行 SyncClipboard 所提供的[脚本](https://github.com/Jeric-X/SyncClipboard/blob/master/script/SyncAutoxJs.js)时，需要 android.permission.READ_LOGS 权限，但是AutoX本身并没有申请，请问可否如[Tasker一样提供](https://tasker.joaoapps.com/userguide/en/help/ah_read_logs_grant.html)一个给用户进行手动申请的权限声明？

**Comment by aiselp** [comment]
这个权限属于系统应用才有效，声明了也没用
