### ISSUE TITLE
循环中的 const 关键字定义的变量值不正确

### ISSUE THREAD

**Issue by pansong291** [kkevsekk1/AutoX#1178]
1. Autox.js 版本：7.0.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：Asus ROG 3
5. Android 系统类别：Asus-user
6. 问题描述：

代码：
```js
for (let i = 0; i < 5; i++) {
    const j = i + 1;
    console.log(`${i}, ${j}`)
}
```
结果：
```
0, 1
1, 1
2, 1
3, 1
4, 1
```
预期：
```
0, 1
1, 2
2, 3
3, 4
4, 5
```

**Comment by pansong291** [comment]
Rhino 的远古问题，https://github.com/mozilla/rhino/issues/939

**Comment by Bob8259** [comment]
你把const 改成var或者let就可以解决
