### ISSUE TITLE
http模块不支持本地局域网请求吗

### ISSUE THREAD

**Issue by luscio** [kkevsekk1/AutoX#1213]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：vivo x21a
5. Android 系统类别：funtouch os_9
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by Liberations** [comment]
支持 你的防火墙记得关了。
