### ISSUE TITLE
无法安装、packgeinfo is null、6.6.7、v7等 6.5.8 以后的所有版本

### ISSUE THREAD

**Issue by Tie-Tie** [kkevsekk1/AutoX#1214]
1. Autox.js 版本：658以后的所有版本
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14、鸿蒙2、安卓9
4. Android 机型：redmi k40、荣耀play
5. Android 系统类别：MIUI

6.5.8以后的所有版本都无法打包后安装，我非常想要知道这是为什么，或者有什么其他的解决方案，任何一个示例代码打包后都是无法安装的，我查阅了大量论坛。都找不出想要的答案，请作者出面讲解一下为什么。安装的时候会提示packgeinfo is null，鸿蒙2可以安装，但是安装后闪退。

**Comment by 957398123** [comment]
好多bug，我真的无语了。模拟器用的是BlueStacks，什么新编辑模式直接空白，其实根本就不需要这种东西，对于功能性来说，要的是功能，比如更强大的api。。。。
还有就是创建项目也是，我真的好无语。好多bug

**Comment by dou4767** [comment]
> 好多bug，我真的无语了。模拟器用的是BlueStacks，什么新编辑模式直接空白，其实根本就不需要这种东西，对于功能性来说，要的是功能，比如更强大的api。。。。 还有就是创建项目也是，我真的好无语。好多bug

你可以自己修改源码,也可以理性的发现问题提出作者修改的思路和方向, 单纯的发泄情绪有什么意义,这是一个免费开源的软件,你选择免费开源的原因你自己清楚

我这里有一瓶奶,你赶紧喝上堵着你的小嘴儿, 甜蜜的巨婴
