### ISSUE TITLE
最新版本打包后的应用无法安装

### ISSUE THREAD

**Issue by Marchen-zcl** [kkevsekk1/AutoX#1223]
1. Autox.js 版本：7.0.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米14
5. Android 系统类别：澎湃
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：最新版本打包后的应用无法安装，v7版本安装报错read failed: EISDIR (Is a directory)，v6版本安装报错packageinfo is null
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![image](https://github.com/user-attachments/assets/be39463b-bd86-4159-ae9d-215e19b74517)

**Comment by Momozxm** [comment]
需要优化，用MT管理器优化一，4K对齐
