### ISSUE TITLE
Autox 7.0.4 版本 ，mqtt demo运行异常退出 MqttAndroidClient.java:111

### ISSUE THREAD

**Issue by acoderleex** [kkevsekk1/AutoX#1241]
1. Autox.js 版本：704
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：华为 TAS-AL00
5. Android 系统类别：HarmonyOS 4.2.0
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

异常日志如下

设备信息: 
App version: 7.0.4
App version code: 704
Android build version: 104.2.0.120SP1C00
Android release version: 
Android SDK version: 31
Android build ID: TAS-AL00 4.2.0.120(SP1C00E100R6P4)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWTAS
Device model: TAS-AL00
Device product name: TAS-AL00
Device hardware name: kirin990
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2332)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2365)
android.os.Handler.handleCallback(Handler.java:966)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:293)
android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
android.app.ActivityThread.main(ActivityThread.java:9975)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

**Comment by aiselp** [comment]
依赖库的问题，参考https://github.com/eclipse/paho.mqtt.android/issues/500

**Comment by acoderleex** [comment]
多谢
