### ISSUE TITLE
打包失败，错误信息：Process exited with an error: 1 (Exit value: 1)

### ISSUE THREAD

**Issue by markixy** [kkevsekk1/AutoX#1244]
1. Autox.js 版本：7.0.4
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米11T PRO（！使用蓝叠模拟器里的机型！）
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：打包失败，页面提示”打包失败，错误信息：Process exited with an error: 1 (Exit value: 1)“
8. 报错日志：（电脑cmd用adb logcat打印的日志）
10-25 10:44:54.130  3237  4148 I System.out: Loaded.
10-25 10:44:54.130  3237  4148 I System.out: Decoding values */* XMLs...
10-25 10:44:54.191  3237  4148 I System.out: txtTranslated: Powered by Autoxjs.com
10-25 10:44:54.191  3237  4148 I System.out: txtTranslated: 使脚本自动操作(点击、长按、滑动等)所需，若关闭则只能执行不涉及自动操作的脚本。
10-25 10:44:59.866  2005  5381 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS www.google.com 0ms OK 31.13.106.4
10-25 10:44:59.866  2005  5382 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS connectivitycheck.gstatic.com 1ms OK 203.208.43.66
10-25 10:45:00.007  2005  5382 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_HTTP http://connectivitycheck.gstatic.com/generate_204 time=141ms ret=204 request={User-Agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.32 Safari/537.36]} headers={null=[HTTP/1.1 204 No Content], Content-Length=[0], Cross-Origin-Resource-Policy=[cross-origin], Date=[Fri, 25 Oct 2024 02:45:00 GMT], X-Android-Received-Millis=[1729824300007], X-Android-Response-Source=[NETWORK 204], X-Android-Selected-Protocol=[http/1.1], X-Android-Sent-Millis=[1729824299917]}
10-25 10:45:09.625  5334  5388 I GMS_MM_Logger: Memory Metric Logging not allowed. Stopping.
10-25 10:45:09.878  2005  5381 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_HTTPS https://www.google.com/generate_204 Probe failed with exception java.net.SocketTimeoutException: failed to connect to /31.13.106.4 (port 443) from /10.0.2.15 (port 55640) after 10000ms
10-25 10:45:11.790  5391  5391 I /sbin/modprobe: Parsing file /system/etc/modules.blacklist...
10-25 10:45:11.790  5391  5391 I /sbin/modprobe: Parsing file /system/lib/modules/4.19.195/modules.alias...
10-25 10:45:11.790  5391  5391 E ProbeModule: insmod_by_dep: cannot load module: [binfmt-464c]
10-25 10:45:11.790  5391  5391 W /sbin/modprobe: failed to load binfmt-464c: No such file or directory
10-25 10:45:11.793  3237  5394 W System.err: /data/app/org.autojs.autoxjs.v7-UtmBVinPwIjio098ZCOyvw==/lib/arm64/lib_bin_aapt2.so[27]: syntax error: unexpected '('
10-25 10:45:11.800  3237  3237 E BuildActivity: Build failed
10-25 10:45:11.800  3237  3237 E BuildActivity: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at com.aiselp.autox.apkbuilder.AAPT_Util.aapt2Optimize(AAPT_Util.kt:31)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.autojs.autojs.build.ApkBuilder$sign$2.invokeSuspend(ApkBuilder.kt:321)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.autojs.autojs.build.ApkBuilder$sign$2.invoke(Unknown Source:8)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.autojs.autojs.build.ApkBuilder$sign$2.invoke(Unknown Source:4)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.autojs.autojs.build.ApkBuilder.sign(ApkBuilder.kt:314)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at org.autojs.autojs.build.ApkBuilder$sign$1.invokeSuspend(Unknown Source:19)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
10-25 10:45:11.800  3237  3237 E BuildActivity:         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
10-25 10:45:11.804  2785  2785 D NotificationObserver: onNotification: [打包失败，错误信息：Process exited with an error: 1 (Exit value: 1)]; EventType: TYPE_NOTIFICATION_STATE_CHANGED; EventTime: 647347; PackageName: org.autojs.autoxjs.v7; MovementGranularity: 0; Action: 0; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: android.widget.Toast$TN; Text: [打包失败，错误信息：Process exited with an error: 1 (Exit value: 1)]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: false; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0
10-25 10:45:11.814  1846  2806 D gralloc_default: gralloc_alloc: Creating ashmem region of size 192512
10-25 10:45:11.818  1846  2806 I chatty  : uid=1000(system) Binder:1846_5 identical 1 line
10-25 10:45:11.819  1846  2806 D gralloc_default: gralloc_alloc: Creating ashmem region of size 192512
10. 屏幕截图（可选）：
![7a68f84748e3b501bf707a9aee6a892](https://github.com/user-attachments/assets/5b134b0f-ffbc-42c2-b4a1-a579addc17ad)

**Comment by aiselp** [comment]
为减小应用体积，不支持在x86模拟上打包

**Comment by markixy** [comment]
6.6.7 版本可行
