### ISSUE TITLE
一旦设置了setWebViewClient后就监听不到js方法了，求解决

### ISSUE THREAD

**Issue by vaecou** [kkevsekk1/AutoX#1265]
1. Autox.js 版本：660
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：一旦设置了setWebViewClient后就监听不到js方法了，求解决

**Comment by vaecou** [comment]
ui.webview.setWebViewClient(new JavaAdapter(android.webkit.WebViewClient, {

}));

使用上面的setWebViewClient之后
下面的registerHandler监听就会失效

ui.webview.jsBridge.registerHandler("data", (data) => {
	console.log(data)
	threads.start(function () {
		engines.execScript("data", data);
	});
});

**Comment by aiselp** [comment]
每次加载新页面后需要调用webview.injectionJsBridge()，修改了默认WebViewClient后就只能由自己手动调用

**Comment by vaecou** [comment]
> 每次加载新页面后需要调用webview.injectionJsBridge()，修改了默认WebViewClient后就只能由自己手动调用

非常非常非常感谢，按照您的方法，已经成功解决这个问题了
