### ISSUE TITLE
定时单次运行的bug

### ISSUE THREAD

**Issue by heham** [kkevsekk1/AutoX#138]
定时单次运行，选择日期比如下一天，确定后程序崩溃，原来的4.11也存在这个bug。

**Comment by kkevsekk1** [comment]
这个功能，建议还是 依赖 外部环境来，主要是android 各种版本，各种环境，各种机型都有差异，完全做到无人值守几乎是件不可能完成的任务

**Comment by heham** [comment]
> 

不是功能的问题，是程序崩溃，这个bug在手机和模拟器上都存在，测试过某个7.0pro版没有这个问题

**Comment by kkevsekk1** [comment]
刚刚刚测试，定时任务--每天运行，10:40 ，到时间允许了，没有发生崩溃啊 o(╥﹏╥)o

**Comment by heham** [comment]
> 刚刚刚测试，定时任务--每天运行，10:40 ，到时间允许了，没有发生崩溃啊 o(╥﹏╥)o

不是每天运行，单次运行，然后选一下日期比如明天或者后天什么的就崩溃了，我这里真机和模拟器都这样的，这个bug在原来版老的4.11也存在
