### ISSUE TITLE
想加ocr可以把百度的Paddle-Lite直接拿过来用

### ISSUE THREAD

**Issue by q751654992** [kkevsekk1/AutoX#148]
日常向大佬问好
过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的

我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右
比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核

**Comment by kkevsekk1** [comment]
应该用 dev 分支，master 没有用了， 如果有界面，你在ui线程里，耗时操作界面会出现无响应。无论你是在java 或 autojs 中，都应该在非ui线程，里去做这个事情，ui线程只是返回结果。

**Comment by kkevsekk1** [comment]
cpu应该没有 大小核吧？这识别是不是本身就是 多线程任务？

**Comment by kkevsekk1** [comment]
PaddleOCR 传闻可以集成的嘛

**Comment by q751654992** [comment]
使用dev或者master对我测试ocr的功能应该没有影响吧
对于ocr,  我的使用场景是在京东首页,执行js脚本, 并没有把js打包成apk, 我需要拿到首页的识别文字信息, 这是一个同步的操作, 不知道你说的ui线程是不是指autojs打包的apk ui

手机的cpu还是大小核分的,  orc的识别也可以开启多线程,   我测试的时候 开的4个线程

**Comment by kkevsekk1** [comment]
测试 影响， UI线程 是指，你写大脚板如果 第一句话是“ui”; 并且，你的识别任务 没有写在 用 threads.start()这里，那你就是在UI线程，
这还的看你启动的个任务是同步任务，还是异步任务。你可以设置线程数等于的cpu核数

**Comment by q751654992** [comment]
> PaddleOCR 传闻可以集成的嘛

没看懂什么意思   PaddleOCR使用主要还是PC端  移动端还是得用Paddle-Lite

**Comment by kkevsekk1** [comment]
> > PaddleOCR 传闻可以集成的嘛
> 
> 没看懂什么意思 PaddleOCR使用主要还是PC端 移动端还是得用Paddle-Lite

具体没研究过 O(∩_∩)O哈哈~

**Comment by q751654992** [comment]
没有启动ui界面  

> 测试不影响， UI线程 是指，你写大脚板如果 第一句话是“ui”; 并且，你的识别任务 没有写在 用 threads.start()这里，那你就是在UI线程， 这还的看你启动的个任务是同步任务，还是异步任务。你可以设置线程数等于的cpu核数

没用异步  代码也很简单 线程数等于的cpu核数 这我到没试, 估计效率提升也不大,  lite绑cpu也可以会失败, 线程数太多绑核失败也会减低性能,  愁  这本地orc识别起来还不如调百度api快

js主要代码就下面, ocrImg是我自己加的方法, java代码主要逻辑就是截屏,调orc识别
var a = new Date();
ocrImg()
console.log("shijian 1", new Date()-a);

**Comment by heham** [comment]
关于OCR我这里到是有两个库文件是别人程序里的，没有研究怎么调用，但是肯定是可以用的libncnn.so，libOcrLite.so，这里不知道怎么上传

**Comment by kkevsekk1** [comment]
so 是linux的一种 库，要用到android开发 jni \(^o^)/~

**Comment by heham** [comment]
> 

这两个库就是别人用在安卓上的

**Comment by kkevsekk1** [comment]
https://gitee.com/computer-vision/Paddle-Lite
https://paddle-lite.readthedocs.io/zh/latest/quick_start/release_lib.html#android
按这个资料搞

**Comment by Aioure** [comment]
> 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的
> 
> 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核

5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。

**Comment by q751654992** [comment]
> > 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的
> > 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核
> 
> 5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。

看了一下  和我用的差不多，只是用的nb文件不一样
新版的app试了下  识别不出来，全是  xxxxx
你放的nb文件是不是有问题

**Comment by Aioure** [comment]
> > > 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的
> > > 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核
> > 
> > 
> > 5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。
> 
> 看了一下 和我用的差不多，只是用的nb文件不一样 新版的app试了下 识别不出来，全是 xxxxx 你放的nb文件是不是有问题

nb文件是下载自官网页面中的中文移动端模型v2.0（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/lite）
不知道你识别哪个图片或页面出的问题？

**Comment by q751654992** [comment]
我是截图屏幕，再识别的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kkevsekk1/AutoX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 晚上9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148)





    
日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的
 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核
  
5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。
  
看了一下 和我用的差不多，只是用的nb文件不一样 新版的app试了下 识别不出来，全是 xxxxx 你放的nb文件是不是有问题
  
nb文件是下载自官网页面中的中文移动端模型v2.0（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/lite）
 不知道你识别哪个图片或页面出的问题？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aioure** [comment]
> 我是截图屏幕，再识别的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kkevsekk1/AutoX" ***@***.***&gt;; 发送时间:&nbsp;2022年1月16日(星期天) 晚上9:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148) 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核 5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。 看了一下 和我用的差不多，只是用的nb文件不一样 新版的app试了下 识别不出来，全是 xxxxx 你放的nb文件是不是有问题 nb文件是下载自官网页面中的中文移动端模型v2.0（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/lite） 不知道你识别哪个图片或页面出的问题？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不知道能否提供出错的图片以及控制台日志的相关信息？以便能够定位问题所在

**Comment by Aioure** [comment]
> 我是截图屏幕，再识别的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kkevsekk1/AutoX" ***@***.***&gt;; 发送时间:&nbsp;2022年1月16日(星期天) 晚上9:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148) 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核 5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。 看了一下 和我用的差不多，只是用的nb文件不一样 新版的app试了下 识别不出来，全是 xxxxx 你放的nb文件是不是有问题 nb文件是下载自官网页面中的中文移动端模型v2.0（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/lite） 不知道你识别哪个图片或页面出的问题？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

刚测试了一下代码界面的截屏识别，确实存在一小部分字符识别错误显示为x的，不过那是OCR引擎都会有的精度问题，不知道你那边怎么会识别出全是 xxxxx 的？

**Comment by q751654992** [comment]
var we = paddle.ocrImage(captureScreen(), 4);
log(we)
we.words.forEach(element =&gt; {
&nbsp; &nbsp; log(element.text)
});



识别后输出全是 xxxx
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kkevsekk1/AutoX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148)





  
我是截图屏幕，再识别的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kkevsekk1/AutoX" @.&gt;; 发送时间:&nbsp;2022年1月16日(星期天) 晚上9:07 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148) 日常向大佬问好 过来是想问下有没有比较好用的ocr, 在后台识别的时候效率不错的 我基于AutoX master的代码, 把百度飞浆里面的ocr加进去了, 测试了下识别效果, 虽然能识别,但是速度还是有点慢,4s左右 比不上直接使用Paddle-Lite的识别效果, 2s左右, 初步猜测是因为在非autoJs的界面, 识别的线程绑不上cpu大核,只能绑小核 5.6.1版已集成PaddleOCR，性能应该和paddle lite直接使用差不多。欢迎测试反馈bug。 看了一下 和我用的差不多，只是用的nb文件不一样 新版的app试了下 识别不出来，全是 xxxxx 你放的nb文件是不是有问题 nb文件是下载自官网页面中的中文移动端模型v2.0（https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.4/deploy/lite） 不知道你识别哪个图片或页面出的问题？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
不知道能否提供出错的图片以及控制台日志的相关信息？以便能够定位问题所在
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aioure** [comment]
> var we = paddle.ocrImage(captureScreen(), 4); log(we) we.words.forEach(element =&gt; { &nbsp; &nbsp; log(element.text) });

在主屏幕测试了下，截屏识别结果正常，无法重现问题，不知道你能否换个界面（如文字比较多的）测试一下，看是否还有全部识别错误的问题？

**Comment by q751654992** [comment]
再次做了测试，这次结果很奇怪，能正常识别了
不过返回的文本还是要处理下，都是一个字符就换行了, 比如识别出来的去完成是
去
完
成




可以参照百度api返回格式，我就是这么干的，能够在百度api和本地ocr中来回切换


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kkevsekk1/AutoX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kkevsekk1/AutoX] 想加ocr可以把百度的Paddle-Lite直接拿过来用 (Issue #148)





  
var we = paddle.ocrImage(captureScreen(), 4); log(we) we.words.forEach(element =&gt; { &nbsp; &nbsp; log(element.text) });
  
在主屏幕测试了下，截屏识别结果正常，无法重现问题，不知道你能否换个界面（如文字比较多的）测试一下，看是否还有全部识别错误的问题？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
