### ISSUE TITLE
建议开放脚本市场，以便吸引更多用户

### ISSUE THREAD

**Issue by Aioure** [kkevsekk1/AutoX#151]
现在的脚本市场需要登录才能浏览，首次登录还要邀请码，操作过于麻烦，建议开放市场，提供免登录浏览市场及快速注册功能（以便上传或下载脚本）。可以为那些有自动化需求 但自身不是开发者的用户提供更好的服务。而且，只有用户增加了，才能吸引更多开发者加入到AutoX的开发完善中。初步建议可以把示例这一块的脚本（有些完成度已经很高）都放到脚本市场中，以丰富市场的脚本数量。

**Comment by kkevsekk1** [comment]
最近没太多时间搞，几乎停滞状态

**Comment by Aioure** [comment]
> 最近没太多时间搞，几乎停滞状态

没时间没办法，不过能不能先把登录限制去掉，要不用户连脚本市场什么样子都看不到……

**Comment by kkevsekk1** [comment]
你哪个 mini 版本 升级到21 很大概率会出 兼容性bug，建议用兼容性写法，低于21 不让使用此功能

用这个
  ScriptRuntime.requiresApi(21);


``` java
public static void requiresApi(int i) {
        if (Build.VERSION.SDK_INT < i) {
            throw new ScriptException(GlobalAppContext.getString(R.string.text_requires_sdk_version_to_run_the_script) + SdkVersionUtil.sdkIntToString(i));
        }
    }
```

**Comment by Aioure** [comment]
> 

升级到21只是因为gradle编译时报错，说引入的openCV4的包最低api21与原项目冲突，要不你修改试试，能编译通过就行
