### ISSUE TITLE
大佬能不能，像图片缩放代码编辑页面，编写时不停切换字体大小，太麻烦了，效率太低！

### ISSUE THREAD

**Issue by ZhengchaoCao** [kkevsekk1/AutoX#152]

**Comment by Aioure** [comment]
AutoX的编辑界面确实比较不方便，不过大佬最近没太多时间，你可以自己实现并PR，或者看看还有没有其它改善的建议，可以一起提出，我尝试实现一个……

**Comment by Aioure** [comment]
自动换行暂时实现不了，先增加字体缩放的快捷按钮，你看能不能用？

**Comment by ZhengchaoCao** [comment]
新版有吗亲，，，我去试试

**Comment by CuteLicense** [comment]
> 自动换行暂时实现不了，先增加字体缩放的快捷按钮，你看能不能用？

字体大小设置后不能保存，每次编辑都要设置一遍。
另外，如果删行后保存的话，然后在最后行多出几个 }} 括号来，有些括号还是在编辑器里面看不到的，但是一运行就报错

**Comment by Aioure** [comment]
> 字体大小设置后不能保存，每次编辑都要设置一遍。 另外，如果删行后保存的话，然后在最后行多出几个 }} 括号来，有些括号还是在编辑器里面看不到的，但是一运行就报错

字体大小设置已修复（PR中……），多出 }} 括号问题我这边测试时没有出现，不知道是每次删行保存都会出现这个问题，还是只有个别文件或偶尔出现？
