### ISSUE TITLE
一些优化以及建议

### ISSUE THREAD

**Issue by Aioure** [kkevsekk1/AutoX#159]
补充完善7zip的api，OCR结果优化（去除多余换行，兼容百度OCR的api格式），编辑界面添加字体缩放快捷键（自动换行没有成功……）
另外，还是建议要有一个可以共享脚本的地方，就算不开放脚本市场，也可以直接让用户提交到GitHub页面，app上只要能打开网页查看就行

**Comment by kkevsekk1** [comment]
可以，类似与，vscode 插件一样，开发完成后，上传。用户从插件市场，点击安装，就可以可以运行，

**Comment by kkevsekk1** [comment]
模板app，被重新打包后，AndroidManifest.xml 中有哪些权限配置，可以考虑实现一下，

**Comment by CuteLicense** [comment]
OCR 速度慢啊， 这个https://gitee.com/yashujs/autojs-easyedge-nodejs用的是 1.1的，速度比2.x的快
同样的一张图片，用这个集成的 1.7-2.3秒 ，调用autojs-easyedge-nodejs这个基本在1秒以内，差异明显。看能不能再优化一下或调整一下相关参数

**Comment by CuteLicense** [comment]
比方说这些参数放出来给我们自行配置 enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False

**Comment by Aioure** [comment]
> OCR 速度慢啊， 这个[https://gitee.com/yashujs/autojs-easyedge-nodejs用的是](https://gitee.com/yashujs/autojs-easyedge-nodejs%E7%94%A8%E7%9A%84%E6%98%AF) 1.1的，速度比2.x的快 同样的一张图片，用这个集成的 1.7-2.3秒 ，调用autojs-easyedge-nodejs这个基本在1秒以内，差异明显。看能不能再优化一下或调整一下相关参数

旧版的会不会识别准确率低一点？另外除了OCR不同版本识别的时间差异，autojs-easyedge-nodejs用的V8引擎在执行性能上也是比Rhino快了一个数量级。不过v2版的提供了普通版与slim版两种模型，目前用的是普通版（速度慢一点，但准确率更高），可以尝试增加一个slim版的选项，看看速度能不能有所提升

**Comment by Aioure** [comment]
> 比方说这些参数放出来给我们自行配置 enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False

这些参数是哪里设置的？paddleOCR的Android源码中没有看到……

**Comment by CuteLicense** [comment]
> > 比方说这些参数放出来给我们自行配置 enable_mkldnn=True, use_tensorrt=True, use_angle_cls=False
> 
> 这些参数是哪里设置的？paddleOCR的Android源码中没有看到……

这些应该可能是pc端的，我用pc端或docker有这些参数
