### ISSUE TITLE
SAF api

### ISSUE THREAD

**Issue by skbeh** [kkevsekk1/AutoX#162]
如题，Android 10 及以上如果想访问 Android/data 必须使用 SAF，建议提供 JS api 用于 SAF 权限申请和文件操作

**Comment by kkevsekk1** [comment]
你访问 这个目录下自己应用对应的目录，不需要单独设置吧？
是要访问这个目录下其他应用的文件？

**Comment by skbeh** [comment]
其他应用的文件。
