### ISSUE TITLE
可以发布一个启动时去更新检查的版本么？

### ISSUE THREAD

**Issue by jiyuefeng** [kkevsekk1/AutoX#163]
如题

**Comment by kkevsekk1** [comment]
打包后的app 都是独立的app， 到哪里去检测更新啊？

**Comment by jiyuefeng** [comment]
> 

我指的是，直接运行app脚本的运行方式（非打包方式），因为使用场景需要 每次需要 pm clear org.autojs.autojs 这样如果碰到有release版本发布的话，就会有弹窗提示。

**Comment by kkevsekk1** [comment]
你是真运行 inrt.apk 这个模板apk？

**Comment by jiyuefeng** [comment]
> 
不是，使用adb 运行
`am start -n org.autojs.autojs/.external.open.RunIntentActivity -d /sdcard/脚本/xxx.js  -t application/x-javascript`

**Comment by kkevsekk1** [comment]
运行 这个activity 不会进行版本检测啊

**Comment by jiyuefeng** [comment]
> 运行 这个activity 不会进行版本检测啊

我会在执行上面这段代码的前面，进行 `pm clear org.autojs.autojs && sleep 5 && dg am start org.autojs.autojs ` 然后使用`adb input tap`  进行无障碍模式的开启。

**Comment by kkevsekk1** [comment]
那随便 检测一下，有这个窗口就勾选一下，然后关闭， 再运行后面的脚本了！

**Comment by kkevsekk1** [comment]
这还是迎合大多数要求，需要去检测一下 ^_^

**Comment by jiyuefeng** [comment]
> 这还是迎合大多数要求，需要去检测一下 ^_^

这个理解，我下载了源码 找到了更新的那段代码，然后注释掉去打包，用了自己的签名，结果启动后不到1秒就闪退了。

**Comment by jiyuefeng** [comment]
> 那随便 检测一下，有这个窗口就勾选一下，然后关闭， 再运行后面的脚本了！

其实我这样做就是为了让autox去开启无障碍模式，有没有其他的脚本方式去开启无障碍模式呢

**Comment by kkevsekk1** [comment]
闪退是编译环境配置的问题，你用这个软件，去开启另一个软件的无障碍？  那你可以用打包后的apk

**Comment by kkevsekk1** [comment]
或者 你写一段 负责点的 adb 脚本，也可以完成 无障碍的开启
