### ISSUE TITLE
一些优化及打包应用ocr的bug（帮忙测试一下……）

### ISSUE THREAD

**Issue by Aioure** [kkevsekk1/AutoX#170]
默认提供64位版本，显著提升原生模块性能，尝试对inrt一些配置进行了完善。但对AutoX的脚本打包机制不了解，不确定是否能修复网友反馈多次的ocr打包bug，目前我这边编译的release版依然闪退，debug版打包又会出错，没法测试，所以麻烦帮忙测试一下，如果没修复就暂时先不要发布新版……

**Comment by nanmeng-sujin** [comment]
打包后的应用好像出了问题

**Comment by kkevsekk1** [comment]
> 打包后的应用好像出了问题

什么问题，好修啊

**Comment by CuteLicense** [comment]
没有下载链接呢 5.7.0

**Comment by CuteLicense** [comment]
这个版本不错，OCR速度飙升

**Comment by nanmeng-sujin** [comment]
打包后的应用  闪退，点开就退出了

**Comment by q751654992** [comment]
你们说的打包是指编译源码后的打包
还是写好js文件后打包

**Comment by Aioure** [comment]
> 你们说的打包是指编译源码后的打包 还是写好js文件后打包

一般是指写好js文件后打包
