### ISSUE TITLE
5.7.0bug

### ISSUE THREAD

**Issue by xq20190308** [kkevsekk1/AutoX#172]
打开音量上键停止脚本后立刻闪退，并且无法再次重新打开软件。

**Comment by heham** [comment]
同

**Comment by xq20190308** [comment]
> 5.7，音量上设置闪退，但是再次能打开

可是我的打不开。。。android8.0

**Comment by happyme531** [comment]
安卓11相同问题, 打开后软件保持闪退, 除非清除数据

**Comment by nnkn** [comment]
安卓12同闪退，音量上设置闪退，无法再次打开，还得清除数据
