### ISSUE TITLE
源码中很多类似LoginActivity_、RegisterActivity_、WebActivity_等找不到的类

### ISSUE THREAD

**Issue by czanan** [kkevsekk1/AutoX#181]
这些包，在原项目找不到对应的类，这样做的目的是啥，和我之前项目中都必须要有的包类有很大的差别，貌似我编译原作者的代码debug模式没有问题，但是release版本闪退，不知道和这个有没有关系

**Comment by kkevsekk1** [comment]
LoginActivity_ 是由 LoginActivity+注解 生成的

**Comment by czanan** [comment]
> LoginActivity_ 是由 LoginActivity+注解 生成的

虽然不太懂，但是还是很感谢作者能给予的回复。

**Comment by kkevsekk1** [comment]
百度 @EActivity 这个注解

**Comment by czanan** [comment]
> @EActivity

太感谢大神了。在最近接触autojs和autoxjs的到时候，发现相同的现象是打包release版本的apk安装后闪退，debug版本就没有这个问题。这个问题网上说是做了混淆优化导致的，不知道是何缘故，怀疑是编译优化后，不怎么兼容。
