### ISSUE TITLE
是故意为之的吗？我怀疑是单词写错了⊙∀⊙？

### ISSUE THREAD

**Issue by nbsda-jh** [kkevsekk1/AutoX#183]
文档里这是控制台的背景颜色是 console.setBackgroud(color),然后我去试了试，嗯！报错，一看我写成了console.setBackground,我Emotional damage了，我写错了？没啊！哈哈😄

**Comment by Aioure** [comment]
AutoX的文档好久没更新了，有空可以帮忙修改一下（采用的是在线文档，直接在Github上PR即可）

**Comment by heham** [comment]
没用过这个，你这一说似乎是的啊，但这搞不好是老版就这样的，你试下老版的看看

**Comment by kkevsekk1** [comment]
没注意，拼写错误，可以修正一下
