### ISSUE TITLE
[Bug]某些应用页面元素无法检查

### ISSUE THREAD

**Issue by kai648846760** [kkevsekk1/AutoX#186]
某些应用的元素无法检查，如 : 某信小程序。。。
但原4.x版本可以正常检查。

**Comment by heham** [comment]
如果你是鸿蒙系统那你可能跟我一样的问题，这可能是系统的某种机制引起的，你可以这样测试一下，删掉APP重启，然后断网的状态下安装，这个时候系统应该还没有标记不安全APP什么的，马上测试一下是否可以分析小程序，如果是那你的APP需要签名，不被标记为不安全就没问题了
