### ISSUE TITLE
请问能否当autojs免费版使用? 

### ISSUE THREAD

**Issue by AIsht669** [kkevsekk1/AutoX#19]
假设:
我不需要用到autoxjs 项目工程化
不想安装nodejs 和 npm .
能否直接用vscode 正常使用autoxjs 呢?

**Comment by kkevsekk1** [comment]
可以没有任何影响

**Comment by kkevsekk1** [comment]
可以，没有任何影响



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： "♡+.史莱姆|" <notifications@github.com>
日期: 2020/11/19 02:11 (GMT+08:00)
收件人： kkevsekk1/AutoX <AutoX@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [kkevsekk1/AutoX] 请问能否当autojs免费版使用?  (#19)


假设:
我不需要用到autoxjs 项目工程化
不想安装nodejs 和 npm .
能否直接用vscode 正常使用autoxjs 呢?
