### ISSUE TITLE
autoxjs闪退

### ISSUE THREAD

**Issue by axin-plus** [kkevsekk1/AutoX#191]
用andriod sudio编译出来的apk 一安装完跳出个储存权限选项 然后再打开一直闪退

**Comment by Aioure** [comment]
可能是gradle编译配置的问题。一般编译release版比较容易出错，debug版不会，你可以先试试能不能编译出正常运行的debug包。另外，GIthub上也有编译好的安装包可供下载。

**Comment by heham** [comment]
如果你是编译的release是可能这样，我这边编译debug版没问题，release就闪退，另外我把作者的包重签名也闪退

**Comment by axin-plus** [comment]
太感谢了 用commonDebug一下子就可以了   之前搞了好久 我是小白

**Comment by axin-plus** [comment]
太感谢了 用commonDebug一下子就可以了   之前搞了好久 我是小白
