### ISSUE TITLE
autoxjs apk 檔案太難下載了

### ISSUE THREAD

**Issue by jiangjiang0228** [kkevsekk1/AutoX#193]
您好  我是台灣的愛好者
在 release 裡面的 apk 載點, 幾乎無法下載
時常中斷, 時常保持 1x kb/s 的下載速度
有其他國際上通用的雲端硬碟嗎?

**Comment by Aioure** [comment]
欢迎来自台湾的朋友！release 下载过慢的话，这边可以提供其它的网盘下载方式。不知道你们那边比较常用、速度比较快的是哪一种？

**Comment by jiangjiang0228** [comment]
google drive

**Comment by Aioure** [comment]
> google drive

https://drive.google.com/drive/folders/1ad_U5QH92Kc25SMFNYVp1kChrb2zTuem?usp=sharing

**Comment by kkevsekk1** [comment]
已使用全球cdn
