### ISSUE TITLE
OCR识别文本次序是乱序，请把List顺序调整一下

### ISSUE THREAD

**Issue by minirain2000** [kkevsekk1/AutoX#199]
stringList = paddle.ocrText(img);文字顺序有颠倒，上下同列串行了！

**Comment by agandab** [comment]
这个是paddle.ocr的通病了。自己根据坐标值重新排序。

**Comment by minirain2000** [comment]
`let stringList = paddle.ocrText(img2, cpuThreadNum, useSlim); 
let stringList = paddle.ocr(img2, cpuThreadNum, useSlim); 
var   words = ''
   for(i=0;i<stringList.length;i++){
        words = words + stringList[i].words;
       }`
       如何根据坐标排序？不会啊！！

**Comment by minirain2000** [comment]
let stringList = paddle.ocrText(img2, cpuThreadNum, useSlim); 
let stringList = paddle.ocr(img2, cpuThreadNum, useSlim); 
var   words = ''
   for(i=0;i<stringList.length;i++)
   {
        words = words + stringList[i].words;
       }

**Comment by minirain2000** [comment]
//let stringList = paddle.ocrText(img2, cpuThreadNum, useSlim);
let stringList = paddle.ocr(img2, cpuThreadNum, useSlim);
var words = ''
for(i=0;i<stringList.length;i++)
{
words = words + stringList[i].words;
}

**Comment by minirain2000** [comment]
public int compareTo(Object o) {
        OcrResult s = (OcrResult) (o);
       // if (this.bounds.bottom == s.bounds.bottom) {
		int deviation = 9;
        if (Math.abs(this.bounds.bottom - s.bounds.bottom) <= deviation) {
            return this.bounds.left - s.bounds.left;
        } else {
            return this.bounds.bottom - s.bounds.bottom;
        }
    }

**Comment by syhyz** [comment]
> https://github.com/kkevsekk1/AutoX/pulls

@minirain2000 @agandab  提交了，被合并到test分支中去了，所以没发布出来。OCR乱序和内存溢出问题不修没法用，尝试自己release了一个专用版，解决燃眉之急：XXQG（https://github.com/syhyz/xxqg 可以自己编译）
