### ISSUE TITLE
麻烦加入shizuku的权限以加强adb的支持

### ISSUE THREAD

**Issue by 1965514404** [kkevsekk1/AutoX#2]
https://github.com/RikkaApps/Shizuku

**Comment by kkevsekk1** [comment]
加 qq 群 895775483 













在 2020-09-17 08:33:49，"icesvalley" <notifications@github.com> 写道：

https://github.com/RikkaApps/Shizuku

**Comment by 710850609** [comment]
> 加 qq 群 895775483 在 2020-09-17 08:33:49，"icesvalley" <notifications@github.com> 写道： https://github.com/RikkaApps/Shizuku — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有找到
![image](https://user-images.githubusercontent.com/9523566/93658047-9e727500-fa6a-11ea-98f9-e04a38ae4819.png)
