### ISSUE TITLE
长按函数索引出来的是封面

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [kkevsekk1/AutoX#20]
![Screenshot_20201122_195131_org autojs autojs](https://user-images.githubusercontent.com/65865633/99902946-32c3b700-2cfc-11eb-9e8f-5e160e15be7c.jpg)

**Comment by kkevsekk1** [comment]
代码里长按？我手机上每办法重现呢

**Comment by NMSL-code** [comment]
> 代码里长按？我手机上每办法重现呢

是的，手机代码里长按

**Comment by NMSL-code** [comment]
开发老弟，这个问题还在![Screenshot_20210222_213628_org.autojs.autojs.jpg](https://user-images.githubusercontent.com/65865633/108715592-0b2bf700-7556-11eb-8818-b561f5a0dc38.jpg)

**Comment by NMSL-code** [comment]
催更一波
