### ISSUE TITLE
能否和其他框架比如uniapp整合在一起使用？

### ISSUE THREAD

**Issue by etjson** [kkevsekk1/AutoX#201]
如题，我是用uniapp开发的原生app，支持自己用java写原生扩展，所以我在想能不能把autojs封装成一个util包，定义成uniapp的第三方扩展调用，实现的思路是啥？或者作者有考虑改一个sdk嘛？

**Comment by kkevsekk1** [comment]
自己编译一个就可以了

**Comment by Kiything** [comment]
有没有思路可以指导一下

**Comment by etjson** [comment]
自定义uniapp扩展api，用广播通知autojs执行脚本即可

storm ***@***.***> 于2024年12月14日周六 21:23写道：

**Comment by Kiything** [comment]
怎么广播呀，没太听明白
