### ISSUE TITLE
请问自带的ppocr可以得到每个字的置信度？

### ISSUE THREAD

**Issue by admin0008** [kkevsekk1/AutoX#210]
如题
@kkevsekk1 @ghost

**Comment by kkevsekk1** [comment]
理论上，可以的

**Comment by admin0008** [comment]
> 

现在只返回每个块的置信度，可能要从ppocr源码修改，但是不知道怎么实现

**Comment by syhyz** [comment]
> 现在只返回每个块的置信度，可能要从ppocr源码修改，但是不知道怎么实现

ppocr的核心代码是C++，app只是调用了接口，如果有疑问也建议先向[官方](https://github.com/PaddlePaddle/PaddleOCR)反馈。
另外，如果只是想提高ocr准确度的话，可以考虑自己编译更好的模型（官方有教程） ，或者改用在线OCR

**Comment by agandab** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/5377
有人在上面问过类似的问题
