### ISSUE TITLE
大佬，能不能让AutoX也能运行这代码  var ocr = $plugins.load("com.hraps.ocr");

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#211]
var ocr = $plugins.load("com.hraps.ocr");这代码目前需要pro8以上才能运行，能不能咱也加上这功能啊

**Comment by kkevsekk1** [comment]
去掉$ 就可以

**Comment by admin0008** [comment]
> 去掉$ 就可以
我也是现在才知道，原来autox支持插件，666，有空去试试

**Comment by heham** [comment]
竟然也能插件了？

**Comment by lnxcyq** [comment]
> 去掉$ 就可以
去掉$运行提示出错。如下，这是怎么回事呢，谢谢
14:57:38.217/E: dlopen failed: "/data/app/com.hraps.ocr-FuUt8tOnUUztjnkIFzzinQ==/lib/arm/libOcrLite.so" is 32-bit instead of 64-bit

**Comment by q751654992** [comment]
> > 去掉$ 就可以
> > 去掉$运行提示出错。如下，这是怎么回事呢，谢谢
> > 14:57:38.217/E: dlopen failed: "/data/app/com.hraps.ocr-FuUt8tOnUUztjnkIFzzinQ==/lib/arm/libOcrLite.so" is 32-bit instead of 64-bit

ocr插件的so文件是32位的  需要64位的才行

**Comment by admin0008** [comment]
测试了，的确可以用，但是由于浩然这个是32bit的，要装5.4autox测试，但是com.hraps.ocr性能太差，不建议用，还是乖乖的ppOCR好用

**Comment by leftAttack** [comment]
版本：6.4.2
Wrapped com.stardust.autojs.core.plugin.Plugin$PluginLoadException: android.content.pm.PackageManager$NameNotFoundException: Application package com.hraps.ocr not found
    at /android_asset/modules/__plugins__.js:6:0
    at [remote]test1.js:13:0

**Comment by kkevsekk1** [comment]
问一下群里的人



发送自我的盖乐世



-------- 原始信息 --------
发件人： leftAttack ***@***.***>
日期: 2023/8/26 12:53 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 大佬，能不能让AutoX也能运行这代码 var ocr = $plugins.load("com.hraps.ocr"); (Issue #211)


版本：6.4.2
Wrapped com.stardust.autojs.core.plugin.Plugin$PluginLoadException: android.content.pm.PackageManager$NameNotFoundException: Application package com.hraps.ocr not found
at /android_asset/modules/plugins.js:6:0
at [remote]test1.js:13:0

―
