### ISSUE TITLE
添加控制台关闭事件

### ISSUE THREAD

**Issue by pharaoh2012** [kkevsekk1/AutoX#217]
添加控制台关闭事件，脚本可以监听事件，在用户关闭控制台的时候结束脚本运行。

可能的修改方式，未验证：
在文件`ConsoleFloaty.java`的`setWindowOperationIconListeners`方法第一句修改为：
原始语句：
```
        view.findViewById(R.id.close).setOnClickListener(v -> window.close());
```
修改语句：
```java
        view.findViewById(R.id.close).setOnClickListener(v -> {
            window.close();
            mHandler.post(() -> emit("consoleClosed"));
        });
```

**Comment by pharaoh2012** [comment]
> 关闭控制台，只是关控制台，没有结束脚本这个功能 有人需要关闭控制台的时候，结束脚本，示例代码中有

请问是那个例子，我刚刚将控制台的几个例子都看了一下，我点击控制台的右上角的X关闭控制台，脚本还是在运行的，并没有结束。

**Comment by kkevsekk1** [comment]
window.exitOnClose()

**Comment by pharaoh2012** [comment]
这个是针对自定义的FloatyWindow窗口吧，对`console.show()`显示的窗口没有作用吧。

```
var window = floaty.window(
  <vertical>
      <input id="input" text="请输入你的名字" textSize="16sp" focusable="true"/>
      <button id="ok" text="确定"/>
  </vertical>
);

window.exitOnClose();
```

**Comment by kkevsekk1** [comment]
那可能是我记错了，关闭控制台就关闭控制台，跟其他东西没关系

**Comment by pharaoh2012** [comment]
控制台示例代码的`设置日志显示最大行数`,运行时候点击X关闭控制台，实际脚本还是一直在运行，如果有关闭事件，就可以比较好的结束程序。

例如京东年兽等脚本，运行时间比较久，关闭控制台结束脚本是一个比较好的中途结束脚本的方法。

**Comment by kkevsekk1** [comment]
> 控制台示例代码的`设置日志显示最大行数`,运行时候点击X关闭控制台，实际脚本还是一直在运行，如果有关闭事件，就可以比较好的结束程序。
> 
> 例如京东年兽等脚本，运行时间比较久，关闭控制台结束脚本是一个比较好的中途结束脚本的方法。

1.停止运行大脚本有音量上键控制，或自己写一个 关闭脚本的功能， 
2.关闭脚本的时候可以关闭 console
3.按照你说的思路，那用户只是不想看console ，就把console关闭了，并不想结束脚本，如何处理？
4,设置日志最大行数只是减少内存中 保存的日志条数， 和console 的显示隐藏，没有任何关系

**Comment by kkevsekk1** [comment]
> 关闭控制台结束脚本是一个比较好的中途结束脚本的方法
关闭console，结束脚本，这是一个很low 的方案，

你完全 可以 理由floaty 制作一个，按钮随时控制脚本开关，

**Comment by pharaoh2012** [comment]
> > 控制台示例代码的`设置日志显示最大行数`,运行时候点击X关闭控制台，实际脚本还是一直在运行，如果有关闭事件，就可以比较好的结束程序。
> > 例如京东年兽等脚本，运行时间比较久，关闭控制台结束脚本是一个比较好的中途结束脚本的方法。
> 
> 1.停止运行大脚本有音量上键控制，或自己写一个 关闭脚本的功能， 2.关闭脚本的时候可以关闭 console 3.按照你说的思路，那用户只是不想看console ，就把console关闭了，并不想结束脚本，如何处理？ 4,设置日志最大行数只是减少内存中 保存的日志条数， 和console 的显示隐藏，没有任何关系

1. 停止运行大脚本有音量上键控制 这个功能在哪里？
2.  关闭console没问题。
3. 关闭console并不是结束脚本，只是发个关闭事件，脚本监听这个事件进行关闭等处理，没有监听事件和现在的没有任何影响.
4. 这个只是一个举例，和内存这类的没关系。

**Comment by heham** [comment]
你还不如换个思路添加一个按钮，关闭控制台结束脚本

**Comment by pharaoh2012** [comment]
> 你还不如换个思路添加一个按钮，关闭控制台结束脚本

也可以，看那种方法实现方便一点。
