### ISSUE TITLE
V5.7.6 使用第三方应用程序 引用脚本快捷方式（非桌面快捷方式）失败

### ISSUE THREAD

**Issue by suochenxi** [kkevsekk1/AutoX#218]
使用第三方应用程序 Button Mapper(flar2.homebutton) 引用 AutoX 快捷方式（非桌面快捷方式）失败：
指定脚本后未提示选择 iCon，而是提示“创建快捷方式被目标应用取消”
![image](https://user-images.githubusercontent.com/8415118/154659159-de0a817d-e542-4458-b1a0-c10e355447cf.png)

**Comment by kkevsekk1** [comment]
？

**Comment by suochenxi** [comment]
长按桌面空白处，添加桌面小控件，拖动截图中右面的快捷方式到桌面，选择脚本后创建桌面快捷方式失败。但是左面的图标拖动到桌面是正常的。这会导致在其他应用中引用脚本快捷方式失败。
![image](https://user-images.githubusercontent.com/8415118/155056283-f77beeaa-4775-4d81-aa5c-8ac62043b384.png)

**Comment by kkevsekk1** [comment]
还有这么个用法，我都不知道 ^_^

**Comment by suochenxi** [comment]
嗯嗯，可以参考一下这个文，当时使用 Tasker 跳转 AutoX 脚本的原因就是设置 AutoX 快捷方式失败。实际上 Tasker 只是用来设置桌面快捷方式和图标。如果这个功能好用的话没有必要过一次 Tasker，脚本的效率应该会快一些。不过不太确定这样用的人多不多。 https://sspai.com/post/65863

**Comment by kkevsekk1** [comment]
你的意思是现在左边的这个，在5.7.6 中也没法用了？

**Comment by suochenxi** [comment]
> 

左边的这个目前是可以使用的，但是因为以下问题，导致没有右边的好用：
1. 没有办法自定义图标，只能使用默认图标
2. 没有办法被第三方 app 引用快捷方式，如我上面发的 Button Mapper。（Intent 调用在我说的应用里是付费功能，快捷方式调用是免费功能）

**Comment by kkevsekk1** [comment]
之前的版本 右边的是可以用的？

**Comment by suochenxi** [comment]
> 之前的版本 右边的是可以用的？

从我开始使用 AutoX 开始，好像就一直不能用。我理解是一开始拉分支的时候就不好用。不太了解 Pro 版本有没有修这个问题，因为我已经没有在用 Pro 版了。

**Comment by kkevsekk1** [comment]
哦，

**Comment by suochenxi** [comment]
再补充一个信息，因为我使用的是第三方 Launcher，所以在桌面添加快捷方式失败的原因，可能和在其他应用中添加快捷方式的原因是一样的。不太清楚系统 Launcher 里面添加快捷方式是否同样会有失败的问题。

**Comment by suochenxi** [comment]
> 哦，

另外再请教一下，AutoX 是否支持通过 Scheme 调起并执行脚本？如 dingtalk://dingtalkclient/page/link?url=xxxxx 可调用钉钉内置浏览器打开网页。

**Comment by kkevsekk1** [comment]
> > 哦，
> 
> 另外再请教一下，AutoX 是否支持通过 Scheme 调起并执行脚本？如 dingtalk://dingtalkclient/page/link?url=xxxxx 可调用钉钉内置浏览器打开网页。

不支持，

**Comment by suochenxi** [comment]
> 

再补充一下信息，刚下载了最新的 Pro 版本，也存在相同问题。这么看这个问题在拉分支的时候就已经存在了。辛苦评估一下后续是否修复吧。 ^_^

**Comment by suochenxi** [comment]
再请教一个问题：目前 AutoX 是否支持通过 Intent 传入脚本路径调用指定脚本？
我找了一个可以设置 Intent 的应用，想通过 Intent 调起 AutoX 执行特定脚本。
在文档里面未找到相关描述，文档里的内容主要是如何通过 AutoX 调用其他应用的 Intent。

**Comment by suochenxi** [comment]
> 再请教一个问题：目前 AutoX 是否支持通过 Intent 传入脚本路径调用指定脚本？ 我找了一个可以设置 Intent 的应用，想通过 Intent 调起 AutoX 执行特定脚本。 在文档里面未找到相关描述，文档里的内容主要是如何通过 AutoX 调用其他应用的 Intent。

这个问题已找到解决方案，参考 https://github.com/hyb1996/Auto.js/issues/496
