### ISSUE TITLE
apk在部分安卓上闪退问题，请大神解决下。

### ISSUE THREAD

**Issue by ghost** [kkevsekk1/AutoX#224]
用5.76打包的app，app在miui10，安卓7,安卓8上运行，到截图ocr时，app闪退，手机实体建失效，屏幕手动操作没问题，试了几台手机都这样。安卓10又没问题。不打包在autox里运行脚本没问题。请指导解决下。谢谢

**Comment by kkevsekk1** [comment]
这还是引包的问题
很可能没测试好inrt 项目

**Comment by syhyz** [comment]
> 这还是引包的问题
> 很可能没测试好inrt 项目

@kkevsekk1  他说的是6天前发布的5.7.6版，打包功能应该还没修复

**Comment by kkevsekk1** [comment]
发布了 5.7.7 测试一下
@syhyz  我估计5.7.7 应该还是有问题

**Comment by syhyz** [comment]
> 这还是引包的问题 很可能没测试好inrt 项目

@kkevsekk1 不一定是引包，感觉更有可能是系统兼容性的问题，还是用WIN10编译试试吧

**Comment by syhyz** [comment]
> 发布了 5.7.7 测试一下 @syhyz 我估计5.7.7 应该还是有问题

示例中的 ocr截屏识别 打包后还是会闪退，不过这不是打包或OCR的问题，应该是这个示例或Canvas引起的闪退

**Comment by kkevsekk1** [comment]
开玩笑哦 ！
inrt 只是给autojs.aar 套个壳而已
现在 最大的问题，ocr模块 的使用方法 问题
有时间的话，把ocr 模块 独立成 aar 或jar 的开源项目

**Comment by syhyz** [comment]
> 开玩笑哦 ！ inrt 只是给autojs.aar 套个壳而已 现在 最大的问题，ocr模块 的使用方法 问题 有时间的话，把ocr 模块 独立成 aar 或jar 的开源项目

@kkevsekk1  就是套个壳，改写才不会太麻烦。而所谓ocr的开源项目，PaddleOCR 官方自己就已经有了Android的SDK，只是没有提供直接引用的包罢了，感觉这种事就算要做，也是应该先去向官方建议比较好吧？

**Comment by kkevsekk1** [comment]
> > 开玩笑哦 ！ inrt 只是给autojs.aar 套个壳而已 现在 最大的问题，ocr模块 的使用方法 问题 有时间的话，把ocr 模块 独立成 aar 或jar 的开源项目
> 
> @kkevsekk1 就是套个壳，改写才不会太麻烦。而所谓ocr的开源项目，PaddleOCR 官方自己就提供了Android的SDK，只是没有给出直接引用的包罢了，感觉这种事就算要做，也是应该先向官方建议比较好吧？
建议给官方？官方欠你的啊

**Comment by kkevsekk1** [comment]
官方只是出个demo 而已，demo 到正式使用还有很多问题 要考虑

**Comment by edimax80** [comment]
5.7.7打包app测试一次，暂时没问题

**Comment by kkevsekk1** [comment]
> 5.7.7打包app测试一次，暂时没问题

没问题，那最好了，我们也懒得修复 
![004C8B10](https://user-images.githubusercontent.com/16631944/155055683-74021788-922e-4a7c-afe8-46f96ba4a446.png)

**Comment by heham** [comment]
5.7.7打包了ocr还是可以用，我只是简单测试了一下
