### ISSUE TITLE
能换下包名,兼容下4.1版本的autojs吗

### ISSUE THREAD

**Issue by q751654992** [kkevsekk1/AutoX#225]
想同时安装autojs和aujsx

**Comment by suochenxi** [comment]
我理解 AutoX 这个项目就是基于 autojs 4.1 版本开发的，AutoX 可以理解为 autojs 4.1 的后续版本。什么场景下需要同时使用一个应用的新版和旧版？

**Comment by q751654992** [comment]
> 我理解 AutoX 这个项目就是基于 autojs 4.1 版本开发的，AutoX 可以理解为 autojs 4.1 的后续版本。什么场景下需要同时使用一个应用的新版和旧版？

我一直用的4.1感觉会稳定一点,autox又有新功能,想着可以来回切换着用
