### ISSUE TITLE
Paint 设置画笔颜色不生效

### ISSUE THREAD

**Issue by KOFKOY** [kkevsekk1/AutoX#234]
> 画出来是白色的，红米k20pro，版本5.7.8 和 最新测试6.多的版本 都不行
贴的代码显示不全，不知道咋回事 ，加了代码块多行不起作用
var w = floaty.rawWindow(
    <frame gravity="center" bg="#00FFFFFF">
        <canvas id="board" w="*" h="*"/>
    </frame>
);
w.setSize(-1, -1);
w.setTouchable(false);
w.board.on("draw",function(canvas){
    var paint = new Paint();
    //设置画笔颜色为红色
    // paint.setColor(colors.rgb(255,0,0));
    paint.setColor(colors.parseColor("#00FF00"));
    paint.setStyle(Paint.Style.STROKE);
    paint.setStrokeWidth(5)
    canvas.drawOval(300,300,600,600,paint);
})
setTimeout(()=>{
    w.close()
},1000 * 60);

![image](https://user-images.githubusercontent.com/30439085/156539419-9021572d-3b85-4978-919e-39561ff0229e.png)

**Comment by kkevsekk1** [comment]
现在还有么？

**Comment by KOFKOY** [comment]
换手机了，等有时间测一下吧
