### ISSUE TITLE
能出个把这个源码autox怎么打包成apk的教程吗

### ISSUE THREAD

**Issue by KB64ba** [kkevsekk1/AutoX#242]
用as提示：“This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.”  as刷更新IDE提示已是最新版了

不是要autox打包脚本的apk的教程

是把源码autox打包成apk在手机上运行， 怎么把源码autox打包成apk

**Comment by CuteLicense** [comment]
打包了几次，不成功，放弃了。还是等作者编译后的了

**Comment by edimax80** [comment]
我第一次打包，一次成功啊，不过编译的apk 里打包脚本不成功。显示：“in is null”

**Comment by Qiihz** [comment]
https://github.com/kkevsekk1/AutoX/actions/workflows/android.yml

**Comment by kkevsekk1** [comment]
https://github.com/kkevsekk1/AutoX/actions

**Comment by kkevsekk1** [comment]
./gradlew inrt:assemble 
  ./gradlew inrt:cp2APP （这就可以解决 in is null）
 ./gradlew app:assembleRelease
执行 这些命令 就可以打包

**Comment by edimax80** [comment]
谢谢

**Comment by edimax80** [comment]
试了试，用命令打包，打包autox后显示没签名，无法安卓，找网上的办法写签名参数，还是不行。

**Comment by kkevsekk1** [comment]
签名要的东西，生成你自己的，设置好久可以签

**Comment by kkevsekk1** [comment]
设置好，打包会自动签

**Comment by edimax80** [comment]
网上搜了n多教程，终于搞定。谢谢

**Comment by iafine** [comment]
> 

大佬可以发一些相关教程链接吗，感谢

**Comment by alphaerp** [comment]
> 网上搜了n多教程，终于搞定。谢谢

如何通过action 打包？ 我action打包提示Failed to load signer "signer #1"。 不知道怎么弄了？

**Comment by kkevsekk1** [comment]
已经有
