### ISSUE TITLE
请问下5.x 版跟6.x版有什么不同？

### ISSUE THREAD

**Issue by ghost** [kkevsekk1/AutoX#245]
请问下5.x 版跟6.x版有什么不同？ 为何发布6.0.2后又发布了5.7.9

**Comment by kkevsekk1** [comment]
5是比较稳定的，6是很不稳定的



发送自我的盖乐世



-------- 原始信息 --------
发件人： edimax80 ***@***.***>
日期: 2022/3/31 18:58 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问下5.x 版跟6.x版有什么不同？ (Issue #245)


请问下5.x 版跟6.x版有什么不同？ 为何发布6.0.2后又发布了5.7.9

―

**Comment by kkevsekk1** [comment]
截止目前，认为6 也是稳定的，兼容性更好一些
