### ISSUE TITLE
分享5.7.9  AutoX 安装包APK

### ISSUE THREAD

**Issue by gxylfm** [kkevsekk1/AutoX#247]
5.7.9  AutoX 安装包
大神没空编译安装包，自己动手用Android Studio编译了。
自己签名打包的，因为与大神5.7.8版本签名不一致，不能直接安装替换旧版本，需要卸载旧版本，再安装5.7.9。
建议会编译打包的自己去打包，毕竟自己编译打包的更安全，这个只是给不懂编译的小伙伴用啊。

https://wwn.lanzouf.com/ivmQo02lag6b
4月4日 修复打包的软件，没有勾选权限情况打开APP闪退小问题（问题：请开启权限后，再运行）。

5.7.9版本优化以下特性： 感谢[falcolee](https://github.com/falcolee) 
增加pro的websocket功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/webSocket)
 增加pro的zip功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/zip) 
增加pro的加解密功能[文档地址](https://pro.autojs.org/docs/#/zh-cn/crypto) 
相关功能 可以参考 实例代码 感谢 [heham](https://github.com/heham) 调整文档

**Comment by CuteLicense** [comment]
感谢，终于有人分享出来了

**Comment by edimax80** [comment]
安卓10  miui12 打包没问题， miui7打包跟你同样问题。

**Comment by gxylfm** [comment]
> 安卓10 miui12 打包没问题，安卓8打包跟你同样问题。

我虚拟机和手机都有问题。

**Comment by gxylfm** [comment]
发布了5.7.10.，可以关闭了。
