### ISSUE TITLE
请问如何下载已经打包好的apk文件

### ISSUE THREAD

**Issue by fanld2007** [kkevsekk1/AutoX#251]
你好，在这个链接中https://github.com/kkevsekk1/AutoX/actions/runs/2088633898没法下载你打包好的apk文件，你能指导一下如何下载不？谢谢

**Comment by kkevsekk1** [comment]
下载不流畅这是墙的原因，用翻墙



发送自我的盖乐世



-------- 原始信息 --------
发件人： fanld2007 ***@***.***>
日期: 2022/4/7 20:20 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问如何下载已经打包好的apk文件 (Issue #251)


你好，在这个链接中https://github.com/kkevsekk1/AutoX/actions/runs/2088633898没法下载你打包好的apk文件，你能指导一下如何下载不？谢谢<https://github.com/kkevsekk1/AutoX/actions/runs/2088633898%E6%B2%A1%E6%B3%95%E4%B8%8B%E8%BD%BD%E4%BD%A0%E6%89%93%E5%8C%85%E5%A5%BD%E7%9A%84apk%E6%96%87%E4%BB%B6%EF%BC%8C%E4%BD%A0%E8%83%BD%E6%8C%87%E5%AF%BC%E4%B8%80%E4%B8%8B%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E4%B8%8D%EF%BC%9F%E8%B0%A2%E8%B0%A2>

―

**Comment by fanld2007** [comment]
非常感谢，已经能下载了
