### ISSUE TITLE
无法创建签名，打包失败

### ISSUE THREAD

**Issue by james-bond-007** [kkevsekk1/AutoX#255]
**创建签名**时，点击确定，无反应。
![Screenshot_2022-04-21-00-56-07-1357412023](https://user-images.githubusercontent.com/46163922/164739820-25fd39e6-b345-4d64-a4e3-df2536b95e0d.png)

显示`已经验证`，却无法打包。

**Comment by Mrzhangqc** [comment]
是的，有这个问题，希望能修复一下
