### ISSUE TITLE
请问有没有连接wifi的api可调用呢

### ISSUE THREAD

**Issue by 17835747843** [kkevsekk1/AutoX#257]

**Comment by kkevsekk1** [comment]
通过无障碍模拟人工连接



发送自我的盖乐世



-------- 原始信息 --------
发件人： 17835747843 ***@***.***>
日期: 2022/4/26 15:19 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问有没有连接wifi的api可调用呢 (Issue #257)


―
