### ISSUE TITLE
建议打包假如是否使用ocr的选项，以减少apk体积

### ISSUE THREAD

**Issue by admin0008** [kkevsekk1/AutoX#261]
如题，希望能加入这些选项

**Comment by kkevsekk1** [comment]
最近我换工作了，没多少时间搞……



发送自我的盖乐世



-------- 原始信息 --------
发件人： admin0008 ***@***.***>
日期: 2022/5/2 00:34 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 建议打包假如是否使用ocr的选项，以减少apk体积 (Issue #261)


如题，希望能加入这些选项

―

**Comment by Warm-rain** [comment]
ReferenceError: "$plugins" is not defined.
我的ocr无法导入 版本6.0.2请问你可以正常使用么

**Comment by kkevsekk1** [comment]
去掉$符号



发送自我的盖乐世



-------- 原始信息 --------
发件人： warmsake ***@***.***>
日期: 2022/5/9 20:49 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 建议打包假如是否使用ocr的选项，以减少apk体积 (Issue #261)


ReferenceError: "$plugins" is not defined.
我的ocr无法导入 版本6.0.2请问你可以正常使用么

―

**Comment by Warm-rain** [comment]
谢谢回复，去掉$后还是报错，感觉是官方下载的插件有问题，我试试其他方法

23:08:44.428/E: Wrapped com.stardust.autojs.core.plugin.Plugin$PluginLoadException: com.stardust.autojs.core.plugin.Plugin$PluginLoadException: java.lang.NoClassDefFoundError: org.autojs.plugin.ocr.MyPluginRegistry (file:///android_asset/modules/__plugins__.js#6)
Wrapped com.stardust.autojs.core.plugin.Plugin$PluginLoadException: com.stardust.autojs.core.plugin.Plugin$PluginLoadException: java.lang.NoClassDefFoundError: org.autojs.plugin.ocr.MyPluginRegistry
    at file:///android_asset/modules/__plugins__.js:6:0
    at /storage/emulated/0/脚本/TEXT/ocr.js:2:0

**Comment by wilinz** [comment]
> 如题，希望能加入这些选项

最新的dev-test已添加此功能
