### ISSUE TITLE
5.7.10打包的APK，华为手机提示有风险，不允许安装

### ISSUE THREAD

**Issue by james-bond-007** [kkevsekk1/AutoX#264]
5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。

**Comment by gxylfm** [comment]
> 5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。

这个或许是证书问题吧，建议打包的时候，用自己签名的证书，不要用默认签名证书。

**Comment by Mrzhangqc** [comment]
> > 5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。
> 
> 这个或许是证书问题吧，建议打包的时候，用自己签名的证书，不要用默认签名证书。

添加签名后无法打包

**Comment by majin78** [comment]
MT改字符串

**Comment by kkevsekk1** [comment]
可以用自己签名吧？



发送自我的盖乐世



-------- 原始信息 --------
发件人： 天马行空 ***@***.***>
日期: 2022/5/16 18:28 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 5.7.10打包的APK，华为手机提示有风险，不允许安装 (Issue #264)


5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。

这个或许是证书问题吧，建议打包的时候，用自己签名的证书，不要用默认签名证书。

添加签名后无法打包

―

**Comment by james-bond-007** [comment]
> 可以用自己签名吧？ 发送自我的盖乐世
> […](#)

创建签名，点击确定无反应。选择自己签名，准备文件，构建中，回到打包界面。文件名_no-sign.apk，打包生成的文件大小为零。

**Comment by kkevsekk1** [comment]
还是跟时间 target 版本有关系，我现在 都没时间 调整代码，你们 试着蒋 target 调 到28  试试吧

**Comment by zhuluquan** [comment]
> > > 5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。
> > 
> > 
> > 这个或许是证书问题吧，建议打包的时候，用自己签名的证书，不要用默认签名证书。
> 
> 添加签名后无法打包

兄弟，解决了吗，我遇到一样得问题

**Comment by zhuluquan** [comment]
> 5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。

兄弟解决了吗

**Comment by Mrzhangqc** [comment]
> > 5.7.10打包的APK，华为手机提示有风险，不允许安装。关闭华为手机纯净模式，能正常安装，打不开。
> 
> 兄弟解决了吗

用了MT修改了名称，把内置的包路径全部改成自己的就可以
