### ISSUE TITLE
在线文档最近是不是打不开

### ISSUE THREAD

**Issue by CuteLicense** [kkevsekk1/AutoX#265]
http://doc.autoxjs.com/
要么很慢，要么打不开

**Comment by kkevsekk1** [comment]
cdn.jsdelivr.net 这个cdn挂了，已经换回本地了，可以了 http://doc.autoxjs.com/index.html

**Comment by kkevsekk1** [comment]
这玩意太坑了，应该几十个小数了，他们都不修复   https://blog.csdn.net/u013014254/article/details/122045331

**Comment by CuteLicense** [comment]
感谢，可以访问了
