### ISSUE TITLE
看一下releases

### ISSUE THREAD

**Issue by wilinz** [kkevsekk1/AutoX#268]
![QQ截图20220523205822](https://user-images.githubusercontent.com/59408438/169824809-0f7eae99-28ce-4ffc-a2b9-f053393a4636.png)
这个好像写错了

**Comment by wilinz** [comment]
LZX284改的是webView

**Comment by wilinz** [comment]
这个是我的commit

**Comment by kkevsekk1** [comment]
已经改了

**Comment by wilinz** [comment]
好像没有合并你就release 6.0.5了， @kkevsekk1
