### ISSUE TITLE
夜间模式关闭后无法恢复正常

### ISSUE THREAD

**Issue by sureLin98** [kkevsekk1/AutoX#27]
版本4.2.10，开启夜间模式，再关闭部分界面还是黑色的，不能恢复正常界面
![Screenshot_2021-01-11-18-25-40-286_org autojs autojs](https://user-images.githubusercontent.com/47566975/104169522-ab144200-543a-11eb-95e5-3de3985825a6.jpg)

**Comment by kkevsekk1** [comment]
此bug，由来已久，属于第三方插件问题，后面考虑关闭此功能
