### ISSUE TITLE
6.0.2打包apk失败

### ISSUE THREAD

**Issue by Jodesen** [kkevsekk1/AutoX#277]
![image](https://user-images.githubusercontent.com/62249320/170264825-261ea36d-fb81-4f44-a73d-5f27a6914e79.png)
你们说的打包无法设置ico是这个意思嘛？

**Comment by wilinz** [comment]
是的，目前我暂时没有时间修复

**Comment by Jodesen** [comment]
可以通过回溯版本，达到可以打包ico的目的嘛🤔🤔

**Comment by wilinz** [comment]
> 

你可以下载旧版本

**Comment by wilinz** [comment]
> 可以通过回溯版本，达到可以打包ico的目的嘛🤔🤔

已修复 6.0.6 https://github.com/wilinz/AutoX/releases/tag/6.0.6

**Comment by Jodesen** [comment]
> > 可以通过回溯版本，达到可以打包ico的目的嘛🤔🤔
> 
> 已修复 6.0.6 https://github.com/wilinz/AutoX/releases/tag/6.0.6
幸苦幸苦
