### ISSUE TITLE
https://github.com/kkevsekk1/AutoX/actions/runs/2374730140 autoxjs.apk 打包出的apk闪退

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#278]
我 无法提供任何日志
但权限申请正常弹出
设备信息 ： vivo s9e 天机800 安卓11  

使用旧版 http://file.ar01.cn/appstore/app/20220301141633.apk 可以正常运行

脚本有使用UI

**Comment by wangwang-code** [comment]
一切正常，我在想，能不能在打包的时候混淆res资源（我应该开一个issue）

**Comment by wilinz** [comment]
> 一切正常，我在想，能不能在打包的时候混淆res资源（我应该开一个issue）

现在默认已经混淆了，不信你解压看看
