### ISSUE TITLE
打包时能否混淆RES资源

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#280]
rt
目的是为防止杀软检测到二进制特性报毒，目前我使用MT对RES资源混淆后就不再报毒了，如果能了在打包时就混淆就好了（懒癌发作）

**Comment by wilinz** [comment]
> rt 目的是为防止杀软检测到二进制特性报毒，目前我使用MT对RES资源混淆后就不再报毒了，如果能了在打包时就混淆就好了（懒癌发作）

目前已经默认混淆了，不信你解压看看，之前就是因为这个混淆造成无法设置图标

**Comment by wangwang-code** [comment]
> > rt 目的是为防止杀软检测到二进制特性报毒，目前我使用MT对RES资源混淆后就不再报毒了，如果能了在打包时就混淆就好了（懒癌发作）
> 
> 目前已经默认混淆了，不信你解压看看，之前就是因为这个混淆造成无法设置图标

如果混淆了，理论上不会报毒，而现实是报毒了，等于混淆了个寂寞
