### ISSUE TITLE
AutoX.js 6.0.6 当文件含有中文时使用自定义证书打包出的apk异常

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#283]
6.0.6 见https://github.com/wilinz/AutoX/releases/tag/6.0.6

比如项目里有一个`头.js` 在打包完成后查看apk 后面的js不见了 `头.`

**Comment by wilinz** [comment]
没有理解你的描述

**Comment by wilinz** [comment]
> 6.0.6 见https://github.com/wilinz/AutoX/releases/tag/6.0.6
> 
> 比如项目里有一个`头.js` 在打包完成后查看apk 后面的js不见了 `头.`

没有理解你的描述

**Comment by kkevsekk1** [comment]
.js 这个后缀不见了？好像代码里有特殊处理这个 后缀，可以排查一下

**Comment by wangwang-code** [comment]
人话: 有中文名称并且使用非默认证书打包出的apk有问题

如果仍然无法理解 解压下面的zip自己看看build里的两个apk

https://musetransfer.com/m/s/uk9onjwfl（有效期至6月3日）｜【Muse】《工程文件》文件待查收，请点击链接获取文件

> 没有理解你的描述
