### ISSUE TITLE
是否应该解除与hyb1996/Auto.js仓库的Fork关系

### ISSUE THREAD

**Issue by wilinz** [kkevsekk1/AutoX#285]
目前hyb1996/Auto.js已不再维护，
如果不解除fork关系，则无法在github搜索到Autox项目，并且不能同时fork Autox.js和Auto.js，导致一些fork了Auto.js项目的无法fork Autox.js项目
[GitHub 中 Fork 出来的项目，如何与原项目断开 Fork 关系？](https://cloud.tencent.com/developer/article/1580573)

**Comment by LZX284** [comment]
试了一下，确实搜不到，不论是精确搜索还是模糊搜索，甚至加上作者名字也搜不到……
对需要AutoX的用户来说虽然可能会有些不便，但hyb1996/Auto.js毕竟是原作者，GitHub官方支持人员会不会同意感觉也很难说……
hyb1996不再维护Auto.js有他自己的理由（参见[这里](https://pro.autojs.org/faq) 以及原项目里的一些讨论），滥用开源的Auto.js这事很不好，但目前这已经成了无奈的事实，原作者虽然不再维护开源的Auto.js，但已经开源的代码却无法收回，只要是懂点开发的人在原代码的基础上改改也就能继续使用。
另一方面，Auto.js作为一个中性的工具，本身应该没有什么对错之分，虽然有人将其用于非法用途，但对于软件作者来说既无法也不应该被要求对此负责。除此之外，也有很多用户的正常需求少不了Auto.js这类应用，究竟要使用哪一个或是怎么使用，这个也还是只能由用户或开发者自己去决定吧……

**Comment by LZX284** [comment]
解除与hyb1996/Auto.js仓库的Fork关系，确实会方便一点，但这个只能看作者的意愿了

**Comment by wilinz** [comment]
@kkevsekk1

**Comment by LZX284** [comment]
> @kkevsekk1

@wilinz  其实他看得到的，之所以没有回复，呃呃，意思你应该懂吧？嗯，大概就是他并没有同意，或者就是他懒得回复你……

**Comment by kkevsekk1** [comment]
可以试一下



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/5/29 09:49 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 是否应该解除与hyb1996/Auto.js仓库的Fork关系 (Issue #285)


@kkevsekk1<https://github.com/kkevsekk1>

@wilinz<https://github.com/wilinz> 其实他看得到的，之所以没有回复，呃呃，意思你应该懂吧？嗯，大概就是他并没有同意，或者就是他懒得回复你……

―

**Comment by kkevsekk1** [comment]
https://github.com/kkevsekk1/kkevsekk1.github.io 我先测试 了一下 文档项目断开连接，大家看看 正常不？

**Comment by wilinz** [comment]
正常的

**Comment by kkevsekk1** [comment]
能正常fork吗？



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/6/16 10:37 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 是否应该解除与hyb1996/Auto.js仓库的Fork关系 (Issue #285)


正常的

―

**Comment by wilinz** [comment]
可以

**Comment by wilinz** [comment]
![image](https://user-images.githubusercontent.com/59408438/174547335-116259d0-df19-4801-baa3-142665519798.png)
可以搜索到了
