### ISSUE TITLE
打包图标异常！！！

### ISSUE THREAD

**Issue by ZhengchaoCao** [kkevsekk1/AutoX#289]
608打包图标配置有问题！，打包后启动界面图标变成了软件图标，，而且启动图标没显示。启动界面一片空白！

**Comment by ZhengchaoCao** [comment]
> ？
> ![Screenshot_2022-05-30-23-31-59-754_com android settings](https://user-images.githubusercontent.com/59408438/171024255-78f3f2f4-262c-49ed-a9a2-9949569c167b.jpg)
> 

你什么版本，

**Comment by ZhengchaoCao** [comment]
我再重新下来看看，，😓，用检测了我用的居然是606![Screenshot_20220530-234632.jpg](https://user-images.githubusercontent.com/39791246/171026252-59031388-3d12-4110-92e3-7c7c5301c943.jpg)

**Comment by wilinz** [comment]
6.0.8构建时没调整版本号

**Comment by wilinz** [comment]
所以显示的还是6.0.6

**Comment by ZhengchaoCao** [comment]
有没有，大佬研究一下什么问题呀，我试了许多次，就是有问题，是bug，，，，，，，，打包单文件正常！！！！！但是打包文件夹就是图标出错，启动界面界面变成软件图标，，然后打开打包的软件启动界面就是一片空白，

**Comment by ZhengchaoCao** [comment]
@kkevsekk1

**Comment by wilinz** [comment]
多文件打包不完善hhh，我没有时间维护

**Comment by kkevsekk1** [comment]
应该是资源文件替换出了问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： ZhengchaoCao ***@***.***>
日期: 2022/6/1 01:41 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包图标异常！！！ (Issue #289)


有没有，大佬研究一下什么问题呀，我试了许多次，就是有问题，是bug，，，，，，，，打包单文件正常！！！！！但是打包文件夹就是图标出错，启动界面界面变成软件图标，，然后打开打包的软件启动界面就是一片空白，

―

**Comment by ZhengchaoCao** [comment]
@wilinz @kkevsekk1 这是我打包的json文件内容，我用以前老版本没有问题。，就最近的新版有问题！![Screenshot_20220601-132415.jpg](https://user-images.githubusercontent.com/39791246/171333912-7a82a31a-eb88-4314-bfb8-a255fbfe0886.jpg)

**Comment by kkevsekk1** [comment]
把json 贴一份出来，只有程序运行起来排查，现在肉眼看不出任何问题

**Comment by wilinz** [comment]
新版本打包多文件未完善
