### ISSUE TITLE
可以在电脑上用vscode生成apk文件吗？

### ISSUE THREAD

**Issue by zhupengfeivip** [kkevsekk1/AutoX#29]
现在是在手机上生成apk文件的，可以在电脑上用vscode生成apk文件吗？
怎么操作呢？

**Comment by kkevsekk1** [comment]
vscode不可以，你可以安装android 开发环境，可以编译出apk

**Comment by zhupengfeivip** [comment]
Ok，我大概明白了，有没有进一步的操作方法或者资料呢，或者大概的方法说明一下？谢谢大佬指点。

**Comment by kkevsekk1** [comment]
这个是就是一anroid app，所有要指定怎么编译，你搞明白anroid开发 就可以了，要学习java安卓开发
