### ISSUE TITLE
现在不支持x86? Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

### ISSUE THREAD

**Issue by haleyrom** [kkevsekk1/AutoX#294]
[INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by wilinz** [comment]
你可以手动编译，修改build.gradle就可以了

**Comment by haleyrom** [comment]
怎么编译呢，小白一只

**Comment by haleyrom** [comment]
导入项目一堆报错，本地起不来
![image](https://user-images.githubusercontent.com/17995614/171549564-e62df0ce-f044-4c34-aa19-988ce65daa07.png)

**Comment by LZX284** [comment]
@haleyrom  黄色的感叹号只是警告，不影响编译成功。
不过x86架构的话可能无法使用OCR，因为百度官方在移动端也只支持了 arm64-v8a和armeabi-v7a 两种架构（2.5版只支持arm64-v8a）
这是x86_64的包，你可以试一下：[AutoX_x86_64(test)](https://github.com/LZX284/AutoX/releases/tag/x86_64(test))
