### ISSUE TITLE
http不能正常使用

### ISSUE THREAD

**Issue by basiiis** [kkevsekk1/AutoX#297]
` Wrapped java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close() (file:///android_asset/modules/__http__.js#49)`

**Comment by LZX284** [comment]
@basiiis  没有具体代码的话不好判断是脚本的问题还是app的问题。不知道6.0.9版能不能正常使用？

**Comment by LZX284** [comment]
@basiiis  尝试修复了一下，你试一下看看这个测试版有没有修复你说的问题：[AutoX_arm64-v8a(测试http模块问题修复情况)](https://github.com/LZX284/AutoX/releases/tag/test)

**Comment by kkevsekk1** [comment]
已解决
