### ISSUE TITLE
使用vue作为页面展示，报路径不存在

### ISSUE THREAD

**Issue by 710850609** [kkevsekk1/AutoX#3]
基于 https://github.com/kkevsekk1/webpack-autojs 的webpack + vant 作为页面展示，autox可以正常显示页面，但打包后，报文件路径不存在
![image](https://user-images.githubusercontent.com/9523566/93471034-61509a80-f925-11ea-8ad3-fb2969781b88.png)

**Comment by kkevsekk1** [comment]
你这个打包出来不是单文件，可能是这个原因







在 2020-09-17 19:38:35，"BoB" <notifications@github.com> 写道：

基于 https://github.com/kkevsekk1/webpack-autojs 的webpack + vant 作为页面展示，autox可以正常显示页面，但打包后，报文件路径不存在

**Comment by 710850609** [comment]
是的。因为引入的是vant框架写多页面（使用路由）。自动打包成多个子文件

**Comment by 710850609** [comment]
> 你这个打包出来不是单文件，可能是这个原因 在 2020-09-17 19:38:35，"BoB" <notifications@github.com> 写道： 基于 https://github.com/kkevsekk1/webpack-autojs 的webpack + vant 作为页面展示，autox可以正常显示页面，但打包后，报文件路径不存在 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

现在情况是autojsx可以跑多文件的vue，但打包后不行。我怀疑是底包的问题

**Comment by kkevsekk1** [comment]
4.2.2 会升级一下template.apk

**Comment by 710850609** [comment]
> 4.2.2 会升级一下template.apk

我发现webview页面里面只要加载本地的js，都是会报错。
我怀疑是，aj打包后，凡是js文件，都会被加密，一旦webview加载本地js，都没有经过aj解密。从此造成webview加载js运行失败

**Comment by 710850609** [comment]
作者你好，已经发现是免费版本打包会对所有js文件进行加密（这里包括了vue或是其他html页面使用到的js），导致webview使用file协议加载的js都是加密后的js，运行就报错了。
