### ISSUE TITLE
生面的apk文件在电脑上被认为是不安全的，如何解决？

### ISSUE THREAD

**Issue by zhupengfeivip** [kkevsekk1/AutoX#30]
生面的apk文件在电脑上，被QQ安全管家认为是不安全的，直接提示有病毒
![image](https://user-images.githubusercontent.com/30720809/105258964-d4189d80-5bc5-11eb-8112-96b7c289a2b6.png)

**Comment by kkevsekk1** [comment]
你这个应该，用正版autox 生成的。或者你下载autox的时候遭到了域名劫持之类攻击

**Comment by pboymt** [comment]
Auto.js被腾讯加到黑名单了，apk里面的关键二进制特征和Auto.js还是一样

**Comment by Rsweater** [comment]
> 你这个应该，用正版autox 生成的。或者你下载autox的时候遭到了域名劫持之类攻击

如果是正版autox生成报毒，该咋解决？

**Comment by Rsweater** [comment]
> 你这个应该，用正版autox 生成的。或者你下载autox的时候遭到了域名劫持之类攻击

我用autox打包的apk。荣耀10手机显示“该应用已感染病毒”

**Comment by 1965514404** [comment]
可以试试重新签名

**Comment by Rsweater** [comment]
> 可以试试重新签名
现在是不良信息      改签名之前显示不良信息，后就变成被感染了。内容应该没问题

**Comment by Rsweater** [comment]
> 可以试试重新签名

也不行

**Comment by zhupengfeivip** [comment]
我个人觉得这个人是否正版是没有关系的。pboymt 的回答可能是正常的。auto生成的apk文件的二进制特征，被一些杀毒软件加入到了黑名单，所以只要是auto,autox生成的都是一样的。

可以放心使用。

国内某些杀软厂家只要不交钱，就会提示不安全，或者不确定是否安全，只要交费了，成为会员，所有开发软件就会显示绿色，这是厂家一些伎俩。

**Comment by zhupengfeivip** [comment]
> 你这个应该，用正版autox 生成的。或者你下载autox的时候遭到了域名劫持之类攻击

您说的正版是指从官方下载的安装文件吧？auto,autox我都是从官方下载的，我用火绒没有提示，我朋友用腾讯杀软提示的。

**Comment by 66ling66** [comment]
为什么我手机微信支付环境会显示异常？
