### ISSUE TITLE
RhinoJS 新版本以及与AutoX相关的版权问题

### ISSUE THREAD

**Issue by LZX284** [kkevsekk1/AutoX#302]
[RhinoJS](https://github.com/mozilla/rhino) 新版本1.7.14，带来了模板字符串等多种特性，并修复了多个bug。似乎Auto.js Pro也早已经把Rhino引擎升级到1.7.14了，AutoX目前在用的是1.7.13版，不知道有没有更新的需要？

**Comment by LZX284** [comment]
有一个比较重要的问题，RhinoJS 的开源许可是 Mozilla Public License Version 2.0， @kkevsekk1 已经解释得很清楚了，“如果你仅使用了MPL-2.0 的东西，你需要开源你修改过的相关代码”，RhinoJS 较新版本的引擎(包括1.7.13 及  1.7.14) 是无法不修改直接用在auto.JS上的（新版的XML解析协议会导致auto.JS的UI模块无法使用），AutoX目前在用的是1.7.13版但并没有开源修改过的源码，这一点明确违反了 MPL-2.0 的 规定，所以这里建议 @kkevsekk1  在项目里补上修改过的RhinoJS源码。另外，Auto.js Pro目前应该是完全闭源的吧，但不知道他们是不是用了修改过的  RhinoJS1.7.14（不改的话auto.JS的UI模块就会直接报错），或者他们是不是已经开源了相关源码？

**Comment by kkevsekk1** [comment]
现在13是没有修改其源码的，可以直接使用，14不可以，或者使用14将不兼容以前的脚本，不建议升级到14，升级到14必须修改autox核心代码，且不好兼容旧版本js代码



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/6/3 16:05 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] RhinoJS 新版本以及旧版的版权问题 (Issue #302)


有一个比较重要的问题，RhinoJS 的开源许可是 Mozilla Public License Version 2.0， @kkevsekk1<https://github.com/kkevsekk1> 已经解释得很清楚了，“如果你仅使用了MPL-2.0 的东西，你需要开源你修改过的相关代码”，RhinoJS 较新版本的引擎(包括1.7.13 及 1.7.14) 是无法不修改直接用在auto.JS上的（新版的XML解析协议会导致auto.JS的UI模块无法使用），AutoX目前在用的是1.7.13版但并没有开源修改过的源码，这一点明确违反了 MPL-2.0 的 规定，所以这里建议 @kkevsekk1<https://github.com/kkevsekk1> 在项目里补上修改过的RhinoJS源码。另外，Auto.js Pro目前应该是完全闭源的吧，但不知道他们是不是用了修改过的 RhinoJS1.7.14（不改的话auto.JS的UI模块就会直接报错），或者他们是不是已经开源了相关源码？

―

**Comment by LZX284** [comment]
> 现在13是没有修改其源码的，可以直接使用，14不可以，或者使用14将不兼容以前的脚本，不建议升级到14，升级到14必须修改autox核心代码，且不好兼容旧版本js代码 发送自我的盖乐世

@kkevsekk1 你可以下载官方提供的jar包放到项目里，运行一下UI模块的脚本就知道有没有修改了。另外，Auto.js Pro 是闭源的，但用的  RhinoJS1.7.14 肯定是需要经过修改的，否则UI模块根本就没法用，不过就国内这开源环境，哪怕它违反开源协议使用开源代码（由于不开源，真用了你也不一定看得出来），大概也没有什么人会去管的……

**Comment by LZX284** [comment]
@kkevsekk1 这个问题并不难，但如果不解决的话，个人感觉这样做并不好，毕竟是直接违反了开源协议规定。
而且 RhinoJS除了XML语法上有一点不兼容，其它方面的改进也是很重要的。比如，在 [auto.js M](https://github.com/TonyJiangWJ/Auto.js) 项目里 就用了 RhinoJS 1.7.14 并且同时提供了源代码：[rhino-jdk7](https://github.com/TonyJiangWJ/Auto.js/tree/main/autojs-aar/rhino-jdk7)
以此参照，AutoX 升级到 RhinoJS 1.7.14 应该是 利大于弊的。
另外，AutoX 的文档还是需要一点维护的，而且 @wangwang-code 好不容易提交了一个 [PR](https://github.com/kkevsekk1/kkevsekk1.github.io/pull/11) 这都已经快一个星期过去了，行或不行希望至少能给个回复，一直挂在那里让人感觉很奇怪呀……

**Comment by kkevsekk1** [comment]
![Screenshot_20220604-235159_Samsung Internet](https://user-images.githubusercontent.com/16631944/172013643-dd8337de-85ba-490f-9313-1b317ee0f92f.jpg)
我这里没有pr要处理
