### ISSUE TITLE
6.0.10 打包好的apk离奇失踪

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#303]
打包好后在相应的路径下没有找到apk 但点击安装却能正常安装 而且还有删除安装包的选项

**Comment by LZX284** [comment]
@wangwang-code 不知道是不是更新导致的，有空的话帮忙测试一下，看这个版本有没有出现这个问题：[AutoX_arm64-v8a(测试http模块问题修复情况)](https://github.com/LZX284/AutoX/releases/tag/test)

**Comment by wangwang-code** [comment]
> @wangwang-code 不知道是不是更新导致的，有空的话帮忙测试一下，看这个版本有没有出现这个问题：[AutoX_arm64-v8a(测试http模块问题修复情况)](https://github.com/LZX284/AutoX/releases/tag/test)

出现了

**Comment by LZX284** [comment]
> 出现了

有没有什么异常或报错信息？

**Comment by wangwang-code** [comment]
> > 出现了
> 
> 有没有什么异常或报错信息？

没有，直到我想要发送apk到电脑上时我才发现在路径下找不到apk

**Comment by LZX284** [comment]
> 没有，直到我想要发送apk到电脑上时我才发现在路径下找不到apk

路径是什么样的？试试手动输入 “/sdcard/” 这样的路径看会不会出错？

**Comment by wangwang-code** [comment]
> > 没有，直到我想要发送apk到电脑上时我才发现在路径下找不到apk
> 
> 路径是什么样的？试试手动输入 “/sdcard/” 这样的路径看会不会出错？

仍然没有任何报错 打包成功但在`/sdcard/`下依旧找不到apk

**Comment by LZX284** [comment]
> 仍然没有任何报错 打包成功但在`/sdcard/`下依旧找不到apk

@wangwang-code 测试了下，打包一个普通的对话框脚本，没有出现你说的问题，你再看看你打包的文件名或是手机系统等有没有什么特别之处？

**Comment by wangwang-code** [comment]
> > 仍然没有任何报错 打包成功但在`/sdcard/`下依旧找不到apk
> 
> @wangwang-code 测试了下，打包一个普通的对话框脚本，没有出现你说的问题，你再看看你打包的文件名或是手机系统等有没有什么特别之处？

灵异事件 我打包一个 test.js 到脚本/目录下就正常 但是如果打包1.js 到脚本/1_v1.0.0.apk 就不正常

**Comment by wangwang-code** [comment]
打包 test.js 如果应用名称和 脚本名称不一致就不正常

**Comment by LZX284** [comment]
> 灵异事件 我打包一个 test.js 到脚本/目录下就正常 但是如果打包1.js 到脚本/1_v1.0.0.apk 就不正常

一般都没什么灵异的，最多就是我们还不理解而已。根据我的经验，这种情况有可能是文件名中的特殊符号引起打包程序逻辑中潜在的bug，比如“.”这类符号，如果文件名以此开头，在linux或Android系统中就是隐藏文件，一般情况下不可见（需要在文件管理器中设置）

**Comment by wangwang-code** [comment]
> > 灵异事件 我打包一个 test.js 到脚本/目录下就正常 但是如果打包1.js 到脚本/1_v1.0.0.apk 就不正常
> 
> 一般都没什么灵异的，最多就是我们还不理解而已。根据我的经验，这种情况有可能是文件名中的特殊符号引起打包程序逻辑中潜在的bug，比如“.”这类符号，如果文件名以此开头，在linux或Android系统中就是隐藏文件，一般情况下不可见（需要在文件管理器中设置）

MT管理器 显示隐藏文件 √ 

打包 test.js 应用名称 test 正常  应用名称 1 不正常

**Comment by LZX284** [comment]
> 打包 test.js 如果应用名称和 脚本名称不一致就不正常

多测试几次，如果应用名称和 脚本名称不一致就会引发问题，那看来就是打包程序逻辑不完善导致的问题 @wilinz

**Comment by wangwang-code** [comment]
> > 打包 test.js 如果应用名称和 脚本名称不一致就不正常
> 
> 多测试几次，如果应用名称和 脚本名称不一致就会引发问题，那看来就是打包程序逻辑不完善导致的 @wilinz

就是 文件已经输出到路径  但就是看不到 （ 新建一个项目 test 但看不到 main.js  想创建一个提升 文件已存在

**Comment by wangwang-code** [comment]
问题好像被重启解决了 不过重启的时候差点起不来 重启后重新打开autoX.js [dev] 不见的文件又回来了

**Comment by wangwang-code** [comment]
当发现车子打不火着时，我们应用尝试先下车然后再上车，然后就能打火了（（（（（（

**Comment by LZX284** [comment]
> 问题好像被重启解决了 不过重启的时候差点起不来 重启后重新打开autoX.js [dev] 不见的文件又回来了

可能是文件系统缓存没有更新吧？这是手机系统的问题，华为手机连接电脑时就曾经发现过类似现象，也是重启后就能解决了

**Comment by wangwang-code** [comment]
> > 问题好像被重启解决了 不过重启的时候差点起不来 重启后重新打开autoX.js [dev] 不见的文件又回来了
> 
> 可能是文件系统缓存没有更新吧？这是手机系统的问题，华为手机连接电脑时就曾经发现过类似现象，也是重启后就能解决了

离离原上谱 创建文件倒是提示文件已存在 yee~~

**Comment by wangwang-code** [comment]
有一点： 重启后不打开autoX.js 直接去MT管理器里看不到 需要打开AutoX.js后才能看的到

**Comment by wangwang-code** [comment]
@LZX284 @wilinz 又出现了 文件存在 但看不到

**Comment by wangwang-code** [comment]
安卓7 原生貌似没发生 手机物理机安卓11 就得重启 才行 恼

**Comment by wangwang-code** [comment]
我在思考 文件写入是不是被丢到异步里了 我重启手机后 打开autox.js[dev]要等一会刷新才能看到文件

**Comment by LZX284** [comment]
> 我在思考 文件写入是不是被丢到异步里了 我重启手机后 打开autox.js[dev]要等一会刷新才能看到文件

不打开autox.js[dev]的话就一直看不到吗？

**Comment by wangwang-code** [comment]
> > 我在思考 文件写入是不是被丢到异步里了 我重启手机后 打开autox.js[dev]要等一会刷新才能看到文件
> 
> 不打开autox.js[dev]的话就一直看不到吗？

对

**Comment by wangwang-code** [comment]
我可以确定这个bug就更新造成的 已经第3次发生了

**Comment by LZX284** [comment]
> 我可以确定这个bug就更新造成的 已经第3次发生了

@wangwang-code 看看这个版本有没有解决这个问题[AutoX_arm64-v8a(test-apk离奇失踪事件)](https://github.com/LZX284/AutoX/releases/tag/test-apk%E7%A6%BB%E5%A5%87%E5%A4%B1%E8%B8%AA%E4%BA%8B%E4%BB%B6)

**Comment by wangwang-code** [comment]
> > 我可以确定这个bug就更新造成的 已经第3次发生了
> 
> @wangwang-code 看看这个版本有没有解决这个问题：[AutoX_arm64-v8a(test-apk离奇失踪事件)](https://github.com/LZX284/AutoX/releases/tag/test-apk%E7%A6%BB%E5%A5%87%E5%A4%B1%E8%B8%AA%E4%BA%8B%E4%BB%B6)

没有

**Comment by LZX284** [comment]
> 没有

@wangwang-code  有点奇怪，这边测试时都没有发现这个问题，或许是和安卓系统版本有关，你看看别的系统手机上有没有出现这个问题？

**Comment by wangwang-code** [comment]
> > 没有
> 
> @wangwang-code 有点奇怪，这边测试时都没有发现这个问题，或许是和安卓系统版本有关，你看看别的系统手机上有没有出现这个问题？

vmos开虚拟机没有出现 但这个问题至少在6.0.8没有出现

**Comment by LZX284** [comment]
> vmos开虚拟机没有出现 但这个问题至少在6.0.8没有出现

 6.0.9 也会吗？这个版本相对于 6.0.8 只调整了UI和加入了TBS依赖

**Comment by wangwang-code** [comment]
> > vmos开虚拟机没有出现 但这个问题至少在6.0.8没有出现
> 
> 6.0.9 也会吗？这个版本相对于 6.0.8 只调整了UI和加入了TBS依赖

6.0.9 出现

**Comment by wangwang-code** [comment]
6.0.8 也出现了

**Comment by wangwang-code** [comment]
![0X5L6H0U(_V)EACHMG)S@LO](https://user-images.githubusercontent.com/64469117/171996644-5243bb6d-5de6-44a3-a6df-be4f31ed7db3.jpg)

**Comment by wangwang-code** [comment]
重启 如果不打开 autox.js 在MT管理器 同 构建文件夹下 删除文件能刷新出来

**Comment by LZX284** [comment]
> 6.0.8 也出现了

不是吧？？？难道非要直接回退到 6.0.6 才行吗？

**Comment by wangwang-code** [comment]
删除构建文件夹 删除构建文件同目录下的其他文件（夹） 前面删除的构建文件夹又出现了

**Comment by LZX284** [comment]
> 删除构建文件夹 删除构建文件同目录下的其他文件（夹） 前面删除的构建文件夹又出现了

这……

**Comment by wangwang-code** [comment]
6.0.7 未出现

**Comment by wangwang-code** [comment]
我感觉 要破案了

**Comment by wangwang-code** [comment]
![Screenshot_20220604_193013](https://user-images.githubusercontent.com/64469117/171997122-ef4c6125-cc1e-4131-a77e-bf7645bd3290.jpg)
不要给这权限，手动到权限设置里给存储权限

**Comment by LZX284** [comment]
> 不要给这权限，手动到权限设置里给存储权限

@wangwang-code 问题完全解决了吗？这权限似乎是 安卓11+ 访问内置存储的必要权限，否则 auto.js 可能读取不了SD卡目录下的文件，不知道改变权限后文件读写是否正常？

**Comment by wangwang-code** [comment]
> > 不要给这权限，手动到权限设置里给存储权限
> 
> @wangwang-code 问题完全解决了吗？这权限似乎是 安卓11+ 访问内置存储的必要权限，否则 auto.js 可能读取不了SD卡目录下的文件，不知道改变权限后文件读写是否正常？

是的，无论是创建文件还是打包项目，都正常了

**Comment by LZX284** [comment]
> 是的，无论是创建文件还是打包项目，都正常了

惊人的发现，这个权限竟然不是完全必要的。看来权限适配方案必须调整一下了

**Comment by wangwang-code** [comment]
> > 是的，无论是创建文件还是打包项目，都正常了
> 
> 惊人的发现，这个权限竟然不是完全必要的。看来权限适配方案必须调整一下了

甚至带来了副作用

**Comment by wangwang-code** [comment]
> > 是的，无论是创建文件还是打包项目，都正常了
> 
> 惊人的发现，这个权限竟然不是完全必要的。看来权限适配方案必须调整一下了

情况一: 只`授予储存权限`，不授予`授权所有文件的管理权限`——正常

情况二: `授予储存权限`和`授权所有文件的管理权限`——不正常

情况三: 只授予`授权所有文件的管理权限`——不正常

**Comment by wangwang-code** [comment]
应该是次提交加的功能（BUG）

https://github.com/kkevsekk1/AutoX/commit/eb6fcee860d649f7aab2210e92289fe594eb8e60

https://github.com/kkevsekk1/AutoX/blob/eb6fcee860d649f7aab2210e92289fe594eb8e60/app/src/main/java/org/autojs/autojs/ui/main/MainActivity.java

**Comment by LZX284** [comment]
> 情况一: 只`授予储存权限`，不授予`授权所有文件的管理权限`——正常
> 
> 情况二: `授予储存权限`和`授权所有文件的管理权限`——不正常
> 
> 情况三: 只授予`授权所有文件的管理权限`——不正常

权限适配方案暂时准备调整如下：
默认申请“储存权限”，接着询问用户是否授予`所有文件的管理权限`并提示该权限可能引发文件读写异常，让用户自己选择是否授权（不确定是否所有新系统都不需要该权限就能正常读写文件，所以加了这一步骤）
@wangwang-code  不知道这样调整是否可以？

**Comment by wangwang-code** [comment]
> > 情况一: 只`授予储存权限`，不授予`授权所有文件的管理权限`——正常
> > 情况二: `授予储存权限`和`授权所有文件的管理权限`——不正常
> > 情况三: 只授予`授权所有文件的管理权限`——不正常
> 
> 权限适配方案暂时准备调整如下： 默认申请“储存权限”，接着询问用户是否授予`所有文件的管理权限`并提示该权限可能引发文件读写异常，让用户自己选择是否授权（不确定是否所有新系统都不需要该权限就能正常读写文件，所以加了这一步骤） @wangwang-code 不知道这样调整是否可以？

主要问题在于 如果 授予`所有文件的管理权限` 后发现读写异常 就没法返回去撤销授予`所有文件的管理权限` 这个权限是由AutoX.js发起的 大部分系统管理都找不到这个权限在哪里设置

**Comment by LZX284** [comment]
> 主要问题在于 如果 授予`所有文件的管理权限` 后发现读写异常 就没法返回去撤销授予`所有文件的管理权限` 这个权限是由AutoX.js发起的 大部分系统管理都找不到这个权限在哪里设置

这确实是个问题，重装APP应该可以撤销授权，只是会比较麻烦……

**Comment by wangwang-code** [comment]
> > 主要问题在于 如果 授予`所有文件的管理权限` 后发现读写异常 就没法返回去撤销授予`所有文件的管理权限` 这个权限是由AutoX.js发起的 大部分系统管理都找不到这个权限在哪里设置
> 
> 这确实是个问题，重装APP应该可以撤销授权，只是会比较麻烦……

可以先申请`“储存权限”` 并提示用户如果读取异常再尝试手动（一个按钮发起）申请 `授予所有文件的管理权限`

**Comment by wangwang-code** [comment]
毕竟各大厂商都对自己的安卓固件进行了深度魔改 说不定就不按照谷歌的干了

**Comment by LZX284** [comment]
> 毕竟各大厂商都对自己的安卓固件进行了深度魔改 说不定就不按照谷歌的干了

这就导致了APP适配机型时麻烦很多，有的甚至还难以解决……
看看这个版本的怎么样：[test-apk离奇失踪事件破案及权限适配方案优化](https://github.com/LZX284/AutoX/releases/tag/test-apk%E7%A6%BB%E5%A5%87%E5%A4%B1%E8%B8%AA%E4%BA%8B%E4%BB%B6%E7%A0%B4%E6%A1%88%E5%90%8E%E7%BB%AD)

**Comment by wangwang-code** [comment]
> > 毕竟各大厂商都对自己的安卓固件进行了深度魔改 说不定就不按照谷歌的干了
> 
> 这就导致了APP适配机型时麻烦很多，有的甚至还难以解决…… 看看这个版本的怎么样：[test-apk离奇失踪事件破案及权限适配方案优化](https://github.com/LZX284/AutoX/releases/tag/test-apk%E7%A6%BB%E5%A5%87%E5%A4%B1%E8%B8%AA%E4%BA%8B%E4%BB%B6%E7%A0%B4%E6%A1%88%E5%90%8E%E7%BB%AD)

可以 另外 发现 `所以文件访问权限` 按钮 在给予权限后这个按钮还能跳转到 `所以文件访问权限`页面

**Comment by kkevsekk1** [comment]
1.在6到9中使用代码动态申请权限，即可访问所有文件
2.在10当中可以在配置中可以关闭分区存储，就能像1，动态申请，即可一样访问文件
3.在11以上，申请 “所有文件访问权限“，无需再执行1，2的动态申请
注意安卓10是个过度版，不能像，11一样处理，只在配置中关闭，然后像9一样动态申请

**Comment by wangwang-code** [comment]
> 1.在6到9中使用代码动态申请权限，即可访问所有文件 2.在10当中可以在配置中可以关闭分区存储，就能像1，动态申请，即可一样访问文件 3.在11以上，申请 “所有文件访问权限“，无需再执行1，2的动态申请 注意安卓10是个过度版，不能像，11一样处理，只在配置中关闭，然后像9一样动态申请

我看了看手机的安卓版本 11 ······

**Comment by kkevsekk1** [comment]
所以现在改动方法，就是在配置中添加禁用，6-10中提醒动态申请，11以上弹出    所有文件访问权限

**Comment by wangwang-code** [comment]
> 所以现在改动方法，就是在配置中添加禁用，6-10中提醒动态申请，11以上弹出 所有文件访问权限

我手机上申请“所有文件访问权限”就发生读取BUG 安卓7好像没这个`所有文件访问权限`

**Comment by kkevsekk1** [comment]
安卓7，按照老版本申请即可



发送自我的盖乐世



-------- 原始信息 --------
发件人： wangwang-code ***@***.***>
日期: 2022/6/5 12:56 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 6.0.10 打包好的apk离奇失踪 (Issue #303)


所以现在改动方法，就是在配置中添加禁用，6-10中提醒动态申请，11以上弹出 所有文件访问权限

我手机上申请“所有文件访问权限”就发生读取BUG 安卓7好像没这个所有文件访问权限

―

**Comment by Warm-rain** [comment]
miui系统权限问题，其实我发现很多应用都有这情况，大家用的时候多留个心眼，不然这个问题真的很难发现

**Comment by wangwang-code** [comment]
> miui系统权限问题，其实我发现很多应用都有这情况，大家用的时候多留个心眼，不然这个问题真的很难发现

国内的都这样
