### ISSUE TITLE
模拟器里截图无画面

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#304]
截图
![image](https://user-images.githubusercontent.com/64469117/171994868-b6b4b48b-aed3-4019-87a1-153758f6e3ee.png)

图片文件
![image](https://user-images.githubusercontent.com/64469117/171994901-29d17836-ecb5-4e1c-a5e9-8b191d72507c.png)

**Comment by LZX284** [comment]
@wangwang-code 先看看模拟器里截图是否成功？或者，先将截图的图片保存下来，再用images.read读取看看行不行？

**Comment by wangwang-code** [comment]
截图images.save(img, "/sdcard/1.jpg", "jpg", 50);保存 黑没有画面

**Comment by LZX284** [comment]
> 截图images.save(img, "/sdcard/1.jpg", "jpg", 50);保存 黑没有画面

那就是截图失败了，OCR应该没有问题

**Comment by wangwang-code** [comment]
@LZX284 要不考虑修下这个?

**Comment by sunshinewithmoonlight** [comment]
macOS版夜神模拟器（Nox Player）截图失败，保存的jpg文件是黑色，png文件是透明的。
夜神模拟器 3.8.5.7（Android 7.1.2）
AutoJSX 6.5.8

**Comment by sunshinewithmoonlight** [comment]
> macOS版夜神模拟器（Nox Player）截图失败，保存的jpg文件是黑色，png文件是透明的。 夜神模拟器 3.8.5.7（Android 7.1.2） AutoJSX 6.5.8
> 
> ```
> requestScreenCapture(true);
> var nowScreen = captureScreen("/sdcard/1.jpg");
> ```

实际上，shell命令就足够用了，`true`保证截图在读取前已经保存。

```
var result = shell("screencap -p /sdcard/1.jpg", true);
var nowScreen = images.read("/sdcard/1.jpg");
```
