### ISSUE TITLE
新版打包应用权限怎么变多了！

### ISSUE THREAD

**Issue by ZhengchaoCao** [kkevsekk1/AutoX#305]
新版打包怎么多那么多权限😱😱😱，，，能不能在打包那里添加打包权限管理呀。选着需要的权限一起打包。

**Comment by LZX284** [comment]
@ZhengchaoCao  更多的权限是给有需要的脚本提供的，不需要可以不勾选。添加选项应该可以，不过目前开发者正处于考试期间，可能没时间处理这个问题……

**Comment by wilinz** [comment]
权限是可选的

**Comment by ZhengchaoCao** [comment]
打包软件权限设置在哪里呀，不想打包的软件安装时显示一大堆权限？

**Comment by wilinz** [comment]
???你不需要就取消勾选就好了
![Screenshot_2022-06-12-18-07-22-795_org autojs autojs dev](https://user-images.githubusercontent.com/59408438/173228245-440c439d-2261-4b6d-9ea7-1c910c7b5826.png)

**Comment by ZhengchaoCao** [comment]
我说的是这些权限😂😂😂，有没有编辑器，怎么取消![Screenshot_2022-06-12-18-28-59-669_com.miui.packageinstaller.jpg](https://user-images.githubusercontent.com/39791246/173229057-88a809b9-60e2-4996-9f2e-efd47e7fa431.jpg)

**Comment by wilinz** [comment]
取消不了，这些不是运行时权限，默认声明了

**Comment by wangwang-code** [comment]
主要是懒，快关issue吧
