### ISSUE TITLE
两脚本不同设备间的通信

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#307]
不知道现在的AutoX支不支持nodejs，如果有那就好

没有的话想让两个脚本相互通信就很麻烦 用ws的话 如何创建ws服务端是个麻烦事 okhttp官网也没有找到 创建ws服务端的示例

反正就人很麻

**Comment by LZX284** [comment]
@wangwang-code Auto.JS Pro 是支持的，就是不知道用起来怎样？

**Comment by wangwang-code** [comment]
> @wangwang-code Auto.JS Pro 是支持的，就是不知道用起来怎样？

那玩意要钱 还得能进行国际交易才行，比如得有双币信用卡等等的

**Comment by wangwang-code** [comment]
目要研究下如果如何创建 ws服务端 正好需要TCP长连接来传递文本

**Comment by LZX284** [comment]
> 那玩意要钱 还得能进行国际交易才行，比如得有双币信用卡等等的

AutoX可以尝试添加nodejs支持，但就怕加入后会导致APP不稳定或引起更多难以解决的Bug，而目前参与AutoX开发的开发者并不多，想要解决这些问题恐怕有点麻烦啊……

**Comment by wangwang-code** [comment]
创建ws服务端有亿点麻烦 前提得能创建http服务端 用nodejs会方便许多

**Comment by wangwang-code** [comment]
我横看竖看都只能创建客户端 恼 一个月前的想法 只是空想罢了

**Comment by kkevsekk1** [comment]
跨进程信，那么多方法，没必要搞个nodejs ，用okhttp的ws创建服务端和客户端，没有任何难度！

**Comment by wangwang-code** [comment]
> 跨进程信，那么多方法，没必要搞个nodejs ，用okhttp的ws创建服务端和客户端，没有任何难度！

so 去把ws文档完善一下?

**Comment by kkevsekk1** [comment]
百度一篇java的okhttp，websocket服务端，看懂了，再改写成js丢进去运行即可

**Comment by wangwang-code** [comment]
> 百度一篇java的okhttp，websocket服务端，看懂了，再改写成js丢进去运行即可

java我不咋懂

**Comment by wangwang-code** [comment]
> 百度一篇java的okhttp，websocket服务端，看懂了，再改写成js丢进去运行即可

https://blog.csdn.net/weixin_39963830/article/details/110467481#t7 

不知道能不能用MockWebSocket 服务，来模拟服务端。

**Comment by wangwang-code** [comment]
> 百度一篇java的okhttp，websocket服务端，看懂了，再改写成js丢进去运行即可

okhttp3只是用来发送请求 哪怕用MockWebSocket也得导入`com.squareup.okhttp3:mockwebserver`

_要不是我的play支付不了，我早就在用pro了_

**Comment by wilinz** [comment]
ktor websocket 了解一下，ktor是kotlin写的一个http服务框架，https://ktor.io/docs/websocket.html#api-overview

**Comment by wilinz** [comment]
别搞什么nodejs，改动太大，风险太大

**Comment by wilinz** [comment]
有时间可以集成ktor server

**Comment by wilinz** [comment]
或者也可以直接使用 tcp socket 通信

**Comment by wilinz** [comment]
js 直接调用java socket Api 进行通信即可

**Comment by wilinz** [comment]
while (true) {
    let s = java.net.ServerSocket()
    s.bind(java.net.InetSocketAddress(12345))
    let client = s.accept()
    threads.start(serve(client))
}

function serve(client) {
    let input = client.getInputStream()
    let output = client.getOutputStream()
    let buffReader = java.io.BufferedReader(java.io.InputStreamReader(input, "utf-8"))
    let ps=java.io.PrintStream(output)
    while (true) {
        //read meessage
        let message = buffReader.readLine()
        if (message == null) break
        else {
            log("客户端发来消息: " + message)
            ps.println("服务端已收到")
        }
    }
}

**Comment by wilinz** [comment]
val socket = java.net.Socket()
connect(socket)

function connect(socket) {
    socket.setSoTimeout(10000)
    socket.connect(java.net.InetSocketAddress("127.0.0.1", 12345))
    let input = socket.getInputStream()
    let output = socket.getOutputStream()
    let buffReader = java.io.BufferedReader(java.io.InputStreamReader(input, "utf-8"))
    let ps = java.io.PrintStream(output)
    threads.start(ping(ps))
    while (true) {
        //read meessage
        let message = buffReader.readLine()
        if (message == null) break
        else {
            log("服户端发来消息: " + message)
            ps.println("客务端已收到")
        }
    }
}

function ping(ps) {
    while (true) {
        ps.println("你好，我是客户端")
        sleep(2000)
    }
}

**Comment by wilinz** [comment]
![Uploading Screenshot_2022-06-06-13-47-39-397_org.autojs.autojs.dev.jpg…]()

**Comment by wilinz** [comment]
![Uploading Screenshot_2022-06-06-13-47-39-397_org.autojs.autojs.dev.jpg…]()

**Comment by wilinz** [comment]
![Uploading Screenshot_2022-06-06-13-47-39-397_org.autojs.autojs.dev.jpg…]()

**Comment by wangwang-code** [comment]
@wilinz 赶紧去完善文档啊

**Comment by wangwang-code** [comment]
> > @wilinz 赶紧去完善文档啊 这不比ws好用
> 
> 我没时间，考试周

测试了下客户端好像不输出服务端的消息耶

**Comment by wilinz** [comment]
threads.start()阻塞了，多线程似乎有点问题

**Comment by wilinz** [comment]
代码已更新，正常运行，之前threads.start不支持传参导致阻塞

**Comment by Warm-rain** [comment]
这真是一个好方法

**Comment by wilinz** [comment]
目前存在的问题，强行停止脚本导致调用close()不起作用，导致停止运行之后端口还被占用，无法再次运行

**Comment by wangwang-code** [comment]
> 目前存在的问题，强行停止脚本导致调用close()不起作用，导致停止运行之后端口还被占用，无法再次运行

强制停止 或者悬浮窗停止按钮

**Comment by wangwang-code** [comment]
@wilinz  主要的问题是两个客户端同时向服务端发消息(连接)会崩服务端

**Comment by TonyDongGuaPi** [comment]
希望更新一下文档，创建websocket 服务器端的例子

**Comment by wangwang-code** [comment]
> 希望更新一下文档，创建websocket 服务器端的例子

+1

**Comment by wilinz** [comment]
没有此功能，未封装

**Comment by 625781186** [comment]
找到了个解决方案 还没尝试 
https://gitee.com/mikeyo/autojs

![image](https://github.com/user-attachments/assets/7e38cbc0-15f2-4d80-814e-fd5e92cf1320)

**Comment by 625781186** [comment]
> 找到了个解决方案 还没尝试 https://gitee.com/mikeyo/autojs
> 
> ![image](https://private-user-images.githubusercontent.com/30521429/383456171-7e38cbc0-15f2-4d80-814e-fd5e92cf1320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MDUzMDEsIm5iZiI6MTczMDkwNTAwMSwicGF0aCI6Ii8zMDUyMTQyOS8zODM0NTYxNzEtN2UzOGNiYzAtMTVmMi00ZDgwLTgxNGUtZmQ1ZTkyY2YxMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE0NTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyY2Y1MGVhNTlmZmJiOWUzOWExMjA4MzhkN2M3MzgxZTBhZGJmODY3MWU0OTA5ODU3NTZiNDY0YzA4YjM3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-yQmm-ni98ejxwMvT_RVhp73oqSKKJohsA_OZtRGBeE)

没解决
```javascript


log(files.path('./'))
// runtime.loadJar("/mnt/shared/Pictures/Java-WebSocket-1.4.1-with-dependencies.jar");
runtime.loadJar("./mir2autologin/Java-WebSocket-1.5.1.jar");


// // 导入必要的 Java 类和包
importClass(java.net.InetSocketAddress);
importClass(org.java_websocket.server.WebSocketServer);
importClass(org.java_websocket.WebSocket);
importClass(org.java_websocket.handshake.ClientHandshake);

// 创建 WebSocket 服务端类，继承 WebSocketServer
function  MyWebSocketServer() {
        let ws = new JavaAdapter(WebSocketServer, {
        onOpen: function(conn, handshake) {
            log(" ============= New connection opened: " + conn.getRemoteSocketAddress());
            conn.send("Welcome to the WebSocket server!"); // 向客户端发送欢迎消息
        },
        // onClose: function(conn, code, reason, remote) {
        //     print("Connection closed: " + conn.getRemoteSocketAddress() + " with reason: " + reason);
        // },
        // onMessage: function(conn, message) {
        //     print("Message received from client: " + message);
        //     // Echo back the message to the client
        //     conn.send("Echo: " + message);
        // },
        onError: function(conn, ex) {
            log("Error occurred: " + ex);
            console.trace()
        },
        onStart: function() {
            print("WebSocket server started successfully on ws://localhost:9317");
        }


    });

    return ws
}



// // 启动 WebSocket 服务端
var server = new MyWebSocketServer(new InetSocketAddress(7777));
// // server.setDaemon(true)



server.start();
print("WebSocket server is running...");

setInterval(() => {
    // log(server.getPort())
}, 1000);

```

logcat 里报错

```
11-06 14:00:50.452 22976 22976 I dex2oat : /system/bin/dex2oat --dex-file=/data/user/0/org.autojs.autoxjs.v6/cache/classes/1730006386811.jar --oat-fd=208 --oat-location=/data/user/0/org.autojs.autoxjs.v6/cache/classes/1730006386811.dex --compiler-filter=speed
11-06 14:00:50.452 22976 22976 E cutils-trace: Error opening trace file: Permission denied (13)
```
不知道什么原因
