### ISSUE TITLE
点“设置”竟然没反应

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#308]
手机机型Vivo x27 下载安装6.1.1后，点“设置”竟然没反应

**Comment by LZX284** [comment]
@lnxcyq  帮忙看看这个测试版修复了没有：[AutoX_arm64-v8a(test-“设置”按钮失效事件)](https://github.com/LZX284/AutoX/releases/tag/test-%E2%80%9C%E8%AE%BE%E7%BD%AE%E2%80%9D%E6%8C%89%E9%92%AE%E5%A4%B1%E6%95%88%E4%BA%8B%E4%BB%B6)

**Comment by agandab** [comment]
灵啊，该测试版“没置”和“退出”都正常了。只是这跑到底下的菜单不太适应，还有顶上3个按钮跟手机系统的时间条重叠了，看着好怪奇呀！
![IMG_20220606_144637](https://user-images.githubusercontent.com/87642242/172110782-b29271cf-e2b9-412e-a9d1-8f0fe79d690f.jpg)

**Comment by agandab** [comment]
补充：我手机是红米note，前摄影头跟左上角“≡”按钮重叠了，每次点开都很尴尬😓。测试版Ocr偶尔会识别失败。

**Comment by lnxcyq** [comment]
@LZX284 感谢您提供的下载，您这个修改好了，而且版本号了正常，太感谢了，能不能以后都提供一下apk的下载。谢谢

**Comment by LZX284** [comment]
测试版2：[AutoX_arm64-v8a(test-“设置”按钮失效事件2)](https://github.com/LZX284/AutoX/releases/tag/test-%E2%80%9C%E8%AE%BE%E7%BD%AE%E2%80%9D%E6%8C%89%E9%92%AE%E5%A4%B1%E6%95%88%E4%BA%8B%E4%BB%B62)

@agandab   红米note9好像是全面屏吧，适配可能会比较困难，你看看测试版2的效果怎样？

@lnxcyq  为了方便测试，这边测试版的链接都是可以即时提供的，正式版的话，现在最新版的Releases页面上也有补上apk的下载链接了吧（还是workflow自动生成的）……

**Comment by agandab** [comment]
测试版2，界面和菜单均显示正常了，完美适配红米note9。只是OCR速度比不上6.0.6版丝滑，且识别偶尔失败：刷了25道题，其中有3道题的选项识别失败（返回为空）。

**Comment by LZX284** [comment]
> 测试版2，界面和菜单均显示正常了，完美适配红米note9。只是OCR速度比不上6.0.6版丝滑，且识别偶尔失败：刷了25道题，其中有3道题的选项识别失败（返回为空）。

识别失败的表现是什么？都是返回空字符吗？有没有什么报错信息？

**Comment by Liu2020Mo** [comment]
还是有不适配的情况，设置按钮都看不到去那了。非全面屏。

**Comment by LZX284** [comment]
> 还是有不适配的情况，设置按钮都看不到去那了。非全面屏。

@Liu2020Mo  右侧侧滑菜单中没有吗？

**Comment by Liu2020Mo** [comment]
> > 还是有不适配的情况，设置按钮都看不到去那了。非全面屏。
> 
> @Liu2020Mo 右侧侧滑菜单中没有吗？

    侧滑提示退出  没有其它对话框弹出。

另外在主屏开节点查看会无法退出

**Comment by Liu2020Mo** [comment]
> > 侧滑提示退出  没有其它对话框弹出。
> > 另外在主屏开节点查看会无法退出
> 
> @Liu2020Mo 测试了几个型号的手机都没有发现这个问题。不知道你的手机系统属于哪个版本或类型？另外，主屏无法退出是在哪个标签页？无法退出是指悬浮按钮展开后无法收回，还是指的无法退出应用？ 这是最新的测试版，看看工具栏新加的按钮能不能打开右侧菜单？ [AutoX_arm64-v8a(test-多项优化及功能增强，工具栏添加“打开右侧菜单”的按钮)]

则测试完美解决.两种全屏模式也都能用.

**Comment by LZX284** [comment]
> 没见报错，就是返回空字符。

@agandab  优化初始化过程，提高OCR速度。识别为空字符却不报错，有两种可能，一是截图失败（图片内容为空，识别结果就会是空字符），二是 PaddleOCR Native代码中存在稳定性问题，我这边无法稳定复现识别失败的情况，这个追踪起来就会比较困难。或者也可以尝试将OCR升级到2.5版，看看情况会不会好一点……

[test-修复潜在问题、新增任务调度器及切换选项、OCR相关优化等](https://github.com/LZX284/AutoX/releases/tag/test-%E4%BF%AE%E5%A4%8D%E6%BD%9C%E5%9C%A8%E9%97%AE%E9%A2%98%E3%80%81%E6%96%B0%E5%A2%9E%E4%BB%BB%E5%8A%A1%E8%B0%83%E5%BA%A6%E5%99%A8%E5%8F%8A%E5%88%87%E6%8D%A2%E9%80%89%E9%A1%B9%E3%80%81OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%96%E7%AD%89)
