### ISSUE TITLE
如果在UI线程里弄一个日志按钮以便在打包应用后查看日志

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#310]
RT 另外，这是个想法

**Comment by twinklelucas** [comment]
app.startActivity("console");这样就能看了

**Comment by kkevsekk1** [comment]
这个想法，是有这个功能的，只是很少人这样写，这样用，所以没看见事例



发送自我的盖乐世



-------- 原始信息 --------
发件人： wangwang-code ***@***.***>
日期: 2022/6/7 07:27 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 如果在UI线程里弄一个日志按钮以便在打包应用后查看日志 (Issue #310)


RT 另外，这是个想法

―
