### ISSUE TITLE
安卓好像提供了后台运行的办法

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#311]
不知道有木有，有的话考虑加进去，这样应该能减少脚本执行的时候被后台杀的概率吧

**Comment by LZX284** [comment]
@wangwang-code  找到办法了吗？照理说应该是可以的，但现在国产厂商对安卓魔改的太厉害，而且由于国内流氓软件多，后台任务一般都是系统清理重点照顾的对象，autojs的脚本想要不被杀后台恐怕不容易……

**Comment by LZX284** [comment]
> 最近在捣鼓套接字，只是见到`USB摄像头`带有后台运行的功能就好奇是否有方法后台运行

后台运行的方式当然有，只是长时间稳定在后台运行比较难以保证，原版系统容易一点，国内定制版就难说了……
