### ISSUE TITLE
一个IDE，自定义OCR模型文件

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#316]
即不打包只带的，用自己训练好转换的模型，（主要是懒得再替换，另外MT管理器得会员才能用自定义证书，NP管理器又不能正常生成APK）

（加个再次签名APK 和 一键替换模型 的功能不就好了

**Comment by LZX284** [comment]
> 即不打包只带的，用自己训练好转换的模型，（主要是懒得再替换，另外MT管理器得会员才能用自定义证书，NP管理器又不能正常生成APK）

@wangwang-code  可以加一个方法，用来指定要加载的模型路径。打包的话，不是有选择自定义签名的功能吗？

**Comment by LZX284** [comment]
> （加个再次签名APK 和 一键替换模型 的功能不就好了

@wangwang-code  将模型路径改到应用专属目录下（/sdcard/Android/data/org.autojs.autojs/models），OCR初始化时会自动加载这个模型目录下的文件（文件名不能改动），这样只要替换一次就行了，不需要再次编译，你看行不行？
[test-修复潜在问题、新增任务调度器及切换选项、OCR相关优化等](https://github.com/LZX284/AutoX/releases/tag/test-%E4%BF%AE%E5%A4%8D%E6%BD%9C%E5%9C%A8%E9%97%AE%E9%A2%98%E3%80%81%E6%96%B0%E5%A2%9E%E4%BB%BB%E5%8A%A1%E8%B0%83%E5%BA%A6%E5%99%A8%E5%8F%8A%E5%88%87%E6%8D%A2%E9%80%89%E9%A1%B9%E3%80%81OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%96%E7%AD%89)

**Comment by wangwang-code** [comment]
> > （加个再次签名APK 和 一键替换模型 的功能不就好了
> 
> @wangwang-code 将模型路径改到应用专属目录下（/sdcard/Android/data/org.autojs.autojs/models），OCR初始化时会自动加载这个模型目录下的文件（文件名不能改动），这样只要替换一次就行了，不需要再次生成，你看行不行？ [test-修复潜在问题、新增任务调度器及切换选项、OCR相关优化等](https://github.com/LZX284/AutoX/releases/tag/test-%E4%BF%AE%E5%A4%8D%E6%BD%9C%E5%9C%A8%E9%97%AE%E9%A2%98%E3%80%81%E6%96%B0%E5%A2%9E%E4%BB%BB%E5%8A%A1%E8%B0%83%E5%BA%A6%E5%99%A8%E5%8F%8A%E5%88%87%E6%8D%A2%E9%80%89%E9%A1%B9%E3%80%81OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%96%E7%AD%89)

我想法是，不打包模型，手动指向模型目录（名字不变），比如  `./models`

**Comment by LZX284** [comment]
> 我想法是，不打包模型，手动指向模型目录（名字不变），比如 `./models`

@wangwang-code  默认的模型还是要有的，要不那些没有自定义模型的用户就无法使用OCR了。要不这样，打包时你把自己的模型打包进去，然后在脚本的开头将这些模型复制到默认目录里覆盖原有的，这样应该就可以了吧？

**Comment by wangwang-code** [comment]
> > 我想法是，不打包模型，手动指向模型目录（名字不变），比如 `./models`
> 
> @wangwang-code 默认的模型还是要有的，要不那些没有自定义模型的用户就无法使用OCR了。要不这样，打包时你把自己的模型打包进去，然后在脚本的开头将这些模型复制到默认目录里覆盖原有的，这样应该就可以了吧？

麻烦 还增大apk  能否加个模型目录设置，默认的路径和现在的一样，可以修改设置模型目录
再配合一个打包选项 `不添加默认OCR模型`


比如
`paddle.setmodeldirectory("./models")`
models是项目中的一个文件夹，会一起打包进apk，里面有模型文件
打包的时候勾选'不添加默认OCR模型' 就能用自己的模型，而不会浪费apk空间去打包那两种用不到的模型
对于那些不需要的 不用管`paddle.setmodeldirectory`和打包选项'不添加默认OCR模型'

**Comment by LZX284** [comment]
> 麻烦 还增大apk 能否加个模型目录设置，默认的路径和现在的一样，可以修改设置模型目录 再配合一个打包选项 `不添加默认OCR模型`

@wangwang-code 添加了新方法和新示例用于自定义模型路径：[AutoX_arm64-v8a(test-OCR相关优化2)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%962)
* result = paddle.ocr(img, cpuThreadNum, myModelPath)
* stringList = paddle.ocrText(img, cpuThreadNum, myModelPath)
用法在新的示例里都有说明。至于添加一个打包选项，这个得看 @wilinz 是否有时间了……

**Comment by wangwang-code** [comment]
> > 麻烦 还增大apk 能否加个模型目录设置，默认的路径和现在的一样，可以修改设置模型目录 再配合一个打包选项 `不添加默认OCR模型`
> 
> @wangwang-code 添加了新方法和新示例用于自定义模型路径：[AutoX_arm64-v8a(test-OCR相关优化2)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%962)
> 
> ```js
> // 新增：自定义模型路径(必须是完整路径)
> // 该路径下必须有以下三个文件： ch_ppocr_mobile_v2.0_cls_opt.nb ch_ppocr_mobile_v2.0_det_opt.nb ch_ppocr_mobile_v2.0_rec_opt.nb，否则就会启用默认模型。
> let myModelPath = "/sdcard/ocr_v2_for_cpu";
> let result = paddle.ocr(img, cpuThreadNum, myModelPath)
> toastLog("完整识别信息: " + JSON.stringify(result))
> const stringList = paddle.ocrText(img, cpuThreadNum, myModelPath)
> toastLog("文本识别信息: " + JSON.stringify(stringList))
> ```
> 
> 用法在新的示例里都有说明。至于添加一个打包选项，这个得看 @wilinz 是否有时间了……

很好，我又有一个IDE了 有什么方法获取类似这个路径"/data/data/org.autojs.autojs" 这样再拼接上"/files/ocr_v2_for_cpu" 
又可以不用复制文件了 

[files.cwd()](http://doc.autoxjs.com/#/files?id=filescwd) 不知道可不可以

**Comment by LZX284** [comment]
> 很好，我又有一个IDE了 有什么方法获取类似这个路径"/data/data/org.autojs.autojs" 这样再拼接上"/files/ocr_v2_for_cpu" 又可以不用复制文件了
> 
> [files.cwd()](http://doc.autoxjs.com/#/files?id=filescwd) 不知道可不可以

@wangwang-code  "/data/data/org.autojs.autojs"这个是以APP ID命名的专属目录，可以把模型目录放到用打包脚本同一目录下，然后用当前目录路径来转换得到：
```javascript
    let myModelpath = files.path("./ocr_v2_for_cpu")
```

**Comment by wangwang-code** [comment]
> > 很好，我又有一个IDE了 有什么方法获取类似这个路径"/data/data/org.autojs.autojs" 这样再拼接上"/files/ocr_v2_for_cpu" 又可以不用复制文件了
> > [files.cwd()](http://doc.autoxjs.com/#/files?id=filescwd) 不知道可不可以
> 
> @wangwang-code "/data/data/org.autojs.autojs"这个是以APP ID命名的专属目录，直接获取比较困难。不过可以通过把模型目录放到用打包脚本同一目录下，然后用当前目录路径来转换得到：
> 
> ```js
>     let myModelpath = files.path("./ocr_v2_for_cpu")
> ```

目前测试发现问题 `let result = paddle.ocr(img, cpuThreadNum, myModelPath)` 无论myModelPath的路径存在，有没有模型文件都会报错

```
Can't find method com.stardust.autojs.runtime.api.Paddle.ocr(com.stardust.autojs.core.image.ImageWrapper,number,string). (/storage/emulated/0/脚本/ocr/main.js#8)
Can't find method com.stardust.autojs.runtime.api.Paddle.ocr(com.stardust.autojs.core.image.ImageWrapper,number,string).
    at /storage/emulated/0/脚本/ocr/main.js:8:0
```

`let result = paddle.ocr(img, cpuThreadNum)`  正常

**Comment by LZX284** [comment]
> 目前测试发现问题 `let result = paddle.ocr(img, cpuThreadNum, myModelPath)` 无论myModelPath的路径存在，有没有模型文件都会报错

@wangwang-code  新示例能正常运行吗？如果能的话，那 估计又是打包后环境存在兼容性问题了……

**Comment by wangwang-code** [comment]
> > 目前测试发现问题 `let result = paddle.ocr(img, cpuThreadNum, myModelPath)` 无论myModelPath的路径存在，有没有模型文件都会报错
> 
> @wangwang-code 新示例能正常运行吗？如果能的话，那 估计又是打包后环境存在兼容性问题了……

1. 卸载Autox.js
2. 安装AutoX_arm64-v8a(test-OCR相关优化2).apk

好的此BUG已修改

**Comment by wangwang-code** [comment]
@kkevsekk1  https://github.com/kkevsekk1/AutoX/pull/322

@wilinz 有空个给打包加个`不添加默认OCR模型`的功能

**Comment by wangwang-code** [comment]
> > > 很好，我又有一个IDE了 有什么方法获取类似这个路径"/data/data/org.autojs.autojs" 这样再拼接上"/files/ocr_v2_for_cpu" 又可以不用复制文件了
> > > [files.cwd()](http://doc.autoxjs.com/#/files?id=filescwd) 不知道可不可以
> > 
> > 
> > @wangwang-code "/data/data/org.autojs.autojs"这个是以APP ID命名的专属目录，直接获取比较困难。不过可以通过把模型目录放到用打包脚本同一目录下，然后用当前目录路径来转换得到：
> > ```js
> >     let myModelpath = files.path("./ocr_v2_for_cpu")
> > ```
> 
> 在打包后会闪退，推测没有权限读取文件，看来还得复制文件到根目录

找到问题了，'paddle.ocrText(img, 8, true)' 忘了改成'paddle.ocrText(img, 8, myModelpath)'

**Comment by wangwang-code** [comment]
兼容性不行，放弃

**Comment by yangy996** [comment]
看看这个
https://blog.csdn.net/YY007H/article/details/124540297
