### ISSUE TITLE
adb控制autox.js连接电脑？

### ISSUE THREAD

**Issue by fgy58963** [kkevsekk1/AutoX#321]
请问可以通过adb的方式启动autox.js，并让其连接电脑到指定IP么？

**Comment by kkevsekk1** [comment]
可以

**Comment by fgy58963** [comment]
> 可以

请问有example么……我github找了一圈没看到 谢谢

**Comment by kkevsekk1** [comment]
直接用adb 启动一个脚本，脚本里的代码就是链接电脑



发送自我的盖乐世



-------- 原始信息 --------
发件人： fgy58963 ***@***.***>
日期: 2022/6/11 21:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] adb控制autox.js连接电脑？ (Issue #321)


可以

请问有example么……我github找了一圈没看到 谢谢

―

**Comment by CzyerChen** [comment]
> 

想问一下如何用adb启动一个手机的脚本文件？

**Comment by kkevsekk1** [comment]
网上可以找到有很多事例



发送自我的盖乐世



-------- 原始信息 --------
发件人： Chen Ziyan ***@***.***>
日期: 2022/9/20 16:13 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, State change ***@***.***>
主题： Re: [kkevsekk1/AutoX] adb控制autox.js连接电脑？ (Issue #321)


想问一下如何用adb启动一个手机的脚本文件？

―
