### ISSUE TITLE
6.1.5 OCR 直接崩溃

### ISSUE THREAD

**Issue by CuteLicense** [kkevsekk1/AutoX#323]
Android 11.  只要调用 ocr 就崩溃或闪退
前面版本正常

**Comment by LZX284** [comment]
> Android 11. 只要调用 ocr 就崩溃或闪退 前面版本正常

@CuteLicense  有没有什么错误提示？示例代码运行正常吗？
这个版本尝试修复了一下，你看看行不行：[AutoX_arm64-v8a(test-OCR相关优化3)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%963)

**Comment by CuteLicense** [comment]
> > Android 11. 只要调用 ocr 就崩溃或闪退 前面版本正常
> 
> @CuteLicense 有没有什么错误提示？示例代码运行正常吗？ 这个版本尝试修复了一下，你看看行不行：[AutoX_arm64-v8a(test-OCR相关优化3)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%963)
一样。
不管是运行示例，还是自己的脚本调用，都是直接闪退，没有任何提示 @LZX284

**Comment by wilinz** [comment]
崩溃日志可否提供

**Comment by CuteLicense** [comment]
没有日志，整个AutoX直接闪退，再打开时日志为空。第二个OCR示例PaddleOCR，有时候（极小几率）会出现查看错误，但太快了，一闪而过就退出了

**Comment by LZX284** [comment]
> > 一样。
> > 不管是运行示例，还是自己的脚本调用，都是直接闪退，没有任何提示 @LZX284

@CuteLicense  看看这个：[AutoX_arm64-v8a(test-OCR相关优化4)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%964) 这个要还是不行，那就实在没有办法了……

**Comment by wilinz** [comment]
不是Autojs日志，是闪退日志，你可以电脑安装Android Studio 查看App 日志

**Comment by CuteLicense** [comment]
> > > 一样。
> > > 不管是运行示例，还是自己的脚本调用，都是直接闪退，没有任何提示 @LZX284
> 
> @CuteLicense 看看这个：[AutoX_arm64-v8a(test-OCR相关优化4)](https://github.com/LZX284/AutoX/releases/tag/test-OCR%E7%9B%B8%E5%85%B3%E4%BC%98%E5%8C%964) 这个要还是不行，那就实在没有办法了……

OCR 示例前两个已经我自己的脚本运行正常了。谢谢 @wilinz  @LZX284

**Comment by LZX284** [comment]
> OCR 示例前两个和我自己的脚本测试运行已经正常了。谢谢 @wilinz @LZX284

能用真是太好了，还以为不行呢……
第三个示例不能运行的话，可能和手机系统不是原版有关，测试过一台Android11的手机，结果是正常的，但如果是国产厂商定制（魔改）过的系统，那兼容性就可能就难以保证了。不过，如果你想自定义模型路径的话，可以试试将示例中的自定义路径改在脚本目录下，并在脚本目录放上相应的模型文件再运行，如果能识别出结果，那应该就可以了 @CuteLicense

**Comment by CuteLicense** [comment]
三星 One UI Android 11 
那个自定义目录没有 root 进不去

**Comment by LZX284** [comment]
> 三星 One UI Android 11 按个自定义示例中那个目录没有 root 进不去

破案了！！原来是文件读写权限问题惹的祸……

**Comment by wangwang-code** [comment]
> > 三星 One UI Android 11 按个自定义示例中那个目录没有 root 进不去
> 
> 破案了！！难怪会崩溃，原来是文件读写权限问题惹的祸……

又双是文件读写权限
