### ISSUE TITLE
全屏后菜单按钮隐藏了，退不出全屏

### ISSUE THREAD

**Issue by wilinz** [kkevsekk1/AutoX#324]
哈哈哈
![Screenshot_2022-06-13-01-44-53-961_org autojs autojs dev](https://user-images.githubusercontent.com/59408438/173246255-37aff379-4de2-480e-b0a8-74bdb4ffe5f5.jpg)

**Comment by LZX284** [comment]
右侧侧滑菜单能打开吗？能打开的话，就可以切换全屏模式或直接退出APP了

**Comment by wilinz** [comment]
滑不了呢，和全面屏手势冲突了

**Comment by LZX284** [comment]
> 滑不了呢，和全面屏手势冲突了

最新的代码，在悬浮按钮菜单那里添加了“设置”和“退出”两个选项，看看能不能用，只要能退出，再启动时全屏模式就会取消了

**Comment by Warm-rain** [comment]
小爱同学，关闭当前应用。

**Comment by wilinz** [comment]
不是不能退出App，而是App不能退出全屏，右滑菜单滑不出来，和全面屏手势冲突了，即全面屏手势优先

**Comment by LZX284** [comment]
> 不是不能退出App，而是App不能退出全屏，右滑菜单滑不出来，和全面屏手势冲突了，即全面屏手势优先

@wilinz  退出再进全屏模式就没有了。不过这样确实比较麻烦，不知道左滑菜单能不能滑出来？能的话，在左滑菜单加一个 切换全屏模式 的按钮，不知道这样行不行？

**Comment by kkevsekk1** [comment]
这等我有全面屏了，来看看 ^_^

**Comment by wilinz** [comment]
@kkevsekk1 这个issues可以关了，ui都改了，没有这个问题了
