### ISSUE TITLE
截屏多点找色有BUG

### ISSUE THREAD

**Issue by yjjdick** [kkevsekk1/AutoX#326]
代码如下：
function test() {
    requestScreenCapture(false);
    //截图
    var img = captureScreen();
    
    var p = images.findMultiColors(img, "#020202",[[-62,-98,"#020202"],[59,-97,"#020202"],[-62,75,"#020202"],[57,75,"#020202"]]);
    
    toast(p);
}

报错：
![image](https://user-images.githubusercontent.com/8224370/173355656-83afc46c-6462-4105-a74a-8efbd2b14ef0.png)

**Comment by LZX284** [comment]
@yjjdick  这个是只有截屏多点找色有BUG吗？
提示找不到opencv的相关方法，一般出现这个错误时，应该大部分和opencv相关的API都用不了吧？
另外，用以上代码测试了一下，APP界面截图找色结果为null，也没有出现上述错误，不知道你用的APP版本和手机系统是哪一种？

**Comment by yjjdick** [comment]
> @yjjdick 这个是只有截屏多点找色有BUG吗？ 提示找不到opencv的相关方法，一般出现这个错误时，应该大部分和opencv相关的API都用不了吧？ 另外，用以上代码测试了一下，APP界面截图找色结果为null，也没有出现上述错误，不知道你用的APP版本和手机系统是哪一种？

夜神模拟器没问题，雷电模拟器3.x的必现

**Comment by LZX284** [comment]
> 夜神模拟器没问题，雷电模拟器3.x的必现

如果没有什么特殊的理由，那用兼容性好一点的模拟器应该就可以了吧？一些模拟器特有的兼容问题，估计比真机还要麻烦的多，APP适配实在兼顾不了那么广……
