### ISSUE TITLE
截图闪退

### ISSUE THREAD

**Issue by wunaidejianao** [kkevsekk1/AutoX#327]
问题描述：申请截图权限后，点击“立即开始”按钮就会崩溃，新老版本大都试过，结果一致。

手机型号：Mi 11、Mi10青春版

MIUI版本：MIUI 13.0.8、 MIUI 13.0.3

Android 版本：12

调试信息：

Version: 614 Android: 31 android.os.RemoteException: Remote stack trace: 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553) 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137) 	at android.os.Binder.execTransactInternal(Binder.java:1182) 	at android.os.Binder.execTransact(Binder.java:1146)  java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs.dev/org.autojs.autojs.ui.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference android.app.ActivityThread.deliverResults(ActivityThread.java:5422) ...... Caused by: android.os.RemoteException:Remote stack trace: 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553) 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137) 	at android.os.Binder.execTransactInternal(Binder.java:1182) 	at android.os.Binder.execTransact(Binder.java:1146)

**Comment by LZX284** [comment]
这边没有 MIUI 13 的设备，无法对此问题进行追踪。或者你可以先测试一下别的APP看截图是否正常，如果也出错那就可能是系统的问题，尝试更新MIUI系统看能不能解决。

**Comment by wunaidejianao** [comment]
我的手机系统是最新版本，通过测试已有的机型，猜测可能是 Autox.js、Auto.js 和 android 12 存在兼容问题，AutoJsPro正常。

**Comment by wilinz** [comment]
见[https://github.com/kkevsekk1/AutoX/issues/246](https://github.com/kkevsekk1/AutoX/issues/246)

**Comment by LZX284** [comment]
> 我的手机系统是最新版本，通过测试已有的机型，猜测可能是 Autox.js、Auto.js 和 android 12 存在兼容问题，AutoJsPro正常。

@wunaidejianao  @wilinz  按照 #246 尝试进行了修复，帮忙测试一下看行不行：[AutoX_arm64-v8a(test-Android12截图闪退事件1)](https://github.com/LZX284/AutoX/releases/tag/test-Android12%E6%88%AA%E5%9B%BE%E9%97%AA%E9%80%80%E4%BA%8B%E4%BB%B61)

**Comment by wilinz** [comment]
> > 我的手机系统是最新版本，通过测试已有的机型，猜测可能是 Autox.js、Auto.js 和 android 12 存在兼容问题，AutoJsPro正常。
> 
> @wunaidejianao @wilinz 按照 #246 尝试进行了修复，帮忙测试一下看行不行：[AutoX_arm64-v8a(test-Android12截图闪退事件1)](https://github.com/LZX284/AutoX/releases/tag/test-Android12%E6%88%AA%E5%9B%BE%E9%97%AA%E9%80%80%E4%BA%8B%E4%BB%B61)

![image](https://user-images.githubusercontent.com/59408438/173542496-0c1c7a6e-138a-4e88-b8da-51ecfa83c683.png)
测试正常

**Comment by wunaidejianao** [comment]
> 问题依旧。我打开了“前台服务”也不行。

**Comment by wunaidejianao** [comment]
@LZX284 应该不是。我的 Mi 6 ,是 MIUI 13，Android 11，执行正常，但不是官方包。有问题的手机上，AutoJsPro 相同操作不会崩溃。

**Comment by hu9029** [comment]
![微信图片_20220615095643](https://user-images.githubusercontent.com/8140861/173721732-e0c5fb9e-f40e-4ecb-8ce5-ec3a9d15f1c5.png)
![image](https://user-images.githubusercontent.com/8140861/173721678-26f713ae-856c-406c-9cdc-9f4175f82cc5.png)

用MIUI13设备调试了一下，第一次getMediaProjection没有问题，在setOrientation-->refreshVirtualDisplay里面第二次getMediaProjection报了空指针，怀疑MIUI13是不是不能重用令牌了，即使用的是clone对象

**Comment by LZX284** [comment]
> 用MIUI13设备调试了一下，第一次getMediaProjection没有问题，在setOrientation-->refreshVirtualDisplay里面第二次getMediaProjection报了空指针，怀疑MIUI13是不是不能重用令牌了，即使用的是clone对象 @LZX284 看看有啥好的解决办法

@hu9029  @wunaidejianao  
调整了程序逻辑，避免重复获取令牌，看看这次行不行：
[AutoX_arm64-v8a(test-Android12截图闪退事件2)](https://github.com/LZX284/AutoX/releases/tag/test-Android12%E6%88%AA%E5%9B%BE%E9%97%AA%E9%80%80%E4%BA%8B%E4%BB%B62)

**Comment by wunaidejianao** [comment]
@LZX284 可以截图了。不过我遇到了新问题，当软件处于后台时，toast 无法显示。

**Comment by LZX284** [comment]
> @LZX284 可以截图了。不过我遇到了新问题，当软件处于后台时，toast 无法显示。

@wunaidejianao  不知道 Android11 或之前版本 可以在后台弹出 toast 吗？
猜测有可能是因为Android12 对后台进程的限制是更严格了。不过要是这样，一般也没什么好办法，只能尝试改用其它方式显示消息了。

**Comment by wunaidejianao** [comment]
@LZX284 开启“前台服务”并将“应用信息”中的“通知管理”设为“允许”就可以了。

**Comment by wunaidejianao** [comment]
@LZX284 @wilinz @hu9029 感谢大家的帮助。

**Comment by lnxcyq** [comment]
@LZX284 大佬，你怎么删除你的Autox.js的库了？

**Comment by manwithsteelnerves** [comment]
> > I debugged it with the MIUI13 device, the first time getMediaProjection is no problem, the second time getMediaProjection reported a null pointer in setOrientation-->refreshVirtualDisplay, I wonder if MIUI13 can not reuse the token, that is, the clone object is used@LZX284see what a good solution
> 
> @hu9029 @wunaidejianao Adjusted the program logic to avoid getting the token repeatedly, and see if it works this time: [AutoX_arm64-v8a (test-Android12 screenshot flashback event 2)](https://github.com/LZX284/AutoX/releases/tag/test-Android12%E6%88%AA%E5%9B%BE%E9%97%AA%E9%80%80%E4%BA%8B%E4%BB%B62)

Doing this will show the permission everytime? @LZX284

**Comment by wilinz** [comment]
@manwithsteelnerves After android 10, there is no "don't ask again" option for screen recording, and each recording needs to be re-authorized

**Comment by manwithsteelnerves** [comment]
> @manwithsteelnerves After android 10, there is no "don't ask again" option for screen recording, and each recording needs to be re-authorized

That's true but I'm asking about cloning captured token with in a launched session. I see Xiaomi from Android 12 not allowing to cache the intent within the session as its crashing.
