### ISSUE TITLE
通知重复读取

### ISSUE THREAD

**Issue by Warm-rain** [kkevsekk1/AutoX#329]
我昨天升级了最新版本6.1.4后出现一条新通知会重复读取三次的情况，最先以为我脚本有问题，后用事例代码依旧一样：
auto();
events.observeNotification();
events.onNotification(function(notification){
    printNotification(notification);
});
toast("监听中，请在日志中查看记录的通知及其内容");

function printNotification(notification){
    log("应用包名: " + notification.getPackageName());
    log("通知文本: " + notification.getText());
    log("通知优先级: " + notification.priority);
    log("通知目录: " + notification.category);
    log("通知时间: " + new Date(notification.when));
    log("通知数: " + notification.number);
    log("通知摘要: " + notification.tickerText);
}
[![XTP2mq.jpg](https://s1.ax1x.com/2022/06/15/XTP2mq.jpg)](https://imgtu.com/i/XTP2mq)

**Comment by LZX284** [comment]
@Warm-rain 最新版本应该是6.1.6了吧，就是作者似乎一直没空发布新版本……
测试了下，确实存在通知重复读取的情况，重复次数似乎并不是固定3遍，也有发现不重复的。查看源码后暂时没发现会导致重复读取的原因。不知道这个问题除了返回数据量会大一点，会不会影响脚本执行的正确性或导致其它错误？

**Comment by Warm-rain** [comment]
@LZX284 我再次下载了一边github上面的最新版本6.1.5但是安装的时候显示却是6.1.4，不排除是作者放错包了，读取三次重复的通知确实对脚本执行有影响，比如我要收到一个新通知取其中的数据并执行一次脚本，但是因为读取了三次脚本就要重复执行三次。

**Comment by kkevsekk1** [comment]
这几天赶项目😂



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/6/15 19:17 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 通知重复读取 (Issue #329)


@Warm-rain<https://github.com/Warm-rain> 最新版本应该是6.1.6了吧，就是作者似乎一直没空发布新版本……
测试了下，确实存在通知重复读取的情况，重复次数似乎并不是固定3遍，也有发现不重复的。查看源码后暂时没发现会导致重复读取的原因。不知道这个问题除了返回数据量会大一点，会不会影响脚本执行的正确性或导致其它错误？
