### ISSUE TITLE
AutoX用自带编辑器打开源码后，在编辑器里运行直接闪退

### ISSUE THREAD

**Issue by minirain2000** [kkevsekk1/AutoX#332]
![微信图片_20220616093915](https://user-images.githubusercontent.com/12096661/173973327-50e0de98-4db5-4250-be13-96a0a4ff37f4.jpg)
![微信图片_20220616094225](https://user-images.githubusercontent.com/12096661/173973348-cc2ff1d4-bfb9-4167-8ed7-6dc80033e550.jpg)
是不是与文件读写权限相关呢．．．？

**Comment by wangwang-code** [comment]
其实，我遇到的问题更多，基本都是兼容性问题，比如在虚拟机里就有概率打开就闪退，刚开无障碍权限就闪

**Comment by kkevsekk1** [comment]
现在应该没有这个问题呢吧
