### ISSUE TITLE
打包遗漏删除文件了

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#335]
project里的文件出现残留了，比如7zip.js没有删(项目里没有7zip.js)，最好就清空project再拷贝

@wilinzx

如果有空的话，能否给打包页面添加 自定义OCR模型文件夹 ，即清空掉models里的东西，然后把选择的文件夹拷贝进去

**Comment by LZX284** [comment]
@wilinz 
既然相关功能都开发完成了，那就把打赏链接发出来吧！看是用 paypal、微信还是支付宝之类的都可以。至于可能某些支付方式用户使用不了你也不用担心。毕竟这是个完全开源自由的项目，捐赠也只是用户表达对项目支持的一种方式罢了。再说了，身为开发者，凭自己的本事恰饭，又有什么不好意思的？

**Comment by wilinz** [comment]
@LZX284 那是把码弄到 readme.md 吗

**Comment by LZX284** [comment]
> @LZX284 那是把码弄到 readme.md 吗

@wilinz  都可以。发到 readme.md  里的话应该需要项目作者同意吧？当然，你也可以把码放到你自己的主页或某个项目首页里，有关注你或愿意捐赠的用户应该很容易就能看到的

**Comment by kkevsekk1** [comment]
你们都可以上传，放到readme里，和供应者对应上，再放一个表格，公布奖励情况，如果打赏的人愿意就公布



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/6/22 13:04 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包遗漏删除文件了 (Issue #335)


@LZX284<https://github.com/LZX284> 那是把码弄到 readme.md 吗

―

**Comment by LZX284** [comment]
> 你们都可以上传，放到readme里，和供应者对应上，再放一个表格，公布奖励情况，如果打赏的人愿意就公布 发送自我的盖

我这边的话就不用了，专业也不是这个，只是前一段时间恰好有空才研究改进了一些auto.js的代码，以后都不一定会继续维护(甚至会不会直接跑路都很难说)。

**Comment by wangwang-code** [comment]
> > 你们都可以上传，放到readme里，和供应者对应上，再放一个表格，公布奖励情况，如果打赏的人愿意就公布 发送自我的盖
> 
> 我这边的话就不用了，专业也不是这个，只是前一段时间恰好有空才研究改进了一些auto.js的代码，以后都不一定会继续维护(甚至会不会直接跑路都很难说)。

哎，可惜啊，我过个两年我也不写脚本了，天下哪有不散的宴席
