### ISSUE TITLE
建议连接电脑增加adb(usb)模式

### ISSUE THREAD

**Issue by a4youma** [kkevsekk1/AutoX#336]
现在连vscode只有一种方式，对不联网的电脑非常不便，建议增加用数据线usb连接模式。这样VScode的扩展也要更新，谢谢

**Comment by wangwang-code** [comment]
> 现在连vscode只有一种方式，对不联网的电脑非常不便，建议增加用数据线usb连接模式。这样VScode的扩展也要更新，谢谢

连接电脑->网络共享->USB共享，还能顺带让电脑联网

如果是笔记本电脑 直接开热点

**Comment by a4youma** [comment]
> > 现在连vscode只有一种方式，对不联网的电脑非常不便，建议增加用数据线usb连接模式。这样VScode的扩展也要更新，谢谢
> 
> 连接电脑->网络共享->USB共享，还能顺带让电脑联网
> 
> 如果是笔记本电脑 直接开热点

如果开启USB共享，电脑就会联网，但有时手机流量不够，怕超了会增加很多费用。所以，还是adb连接比较适用

**Comment by kkevsekk1** [comment]
现阶段就这么玩吧，不是大家想像的引入个usb 那边简单，
1.要处理和as 或一些模拟器的兼容问题，
2.还有想处理调试代码的问题
