### ISSUE TITLE
定时任务无法触发

### ISSUE THREAD

**Issue by wunaidejianao** [kkevsekk1/AutoX#337]
问题描述：自 6.1.5 版本开始，除了“特定时间(广播)触发运行”下的触发条件外，“每天运行“和“按星期运行”不执行，“只运行一次”无论是前台还是后台，须由其它 activity 切换回 Autox.js[dev] 的 main activity，定时任务才能执行。

手机型号：Mi 11、Mi 6

MIUI版本：MIUI 13.0.8、 MIUI 22.2.21（非官方）

Android 版本：12、11

**Comment by LZX284** [comment]
@wunaidejianao  不知道这个问题是否会严重影响日常使用？如果在这里一直得不到回复的话，不妨就到 [这里](https://github.com/wangwang-code/AutoX) 看看吧，这虽然只是个人自用的一个Fork，但遇到问题还是会积极解决的。

**Comment by 386408003** [comment]
我的也是，下载的6.1.8版本，安装换成后关于里面查看是6.1.4，定时任务每天一次无法触发了，其他频率没有试过。
手机型号：红米k50pro

MIUI版本：MIUI 13.0.12

Android 版本：12

**Comment by kkevsekk1** [comment]
定时这个建议用第三方APP启动，直接启动容易被清理



发送自我的盖乐世



-------- 原始信息 --------
发件人： 朱峰 ***@***.***>
日期: 2022/6/26 17:27 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 定时任务无法触发 (Issue #337)


我的也是，下载的6.1.8版本，安装换成后关于里面查看是6.1.4，定时任务每天一次无法触发了，其他频率没有试过。
手机型号：红米k50pro

MIUI版本：MIUI 13.0.12

Android 版本：12

―

**Comment by 386408003** [comment]
手机已root，各种保活都设置了，悬浮窗也还在，应该是没有被清理，之前一直没有用dev版本，是正常的。不过还是谢谢作者大大！！顺便问一下，第三方启动App，用什么软件，能触发写好的js脚本么？

**Comment by wunaidejianao** [comment]
6.1.5 版本，作者修改了定时任务部分，可能是因为这个原因。

**Comment by kkevsekk1** [comment]
那，可以检查一下



发送自我的盖乐世



-------- 原始信息 --------
发件人： wunaidejianao ***@***.***>
日期: 2022/6/26 23:24 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 定时任务无法触发 (Issue #337)


6.1.5 版本，作者修改了定时任务部分，可能是因为这个原因。

―

**Comment by kkevsekk1** [comment]
如果没有被清理，不能触发可能代码有问题，我现在不具备排查的条件！
这个也不是什么多么复杂的bug，很大改了是贡献者 引入的，我希望相应的人能自己排查！（这是参与开源项目最起码的要求）
如果个把月都无人处理，说明其已经放弃治疗了，我会亲自动手！

**Comment by wunaidejianao** [comment]
就依你。

**Comment by wunaidejianao** [comment]
@LZX284 好啦，谢谢。

**Comment by 386408003** [comment]
@LZX284 测试过没有问题了，谢谢！
安装的时候提示替换旧版autox，而不是autox[dev]，须先卸载旧版，然后安装，否则签名不一致

MIUI版本：MIUI 13.0.12
Android 版本：12
