### ISSUE TITLE
作者可以开通github打赏吗

### ISSUE THREAD

**Issue by ixinwiki** [kkevsekk1/AutoX#338]
能否考虑一下开通github打赏，方便我们用户给代码贡献者一些支持，也能提高你们维护项目的动力

**Comment by kkevsekk1** [comment]
可以，最近几个开发者，可以发二维码你们



发送自我的盖乐世



-------- 原始信息 --------
发件人： ixinwiki ***@***.***>
日期: 2022/6/20 18:31 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 作者可以开通github打赏吗 (Issue #338)


能否考虑一下开通github打赏，方便我们用户给代码贡献者一些支持，也能提高你们维护项目的动力

―

**Comment by ixinwiki** [comment]
[https://github.com/sponsors](https://github.com/sponsors)现在github推出了官方打赏通道

**Comment by kkevsekk1** [comment]
是不是用美元？😂



发送自我的盖乐世



-------- 原始信息 --------
发件人： ixinwiki ***@***.***>
日期: 2022/6/20 18:39 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 作者可以开通github打赏吗 (Issue #338)


https://github.com/sponsors现在github推出了官方打赏通道

**Comment by ixinwiki** [comment]
好像是

**Comment by ixinwiki** [comment]
[https://github.com/vuejs/vue](https://github.com/vuejs/vue)你可以看一下这个项目（开通了打赏），

**Comment by kkevsekk1** [comment]
那还是开发者提交二维码到，readme,收到打赏，再更新一下readme



发送自我的盖乐世



-------- 原始信息 --------
发件人： ixinwiki ***@***.***>
日期: 2022/6/20 18:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 作者可以开通github打赏吗 (Issue #338)


好像是

―

**Comment by ixinwiki** [comment]
可以用paypal（支持银联）

**Comment by kkevsekk1** [comment]
那就走远了，我们贡献者好几个是学生，大家可以支持一下他们



发送自我的盖乐世



-------- 原始信息 --------
发件人： ixinwiki ***@***.***>
日期: 2022/6/20 18:50 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 作者可以开通github打赏吗 (Issue #338)


可以用paypal（支持银联）

―

**Comment by ixinwiki** [comment]
可以两个方案都试试

**Comment by wangwang-code** [comment]
> 可以用paypal（支持银联）

我要是能用paypal 我早跑pro去了，要么爱发电（大概7%的手续费），要么微信赞赏码（容易被爆菊）

**Comment by kkevsekk1** [comment]
我支持有能力的人去鼓励我们的贡献者。
贡献者得到鼓励和支持没有任何不妥

你只要贡献过代码 就可以在readme中留下你二维码，博客等等，合适我会 同意pr，也希望贡献者 最好公布一下，被捐助的情况

**Comment by kkevsekk1** [comment]
开通github 自带的弊大于利！先阶段没必要！

**Comment by lzx28400** [comment]
Github后台对贡献者的记录可以证明，这个 ixinwiki 就是 本项目贡献者之一 [wilinz](https://github.com/wilinz/Sponsor) 的小号
![2](https://user-images.githubusercontent.com/120650790/208102003-869af811-46e4-41f1-b986-2b044392381c.png)

![1](https://user-images.githubusercontent.com/120650790/208101977-f3466d6d-37ea-4cc8-84e8-dd2baf0c589c.png)
