### ISSUE TITLE
x86 opencv错误

### ISSUE THREAD

**Issue by hzwjm** [kkevsekk1/AutoX#339]
在x86上图色不能用，提示这个
No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)

把app/build.gradle 和 /inrt/build.gradle 改成 include 'x86' 编译的，不知道对不对
[](https://github.com/hzwjm/AutoX/releases/download/x86test/app-dev-x86-release-unsigned-signed.apk)

**Comment by hzwjm** [comment]
[app-dev-arm64-v8a-release-unsigned-signed.apk](https://github.com/hzwjm/AutoX/releases/download/tag1/app-dev-arm64-v8a-release-unsigned-signed.apk)

**Comment by wilinz** [comment]
app/build.gradle也要改

**Comment by wangwang-code** [comment]
> 在x86上图色不能用，提示这个 No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)
> 
> 把app/build.gradle 和 /inrt/build.gradle 改成 include 'x86' 编译的，不知道对不对

https://github.com/wangwang-code/AutoX/releases/tag/6.1.8t_3

这个是全平台的，就是有点大

**Comment by kkevsekk1** [comment]
底层c++ 的编译 就没有支持x86， 上层 怎么搞瞎掰扯！
这个项目要打包支持，得编译inrt 这个 apk 支持，再编译app 这支持，而且最后要保存一致，inrt 最终觉得你重新打包后支持的平台
