### ISSUE TITLE
考完试了没事做，有什么需求提一下

### ISSUE THREAD

**Issue by wilinz** [kkevsekk1/AutoX#340]

**Comment by wilinz** [comment]
> 希望增加用ADB（USB）方式连接电脑vscode功能，谢谢

正在开发中

**Comment by wilinz** [comment]
> 希望增加用ADB（USB）方式连接电脑vscode功能，谢谢

https://github.com/wilinz/AutoX/releases/tag/6.2.0-1

**Comment by jim19770812** [comment]
能否增加断点调试功能？
