### ISSUE TITLE
建议:或许可以弄个组织，或直接邀请核心贡献人员加入项目

### ISSUE THREAD

**Issue by Ecalose** [kkevsekk1/AutoX#342]
这样就不需要手动合pr了，核心贡献人员可以直接commit

**Comment by wilinz** [comment]
> 这样就不需要手动合pr了，核心贡献人员可以直接commit

容易导致项目管理混乱

**Comment by wangwang-code** [comment]
> > 这样就不需要手动合pr了，核心贡献人员可以直接commit
> 
> 容易导致项目管理混乱

两个人都能混，https://github.com/wangwang-code/AutoX/issues/13#issuecomment-1162852765

**Comment by kkevsekk1** [comment]
看了这种评论，很来气，我今天就有用上班时间，回答 一下 你们这些问题！
1.开源项目现在这种合作方式 我觉得利大于弊，有杠精一定会说，“弊大于利”！
2.就现在 我看到的贡献者里，自发性 非没有达到，邀请进  Collaborators 的程度！缺人！

肯定有杠精说 你这要求太高了！ 这个很简单，去找一个每天都有人合并请求的开源项目，，去提个pr 看看 ，人家怎么回应你的pr就懂了！
