### ISSUE TITLE
有交流群吗，微信或者qq

### ISSUE THREAD

**Issue by LZX284** [kkevsekk1/AutoX#345]
[有交流群吗，微信或者qq](http://www.autoxjs.com/topic/117/%E6%9C%89%E4%BA%A4%E6%B5%81%E7%BE%A4%E5%90%97-%E5%BE%AE%E4%BF%A1%E6%88%96%E8%80%85qq)
AutoX社区目前没什么人打理，Github这边主要是面向开发者的。而且由于网络的原因普通用户访问也不便。感觉这个需求很有必要。
这个项目现在维护者不多，如果能够多建立一些面向用户的交流渠道，那有一些问题就可以靠用户自己互相帮助解决，而且这也有利于提高这个项目的知名度
@wilinz  @kkevsekk1

**Comment by LZX284** [comment]
@wilinz  @kkevsekk1 看到了还请回复一下。这也只是一个建议吧。身为项目的维护者，总不能对用户的需求反馈一直爱理不理的吧？如果是这样，那用户又凭什么要去支持和赞助这个项目呢？

**Comment by kkevsekk1** [comment]
打开autoxjs就能看到 qq 群的提醒，有些人选择视而不见，有必要回复么？

**Comment by wilinz** [comment]
QQ，微信 群 主要是怕被和谐，看看auto.js就懂，至于TG，要科学上网，增加使用成本

**Comment by LZX284** [comment]
> 打开autoxjs就能看到 qq 群的提醒，有些人选择视而不见，有必要回复么？

@kkevsekk1 认真找了一下，目前能看到Q群的就两个地方，一个是打开社区-第四个页面-第二帖，另一个是APP-设置-关于开发者，这两个都算不上是显眼的地方，如果直接放在首页或开屏界面中的话会好很多，毕竟用户也是真的不知道才发帖询问的。至于有没有必要回复，这个，这也是你的自由吧，只是，个人感觉，回复一下，对这个项目未来的发展、对用户的使用体验来说会不会好一点呢？

**Comment by LZX284** [comment]
> QQ，微信 群 主要是怕被和谐，看看auto.js就懂，至于TG，要科学上网，增加使用成本

@wilinz 如果TG群不方便就算了。而Q群的话，作者其实早就已经建立了一个，可是直到现在也都没有被和谐呢。微信群的话应该也不会，别的应用也建立了微信群，也没有什么的。既然公开维护，那当然是要遵纪守法的，Auto.JS这类应用虽然有可能被用于黑灰产，但开发者自己应该坚持原则，只要不要带头去搞这些，那也就应该没有什么可顾虑的吧？

**Comment by okziji** [comment]
> 打开autoxjs就能看到 qq 群的提醒，有些人选择视而不见，有必要回复么？

QQ群早就满了

**Comment by LZX284** [comment]
> > 打开autoxjs就能看到 qq 群的提醒，有些人选择视而不见，有必要回复么？
> 
> @kkevsekk1 视而不见？你认为用户是故意装作看见发帖询问的吗？不愿意回复就算了，没必要找这么一个拙劣的理由。另外，除非你是真的不希望这个项目变好，否则的话，回复一下，对这个项目未来的发展、对用户的使用体验来都会好很多。

**Comment by wilinz** [comment]
作者可能没那么多时间

**Comment by wilinz** [comment]
精力有限

**Comment by kkevsekk1** [comment]
没有！有问题再这题，或发邮件！
