### ISSUE TITLE
 webpack-autojs 无法自动运行

### ISSUE THREAD

**Issue by ywzhaiqi** [kkevsekk1/AutoX#346]
经过排除，发现是 `autox-deploy-webpack-plugin`  中 `module.userRequest == this.changFile` 路径的斜线不一致导致的
```
/XXX/work/aaa/main.js   \XXX\work\aaa\main.js
```

**Comment by kkevsekk1** [comment]
可以升级这个



发送自我的盖乐世



-------- 原始信息 --------
发件人： ywzhaiqi ***@***.***>
日期: 2022/6/26 10:55 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] webpack-autojs 无法自动运行 (Issue #346)


经过排除，发现是 autox-deploy-webpack-plugin 中 module.userRequest == this.changFile 路径的斜线不一致导致的

/XXX/work/aaa/main.js   \XXX\work\aaa\main.js



―

**Comment by LZX284** [comment]
> 可以升级这个 发送自我的盖乐世

咦？作者这不是有时间回复问题了？那为什么AutoX社区的[这个帖子](http://www.autoxjs.com/topic/117/%E6%9C%89%E4%BA%A4%E6%B5%81%E7%BE%A4%E5%90%97-%E5%BE%AE%E4%BF%A1%E6%88%96%E8%80%85qq) 至今还是没有任何回复？
也许是真的 [精力有限](https://github.com/kkevsekk1/AutoX/issues/345#issuecomment-1166205333) 、
[作者可能没那么多时间](https://github.com/kkevsekk1/AutoX/issues/345#issuecomment-1166205248) 吧，但这个帖子：
[有交流群吗，微信或者qq](https://github.com/kkevsekk1/AutoX/issues/345)
作者确实是一点也没有去回复的意思的。除此以外，这个app版本号错误问题（ #291 #331 ）反复向作者提了很多次，但作者就是没有改，也许一次两次是真的忙吧，但反复提了这么多次，可这个错误的版本号可是直到现在也还没改啊！没有改！
真的搞不懂，如果不是要故意恶心人，那为什么一定非这么做不可呢？

**Comment by LZX284** [comment]
作为这个项目的贡献者，对这个项目付出了多少精力，大家自己可以自己去看 
[版本记录](https://github.com/kkevsekk1/AutoX/releases) 
[Contributors](https://github.com/kkevsekk1/AutoX/graphs/contributors)
[commits](https://github.com/kkevsekk1/AutoX/commits/dev-test)
也就是当初对这个项目倾注了这么多精力吧，否则现在也不会对这个项目多了几分关注。个人是真的希望这个项目能够好起来，但AutoX作者现在这个态度，这真的实在是让人一点儿也无法接受的……

**Comment by LZX284** [comment]
也许当初是真的傻吧……毕竟，辛辛苦苦改进的代码 PR 给了作者，但最后竟然没想到，作者竟然会是这种态度！
也许作者对这些是完全无所谓的吧，毕竟代码一旦提交上去是无法收回的，而Github上的Stars数和知名度最终也只会属于作者的这个项目以及作者自己。而就算贡献者有提出了什么问题、反馈了什么建议，作者也完全可以装作没看到，哪怕有时不得不回复一两句，对他也完全没有损失。毕竟贡献者的付出是没有保障的，哪怕出了问题，只要作者装聋作哑一段时间，那些贡献者应该就会自己受不了自行离去吧？那一切又可以回复原样，过一段时间，又会继续有另一个热心的贡献者继续把他编写的代码交给自己吧？

**Comment by LZX284** [comment]
请尊重一下Github上的开源作者们及背后默默付出的贡献者吧！
毕竟 AutoX 这个项目也不是作者一个人能原创出来的，其中真正的源头项目是 @hyb1996 的 [auto.js](https://github.com/hyb1996/Auto.js),如今AutoX虽然断开了同源头项目的Fork关系并开了赞助，但也决不能否定真正原作者的贡献
适配新系统所用的一部分代码是出自 [autojs M](https://github.com/TonyJiangWJ/Auto.js)，包括 为解决RhinoJS 新版本以及与AutoX相关的版权问题（ #302 ）而引用了其中的 Rhino1.7.14 AAR包及源码，这点在提交commit时是有注明的，但在版本发布后的改动说明里，作者却是有意或无意的忽略了这部分内容（项目中的 RhinoJS AAR包 已经由 1.7.13 版 变成1.7.14 版 还多了一个源码的jar包，但版本变更记录上丝毫没有提到）。如果作者不是故意忽略这个问题的话，那还是请作者把这个出处的声明补上吧！毕竟，人家大佬为完成这个项目也付出了许多辛苦的工作，并且也明确声明了引用他代码的[必要要求](https://github.com/TonyJiangWJ/Auto.js/issues/17)

**Comment by kkevsekk1** [comment]
> 也许当初是真的傻吧……毕竟，辛辛苦苦改进的代码 竟然 PR 给了这样的作者，任谁都竟然没想到，作者最后竟然会是这样的态度！ 也许作者对这些是完全无所谓的吧，毕竟代码一旦提交上去是无法收回的，而Github上的一切成就最终也只会属于作者自己。而就算用户有提出了什么问题、贡献者反馈了什么建议，作者也完全可以 [选择视而不见](https://github.com/kkevsekk1/AutoX/issues/345#issuecomment-1165216700) ，哪怕有时不得不回复一两句，对他也完全没有损失。作者大概是觉得，反正贡献者的付出是没有保障的，哪怕出了问题，哪怕问题再明显，只要 [选择视而不见](https://github.com/kkevsekk1/AutoX/issues/345#issuecomment-1165216700) ，那些贡献者应该就会自己受不了自行离去吧？那一切又可以回复原样，过一段时间，又会继续有另一个热心的贡献者继续把他辛辛苦苦编写的代码交给自己吧？

 谁说的代码 不可以 收回去？ 谁说的你写的代码 属于 我了？
你想收回去，你删掉你的 我同一pr 就ok了！ 要是其他人。 开源，什么是开源，其他人贡献的代码属于 作者？ 
回到 最基本的问题，打开autoxjs 就能看见群的消息，看不到？500多人都看到了，就你看不见？
1.7.14 是我贡献的？ 属于我的版权？  作为一名贡献者，要知道开源贡献者的基本要求！
还有 这个1.7.14  有改过 源码？我看到的结果根本就不兼容 老版本的ui代码！如果没改，app里的开源引用协议，需要改？
之前有个贡献者 提交一波代码，连基本的编译都不过，还有我写封感谢信给他！
开源社区也不是什么老师学生关系，大家都是平等的，我没有责任和义务给任何人批改作业！
我加的对外的接口，没有哪一个没有在说明文档中体现！
我加的权限申请至少稳定10多个版本，后来有人连Android版本关系都没搞懂，就要升级target，把权限改得一塌糊涂，不是我去擦的屁股，我说什么了？
最后在说一遍，选择参与开源，请把自己的东西搞好，不要觉得写了几行代码，就把开源这个事做完了！

群是我建的，不是开源项目的一部分，我愿意公布就公布，任何人都关不着！

关于捐赠，有人提，我也支持大家鼓励这些默默付出的人！时至今日 我没有收过任何人，一分钱，我也不需要！

![image](https://user-images.githubusercontent.com/16631944/175844019-e23f3c68-c87d-45c8-b5db-52c233ca175c.png)

不看不来气，越看越来气，还请求解释一下 “这样的作者“，是那样的？ 你pr的代码，没帮你配上文档，你问的有没有群，没告诉你？

**Comment by kkevsekk1** [comment]
你不是就想说 你对项目 贡献 巨大无比？ 在这！ 感谢你提交了63万行，删除了63万

![image](https://user-images.githubusercontent.com/16631944/175845503-c9ab6b86-5893-4953-b5f3-467dca70ba91.png)

**Comment by kkevsekk1** [comment]
> 经过排除，发现是 `autox-deploy-webpack-plugin` 中 `module.userRequest == this.changFile` 路径的斜线不一致导致的
> 
> ```
> /XXX/work/aaa/main.js   \XXX\work\aaa\main.js
> ```

可以考虑 把这个两边的 符合 替换 成统一的在进行比较

**Comment by LZX284** [comment]
> 你不是就想说 你对项目 贡献 巨大无比？ 在这！ 感谢你提交了63万行，删除了63万

这个数据是Github自动统计出来的，也许是统计方法有bug，导致数字看起来有点大。但这不是关键，哪怕就只有63行呢，难道你就不能好好说话，尊重一下这个项目的用户和贡献者吗？
另外，请按 [autojs M](https://github.com/TonyJiangWJ/Auto.js)项目的要求，补上必要的出处声明及感谢吧，毕竟你自己也说过，开源不等于随意使用。使用了别人的代码，按原作者的要求注明一下出处和感谢，这怎么也不算过分吧？

**Comment by kkevsekk1** [comment]
项目 原作者运行 抄袭他代码了吗？ 
我有一定的责任，但不是，引用人家的东西，谁引用，谁跟有责任讲清楚这些东西

**Comment by kkevsekk1** [comment]
甭管了你搞了多少新东西，
让以前的代码能够正确运行，是最低要求！

**Comment by LZX284** [comment]
> 项目 原作者允许 抄袭他代码了吗？ 我有一定的责任，但不是，引用人家的东西，谁引用，谁更有责任讲清楚这些东西！ 就是升级的1.7.14 这个版本，兼容性问题也没修，也没说，我还退回到1.7.13 的版本！

居然有种说法！上面已经说过了，这边引用的已经在提交给你的commit和pr中注明了，但你在发布版本时却有意无意忽略了这些内容。也就是说，用户只要不去深入查看commit记录，就根本不知道你这个版本其实是换了Rhino版本的，你说是不是？另外，原作者的许可这边也有，这边也亲自跟原作者谈了，人家大佬也允许了：[引用这边代码写明来源就行](https://github.com/TonyJiangWJ/Auto.js/issues/18#issuecomment-1162639720)

**Comment by LZX284** [comment]
> 谁说的代码 不可以 收回去？ 谁说的你写的代码 属于 我了？你想收回去，你删掉你的 我同意pr 就ok了！

你也应该明白，按开源协议的要求，一旦提交上去这些代码作者接受了，那这些代码也就属于这个项目，虽然版权并不完全属于作者一个人，但作者是这个项目的拥有者及主导人。哪怕就是这边提PR了，作者也照样有权不同意。你说是不是？而且，既然都属于这个项目了，哪怕你不想要，也不该是这边提PR，你只要想删除的话，你就完全有这个权力，你说是不是？

**Comment by kkevsekk1** [comment]
![image](https://user-images.githubusercontent.com/16631944/175858955-b005170d-e28f-425c-941b-e8147bafa2cd.png)

**Comment by kkevsekk1** [comment]
不是这玩？

**Comment by LZX284** [comment]
> ![image](https://user-images.githubusercontent.com/16631944/175858955-b005170d-e28f-425c-941b-e8147bafa2cd.png)

这是以前升级过的一个版本，后来你又回退了不是？现在加入的这个，是 autojs M这个项目中的吧

**Comment by kkevsekk1** [comment]
> > 谁说的代码 不可以 收回去？ 谁说的你写的代码 属于 我了？你想收回去，你删掉你的 我同意pr 就ok了！
> 
> 你也应该明白，按开源协议的要求，这些代码一旦提交上去并且作者接受了，那这些代码也就属于这个项目了，虽然版权并不完全属于作者一个人，但作者是这个项目的拥有者及主导人。哪怕就是这边提PR了，作者也照样有权不同意。你说是不是？而且，既然都属于这个项目了，哪怕你不想要，也不该是这边提PR，你只要想删除的话，你就完全有这个权力，你说是不是？

你怕是搞错了哦 ！那么简单，就不会有很多开源项目 求爷告奶奶 的找贡献者 删除他们的pr

**Comment by kkevsekk1** [comment]
> > ![image](https://user-images.githubusercontent.com/16631944/175858955-b005170d-e28f-425c-941b-e8147bafa2cd.png)
> 
> 这是以前升级过的一个版本，后来你又回退了不是？现在加入的这个，是 autojs M这个项目中的吧

我退的是dev分支，5xx 版本的，他当时好像是提交了以后dev-test，好像是那个一版本导致编译都没法过，当时我手还贱还给他合并进去了，我记得我还专门@ 贡献的人，好像他也没管。就跟你说的一样，我合并了pr的代码，这代码就是我的了！责任也是我的了，如果各个都搞些这种代码进来，开源项目还怎么发展哦！ 作为一个贡献者 是来解决问题的，不是来制造问题的！

**Comment by LZX284** [comment]
> 我退的是dev分支，5xx 版本的，他当时好像是提交了以后dev-test，好像是那个一版本导致编译都没法过，当时我手还贱还给他合并进去了，我记得我还专门@ 贡献的人，好像他也没管。就跟你说的一样，我合并了pr的代码，这代码就是我的了！责任也是我的了，如果各个都搞些这种代码进来，开源项目还怎么发展哦！ 作为一个贡献者 是来解决问题的，不是来制造问题的！

这不就是了？你确实有权力删除而且也已经删除了你不想要的代码，不管是哪个分支都一样。
就算在6.X版本，也就是dev-test分支，之前用的也是 Rhino 1.7.13版，但这个版本存在不符合MPL2.0协议要求的问题。
之前的不清楚，但当前云编译不能通过的版本也只有5.X，也就是dev的这个分支。而关于版权，有一点已经说的很清楚了，代码是属于这个项目的，而不是属于个人的。而且GPL2.0这个协议也是发布后不可撤销的：[只要某个软件开始使用了GPL（2.0 or 3.0）,那么该许可证下的授权是不能撤回的。](https://www.zhihu.com/question/287106255)，这个不论对于作者还是贡献者来说都是一样的。

**Comment by CuteLicense** [comment]
神仙打架。两位息怒息怒，开源项目大都是在靠爱发电，多包容多理解

**Comment by wangwang-code** [comment]
哎······

**Comment by gxylfm** [comment]
作者说换工作了，忙应该是真的。但我说一句，我至今不用6的版本，用的我自己AS打包的5.0.9版本，因为最近更新和修复太频繁，而且新版本不支持一些前缀语法，虽然说测试版，新功能也固然好，但同时各种问题不断，希望贡献者能在自己的库，耐心多测试几次，没什么问题再PR，本来作者本来就忙了，更新一个版本号，修复问题又两三个版本号，腾讯都不敢这么升级（支持版本号只有作者能改）。

**Comment by LZX284** [comment]
> 作者说换工作了，忙应该是真的。但我说一句，我至今不用6的版本，用的我自己AS打包的5.0.9版本，因为最近更新和修复太频繁，而且新版本不支持一些前缀语法，虽然说测试版，新功能也固然好，但同时各种问题不断，希望贡献者能在自己的库，耐心多测试几次，没什么问题再PR，本来作者本来就忙了，更新一个版本号，修复问题又两三个版本号，腾讯都不敢这么升级（支持版本号只有作者能改）。

这种说法有一些问题。
首先，6.x版本的不稳定是之前就有的，并不是这边PR时带进去的，这个作者自己也可以证明。
第二，关于测试，至少这边在提交PR时都经过必要的测试的，但一些适配机型和兼容性相关的，个人能力所及难免疏漏，而且想要在测试中包含所有机型和情况，这个也是不现实的。
第二，都说支持版本号只有作者能改了，事实上这边在PR时也基本不会去动版本号（除非作者自己要求贡献者去改，但这样也不太合适）。但有时作者自己怎么说都不愿意去改，谁有办法？
第三，你说 “更新一个版本号，修复问题又两三个版本号，腾讯都不敢这么升级” ，但事实上这些版本号可都是作者自己发布的，作者合并PR是有责任加以审核的，也不能简单的说一句说作者忙，就把责任全部都怪到我们这些贡献者头上。
最后，你说“忙应该是真的”（没有了解过作者的新工作的话，随意说应该并不客观可信），这大家都有事忙，但总不能一天天二十四小时连续不停的忙，而且从上面反馈的一系列问题也可以看出来，作者就算有时比较忙但却经常会有空闲浏览这个项目的Issue和回复（至于是不是有回复那就要看作者的心情了）。

**Comment by wilinz** [comment]
我也不是偏袒谁，只是实话实说

**Comment by wilinz** [comment]
建议作者合Pr先测试测试

**Comment by wilinz** [comment]
版本号和release界面不一致也确实存在

**Comment by wilinz** [comment]
还有规范一下代码，字符串资源硬编码不太好吧？希望作者合pr审核一下

**Comment by wilinz** [comment]
图标资源应该要导入svg矢量图了吧，png在一些设备失真看着都难受

**Comment by wilinz** [comment]
希望作者有时间规范一下pr要求

**Comment by wilinz** [comment]
所以，改UI建议先了解一下Google Material Design设计规范

**Comment by kkevsekk1** [comment]
@ywzhaiqi  bug已修复
