### ISSUE TITLE
6.1.X 运行示例代码“PaddleOCR(自定义模型路径)"闪退崩溃及原因

### ISSUE THREAD

**Issue by agandab** [kkevsekk1/AutoX#347]
运行示例代码：PaddleOCR(自定义模型路径)，AutoX系统闪退崩溃，要重新授无障碍权限。

调试：（修正该示例代码自定义模型路径：org.autojs.autojs.dev）
//let myModelPath = "/sdcard/Android/data/org.autojs.autojs/models/ocr_v2_for_cpu";
let myModelPath = "/sdcard/Android/data/org.autojs.autojs.dev/models/ocr_v2_for_cpu";

修改后运行正常。

**Comment by wilinz** [comment]
这是由于调试版本和release版本的包名不一致导致的
