### ISSUE TITLE
5.x版本云编译无法通过问题及违反MPL2.0协议的情况

### ISSUE THREAD

**Issue by LZX284** [kkevsekk1/AutoX#348]
我退的是dev分支，5xx 版本的，他当时好像是提交了以后dev-test，好像是那个一版本导致编译都没法过，当时我手还贱还给他合并进去了，我记得我还专门@ 贡献的人，好像他也没管。就跟你说的一样，我合并了pr的代码，这代码就是我的了！责任也是我的了，如果各个都搞些这种代码进来，开源项目还怎么发展哦！ 作为一个贡献者 是来解决问题的，不是来制造问题的！

_Originally posted by @kkevsekk1 in https://github.com/kkevsekk1/AutoX/issues/346#issuecomment-1166837053_

**Comment by LZX284** [comment]
> 我退的是dev分支，5xx 版本的，他当时好像是提交了以后dev-test，好像是那个一版本导致编译都没法过，当时我手还贱还给他合并进去了，我记得我还专门@ 贡献的人，好像他也没管。就跟你说的一样，我合并了pr的代码，这代码就是我的了！责任也是我的了，如果各个都搞些这种代码进来，开源项目还怎么发展哦！ 作为一个贡献者 是来解决问题的，不是来制造问题的！

@kkevsekk1  查了一下，5.x版本是在这个commit之后才出现云编译都没法过的问题的：
[添加新版本的无障碍全局动作函数](https://github.com/kkevsekk1/AutoX/pull/252)
另外，5.x版本中仍然存在违反开源协议的情况，请注意修正：
 Rhino 1.7.13 没有提供修改过的源码：[RhinoJS 新版本以及与AutoX相关的版权问题](https://github.com/kkevsekk1/AutoX/issues/302)

**Comment by wilinz** [comment]
可以回滚的

**Comment by wilinz** [comment]
这个分支也没多少人维护了，有问题可以回滚

**Comment by wilinz** [comment]
代码已经合并我也无能为力，测试不过不应该拒绝pr么

**Comment by wilinz** [comment]
已提交回滚pr
