### ISSUE TITLE
能否增加防无障碍检测功能

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#355]
不知道技术上能不能实现，现在某些app会检测无障碍，发现无障碍开启就会封号，所以对使用autox.js造成影响，希望能考虑一下增加防无障碍检测功能

**Comment by kkevsekk1** [comment]
这种，单纯靠本软件开发是没法解决的，你得做一套完整的解决方案……



发送自我的盖乐世



-------- 原始信息 --------
发件人： lnxcyq ***@***.***>
日期: 2022/7/7 15:11 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 能否增加防无障碍检测功能 (Issue #355)


不知道技术上能不能实现，现在某些app会检测无障碍，发现无障碍开启就会封号，所以对使用autox.js造成影响，希望能考虑一下增加防无障碍检测功能

―

**Comment by lnxcyq** [comment]
如果脚本需要防止类似淘宝的无障碍检测，请使用 AutoJs.fakeIdlefish。可以规避无障碍检测，将包名直接改成XX的包名，加了个.x的后缀
    我看到另一个auto.js说可以规避，不知道是不是真的能做到

**Comment by wilinz** [comment]
https://www.zhihu.com/question/426764228
