### ISSUE TITLE
paddle.ocr无结果

### ISSUE THREAD

**Issue by inoryFly** [kkevsekk1/AutoX#358]
新版调用paddle.ocr，分析不出结果，但是ocrText是好的
![image](https://user-images.githubusercontent.com/32086607/178274384-69498af4-97fd-46eb-b2b1-d15d8c99d1bd.png)

**Comment by LZX284** [comment]
@inoryFly PaddleOCR升级到2.5版了(提升识别速度及准确率)，你看看是否还有这些问题：
[Auto.Js+ V6.2.5](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5)

**Comment by jeromeleong** [comment]
看看示範的ocr使用方法吧，應該幫到你
https://github.com/kkevsekk1/AutoX/blob/dev-test/app/src/main/assets/sample/AI/OCR%E6%88%AA%E5%9B%BE%E8%AF%86%E5%88%AB.js
```js
result = paddle.ocr(img);
for(x of result){
    if (x.confidence > 0.9){
        log(x.words);
    }
}
```

**Comment by yangy996** [comment]
https://blog.csdn.net/YY007H/article/details/124540297
