### ISSUE TITLE
安卓11，root 手势函数都用了没反应有大佬知道为啥吗

### ISSUE THREAD

**Issue by haleyrom** [kkevsekk1/AutoX#359]

**Comment by kkevsekk1** [comment]
没有以管理员权限运行app



发送自我的盖乐世



-------- 原始信息 --------
发件人： haleyrom ***@***.***>
日期: 2022/7/12 14:47 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 安卓11，root 手势函数都用了没反应有大佬知道为啥吗 (Issue #359)


―

**Comment by haleyrom** [comment]
大佬是说用RootAutomator是吗

**Comment by kkevsekk1** [comment]
整个app进程

**Comment by haleyrom** [comment]
有eg给我看下吗？

**Comment by haleyrom** [comment]
有eg或者文档没？很奇怪，root点击都可以就是滚动这些手势函数不行，要说没权限也不会吧

**Comment by Bob8259** [comment]
看看这个帖子，直接使用shell发送命令就可以。https://github.com/kkevsekk1/AutoX/issues/1207
