### ISSUE TITLE
我下载了这个项目，用这个Android Studio编译的autoxjs为什么无法打包

### ISSUE THREAD

**Issue by daiyh** [kkevsekk1/AutoX#36]
我下载了这个项目，用这个Android Studio编译的autoxjs为什么无法打包
打包的时候如下提示：
java.io.FileNotFoundException: template.apk

有没有高手提点一下，感谢。

**Comment by kkevsekk1** [comment]
运行 inrt 中build ，在运行 cp2app ，然后在运行 app的 build 就可以了，
原来就是 inrt 项目 会编译出 一个template.apk 的文件，这文件要copy到 app 项目中作为模板文件

**Comment by Boris-code** [comment]
cp2app 是啥命令呢 没找到

**Comment by wilinz** [comment]
看仓库readme.md
