### ISSUE TITLE
定时脚本(含wakeUp函数)无法运行(OPPO手机)

### ISSUE THREAD

**Issue by TFSN20** [kkevsekk1/AutoX#360]
定时脚本(有唤醒屏幕函数wakeUp等)无法运行, 好像一旦手机息屏后, 未执行的定时脚本到点不能执行, 只能手动唤醒屏幕, 好想只有亮屏后脚本才会执行, 但我醒脚本唤醒屏幕啊

**Comment by kkevsekk1** [comment]
已修复
