### ISSUE TITLE
TBS授权的PR已提交却又被关闭了，那些所谓的问题这边也都给出相关说明了，如果作者还是坚持不接受PR，那么侵权责任也只能算在作者身上

### ISSUE THREAD

**Issue by LZX284** [kkevsekk1/AutoX#366]
> 改好了再提，还有 你不是说现在的 rhino 1.7.14 是给修改过的么，属于侵权版本的？给恢复到 rhino 1.7.13

> @kkevsekk1  怎么又把 [PR](https://github.com/kkevsekk1/AutoX/pull/365) 给关了呢？  @kkevsekk1  @wilinz  问题是没法那样提交啊，那个License组件是专门用于“开放源代码许可”的，只适合添加开源组件，TBS 根本就不是开源组件，又怎么能够强行按开源的方式添加呢？！所以这边也只能另开一个页面了
> 
@kkevsekk1 关于 [PR中问题的解释](https://github.com/kkevsekk1/AutoX/pull/365#issuecomment-1186684856)，是没法那样改，不是这边不想改，现在可是你自己找借口关闭的PR，那就不要再无端指责别人不负责了
 rhino 1.7.14 是给修改过的，但这个早就修正好了，在项目里附带了修改过的源码，不会又是你自己忘了吧？

_Originally posted by @LZX284 in https://github.com/kkevsekk1/AutoX/issues/364#issuecomment-1186689328_

**Comment by LZX284** [comment]
[补充 TBS 相关授权许可 第二次PR](https://github.com/kkevsekk1/AutoX/pull/367)
PR的相关说明：
> @kkevsekk1 关于 [PR中问题的解释](https://github.com/kkevsekk1/AutoX/pull/365#issuecomment-1186684856)，不是这边不想改，是真的没法像你说的那样改
> @kkevsekk1  怎么又把 [PR](https://github.com/kkevsekk1/AutoX/pull/365) 给关了呢？  @kkevsekk1  @wilinz  问题是没法那样提交啊，那个License组件是专门用于“开放源代码许可”的，只适合添加开源组件，TBS 根本就不是开源组件，又怎么能够强行按开源的方式添加呢？！所以这边也只能另开一个页面了

**Comment by kkevsekk1** [comment]
![lADPJw1WS_J4aGnNBP_NAm4_622_1279](https://user-images.githubusercontent.com/16631944/179439350-6a7f0d6b-68a6-4747-8858-786a08082172.jpg)

**Comment by LZX284** [comment]
@kkevsekk1 没找到啊？这个是AutoX里页面的吗？
再说了，只要这边提交的PR能解决版权上的问题，作者也可以先合并后再进行其它方面的完善吧？
作为这个项目的主导者，也没必要这样为难贡献者吧？

**Comment by kkevsekk1** [comment]
就这样吧……
你跟其他团队合作也这样搞，代码一提交锅都是别人的……



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/7/18 11:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] TBS授权的PR已提交却又被关闭了，那些所谓的问题这边也都给出相关说明了，如果作者还是坚持不接受PR，那么侵权责任也只能算在作者身上 (Issue #366)


@kkevsekk1<https://github.com/kkevsekk1> 没找到啊？这个是AutoX里页面的吗？
再说了，只要这边提交的PR能解决版权上的问题，作者也可以先合并后再进行其它方面的完善吧？
作为这个项目的主导者，也没必要这样为难贡献者吧？

―

**Comment by wilinz** [comment]
没必要的话把tbs删了也可以，这里开发的是Autox.js , 不是开发浏览器，没必要搞得比浏览器还复杂，而且EWebView这个类目前版本没有使用（BUG多如牛毛）

**Comment by LZX284** [comment]
> 没必要的话把tbs删了也可以，这里开发的是Autox.js , 不是开发浏览器，没必要搞得比浏览器还复杂，而且EWebView这个类目前版本没有使用（BUG多如牛毛）

@wilinz  关键也不是要当浏览器用吧。不知道你还记不记得AutoX除了云文档外还有社区和脚本商店这回事？虽然很久没维护了，但这些个功能都是依赖于webview实现的，且搞好的话是非常有益于这个项目未来发展的，而TBS网页兼容性在很多地方都强于系统webview，也有助减少以后开发WebView相关功能的麻烦

**Comment by LZX284** [comment]
@wilinz 以前也有不少人提过相关建议的。而现在除了作者外，这个项目终于有了另一个有能力的主导者了。相信你也是希望这个项目未来也能有更好发展的吧？而不管是 PRO 还是 类似 Hamibot 这类的autojs项目都早已有了完善的脚本市场功能，作为用户，除了APP本身的完善，对定制脚本的需求也应该是更多更广泛的吧

**Comment by wilinz** [comment]
作者的市场多年未维护了吧😄

**Comment by LZX284** [comment]
> 作者的市场多年未维护了吧😄

@wilinz 是的。感觉很可惜……
