### ISSUE TITLE
感谢 @wilinz增加adb功能，反映一个bug 

### ISSUE THREAD

**Issue by a4youma** [kkevsekk1/AutoX#369]
adb连接正常了，但更新vscode插件到1.08后，同样的代码，即使是简单log(111),也无法在vc上执行，提示出错，而在手机autox上可以正常运行。
还有，以前的log语句既可以在日志控制台显示，还可在vc的输出栏显示，而现在，vc的输出栏不显示了，只能显示adb的连接信息，调试起来很不方便。请 @wilinz有时间能优化下，谢谢~~~
![Screenshot_20220719_212809_org autojs autojs dev](https://user-images.githubusercontent.com/53590238/179765192-8a1a04f9-b9c7-4ba6-ab47-7d055ad30768.jpg)
![Screenshot_20220719_095721_org autojs autojs dev](https://user-images.githubusercontent.com/53590238/179765190-f96c12be-2d6d-4c4b-a427-516d23cdbe5d.jpg)

**Comment by wilinz** [comment]
最新版已修复，请看我仓库release

**Comment by a4youma** [comment]
> 最新版已修复，请看我仓库release

非常感谢
