### ISSUE TITLE
各位大佬，有没遇见脚本运行到6-7个小时默认就闪退了

### ISSUE THREAD

**Issue by haleyrom** [kkevsekk1/AutoX#371]
各位大佬，有没遇见脚本运行到6-7个小时默认就闪退了，环境手机root的

**Comment by kkevsekk1** [comment]
打包厚的版本inrt修复过这个问题，如果是带开发功能的版本没测试过，我们运行几天都不会挂



发送自我的盖乐世



-------- 原始信息 --------
发件人： haleyrom ***@***.***>
日期: 2022/7/20 14:11 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 各位大佬，有没遇见脚本运行到6-7个小时默认就闪退了 (Issue #371)


各位大佬，有没遇见脚本运行到6-7个小时默认就闪退了

―

**Comment by haleyrom** [comment]
用的是6.2.2有没推荐的版本号呢
