### ISSUE TITLE
悬浮窗点击脚本名称崩溃

### ISSUE THREAD

**Issue by 5460** [kkevsekk1/AutoX#375]
从6.1.9升级到6.2.3，发现出现了这个问题，系统是基于安卓12的MIUI13。
操作：在悬浮窗界面点击脚本名称位置
预期行为：执行该脚本
实际行为：AutoX.js崩溃，无障碍权限关闭

操作：在主界面点击脚本名称位置
预期行为：编辑该脚本
实际行为：无动作

崩溃调试信息：
Version: 623
Android: 31
java.lang.NullPointerException: Attempt to invoke interface method 'org.autojs.autojs.model.script.ScriptFile org.autojs.autojs.model.explorer.ExplorerItem.toScriptFile()' on a null object reference
org.autojs.autojs.ui.floating.CircularMenu.lambda$showScriptList$2(CircularMenu.java:149)
org.autojs.autojs.ui.floating.CircularMenu$$ExternalSyntheticLambda7.invoke(Unknown Source:4)
org.autojs.autojs.ui.explorer.ExplorerViewKt$ExplorerItemViewHolder.onItemClick(ExplorerViewKt.kt:522)
org.autojs.autojs.ui.explorer.ExplorerViewKt$ExplorerItemViewHolder_ViewBinding$4.doClick(ExplorerViewKt$ExplorerItemViewHolder_ViewBinding.java:66)
butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
android.view.View.performClick(View.java:7753)
android.view.View.performClickInternal(View.java:7730)
android.view.View.access$3700(View.java:861)
android.view.View$PerformClick.run(View.java:29146)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8293)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by LZX284** [comment]
@5460  尝试修复了一下，并升级OpenCV及PaddleOCR(提升识别速度及准确率)，你看看效果如何：
[Auto.Js+ V6.2.5](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5)

**Comment by wilinz** [comment]
已修复

**Comment by 5460** [comment]
实测问题已解决，感谢二位的快速修复
