### ISSUE TITLE
布局范围分析，经常显示的不一样

### ISSUE THREAD

**Issue by djnjbjb** [kkevsekk1/AutoX#379]
用布局范围分析，经常显示的不一样，有时候显示的多，有时候显示的少。

如果用脚本输出所有控件，似乎是一致的。
但布局范围分析的图形显示，就经常不一样。

目标APP是抖音。

**Comment by kkevsekk1** [comment]
这是正常的，因为来回切换，以及页面没有稳定，解决办法是你在代码里， 脚本你 控制一下

**Comment by djnjbjb** [comment]
就是有些控件的信息我想看一下，有时看得到有时看不到。


页面没有稳定是怎么回事？
我现在发现，一般重新开一下抖音，显示的控件会相对多一些，但每次也不太一样。
使用一会儿，控件好像就变少了。
所以显示少的时候就重新开一下，碰碰运气。


我现在会用脚本输出，看一下全部控件。
但我还不太熟悉，不能看的很明白。配合图形化显示更方便一些。
我看你说“解决办法是你在代码里， 脚本你 控制一下”，脚本和布局范围分析能协同吗？

**Comment by djnjbjb** [comment]
脚本输出所有控件，好像也是在变化的。
只是信息太多了，所以之前没注意到变化。

**Comment by kkevsekk1** [comment]
对find 的结果进行打印，如果有就进一步执行，没有就继续查找




发送自我的盖乐世



-------- 原始信息 --------
发件人： djnjbjb ***@***.***>
日期: 2022/7/25 17:14 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 布局范围分析，经常显示的不一样 (Issue #379)


就是有些控件的信息我想看一下，有时看得到有时看不到。

页面没有稳定是怎么回事？
我现在发现，一般重新开一下抖音，显示的控件会相对多一些，但每次也不太一样。
使用一会儿，控件好像就变少了。
所以显示少的时候就重新开一下，碰碰运气。

我现在会用脚本输出，看一下全部控件。
但我还不太熟悉，不能看的很明白。配合图形化显示更方便一些。
我看你说“解决办法是你在代码里， 脚本你 控制一下”，脚本和布局范围分析能协同吗？

―

**Comment by djnjbjb** [comment]
好的，谢谢
