### ISSUE TITLE
安卓11，click 手势函数都没反应有大佬知道问题吗？

### ISSUE THREAD

**Issue by haleyrom** [kkevsekk1/AutoX#381]
安卓11，click 手势函数都没反应有大佬知道问题吗？

**Comment by kkevsekk1** [comment]
这类问题真的不好回答，
第一条建议先百度，自己解决
建议到 autojs 或autoxjs的群里问题

**Comment by wangwu2003** [comment]
或者是按钮有检测触屏事件？试了各种脚本的点击都有反应但是没有触发事件
