### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by bybyhuang** [kkevsekk1/AutoX#382]
6.2.4版本脚本打包的时应用图标和启动界面图标打包错乱，启动界面文本修改设置不生效

**Comment by gxylfm** [comment]
> 
是的。

**Comment by wilinz** [comment]
已修复

**Comment by kkevsekk1** [comment]
[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20220814-163213_Samsung_Internet_jpg_1660466144619]
我不知道这3个步骤是不是这样运行的:

1.编译inrt的 arm7 为inrt32.apk
2.复制inrt32.apk 到template.apk
3.编译app32.apk
 再重复
1.编译inrt的arm8为inrt64.apk
2.复制inrt64.apk 到template.apk
3.编译出app64.apk





发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/8/14 16:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包问题 (Issue #382)


已修复

―
