### ISSUE TITLE
$crypto.encrypt 加密解密的问题,会出现

### ISSUE THREAD

**Issue by honsinshen** [kkevsekk1/AutoX#383]
let message = 'Hello World';
let key  = new $crypto.Key("1234561234561234");
let aes = $crypto.encrypt(message, key,'aes/ecb/PKCS5Padding');
log(aes);

这种 语法只能在 文件根部执行, 如果放到
function(){
let message = 'Hello World';
let key  = new $crypto.Key("1234561234561234");
let aes = $crypto.encrypt(message, key,'aes/ecb/PKCS5Padding');
log(aes);
}

就会报错 ReferenceError: "key" is not defined.

**Comment by honsinshen** [comment]
加密方式 AES/ECB/PKCS5Padding  可以用了 但$crypto.digest(data, "MD5") 生成的md5与php7.0生成的md5不统一 不知道啥情况,php 各版本 生成的md5都是一样的, 但$crypto.digest(data, "MD5") 生成的就不同了.    当前用java.math.BigInteger(1,java.security.MessageDigest.getInstance("MD5").digest(java.lang.String(str).getBytes())).toString(16) 来替代,但如果str内容多的话 生成的会与php生成的不同,还存在一个问题,就是 如果这个命令 生成的md5 开头数字为0的话 就不会展示出来, 32位 成了 31位或者30 位

**Comment by kkevsekk1** [comment]
> 

![Screenshot_20220803-234935_OpenHub](https://user-images.githubusercontent.com/16631944/182654345-bc9d28f0-9852-4505-8b3d-5a5a5c3e07e4.jpg)

**Comment by kkevsekk1** [comment]
改为this.data

**Comment by wilinz** [comment]
md5问题已修复
