### ISSUE TITLE
状态栏快捷按钮无法使用

### ISSUE THREAD

**Issue by jiemo9527** [kkevsekk1/AutoX#384]
添加手机系统下拉状态栏 快捷按钮“布局范围分析”后，无法点击使用  灰色。
6.2.4版本  设备安卓12

**Comment by honsinshen** [comment]
因为有的界面不是安卓原生的视图渲染的  所以不支持, 就像2d3d的游戏界面中 ,无法分析布局,因为那些布局是在引擎中渲染的,autojs 无法 分析

**Comment by jiemo9527** [comment]
你理解错了，不是无法渲染分析模块，而是状态栏按钮灰色无法一键进入分析状态;相同情景下，老版的autojs可以正常使用
见图
![Uploading Screenshot_2022-07-31-18-35-00-41_d365b52accad0f47adbc08c16219827d.jpg…]()

**Comment by jiemo9527** [comment]
![Screenshot_2022-07-31-18-35-00-41_d365b52accad0f47adbc08c16219827d](https://user-images.githubusercontent.com/36528975/182022218-2d5884f7-c90a-4829-aa2f-2145ee9d9c48.jpg)

**Comment by jiemo9527** [comment]
thanks
