### ISSUE TITLE
使用http.request做请求时 会报错 writeTo is not a function, it is object.

### ISSUE THREAD

**Issue by honsinshen** [kkevsekk1/AutoX#385]
var 爱仕达 =  http.request(p,{
    method: "POST",
    headers: { },
    body:body ,
  });
  return 爱仕达.body.string()   ;

TypeError: writeTo is not a function, it is object. (file:///android_asset/modules/__http__.js#49)
TypeError: writeTo is not a function, it is object.
    at file:///android_asset/modules/__http__.js:49:0
    at hh ([remote]main.js:428:0)
    at httpPost ([remote]main.js:404:0)
    at checkVersion ([remote]main.js:346:0)
    at [remote]main.js:131:0

单文件内测试是没有问题的,当放入项目中就会报错, 包内也 只引入了 

importClass(android.animation.ObjectAnimator);
importClass(android.animation.AnimatorSet); 
importClass(android.view.animation.BounceInterpolator);
importClass(android.content.ContextWrapper);
importClass(android.content.IntentFilter); 

importClass("javax.crypto.spec.DESKeySpec");
importClass("javax.crypto.SecretKeyFactory");
importClass("javax.crypto.Cipher");
importClass("javax.crypto.KeyGenerator");
importClass("javax.crypto.SecretKey");
importClass("javax.crypto.spec.SecretKeySpec");
importClass("javax.crypto.KeyGenerator");
importClass("javax.crypto.spec.IvParameterSpec");

**Comment by honsinshen** [comment]
http的问题解决了 谢谢

**Comment by honsinshen** [comment]
http 还出现问题了, 只能请求一次, 第二次就会报错 
21:20:48.130/E: JavaException: java.lang.RuntimeException: java.util.concurrent.TimeoutException (file:///android_asset/modules/__http__.js#107)
JavaException: java.lang.RuntimeException: java.util.concurrent.TimeoutException

**Comment by kkevsekk1** [comment]
这个问题 应该修复了把，是改动http.js
