### ISSUE TITLE
使用应用自带悬浮窗出现的问题和vscode连接出现的问题

### ISSUE THREAD

**Issue by honsinshen** [kkevsekk1/AutoX#386]
悬浮窗目前发现两个问题
1:使用布局分析中的 布局层次分析后 ,无法退出该模式,只能通过重启手机才可以退出
2:使用布局分析中的 布局范围分析,可以对微信进行分析但无法对微信中的小程序界面进行分析  ,版本号6.1.4则可以对小程序中的界面进行分析  还望解决 感谢

还有一个问题是vscode连接的问题,无法通过ip地址进行连接, 电脑关闭防火墙后 还是无法连接,只能通过adb 进行连接,当前vscode插件的版本号为1.108.0  ,这个问题不知是PC端的问题还是手机的问题

**Comment by wilinz** [comment]
检查是否在同一局域网

**Comment by wilinz** [comment]
布局分析的问题不知道你用什么版本

**Comment by honsinshen** [comment]
布局层次分析  这个是用的 6.2.5 c 版本, 6.2.5的 布局范围分析这个问题解决了, 能否识别元素 还未测试,

**Comment by honsinshen** [comment]
检查是否在同一局域网
电脑连接在光纤猫上, 无线路由器 连接在光纤猫上, 使用 autojspro 可以进行连接 ,之前忘记哪个版本了, 也是可以通过这种方式进行连接的

**Comment by wilinz** [comment]
> 布局层次分析 这个是用的 6.2.5 c 版本, 6.2.5的 布局范围分析这个问题解决了, 能否识别元素 还未测试,

你说的版本不是我们项目的

**Comment by honsinshen** [comment]
> > 布局层次分析 这个是用的 6.2.5 c 版本, 6.2.5的 布局范围分析这个问题解决了, 能否识别元素 还未测试,
> 
> 你说的版本不是我们项目的

这个是你们的项目, 我之前提交了几个 bug  ,你们算是给了个修复包,我来测试  然后就遇到这个问题了, 在没安装这个版本前,用的是6.2.5 并不是延伸板 ,问题还是有这个 问题, 所以来请教了

**Comment by wilinz** [comment]
我们目前只更新到6.2.4

**Comment by wilinz** [comment]
![image](https://user-images.githubusercontent.com/59408438/182639285-af87745d-3ae2-43b5-89e1-143e49ba5254.png)

**Comment by honsinshen** [comment]
记错了 哈哈 别见怪哈 ,但是这个版本也有连接不上的问题 ,奇怪了

**Comment by wilinz** [comment]
插件开启服务了没有

**Comment by honsinshen** [comment]
> 



> 插件开启服务了没有

如梦初醒呀! 一语点醒梦中人!

**Comment by wilinz** [comment]
我就说我测试过没有问题，看来连接失败要弹个toast提示 开启服务

**Comment by honsinshen** [comment]
布局分析那个  6.2.4 有这个问题, 然后应该你们团队的贡献者  修复了一下 发了个6.2.5c  所以 在这个版本中解决了

**Comment by wilinz** [comment]
> 布局分析那个 6.2.4 有这个问题, 然后应该你们团队的贡献者 修复了一下 发了个6.2.5c 所以 在这个版本中解决了

那个是衍生版本

**Comment by wilinz** [comment]
> 我就说我测试过没有问题，看来连接失败要弹个toast提示 开启服务

![image](https://user-images.githubusercontent.com/59408438/182643408-d448e3d2-a393-4d50-b108-a29876253523.png)

**Comment by wilinz** [comment]
我们版本从来没有这个问题

**Comment by wilinz** [comment]
我们的 App 名是Autox.js 或 Autox6.js 、 Autox.js V6 、Autox.js[dev]，你说的那个是 Auto.Js+

**Comment by honsinshen** [comment]
> 我们版本从来没有这个问题

布局分析没问题
使用
$crypto.encrypt(
      JSON.stringify(data),
      key,
      "AES/ECB/PKCS5Padding",
      { output: "base64" }
    );
会报错:
ReferenceError: "key" is not defined.

**Comment by honsinshen** [comment]
ReferenceError: "key" is not defined. (file:///android_asset/modules/__$crypto__.js#146)
ReferenceError: "key" is not defined.

**Comment by wilinz** [comment]
有时间看看

**Comment by honsinshen** [comment]
$crypto.digest( cod, "MD5"); 也有问题 , 生成的和md5 和其他的对不上

**Comment by kkevsekk1** [comment]
https://github.com/kkevsekk1/AutoX/blob/dev/autojs/src/main/assets/modules/__$crypto__.js

发送自我的盖乐世



-------- 原始信息 --------
发件人： honsinshen ***@***.***>
日期: 2022/8/3 23:18 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 使用应用自带悬浮窗出现的问题和vscode连接出现的问题 (Issue #386)


$crypto.digest( cod, "MD5"); 也有问题 , 生成的和md5 和其他的对不上

―

**Comment by honsinshen** [comment]
jiami();
function jiami (){
    let key = new $crypto.Key("1234123412341234");
    let data = "1231231231";
    var body = $crypto.encrypt(
        JSON.stringify(data),
        key,
        "AES/ECB/PKCS5Padding",
        { output: "base64" }
      );
    log(body);
}
这样使用的时候就会报错 
23:30:41.468/E: ReferenceError: "key" is not defined. (file:///android_asset/modules/__$crypto__.js#146)
ReferenceError: "key" is not defined.

**Comment by honsinshen** [comment]
var sign = $crypto.digest( "1659539816", "MD5");
log(sign);// 3561641e07db0076b9c5410bca9055ed
//            网站生成的则是 3561641fa7ec0a76c9d5410cdb9a55fe

**Comment by kkevsekk1** [comment]
规则不一样，参考源码



发送自我的盖乐世



-------- 原始信息 --------
发件人： honsinshen ***@***.***>
日期: 2022/8/3 23:35 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 使用应用自带悬浮窗出现的问题和vscode连接出现的问题 (Issue #386)


var sign = $crypto.digest( "1659539816", "MD5");
log(sign);// 3561641e07db0076b9c5410bca9055ed
// 网站生成的则是 3561641fa7ec0a76c9d5410cdb9a55fe

―

**Comment by honsinshen** [comment]
看不懂呀.....大神 有时间了 帮忙搞下这个规则吧.. 早些休息吧

**Comment by kkevsekk1** [comment]
[cid:storage_emulated_0__EmailTempImage_HEV_1659541784952_jpg_1659541784962]😂😂😂😂😂改源码为 this.data


发送自我的盖乐世



-------- 原始信息 --------
发件人： honsinshen ***@***.***>
日期: 2022/8/3 23:33 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 使用应用自带悬浮窗出现的问题和vscode连接出现的问题 (Issue #386)


jiami();
function jiami (){
let key = new $crypto.Key("1234123412341234");
let data = "1231231231";
var body = $crypto.encrypt(
JSON.stringify(data),
key,
"AES/ECB/PKCS5Padding",
{ output: "base64" }
);
log(body);
}
这样使用的时候就会报错
23:30:41.468/E: ReferenceError: "key" is not defined. (file:///android_asset/modules/$crypto.js#146)
ReferenceError: "key" is not defined.

**Comment by kkevsekk1** [comment]
网站的编码规则，或其程序编码规则和这个保持一致，就可以得到一样的结果



发送自我的盖乐世



-------- 原始信息 --------
发件人： honsinshen ***@***.***>
日期: 2022/8/3 23:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 使用应用自带悬浮窗出现的问题和vscode连接出现的问题 (Issue #386)


看不懂呀.....大神 有时间了 帮忙搞下这个规则吧.. 早些休息吧

―

**Comment by honsinshen** [comment]
上边那张图片看不到
没给显示

**Comment by honsinshen** [comment]
https://www.sojson.com/encrypt_md5.html 这个网站生的md5 与php 后台生成的是相同的 3561641fa7ec0a76c9d5410cdb9a55fe
而 $crypto.digest( "1659539816", "MD5");  生成的是 3561641e07db0076b9c5410bca9055ed

**Comment by honsinshen** [comment]
https://www.sojson.com/encrypt_md5.html 这个网站生的md5 与php 后台生成的是相同的 3561641fa7ec0a76c9d5410cdb9a55fe
而 $crypto.digest( "1659539816", "MD5");  生成的是 3561641e07db0076b9c5410bca9055ed

**Comment by kkevsekk1** [comment]
已解决了把
