### ISSUE TITLE
衍生版本请改项目里的仓库地址

### ISSUE THREAD

**Issue by wilinz** [kkevsekk1/AutoX#387]
衍生版本的Issues不要提到这里来，请找对应项目提Issues，也请衍生版本的作者把仓库里的项目路径改成自己仓库的，不要老是让你们的用户把你们版本的问题发到这里

**Comment by wilinz** [comment]
@LZX284

**Comment by wilinz** [comment]
@LZX284 
![Screenshot_20220803-220729_Auto Js+](https://user-images.githubusercontent.com/59408438/182629111-e2601549-3c61-48d0-8139-71a609127e28.png)

**Comment by wilinz** [comment]
用户使用谁的版本就应该向谁反馈问题

**Comment by wilinz** [comment]
而且不止一次 https://github.com/kkevsekk1/AutoX/issues/374#issuecomment-1193075372

**Comment by wilinz** [comment]
那是不是要改成hyp1996 ?

**Comment by wilinz** [comment]
软件源代码地址也没改

**Comment by wilinz** [comment]
![image](https://user-images.githubusercontent.com/59408438/182633797-60d7878a-3aff-4df9-bcbb-08407824a084.png)

**Comment by honsinshen** [comment]
> > [#386 (comment)](https://github.com/kkevsekk1/AutoX/issues/386#issuecomment-1203953278)
> 
> @wilinz 这个Issue里提到的问题有的是衍生版本独有的，有些，如VSCODE连接问题很可能是从上游(AutoX)开始就存在的，所以，用户到这里来寻求帮助也是无可厚非的事情，但如果你非要以此指责别人，那这边也无话可说

对不起哈,这个事情怪我, 小白,不懂版本,我用的这个还以为在autoxjs中寻找就可以了, [wilinz](https://github.com/wilinz) 也别怪人家,,我自己的问题 ,你们都是大神,我的过错, [LZX284](https://github.com/LZX284) 还帮我解决了问题呢

**Comment by tiyo** [comment]
都是大佬。共赢不好？

**Comment by wilinz** [comment]
？？？

**Comment by wilinz** [comment]
他的版本的问题跟他提行不行

**Comment by kkevsekk1** [comment]
你爱咋整，咋整



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/8/4 16:20 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 衍生版本请改项目里的仓库地址 (Issue #387)


@kkevsekk1<https://github.com/kkevsekk1> 之前就上下游合作的问题@过 wilinz ，但直到他成为我们那边项目 wangwang-code/AutoX<https://github.com/wangwang-code/AutoX> 的项目合作者，他也一直没有回复。
所以，有时间的话，这边其实是希望可以和作者大人直接谈谈。虽然过去有过一些误会，但大家都是希望这个社区未来发展能更好，那AutoX社区上下游之间的正常合作交流就不应该受到阻碍。
作者大人在Readme中说过，“由于原作者<https://github.com/hyb1996/Auto.js> 不再维护 Auto.js 项目 我计划在原来基础上继续维护者项目”，原autojs停止维护，所以AutoX可以替换掉原项目中的作者信息，而现在AutoX并没有停止维护，并且作者大人怎么看也不像是一个会删库跑路的人，所以衍生项目中保留原作者信息也就应该是没问题的吧？

―

**Comment by wilinz** [comment]
> 但直到他成为我们那边项目 [wangwang-code/AutoX](https://github.com/wangwang-code/AutoX) 的项目合作者

我手贱点同意了，马上退
