### ISSUE TITLE
需求:能否帮忙引入'个推'sdk进去

### ISSUE THREAD

**Issue by gaokui2010** [kkevsekk1/AutoX#389]
我尝试引入但是bug没办法解决,只能来麻烦下大佬们

**Comment by kkevsekk1** [comment]
这个不会引入



发送自我的盖乐世



-------- 原始信息 --------
发件人： gaokui2010 ***@***.***>
日期: 2022/8/8 06:07 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 需求:能否帮忙引入'个推'sdk进去 (Issue #389)


我尝试引入但是bug没办法解决,只能来麻烦下大佬们

―
