### ISSUE TITLE
请教作者大大，原autojs协议的不准盈利规定与本项目中的捐赠支持是否冲突

### ISSUE THREAD

**Issue by LZX284** [kkevsekk1/AutoX#395]
@kkevsekk1 
如题，最近研究了一下开源协议的相关内容，感觉原作者定的这个协议相当的坑，甚至本项目中的捐赠支持都很可能违反了这一规定
原协议如下：
> 基于[Mozilla Public License Version 2.0](https://github.com/hyb1996/NoRootScriptDroid/blob/master/LICENSE.md)并附加以下条款：
> 非商业性使用 — 不得将此项目及其衍生的项目的源代码和二进制产品用于任何商业和盈利用途

里面明确规定了不得将衍生的项目(AutoX)用于任何商业和盈利用途，本项目没有商用，但盈利这一条，若按目前流行的观点（例如，在企业会计核算中，捐赠属于非营业外收入，也算是盈利的一部分），本项目却是难以推脱，

以下图为例，贡献者明确是收到了本项目用户的捐赠

![184494121-24776e36-4402-495a-b608-d54d2b92e63a](https://user-images.githubusercontent.com/105829296/184527998-00a68934-4778-4dce-8251-f1d344733e80.png)

个人觉得这个问题有点难办，之前和  @wilinz 讨论过：[捐赠问题](https://github.com/wangwang-code/AutoX/issues/44#issuecomment-1214249866)，感觉如果之前是不知情误犯，并且如果在发现违规的情况下没有继续下去，那么即使原作者也不该追究相关责任的。但这究竟是否合乎原作者协议规定和合乎开源协议规范，还是需要请教一下作者大大 @kkevsekk1

**Comment by kkevsekk1** [comment]
哈哈……



发送自我的盖乐世



-------- 原始信息 --------
发件人： LZX284 ***@***.***>
日期: 2022/8/14 16:09 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： [kkevsekk1/AutoX] 请教作者大大，原autojs协议的不准盈利规定与本项目中的捐赠支持是否问题 (Issue #395)


@kkevsekk1<https://github.com/kkevsekk1>
如题，最近研究了一下开源协议的相关内容，感觉原作者定的这个协议相当的坑，甚至本项目中的捐赠支持都很可能违反了这一规定
原协议如下：

基于Mozilla Public License Version 2.0<https://github.com/hyb1996/NoRootScriptDroid/blob/master/LICENSE.md>并附加以下条款：
非商业性使用 ― 不得将此项目及其衍生的项目的源代码和二进制产品用于任何商业和盈利用途

里面明确规定了不得将衍生的项目(AutoX)用于任何商业和盈利用途，本项目没有商用，但盈利这一条，若按目前流行的观点（例如，在企业会计核算中，捐赠属于非营业外收入，也算是盈利的一部分），本项目却是难以推脱，

以下图为例，贡献者明确是收到了本项目用户的捐赠

[184494121-24776e36-4402-495a-b608-d54d2b92e63a]<https://user-images.githubusercontent.com/105829296/184527998-00a68934-4778-4dce-8251-f1d344733e80.png>

个人觉得这个问题有点难办，之前和 @wilinz<https://github.com/wilinz> 讨论过：捐赠问题<https://github.com/wangwang-code/AutoX/issues/44#issuecomment-1214249866>，感觉如果之前如果不知情，并且如果在发现违规的情况下没有继续下去，那么即使原作者也不会追究相关责任的。但这究竟是否合乎原作者协议规定，还是需要请教一下作者大大 @kkevsekk1<https://github.com/kkevsekk1>

―

**Comment by wilinz** [comment]
你可以闭嘴吗？整天没事找事？？？

**Comment by CuteLicense** [comment]
实在看不下去了，有完没完，近期的几个争论都是你挖好的坑，现在又跳出来说三道四。
捐助是单方自愿行为，无附带条件。

**Comment by wilinz** [comment]
@LZX284 [请问你把GPL V2删了是否违反开源协议](https://github.com/LZX284/Auto.Js/commit/34d5c5275a0370976e2f4771a5dc7f8fb5f91938)

**Comment by wilinz** [comment]
@kkevsekk1 某人fork Autox 然后删除GPL V2协议
