### ISSUE TITLE
打包完成之后某些ui样式失效

### ISSUE THREAD

**Issue by cybinlin** [kkevsekk1/AutoX#397]
打包完成之后一些ui样式失效。比如下面这个代码打包前没有问题，打包后样式就显示不正常
vertical padding="5" w="*"
button id="start" style="Widget.AppCompat.Button.Colored" text="开始运行"
vertical

**Comment by cybinlin** [comment]
style="Widget.AppCompat.Button.Colored"这个样式失效了

**Comment by kkevsekk1** [comment]
已修复

**Comment by kkevsekk1** [comment]
现在是不是要用Androidx?



发送自我的盖乐世



-------- 原始信息 --------
发件人： cybinlin ***@***.***>
日期: 2022/8/18 16:24 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包完成之后某些ui样式失效 (Issue #397)


style="Widget.AppCompat.Button.Colored"这个样式失效了

―
