### ISSUE TITLE
最新版本，web扩展与游戏编程的示例报错

### ISSUE THREAD

**Issue by 3026187875** [kkevsekk1/AutoX#398]
id无效，不在[0,16]范围内
![637F0DE7EEB566EDC1FC90DE8D441490](https://user-images.githubusercontent.com/60430874/184753141-0b91a5ff-faf9-4849-93e8-3949ff717db0.jpg)

**Comment by kkevsekk1** [comment]
已由 其他开发者修复

**Comment by 3026187875** [comment]
额，没有修复，我还是运行报同样的错误，红米k40，miui13.0.6

**Comment by 3026187875** [comment]
没有修复我还是报错，同样的错误，红米k40,miui13.0.6
