### ISSUE TITLE
VSCode 使用 "运行项目" 命令, 无反应

### ISSUE THREAD

**Issue by xxxxue** [kkevsekk1/AutoX#399]
![image](https://user-images.githubusercontent.com/32764266/184807355-1c6644ba-58d4-4a16-bf2d-5e5ba258c94a.png)

# 描述

`AutoX.js 6.2.7 `
 VSCode 控制台只有 `发送项目耗时: 0.006 秒`, 再也没啥反应了.
此时 App 也没有任何反应

把 App 换成 `Autojs 4.1.1 Alpha2`  ( VSCode插件还用 AutoX 的 ) 
控制台显示如下,  同时 App 也正常出现了项目的界面
```
发送项目耗时: 0.007 秒
14:09:20.752/V: 开始运行[/data/user/0/org.autojs.autojs/cache/remote_project/460c869606aa48f5114c804c7777e100/main.js]
14:09:25.070/V: 
------------
[/data/user/0/org.autojs.autojs/cache/remote_project/460c869606aa48f5114c804c7777e100/main.js]运行结束，用时4.317000秒
```

# 复现过程
- 通过 AutoX VSCode 新建项目 命令.  生成 `project.json` 和 `main.js`
- 连接后, 直接 `运行项目`

# 环境
64位的雷电模拟器 
版本号: 4.0.64 (64)

自用的 小米MIX2 安卓9 手机 也是一样的效果

**Comment by xxxxue** [comment]
"运行脚本" 命令正常,  不过只能运行一个js
如果有其他文件. 都会找不到.
比如 `示例` 中的  `AutoX注入webview`
同时拥有 main.js 和 game.html . 
VSCode 只能通过 `运行项目` 来执行.  否则会找不到 game.html

**Comment by xxxxue** [comment]
"运行脚本" 命令正常,  不过只能运行一个js
如果有其他文件. 都会找不到.
比如 `示例` 中的  `AutoX注入webview`
同时拥有 main.js 和 game.html . 
VSCode 只能通过 `运行项目` 来执行.  否则会找不到 game.html

**Comment by kkevsekk1** [comment]
可能有这个 bug，建议 使用  https://github.com/kkevsekk1/webpack-autojs 或者  在文件夹上右键，“保存项目到设备”

**Comment by xxxxue** [comment]
> 可能有这个 bug，建议 使用 https://github.com/kkevsekk1/webpack-autojs 或者 在文件夹上右键，“保存项目到设备”

`保存项目到设备` 也是 `发送项目耗时: 0.006 秒` , APP没反应, 文件夹也没出现
 
Auto 4.1 , 是  APP 会 toast 提示 保存成功,  文件夹也成功出现
