### ISSUE TITLE
调用images.captureScreen()报错

### ISSUE THREAD

**Issue by X3ZvaWQ** [kkevsekk1/AutoX#40]
使用的AutoX.js的版本是github releases 2021.3.11 最新的版本4.2.13
实测使用Autojs原仓库的V4.1.1.Alpha2构建 也有该问题

这个bug应该不是由用户代码导致的，因为在尝试运行autojs自带的截图例程也会弹出该报错。
环境是 逍遥模拟器 安卓版本7.1
以下是报错记录
18:52:31.814/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1. (<init>#30)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
    at <init>:30:0
    at [remote]main.js:16:0

18:52:31.816/V:

**Comment by kkevsekk1** [comment]
这个应该是系统兼容性问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： X3ZvaWQ ***@***.***>
日期: 2021/3/11 20:16 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 调用images.captureScreen()报错 (#40)


使用的AutoX.js的版本是github releases 2021.3.11 最新的版本4.2.13
实测使用Autojs原仓库的V4.1.1.Alpha2构建 也有该问题

这个bug应该不是由用户代码导致的，因为在尝试运行autojs自带的截图例程也会弹出该报错。

以下是报错记录，环境是 逍遥模拟器 安卓版本7.1
18:52:31.814/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1. (#30<https://github.com/kkevsekk1/AutoX/issues/30>)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
at :30:0
at [remote]main.js:16:0

18:52:31.816/V:

―

**Comment by X3ZvaWQ** [comment]
更新：但是例程打包的app运行并不会报错并且可以正常截图（

**Comment by 1965514404** [comment]
这个是云手机的bug,有时候模拟器也会报这个错

**Comment by kkevsekk1** [comment]
下了一个最新版的逍遥模拟器，没有这个bug,这个主要系统底层输出的图片格式有关系，代码设定的0x01格式应该是系统底层输出的是匹配的，有可能属于系统的bug，系统没有按设定输出，导致接收失败！如果是这种情况有可能模拟器官方优化系统导致的bug



发送自我的盖乐世



-------- 原始信息 --------
发件人： X3ZvaWQ ***@***.***>
日期: 2021/3/11 20:16 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 调用images.captureScreen()报错 (#40)


使用的AutoX.js的版本是github releases 2021.3.11 最新的版本4.2.13
实测使用Autojs原仓库的V4.1.1.Alpha2构建 也有该问题

这个bug应该不是由用户代码导致的，因为在尝试运行autojs自带的截图例程也会弹出该报错。

以下是报错记录，环境是 逍遥模拟器 安卓版本7.1
18:52:31.814/E: Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1. (#30<https://github.com/kkevsekk1/AutoX/issues/30>)
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
at :30:0
at [remote]main.js:16:0

18:52:31.816/V:

―

**Comment by kkevsekk1** [comment]
那云手机有可能用了模拟器这套代码😂



发送自我的盖乐世



-------- 原始信息 --------
发件人： icesvalley ***@***.***>
日期: 2021/3/11 20:37 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 调用images.captureScreen()报错 (#40)


这个是云手机的bug,有时候模拟器也会报这个错

**Comment by X3ZvaWQ** [comment]
更正：经过测试是模拟器引擎的问题，尝试修改系统设置-引擎-渲染模式
通过DirectX渲染会报这个错误，但是通过OpenGL渲染就没有报错并且可以正常截图。
问题已解决，issue先关了，有遇到相似情况的用户可以参考该解决方案。
