### ISSUE TITLE
有没有考虑用v8引擎

### ISSUE THREAD

**Issue by Layne2016** [kkevsekk1/AutoX#400]

**Comment by kkevsekk1** [comment]
没有



发送自我的盖乐世



-------- 原始信息 --------
发件人： Layne2016 ***@***.***>
日期: 2022/8/16 20:43 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 有没有考虑用v8引擎 (Issue #400)


―

**Comment by AXFOX** [comment]
我想吐槽的是，现在还不支持padStart（）这样的新函数。我都只能用if去补全日期缺的0。

**Comment by gucong3000** [comment]
> 我想吐槽的是，现在还不支持padStart（）这样的新函数。我都只能用if去补全日期缺的0。 rhino已经更新了1.7.14，我不知道现有的版本是不是还在用1.7.13？非常迫切的希望能尽可能跟进新的JS标准和特性。

我看到文档首页写着`目前使用Rhino 1.7.13作为脚本引擎`
另外为看了git提交日志，发现作者尝试过更新到1.7.14，但后来又会退了，作者没在日志里说原因

`padStart`等问题，在作者暂时无力推进Rhino 1.7.14时，我建议通过bable的配置来解决问题。建议采取以下配置

```javascript
// https://github.com/gucong3000/MiuiCleaner/blob/dev/babel.config.js
module.exports = {
	sourceType: "script",
	targets: {
		rhino: "1.7.13",
	},
	presets: [
		"@babel/preset-env",
	],
	plugins: [
		"@babel/plugin-transform-runtime",
		"@babel/plugin-syntax-jsx",
	],
};

```

**Comment by kkevsekk1** [comment]
兼容问题，你可以自己单独升级，自己使用



发送自我的盖乐世



-------- 原始信息 --------
发件人： 刘祺 ***@***.***>
日期: 2022/10/6 07:55 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 有没有考虑用v8引擎 (Issue #400)


我想吐槽的是，现在还不支持padStart（）这样的新函数。我都只能用if去补全日期缺的0。 rhino已经更新了1.7.14，我不知道现有的版本是不是还在用1.7.13？非常迫切的希望能尽可能跟进新的JS标准和特性。

我看到文档首页写着目前使用Rhino 1.7.13作为脚本引擎
另外为看了git提交日志，发现作者尝试过更新到1.7.14，但后来又会退了，作者没在日志里说原因

padStart等问题，在作者暂时无力推进Rhino 1.7.14时，我建议通过bable的配置来解决问题。建议采取以下配置

// https://github.com/gucong3000/MiuiCleaner/blob/dev/babel.config.js
module.exports = {
        sourceType: "script",
        targets: {
                rhino: "1.7.13",
        },
        presets: [
                ***@***.***/preset-env",
        ],
        plugins: [
                ***@***.***/plugin-transform-runtime",
                ***@***.***/plugin-syntax-jsx",
        ],
};

―
