### ISSUE TITLE
保存到设备出现问题v6.2.7

### ISSUE THREAD

**Issue by CuteLicense** [kkevsekk1/AutoX#403]
前面版本正常，v6.2.7，无法保存到设备

**Comment by CuteLicense** [comment]
补充一下，是在vscode中编辑代码后，左侧项目文件夹右键“**保存项目到设备**”，无法保存到手机端，直接在vscode中运行脚本正常。

**Comment by q751654992** [comment]
试试ctrl+shift+s能不能保存

**Comment by CuteLicense** [comment]
> 试试ctrl+shift+s能不能保存
Ctrl+Shift+s可以保存到手机上，但是却保存到“脚本”根目录了，而不是项目文件夹中😂

**Comment by kkevsekk1** [comment]
是插件的问题？还是app存储问题？



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/8/18 23:51 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 保存到设备出现问题v6.2.7 (Issue #403)


等作者发6.2.8 @kkevsekk1<https://github.com/kkevsekk1>

―

**Comment by wilinz** [comment]
@kkevsekk1 app的问题，前天的那个pr修复了

**Comment by wilinz** [comment]
@kkevsekk1 明天再发新版吧，我修一下其他问题

**Comment by kkevsekk1** [comment]
哦，我看一下，我以为只是改示例js脚本呢



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/8/19 00:01 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 保存到设备出现问题v6.2.7 (Issue #403)


@kkevsekk1<https://github.com/kkevsekk1> app的问题，前天的那个pr修复了

―

**Comment by kkevsekk1** [comment]
ok



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/8/19 00:02 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 保存到设备出现问题v6.2.7 (Issue #403)


@kkevsekk1<https://github.com/kkevsekk1> 明天再发新版吧，我修一下其他问题

―
