### ISSUE TITLE
最后一个要求：TBS问题早已澄清多时，但release 6.2.0 中的无端指责内容仍未删除，请立即删除，否则即视同恶意造谣诽谤污蔑他人

### ISSUE THREAD

**Issue by ghost** [kkevsekk1/AutoX#407]
（注：本人多日前已被作者屏蔽，故不得不注册小号进行申诉，以维护自己的正当权益）

[Release 6.2.0中的无端指责](https://github.com/kkevsekk1/AutoX/releases/tag/6.2.0)：
> 最后 [LZX284](https://github.com/LZX284) 由于没有按期对未经授权的第三方代码进行删除或提交相关授权，视为其主动放弃对侵权行为的整改，一切后果将由其[LZX284](https://github.com/LZX284)承担。随后我会对相关代码（包括他侵权和不侵权）进行整改，并贡献到开源社区，社区共同享有其版权，而[LZX284](https://github.com/LZX284)除外！

早已多次澄清的Issue：
[关于AutoX通告中的无端指责：强制规定修改期限并不合理，且TBS项目地址及授权方式都告知作者了，就没必要非逼着别人提交PR了吧？](https://github.com/kkevsekk1/AutoX/issues/364)
[TBS授权的PR已提交却又被关闭了，那些所谓的问题这边也都给出相关说明了，如果作者还是坚持不接受PR，那么侵权责任也只能算在作者身上](https://github.com/kkevsekk1/AutoX/issues/366)
[没能及时回复的原因](https://github.com/kkevsekk1/AutoX/issues/395#issuecomment-1214317335)

[恶意诽谤诬陷他人会承担什么法律后果？](https://www.66law.cn/laws/1438972.aspx)

**Comment by 1027603857** [comment]
哗众取宠罢了
