### ISSUE TITLE
哈哈，真好，把AutoX加入白名单后，再也不用重复开启无障碍了

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#41]
哈哈，真好，把AutoX加入白名单后，再也不用重复开启无障碍了

**Comment by 85524365** [comment]
又遇到了，呵呵，请问啥手机这么牛呀？需要root吗？

**Comment by aniux** [comment]
> ，把AutoX加入白名单后，再也不用重复开启无障碍了

如何加，荣耀手机

**Comment by kkevsekk1** [comment]
关于无障碍掉的问题，可以参考这里 https://www.yuque.com/chengshulun/iybzfr/ou7gov 这都是跟手机系统的优化有关系，搞明白原理，其他类型手机 参考解决！记住 没有银弹

**Comment by lnxcyq** [comment]
我的是vivo，点击电池，在后台耗电里允许autox就可以了
