### ISSUE TITLE
ui的style属性设置失效-v6.28

### ISSUE THREAD

**Issue by CuteLicense** [kkevsekk1/AutoX#412]
在线文档中的例子：
`<button style="Widget.AppCompat.Button.Colored" text="漂亮的按钮"/>`
没有效果，并且控件其他属性也失效

**Comment by wilinz** [comment]
这个6.2.8修复了

**Comment by CuteLicense** [comment]
6.28 出现的，不是打包后，是直接运行脚本时
`"ui";
/********************************************UI部分***********************************************/
ui.layout(
    <vertical>
        <button id="click_me" text="先点我开启无障碍和悬浮窗,如果没有反应，说明已经开启" style="Widget.AppCompat.Button.Colored" w="*" />
        <button id="checkUpdate" h="50" text="检测更新" style="Widget.AppCompat.Button.Colored" />
        <button id="stopMe" h="50" text="停止运行" style="Widget.AppCompat.Button.Colored" />
        <button text="-------以下为单个任务执行-------" style="Widget.AppCompat.Button.Borderless.Colored" w="*" />
        <button id="task1" w="*" text="执行任务一" style="Widget.AppCompat.Button.Colored" />
        <button id="task2" w="*" text="执行任务二" style="Widget.AppCompat.Button.Colored" />
    </vertical>
);
`
![Screenshot_20220821-174416](https://user-images.githubusercontent.com/97828367/185785294-56f73584-f0fe-4934-8647-2919ea7a4e8f.jpg)
![Screenshot_20220821-174439](https://user-images.githubusercontent.com/97828367/185785295-94edb30a-8286-4022-a101-3bda8c961057.jpg)

**Comment by CuteLicense** [comment]
> 6.2.9试一下

@wilinz v6.2.9 测试结果：没有修复，一样的是下方那张图片那样，只有纯文字显示

**Comment by wilinz** [comment]
为啥我测试就正常了

**Comment by wilinz** [comment]
https://user-images.githubusercontent.com/59408438/186389892-e985a6f5-3a1d-4029-a393-4b78dcb9692a.mp4

**Comment by kkevsekk1** [comment]
他说的是打包后的apk，inrt 应该是没有 基础包 @wilinz

**Comment by wilinz** [comment]
@kkevsekk1 inrt也是没问题的
![Screenshot_20220824-190437_UI TEST](https://user-images.githubusercontent.com/59408438/186403410-920f3ec1-e292-4816-965a-e44c404a7445.png)

**Comment by kkevsekk1** [comment]
哦



发送自我的盖乐世



-------- 原始信息 --------
发件人： wilinz ***@***.***>
日期: 2022/8/24 19:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] ui的style属性设置失效-v6.28 (Issue #412)


@kkevsekk1<https://github.com/kkevsekk1> inrt也是没问题的
[Screenshot_20220824-190437_UI TEST]<https://user-images.githubusercontent.com/59408438/186403410-920f3ec1-e292-4816-965a-e44c404a7445.png>

―

**Comment by CuteLicense** [comment]
抱歉抱歉，6.2.9 确认已经修复。
6.2.9是我自己改了一下包名后出现的，因为手机总是提醒风险，所以改了一下。看了上面几位的截图和视频，重新直接下载安装测试了一下，正常展示

**Comment by yqchilde** [comment]
该问题在目前最新版6.3.8中又出现了，官方的按钮控件打包后都没样式了，又下载6.3.7试了一下，打包是没问题的
