### ISSUE TITLE
tasker调用任务得切到AlarmManager

### ISSUE THREAD

**Issue by q751654992** [kkevsekk1/AutoX#416]
autojs使用 6.2.9版本
安卓版本 10
感觉这是一个不算bug的bug，tasker调用autojs的时候autojs会崩溃重启，切换成AlarmManager的任务调度器就好了
下面是报错信息

Version: 629
Android: 29
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
java.lang.RuntimeException:Unable to create application org.autojs.autojs.App: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7409)
......
Caused by:
java.lang.IllegalStateException:WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
androidx.work.WorkManager.getInstance(WorkManager.java:184)
org.autojs.autojs.timing.work.WorkManagerProvider.enqueuePeriodicWork(WorkManagerProvider.kt:44)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.createCheckWorker(TimedTaskScheduler.kt:97)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.init(TimedTaskScheduler.kt:91)
org.autojs.autojs.App.init(App.kt:89)
org.autojs.autojs.App.onCreate(App.kt:51)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1202)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7393)
android.app.ActivityThread.access$2400(ActivityThread.java:251)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2284)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loop(Looper.java:219)
android.app.ActivityThread.main(ActivityThread.java:8393)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by PutinYpa** [comment]
同样问题，使用tasker的脚本运行替代解决
am start -n org.autojs.autoxjs.v6/org.autojs.autojs.external.open.RunIntentActivity file:///sdcard/脚本/xxx.js
