### ISSUE TITLE
libtermexec

### ISSUE THREAD

**Issue by RFSN** [kkevsekk1/AutoX#418]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：雷电模拟器9
5. Android 系统类别：类原生
7. 问题描述： libtermexec 模块缺少X86_64的so库文件，导致编译的autoX_X64版本在雷电模拟器上使用异常，找不到对应的 libjackpal-androidterm5.so、libjackpal-termexec2.so 文件

**Comment by RFSN** [comment]
大佬，能不能先 看下这个问题啊，少了对于64位模拟器的支持。

**Comment by kkevsekk1** [comment]
没有x86的底层，支持不了



发送自我的盖乐世



-------- 原始信息 --------
发件人： RFSN ***@***.***>
日期: 2022/8/27 01:19 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] libtermexec (Issue #418)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 9
  4.  Android 机型：雷电模拟器9
  5.  Android 系统类别：类原生
  6.  问题描述： libtermexec 模块缺少X86_64的so库文件，导致编译的autoX_X64版本在雷电模拟器上使用异常，找不到对应的 libjackpal-androidterm5.so、libjackpal-termexec2.so 文件

―

**Comment by RFSN** [comment]
能提供一下这个 libtermexec-release.aar 的开源项目地址吗？我看 [libtermexec-release.aar](https://github.com/kkevsekk1/AutoX/blob/dev-test/LocalRepo/libtermexec/libtermexec-release.aar) 的最后更新日期是3个月之前，不知道是否可以编译到x86_64 的的 so 。

**Comment by kkevsekk1** [comment]
这个时候模拟器的吧？



发送自我的盖乐世



-------- 原始信息 --------
发件人： RFSN ***@***.***>
日期: 2022/8/27 23:46 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] libtermexec (Issue #418)


能提供一下这个 libtermexec-release.aar 的开源项目地址吗？我看 libtermexec-release.aar<https://github.com/kkevsekk1/AutoX/blob/dev-test/LocalRepo/libtermexec/libtermexec-release.aar> 的最后更新日期是3个月之前，不知道是否可以编译到x86_64 的的 so 。

―

**Comment by kkevsekk1** [comment]
模拟器，搞一下GPU的选项设置，



发送自我的盖乐世



-------- 原始信息 --------
发件人： RFSN ***@***.***>
日期: 2022/8/27 23:46 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] libtermexec (Issue #418)


能提供一下这个 libtermexec-release.aar 的开源项目地址吗？我看 libtermexec-release.aar<https://github.com/kkevsekk1/AutoX/blob/dev-test/LocalRepo/libtermexec/libtermexec-release.aar> 的最后更新日期是3个月之前，不知道是否可以编译到x86_64 的的 so 。

―

**Comment by RFSN** [comment]
是雷电模拟器。GPU选项搞哪里？使用打包的x86 版本是可以的，只是限制模拟器都是64位了，我想着是不是64位的性能能高点，如果这个没有办法弄，使用x86版本的包是可以可以在模拟器上运行的。问题不大。

**Comment by flying911** [comment]
> 是雷电模拟器。GPU选项搞哪里？使用打包的x86 版本是可以的，只是限制模拟器都是64位了，我想着是不是64位的性能能高点，如果这个没有办法弄，使用x86版本的包是可以可以在模拟器上运行的。问题不大。

兄弟是如何解决的，我也遇到了同样的问题，才开始接触这autoX，不怎么了解。
看兄弟的描述，我理解是去找一个AutoX的x86版本重新打包，但找不到，在打包选项里也把x86_64去掉了，但还是没能正常运行...

**Comment by RFSN** [comment]
你下载x86版本的啊，x86 是可以运行在x64上的啊
