### ISSUE TITLE
AutoX 在模拟器上运行异常，通过定时任务运行脚本时，获取设备信息异常

### ISSUE THREAD

**Issue by RFSN** [kkevsekk1/AutoX#419]
1. Autox.js 版本：632
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：雷电模拟器9
5. Android 系统类别：类原生
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：通过autoX 提供的定时任务运行脚本，但在脚本中获取数据异常，主要是device 相关api 异常，且在异常之后，手动再次运行任何脚本也会异常，只有删除任务，再次重启模拟器才能正常获取。部分截图参考如下，谢谢。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

定时任务创建详情
![定时任务创建列表 ](https://user-images.githubusercontent.com/10191324/186987873-ba31d966-73a4-4a72-8f21-6068aaec95d8.png)
通过定时任务自动运行截图
![AutoJS自动运行结果](https://user-images.githubusercontent.com/10191324/186987864-4f6a6c7c-3beb-431c-b30a-ce43b7fc760f.png)
停止定时任务之后，再次手动运行截图
![再次手动运行异常](https://user-images.githubusercontent.com/10191324/186987877-c1871308-b3d0-42fc-9b71-3ad82d2816bc.png)
删除任务，再重启设备之后手动运行正
![非AutoJS启动运行](https://user-images.githubusercontent.com/10191324/186987874-a68e5ebc-5840-4a66-8ab4-cb3e5e459772.png)

**Comment by kkevsekk1** [comment]
可能跟定时任务直接让脚本在后台运行有关，先解锁，把app加载到前台，在运行任务



发送自我的盖乐世



-------- 原始信息 --------
发件人： RFSN ***@***.***>
日期: 2022/8/27 04:39 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] AutoX 在模拟器上运行异常，通过定时任务运行脚本时，获取设备信息异常 (Issue #419)


  1.  Autox.js 版本：632
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 9
  4.  Android 机型：雷电模拟器9
  5.  Android 系统类别：类原生
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：通过autoX 提供的定时任务运行脚本，但在脚本中获取数据异常，主要是device 相关api 异常，且在异常之后，手动再次运行任何脚本也会异常，只有删除任务，再次重启模拟器才能正常获取。部分截图参考如下，谢谢。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
[定时任务创建列表]<https://user-images.githubusercontent.com/10191324/186987156-6c2ae275-b3da-4ab8-800a-c1e9e6b5d9f6.png>
[AutoJS自动运行结果]<https://user-images.githubusercontent.com/10191324/186987150-3d61138e-4fe1-4679-ac03-b7f522b381db.png>
[再次手动运行异常]<https://user-images.githubusercontent.com/10191324/186987162-bb910475-43fb-4b81-9732-f7cccc3cd167.png>
删除任务，再重启设备之后手动运行正
[非AutoJS启动运行]<https://user-images.githubusercontent.com/10191324/186987160-f4b115df-cbd0-4101-aa59-9969498dd321.png>

―

**Comment by RFSN** [comment]
好的，这个可以解决，感谢 。只要开启机不自动启动autox，通过手动启动，则没有问题。

**Comment by small-tk** [comment]
同问题，开机运行一段时间后，定时任务启动的脚本就获取不到 width,height 了，需要重启手机才可以

**Comment by kkevsekk1** [comment]
你可以把他存起来，后面就直接用



发送自我的盖乐世



-------- 原始信息 --------
发件人： SmallTank ***@***.***>
日期: 2022/10/7 13:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] AutoX 在模拟器上运行异常，通过定时任务运行脚本时，获取设备信息异常 (Issue #419)


同问题，开机运行一段时间后，定时任务启动的脚本就获取不到 width,height 了，需要重启手机才可以

―

**Comment by wanZzz6** [comment]
虽然不清楚bug原因，但我参考了Device类的源码可以正常获取到
https://github.com/kkevsekk1/AutoX/blob/e66a8f9b3fac483fb7045196e449ba53810f8fb6/autojs/src/main/java/com/stardust/autojs/runtime/api/Device.java#L48C1-L48C1
![image](https://github.com/kkevsekk1/AutoX/assets/28629837/fb0feaeb-5e98-44da-837c-1ceaaea45dc3)
