### ISSUE TITLE
indexInParen()出错 及 vscode的F5键失效

### ISSUE THREAD

**Issue by a4youma** [kkevsekk1/AutoX#421]
1. Autox.js 版本：600--633
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：1.08--1.09
7. 问题描述： log(text("首页").findOne().indexInParen()) 正常显示，“首页”上还有父控件，log(text("首页").findOne().parent().indexInParen())，显示-1。
另外，vscode中按F5及右键命令面板中选run，依然不能正常运行脚本，只有点击右上角的运行图标可以正常运行。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
脚本问题，你可以打印全部做对比，根据实际情况优化，没有更好的办法，
f5运行这种我们再看看，
我建议把webpack项目结合起来


发送自我的盖乐世



-------- 原始信息 --------
发件人： a4youma ***@***.***>
日期: 2022/8/27 23:01 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] indexInParen()出错 及 vscode的F5键失效 (Issue #421)


  1.  Autox.js 版本：600--633
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：1.08--1.09
  7.  问题描述： log(text("首页").findOne().indexInParen()) 正常显示，“首页”上还有父控件，log(text("首页").findOne().parent().indexInParen())，显示-1。
另外，vscode中按F5及右键命令面板中选run，依然不能正常运行脚本，只有点击右上角的运行图标可以正常运行。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―
