### ISSUE TITLE
Tasker调用出错

### ISSUE THREAD

**Issue by bingxizhe** [kkevsekk1/AutoX#426]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：红米10x 4g
5. Android 系统类别：pixel
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：Version: 629
Android: 29
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
java.lang.RuntimeException:Unable to create application org.autojs.autojs.App: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
......
Caused by:
java.lang.IllegalStateException:WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
androidx.work.WorkManager.getInstance(WorkManager.java:184)
org.autojs.autojs.timing.work.WorkManagerProvider.enqueuePeriodicWork(WorkManagerProvider.kt:44)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.createCheckWorker(TimedTaskScheduler.kt:97)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.init(TimedTaskScheduler.kt:91)
org.autojs.autojs.App.init(App.kt:89)
org.autojs.autojs.App.onCreate(App.kt:51)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
android.app.ActivityThread.access$1300(ActivityThread.java:219)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:214)
android.app.ActivityThread.main(ActivityThread.java:7356)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
9. 屏幕截图（可选）：
![Screenshot_20220906-115413039](https://user-images.githubusercontent.com/88787304/188543738-fd5bd11f-8cf6-4f88-af44-94feb4e1c882.jpg)
![Screenshot_20220906-115413039](https://user-images.githubusercontent.com/88787304/188543739-6101ea39-e967-45a6-bab2-527d97615917.jpg)

**Comment by q751654992** [comment]
在切换定时任务调度器里面把调度器换了

**Comment by lolipoi** [comment]
小米6也有同样的问题，参考2楼的兄台用root执行shall命令勉强解决

**Comment by zhseren** [comment]
魅族16X，安卓8，Autox6.3.5，MacroDroid5.28.8。在Mac里调用Autox也是会崩溃/无反应，还有直接卡死需要长安电源键重启的(二楼的脚本命令也试了，可以没生效)

**Comment by kkevsekk1** [comment]
只能自己排查了，估计是ui线程问题，我基本离开这个行业了，很难去更新这了



发送自我的盖乐世


-------- 原始信息 --------
发件人： 贵凰 ***@***.***>
日期: 2023/2/19 00:41 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] Tasker调用出错 (Issue #426)


魅族16X，安卓8，Autox6.3.5，MacroDroid5.28.8。在Mac里调用Autox也是会崩溃/无反应，还有直接卡死需要长安电源键重启的(二楼的脚本命令也试了，可以没生效)
