### ISSUE TITLE
PC端日志输出先后顺序有问题

### ISSUE THREAD

**Issue by CuteLicense** [kkevsekk1/AutoX#428]
**Autox.js 版本**：634
**vscode扩展**  v1.109.0
PC端日志输出先后顺序有问题，我还以为是代码的问题，查看手机端正常，PC端有时候会出现先后顺序错乱情况

**Comment by CuteLicense** [comment]
提多几个问题：手机端的编辑器，跳转菜单项下的，除了跳转到行正常外，其余跳转（文件开始 文件末尾 行首 行尾）均失效

**Comment by kkevsekk1** [comment]
哦，可以看看修复一下，但是更建议在电脑上写脚本



发送自我的盖乐世



-------- 原始信息 --------
发件人： CuteLicense ***@***.***>
日期: 2022/9/12 14:51 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] PC端日志输出先后顺序有问题 (Issue #428)


提多几个问题：手机端的编辑器，跳转菜单项下的，除了跳转到行正常外，其余跳转（文件开始 文件末尾 行首 行尾）均失效

―

**Comment by songjiang951130** [comment]
我也出现了，调试脚本流程的时候后面的日志先打印了 我开始怀疑人生，后来看时间戳才发现

**Comment by wilinz** [comment]
日志顺序已修复
