### ISSUE TITLE
压缩时，只能压缩成7z，压缩zip报致命错误。

### ISSUE THREAD

**Issue by xiaobai-sci** [kkevsekk1/AutoX#429]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：红米K30s
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：压缩时，只能压缩成7z，压缩zip报致命错误。
8. 报错日志（可选）：
9. 屏幕截图（可选）：
//压缩文件路径(必须是完整路径)
var filePath = "/sdcard/脚本.zip";
//目录路径(必须是完整路径)
var dirPath = "/sdcard/脚本";
//压缩类型
//支持的压缩类型包括:
//  zip 7z bz2 bzip2 tbz2 tbz gz gzip tgz tar wim swm xz txz。
var type = "zip";
//压缩密码
var password = "password"

//7z加密压缩(若文件已存在则跳过)
//zips.A(type, filePath, dirPath, password)

//压缩
switch (zips.A(type, filePath, dirPath)) {
    case 0:
        toastLog("压缩成功！文件已保存为： " + filePath)
        break;
    case 1:
        toastLog("压缩结束，存在非致命错误（例如某些文件正在被使用，没有被压缩）")
        break;
    case 2:
        toastLog("致命错误")
        break;
    case 7:
        toastLog("命令行错误")
        break;
    case 8:
        toastLog("没有足够内存")
        break;
    case 255:
        toastLog("用户中止操作")
        break;
    default: toastLog("未知错误")
}

**Comment by kkevsekk1** [comment]
嗯嗯，可以排查一下



发送自我的盖乐世



-------- 原始信息 --------
发件人： xiaobai-sci ***@***.***>
日期: 2022/9/12 16:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 压缩时，只能压缩成7z，压缩zip报致命错误。 (Issue #429)


  1.  Autox.js 版本：634
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：红米K30s
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：压缩时，只能压缩成7z，压缩zip报致命错误。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
//压缩文件路径(必须是完整路径)
var filePath = "/sdcard/脚本.zip";
//目录路径(必须是完整路径)
var dirPath = "/sdcard/脚本";
//压缩类型
//支持的压缩类型包括:
// zip 7z bz2 bzip2 tbz2 tbz gz gzip tgz tar wim swm xz txz。
var type = "zip";
//压缩密码
var password = "password"

//7z加密压缩(若文件已存在则跳过)
//zips.A(type, filePath, dirPath, password)

//压缩
switch (zips.A(type, filePath, dirPath)) {
case 0:
toastLog("压缩成功！文件已保存为： " + filePath)
break;
case 1:
toastLog("压缩结束，存在非致命错误（例如某些文件正在被使用，没有被压缩）")
break;
case 2:
toastLog("致命错误")
break;
case 7:
toastLog("命令行错误")
break;
case 8:
toastLog("没有足够内存")
break;
case 255:
toastLog("用户中止操作")
break;
default: toastLog("未知错误")
}

―

**Comment by LZX2840** [comment]
> 嗯嗯，可以排查一下 发送自我的盖乐世

@xiaobai-sci  @现在p7zip的问题解决了吗？其实我只是想来修复一些bug就走的，但奈何作者总是不肯和解，
（作者之前直接封禁了我，现在也只能开着个小号回一下消息，呜呜呜……）
