### ISSUE TITLE
webpack项目开发环境如何不对脚本进行加密

### ISSUE THREAD

**Issue by XAGU** [kkevsekk1/AutoX#43]
webpack项目开发环境如何不对脚本进行加密

**Comment by kkevsekk1** [comment]
研究webpack，可以做到



发送自我的盖乐世



-------- 原始信息 --------
发件人： XAGU ***@***.***>
日期: 2021/3/25 23:12 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] webpack项目开发环境如何不对脚本进行加密 (#43)


webpack项目开发环境如何不对脚本进行加密

―

**Comment by XAGU** [comment]
我之前尝试注释掉plugins中的new JavascriptObfuscator，但是会导致build出来的脚本为空白内容

**Comment by gucong3000** [comment]
> 我之前尝试注释掉plugins中的new JavascriptObfuscator，但是会导致build出来的脚本为空白内容

我也遇到相同问题了，最终通过重写webpack配置解决
https://github.com/gucong3000/MiuiCleaner/blob/dev/webpack.config.js

**Comment by d1bug** [comment]
问题不是说从6.1.1版本开始，就不支持dex了么。混淆加密好像用处不是很大啊。
