### ISSUE TITLE
中文文案标点错误，双引号写反了

### ISSUE THREAD

**Issue by gucong3000** [kkevsekk1/AutoX#431]
![image](https://user-images.githubusercontent.com/1171691/190591890-dabd9923-d981-488d-997d-9d826813bef1.png)
发现了一些文案的标点问题，也定位了bug所在代码，我想发起PR来修复，但本仓库的混乱的分支起名实在是对贡献者不太友好，master分支几年没更新过了，当前默认分支名字又不像个稳定分支的名字，实在不知道我该从何分支起fork。

**Comment by kkevsekk1** [comment]
默认分支



发送自我的盖乐世



-------- 原始信息 --------
发件人： 刘祺 ***@***.***>
日期: 2022/9/16 16:26 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 中文文案标点错误，双引号写反了 (Issue #431)


[image]<https://user-images.githubusercontent.com/1171691/190591890-dabd9923-d981-488d-997d-9d826813bef1.png>
发现了一些文案的标点问题，也定位了bug所在代码，我想发起PR来修复，但本仓库的混乱的分支起名实在是对贡献者不太友好，master分支几年没更新过了，当前默认分支名字又不像个稳定分支的名字，实在不知道我该从何分支起fork。

―
