### ISSUE TITLE
请求添加”隐藏应用程序后台卡片“功能

### ISSUE THREAD

**Issue by Pil0tXia** [kkevsekk1/AutoX#433]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K40
5. Android 系统类别：MIUI 13
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：锁上后台、省电无限制、打开自启动，再开启隐藏后台，回到桌面，多任务里清清爽爽，也不会手滑误关闭。像auto tools这种跳弹窗的app都有这个功能，希望可以添加隐藏后台功能。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
可以，我还不知道 有这个呢 ，哈哈
________________________________
发件人: Pil0tXia ***@***.***>
发送时间: 2022年9月16日 12:27
收件人: kkevsekk1/AutoX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kkevsekk1/AutoX] 请求添加”隐藏应用程序后台卡片“功能 (Issue #433)


  1.  Autox.js 版本：634
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：红米K40
  5.  Android 系统类别：MIUI 13
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
  7.  问题描述：锁上后台、省电无限制、打开自启动，再开启隐藏后台，回到桌面，多任务里清清爽爽，也不会手滑误关闭。像auto tools这种跳弹窗的app都有这个功能，希望可以添加隐藏后台功能。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by Pil0tXia** [comment]
谢谢！期待新版本
