### ISSUE TITLE
手机连接电脑

### ISSUE THREAD

**Issue by starboatman** [kkevsekk1/AutoX#434]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：vivo z3i
6. Android 系统类别：V1813A
7. VSCODE Autox.js 扩展版本：v0.2.3
8. 问题描述：手机连接电脑的时候，显示握手失败，连接不到手机，ip地址正确

**Comment by wilinz** [comment]
更新版本

**Comment by starboatman** [comment]
您好 方便更详细说一下吗 更新autox版本还是更新其他的

**Comment by wilinz** [comment]
都更

**Comment by wilinz** [comment]
客户端和vscode插件都要更新

**Comment by starboatman** [comment]
您好，我更新之后还是显示握手失败，但是auto.js还是可以正常使用，只有autox.js显示握手失败
