### ISSUE TITLE
针对TBS问题的再度澄清：真不想把事情闹大，但你们总不能这样无底线抹黑别人吧……

### ISSUE THREAD

**Issue by LZX2840** [kkevsekk1/AutoX#435]
（注：本人多日前已被作者屏蔽，故不得不注册小号进行申诉，以维护自己的正当权益。鉴于作者可能再次使用屏蔽手段屏蔽封杀本人申诉解释的权利，本人只能预先做此说明，若其他人对此有所疑问，而本人又无法在此帖回复的情况下，请到 [本人项目](https://github.com/LZX284/Auto.Js/issues) 中发帖咨询！）

[第一次申诉贴](https://github.com/kkevsekk1/AutoX/issues/407)

[Release 6.2.0中的无端指责](https://github.com/kkevsekk1/AutoX/releases/tag/6.2.0)：

> 最后 [LZX284](https://github.com/LZX284) 由于没有按期对未经授权的第三方代码进行删除或提交相关授权，视为其主动放弃对侵权行为的整改，一切后果将由其[LZX284](https://github.com/LZX284)承担。随后我会对相关代码（包括他侵权和不侵权）进行整改，并贡献到开源社区，社区共同享有其版权，而[LZX284](https://github.com/LZX284)除外！

所谓的”未经授权的第三方代码“问题，指的是本人在Autoxjs 项目中引入的 腾讯浏览服务(TBS)：https://x5.tencent.com/tbs/product/tbs.html
本人当时在引入TBS服务时，是严格按照 腾讯TBS接入文档的指示：https://x5.tencent.com/docs/access.html
可能是TBS官方的疏忽吧，该文档中并没有提及需要版权声明的注意事项，以至于本人当时也没有注意忽略了这一方面，提交给Autoxjs 项目的代码就没有版权声明的相关内容。这确实是本人的疏忽，因此作者提出后（除去住院的几天时间），本人也一直在努力寻找TBS相关的授权信息，最终在Github的一个偏僻的[项目地址](https://github.com/TencentBrowsingService/TBS_SDK)中发现了[授权信息](https://github.com/TencentBrowsingService/TBS_SDK/blob/main/LICENSE.txt)，并马上将这一[信息](https://github.com/TencentBrowsingService/TBS_SDK/blob/main/LICENSE.txt)告知作者

此通告发布时间是在 2022年7月18日 12:01，而本人早已在 2022年7月12日 就给作者提交了相关修复内容：https://github.com/kkevsekk1/AutoX/issues/350#issuecomment-1181535437

但是作者还是无视了本人提交的修复内容，仍然执意在一周后的更新通告中对本人进行了不实指责和没收版权威胁：
[Release通告中的不实指责和威胁内容至今仍在](https://github.com/kkevsekk1/AutoX/releases/tag/6.2.0)

澄清相关问题的Issue：
[关于AutoX通告中的无端指责：强制规定修改期限并不合理，且TBS项目地址及授权方式都告知作者了，就没必要非逼着别人提交PR了吧？](https://github.com/kkevsekk1/AutoX/issues/364
)
[TBS授权的PR已提交却又被关闭了，那些所谓的问题这边也都给出相关说明了，如果作者还是坚持不接受PR，那么侵权责任也只能算在作者身上](https://github.com/kkevsekk1/AutoX/issues/366
)
[没能及时回复的原因](https://github.com/kkevsekk1/AutoX/issues/395#issuecomment-1214317335)

[修复TBS授权问题的PR，已合并](https://github.com/kkevsekk1/AutoX/pull/367)
时至如今，谁对谁错暂且不论，在TBS授权问题早已解决的情况下，此通告中的指责及威胁内容也没有任何再保留的必要了吧？

**Comment by LZX2840** [comment]
注：鉴于作者可能再次使用屏蔽手段屏蔽封杀本人申诉解释的权利，本人只能预先做此说明，若其他人对此有所疑问，而本人又无法在此帖回复的情况下，请到 [本人项目](https://github.com/LZX284/Auto.Js/issues) 中发帖咨询！

**Comment by wanyanjiabin** [comment]
这问题其实真的没必要讨论,之前作者都说的很清楚了.
1.不是开发浏览器,用不上那么高端的TBS.
2.TBS开源协议并不是很明确,再加上南山必胜客的名号,你确定以后不会有风险?
3.TBS内含有腾讯代理,URL过滤(拦截),JS劫持等技术,基本你的操作腾讯都统计备份记录保存,你确定安全?
4.TBS内置广告服务,可以产生经济利益,你确定不会成为被告?(要知道有的开源浏览器,论坛回个帖都被告20W.)

为了一个不重要的浏览业务引入一大堆法律分险和隐私分险你确定有必要?

其实如果TBS是一个国外开发者开发发布的程序,我估计作者也不会那么抵触.腾讯...你心是真大.

**Comment by LZX2840** [comment]
> 这问题其实真的没必要讨论,之前作者都说的很清楚了. 1.不是开发浏览器,用不上那么高端的TBS. 2.TBS开源协议并不是很明确,再加上南山必胜客的名号,你确定以后不会有风险? 3.TBS内含有腾讯代理,URL过滤(拦截),JS劫持等技术,基本你的操作腾讯都统计备份记录保存,你确定安全? 4.TBS内置广告服务,可以产生经济利益,你确定不会成为被告?(要知道有的开源浏览器,论坛回个帖都被告20W.)
> 
> 为了一个不重要的浏览业务引入一大堆法律风险和隐私风险你确定有必要?
> 
> 其实如果TBS是一个国外开发者开发发布的程序,我估计作者也不会那么抵触.腾讯...你心是真大.

@wanyanjiabin  
另外，不好意思。真的是不知道该怎么跟你说才好OO……
> 2.TBS开源协议并不是很明确,再加上南山必胜客的名号,你确定以后不会有风险?

明明都科普那么多遍了，为什么还会有人认为TBS的协议是开源协议？！
而且，TBS的协议是腾讯公司自己给出的，白纸黑字清清楚楚，真有问题请具体指出。至于要不要删除也是你们自己决定的。但release 6.2.0通告中那些针对本人的内容还请删除。
另外……算了，作者自己不出来就每天找一个人来乱说几句这本人也受不了，而且，作者还会使手段封禁别人，这样对话下去真的不公平，就这样吧，如果能够不再见到你们，祝你们早安、午安、晚安……

**Comment by wanyanjiabin** [comment]
没人想对你怎样,我也不是作者找来对你怎样.我甚至没和作者说过一句话.我只是个使用者.甚至之前版本还受到过你的代码照顾.

只是想跟你说,别钻牛角尖.

_商用产品可以接入TBS，目前TBS对普通第三方开发者是完全免费的，可以自助接入_
_为实现各类腾讯浏览服务SDK的特定业务功能，我们可能需要向开发者和/或终端用户收集相关个人信息。以下将详细列出腾讯浏览服务SDK的各项业务功能及为实现该功能所收集的个人信息情况：_
_为了便于用户搜索、分享已复制的内容，我们需要访问剪切板，读取其中包含的链接、内容，从而保证搜索、分享等功能的实现。_

这是TBS常见问题里的描述.
最终解释权在腾讯,只是目前免费.如果大量的业务发展用在TBS基础上,以后难以剥离,就会被釜底抽薪,这你能理解吧.

另外,你也说了,TBS不是开源协议,那么会和Autojsx遵循的MPL-2开源协议的1.11条专利申明冲突,所以作者说需要一份腾讯的授权

再另外,你找到那个是个免责协议,并非对本项目的授权信息.

就算退一万步来说,作者不用你自己分支自己用就是.何必这里强求.

最后,祝你幸福.

**Comment by LZX2840** [comment]
@wanyanjiabin  

> 没人想对你怎样,我也不是作者找来对你怎样.我甚至没和作者说过一句话.我只是个使用者.甚至之前版本还受到过你的代码照顾.
> 
> 只是想跟你说,别钻牛角尖.
> 
> ~_商用产品可以接入TBS，目前TBS对普通第三方开发者是完全免费的，可以自助接入_~ ~_为实现各类腾讯浏览服务SDK的特定业务功能，我们可能需要向开发者和/或终端用户收集相关个人信息。以下将详细列出腾讯浏览服务SDK的各项业务功能及为实现该功能所收集的个人信息情况：_~ ~_为了便于用户搜索、分享已复制的内容，我们需要访问剪切板，读取其中包含的链接、内容，从而保证搜索、分享等功能的实现。_~
> 
> ~这是TBS常见问题里的描述.~ ~最终解释权在腾讯,只是目前免费.如果大量的业务发展用在TBS基础上,以后难以剥离,就会被釜底抽薪,这你能理解吧.~
> 
> ~另外,你也说了,TBS不是开源协议,那么会和Autojsx遵循的MPL-2开源协议的1.11条专利申明冲突,所以作者说需要一份腾讯的授权~
> 
> ~再另外,你找到那个是个免责协议,并非对本项目的授权信息.~
> 
> ~就算退一万步来说,作者不用你自己分支自己用就是.何必这里强求.~
> 
> ~最后,祝你幸福.~
> 
> ~至于作者挂你的事情,请直接联系作者比较好.~ ~解铃还须系铃人,看6.20之前版本作者对你评价都是正面的,突然反转一定有原因的~
> 
> 吃完整个西瓜才看完你们的前尘过往,不想评价.似乎都是对的,也似乎没那么不可调解.大概是团队融合问题,正视即可.

@wanyanjiabin 事情都过去那么久了，即便作者现在还把那些东西挂着，我这边也不想再追究什么了。之所以发帖也只是想来找作者和解，之前也去了QQ群，但奈何作者就i是不给一个好好说话的机会。
包括之前分支也一直是，一直想放下争端和解，实现合作，但奈何作者那边总是不允许。
我一直是只想找作者的，不过你能主动出现并且列出那么多反驳我的观点，研究的那么仔细，想来也绝不可能只是一个普通的路人，那能不能麻烦你和作者 @kkevsekk1 说一声，大家和解不好吗？

**Comment by LZX2840** [comment]
@kkevsekk1 能看到吗？继续让这个争论挂在Autoxjs的页面上对这个项目以及对这个项目的用户也没有什么好处吧？非常抱歉，之前那些我也有不对的地方，事情都过去那么久了，大家放下争端实现和解不好吗？
