### ISSUE TITLE
为什么要升级为rhino-1.7.14

### ISSUE THREAD

**Issue by d1bug** [kkevsekk1/AutoX#436]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：自从升级成 rhino-1.7.14后，就无法使用dex进行js加密了。
8. 报错日志（可选）：
No static method cmp_LT(Ljava/lang/Object;Ljava/lang/Object;)Z in class Lorg/mozilla/javascript/ScriptRuntime; or its super classes (declaration of 'org.mozilla.javascript.ScriptRuntime' appears in /data/app/org.autojs.autojs-jAzc9j3uD4GN5lSGjrGLYA==/base.apk!classes2.dex)

只有在使用5.7.8才能正常。不能用dex，者大家都是裸奔开发，对不起辛苦的开发人员啊
10. 屏幕截图（可选）：

**Comment by LZX2840** [comment]
@d1bug  
[Rhino 1.7.13 违反开源协议问题](https://github.com/kkevsekk1/AutoX/issues/350#issuecomment-1181784272)
[[Rhino 1.7.13 违反开源协议问题需要作者给一个解释或解决方案，但作者明明知道却一直没打算解决](https://github.com/kkevsekk1/AutoX/issues/364#issuecomment-1186649200)
