### ISSUE TITLE
打包后闪退

### ISSUE THREAD

**Issue by haleyrom** [kkevsekk1/AutoX#437]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：三星a5
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by wilinz** [comment]
三星？miui?

**Comment by haleyrom** [comment]
三星跟红米都会闪退

三星/红米都是用lineageos系统

**Comment by kkevsekk1** [comment]
这个要有日志才好排查问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： haleyrom ***@***.***>
日期: 2022/9/21 11:22 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包后闪退 (Issue #437)


三星跟红米都会闪退

三星/红米都是用lineageos系统

―
