### ISSUE TITLE
【需要更新文档】engines.execScriptFile执行子脚本结束的API

### ISSUE THREAD

**Issue by tignioj** [kkevsekk1/AutoX#441]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米MAX
5. Android 系统类别：MIUI
7. 问题描述：使用`let e = engines.execScriptFile("xx.js");` 执行脚本时，如果我们要检测该脚本是否执行结束，可以使用`e.getEngine().isDestroyed()`的方法来判断，但是文档中并没有`isDestroyed()`的API，建议更新文档

**Comment by gucong3000** [comment]
我也遇到了这个问题，但我是这样判断的
```js
let scriptEngine;
function sleep (time) {
	return new Promise((resolve) => setTimeout(resolve, time));
}

function waitForEngineStart () {
	return sleep(0x50).then(() => {
		if (scriptEngine.engine) {
			return scriptEngine.engine;
		} else {
			return waitForEngineStart();
		}
	});
}

function waitForEngineStop () {
	return sleep(0x50).then(() => {
		if (scriptEngine && scriptEngine.engine && !scriptEngine.engine.destroyed) {
			return waitForEngineStart();
		}
	});
}

```

**Comment by Le-u** [comment]
怎么把主线程的参数传给 engines.execScriptFile("xx.js") 运行的新脚本引擎里面，想要拿到新的脚本引擎，ScriptExecution.getEngine() 是在 脚本运行后才可以拿到

**Comment by kkevsekk1** [comment]
有相关api



发送自我的盖乐世



-------- 原始信息 --------
发件人： Le-U ***@***.***>
日期: 2023/7/1 17:26 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 【需要更新文档】engines.execScriptFile执行子脚本结束的API (Issue #441)


怎么把主线程的参数传给 engines.execScriptFile("xx.js") 运行的新脚本引擎里面，想要拿到新的脚本引擎，ScriptExecution.getEngine() 是在 脚本运行后才可以拿到

―

**Comment by Le-u** [comment]
> 
在哪个地方，我好像没看到，
 const engine = engines.execScriptFile('./script/k.js')
  setTimeout(() => {
    console.log(engine.getEngine());
  },100)
  只有在新脚本运行完成后才可以拿到脚本引擎
