### ISSUE TITLE
OCR文档错误

### ISSUE THREAD

**Issue by songjiang951130** [kkevsekk1/AutoX#445]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：http://doc.autoxjs.com/#/AI?id=paddleocrimg-cputhreadnum-useslim 。里面描述改为代码里的就好。 PaddleOCR 移动端提供了两种模型：ocr_v2_for_cpu与ocr_v2_for_cpu(slim)，此选项用于选择加载的模型,默认true使用v2的slim版(速度更快)，false使用v2的普通版(准确率更高）

8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by songjiang951130** [comment]
没搜到文档的位置，前者更快后者更精准，是另外的项目？

**Comment by kkevsekk1** [comment]
是这个项目

**Comment by songjiang951130** [comment]
> 

https://github.com/kkevsekk1/kkevsekk1.github.io/search?q=%E5%89%8D%E8%80%85%E6%9B%B4%E5%BF%AB%E5%90%8E%E8%80%85%E6%9B%B4%E7%B2%BE%E5%87%86

在这个项目里

**Comment by songjiang951130** [comment]
> 是这个项目

https://github.com/kkevsekk1/kkevsekk1.github.io/pull/19
