### ISSUE TITLE
uniapp的支持

### ISSUE THREAD

**Issue by ykf87** [kkevsekk1/AutoX#447]
希望能支持uniapp，这样页面逻辑和脚本逻辑可不同人写.
类似 https://github.com/yooge/robot ，将autojs打包成基座, uniapp调用.

**Comment by kkevsekk1** [comment]
这个本身是支持的，webview就可以



发送自我的盖乐世



-------- 原始信息 --------
发件人： Brother Fei ***@***.***>
日期: 2022/10/11 14:51 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] uniapp的支持 (Issue #447)


希望能支持uniapp，这样页面逻辑和脚本逻辑可不同人写.
类似 https://github.com/yooge/robot ，将autojs打包成基座, uniapp调用.

―

**Comment by kkevsekk1** [comment]
本身就支持



发送自我的盖乐世



-------- 原始信息 --------
发件人： Brother Fei ***@***.***>
日期: 2022/10/11 14:51 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] uniapp的支持 (Issue #447)


希望能支持uniapp，这样页面逻辑和脚本逻辑可不同人写.
类似 https://github.com/yooge/robot ，将autojs打包成基座, uniapp调用.

―

**Comment by ykf87** [comment]
@kkevsekk1 非常感谢回复！看到有人用vue实现了，但是uniapp语法有点不一样，我做后端的前端不是很熟，请问有uniapp的示例代码吗？或者说 webview 内的js应该怎么和 autox js 通讯呢?

**Comment by podywu** [comment]
同样需求，有和uniapp通讯的方式吗？
