### ISSUE TITLE
device.getVirtualBarHeigh()获取不正确的坐标

### ISSUE THREAD

**Issue by WuMing-20** [kkevsekk1/AutoX#448]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. device.getVirtualBarHeigh()获取到的坐标是81实际84
5. 获取代码如下，来自csdn

> /** 获取状态栏⾼度 */
function getStatusBarHeight() {
    let resources = context.getResources();
    let resourceId = resources.getIdentifier("status_bar_height", "dimen", "android");
    let height = resources.getDimensionPixelSize(resourceId);
    return height;
};
alert(getStatusBarHeight());

**Comment by kkevsekk1** [comment]
sdk问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： WuMing-20 ***@***.***>
日期: 2022/10/15 17:27 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] device.getVirtualBarHeigh()获取不正确的坐标 (Issue #448)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 11
  4.  device.getVirtualBarHeigh()获取到的坐标是81实际84
  5.  获取代码如下，来自csdn
  6.  /** 获取状态栏⾼度 */

function getStatusBarHeight() {

let resources = context.getResources();



let resourceId = resources.getIdentifier("status_bar_height", "dimen", "android");



let height = resources.getDimensionPixelSize(resourceId);



return height;



};
console.log(getStatusBarHeight());
