### ISSUE TITLE
下载最新版本号为6.3.5的链接后，安卓后实际版本号是6.3.4

### ISSUE THREAD

**Issue by IMXeno123** [kkevsekk1/AutoX#450]
下载最新版本号为6.3.5的链接后，安装后实际版本号是6.3.4

**Comment by kkevsekk1** [comment]
这是之前没有修改配置导致，不影响使用



发送自我的盖乐世



-------- 原始信息 --------
发件人： IMXeno123 ***@***.***>
日期: 2022/10/18 17:49 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 下载最新版本号为6.3.5的链接后，安卓后实际版本号是6.3.4 (Issue #450)


下载最新版本号为6.3.5的链接后，安卓后实际版本号是6.3.4

―
