### ISSUE TITLE
请问 脚本完全兼容 原版autojs 的吗?

### ISSUE THREAD

**Issue by ji4ozhu** [kkevsekk1/AutoX#452]
请问 js 脚本完全兼容 原版 autojs 的吗?

**Comment by kkevsekk1** [comment]
完全兼容以前的4
收费的pro和7不兼容



发送自我的盖乐世



-------- 原始信息 --------
发件人： Wanli ***@***.***>
日期: 2022/10/25 11:52 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问 脚本完全兼容 原版autojs 的吗? (Issue #452)


请问 js 脚本完全兼容 原版 autojs 的吗?

―

**Comment by songjiang951130** [comment]
定时任务类的不兼容，我试过了

**Comment by kkevsekk1** [comment]
这个改的时候就没考虑过兼容



发送自我的盖乐世



-------- 原始信息 --------
发件人： Dream ***@***.***>
日期: 2022/11/14 01:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 请问 脚本完全兼容 原版autojs 的吗? (Issue #452)


定时任务类的不兼容，我试过了

―
