### ISSUE TITLE
click函数调用在swipe滑动之后失灵

### ISSUE THREAD

**Issue by crazyn2** [kkevsekk1/AutoX#455]
1. Autox.js 版本：6.3.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases/download/6.3.5/app-v6-arm64-v8a-release-unsigned-signed.apk
3. Android 版本：Android 11
4. Android 机型：小米k40
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）： v1.109.0, codium: 1.72.2-22289
7. 问题描述：
场景: 在公众号列表中，不断下滑，找到青春大学习后，点击该公众号。但是出现后，并没有点击
click函数调用在swipe滑动之后失灵
```
for (var i = 0; i < 9; i++){
     swipe(200, 1000, 200, 500, 1000);
    sleep(2000);
     click("青春大学习");
}
```
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by crazyn2** [comment]
1. 类似的操作，在微信公众号列表下滑，点击公众号
```
for (var i = 0; i < 9; i++){
    swipe(200, 1000, 200, 500, 1000);
    toast(i);
    sleep(1000);
}
while (!click("青春×××"));
toast("青春×××");
```
经过九次循环，最后会出现青春×××公众号，但是没有一直出现点击后的效果，也没有出现toast

2. 如果手动滑动，出现青春×××公众号，
执行以下代码
```
while (!click("青春×××"));
toast("青春×××");
```
我尝试了8次，只有第一次点击成功，之后重启无障碍服务，才可以点击成功。

再次尝试
```
for (var i = 0; i < 9; i++){
    swipe(200, 1000, 200, 500, 1000);
    toast(i);
    sleep(1000);
}
while (!click("青春×××"));
toast("青春×××");
```
只能滑动无法点击，同时执行
```
while (!click("青春×××"));
toast("青春×××");
```
也无法点击

**Comment by HDJN** [comment]
Autox.js 版本：6.3.5
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases/download/6.3.5/app-v6-arm64-v8a-release-unsigned-signed.apk
这个地址下载下来的是 6.3.4 版本，不是 6.3.5

**Comment by crazyn2** [comment]
所以这是什么情况

**Comment by HDJN** [comment]
> 所以这是什么情况

不知道呢

**Comment by crazyn2** [comment]
最新代码也是同样的情况

**Comment by James4Ever0** [comment]
嘤嘤嘤
