### ISSUE TITLE
调用快捷方式导致应用崩溃

### ISSUE THREAD

**Issue by lzlv312** [kkevsekk1/AutoX#456]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：realme gt
5. Android 系统类别：colorOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：从外部调用脚本的快捷方式报错，v5版本可以工作，v6不行，还有就是这个界面顶部的导航栏长期以来都是这样子。
8. 报错日志（可选）：Version: 634
Android: 30
java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
java.lang.RuntimeException:Unable to create application org.autojs.autojs.App: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7228)
......
Caused by:
java.lang.IllegalStateException:WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:158)
androidx.work.WorkManager.getInstance(WorkManager.java:184)
org.autojs.autojs.timing.work.WorkManagerProvider.enqueuePeriodicWork(WorkManagerProvider.kt:44)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.createCheckWorker(TimedTaskScheduler.kt:97)
org.autojs.autojs.timing.TimedTaskScheduler$Companion.init(TimedTaskScheduler.kt:91)
org.autojs.autojs.App.init(App.kt:89)
org.autojs.autojs.App.onCreate(App.kt:51)
android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
android.app.ActivityThread.handleBindApplication(ActivityThread.java:7223)
android.app.ActivityThread.access$1500(ActivityThread.java:291)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2137)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:260)
android.app.ActivityThread.main(ActivityThread.java:8228)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

9. 屏幕截图（可选）：
![Screenshot_2022-11-01-07-41-50-13_da1609eef9f7e3f5e1ae7ca4f8388be1](https://user-images.githubusercontent.com/36726139/199129631-02e28ccc-5232-4ccf-a210-474e9e9f2ec5.jpg)

**Comment by lzlv312** [comment]
补充： 切换定时任务调度器 后可以使用了。

**Comment by yangxiaoge** [comment]
> 补充： 切换定时任务调度器 后可以使用了。

我也碰到这个问题，我换了个方案，在`定时任务`里设置了广播`广播`，然后通过其他应用（例如macrodroid，tasker）发送广播即可😀
