### ISSUE TITLE
是否可以启动一个后台服务 类似于appium或者airtest 用电脑远程操控autox

### ISSUE THREAD

**Issue by James4Ever0** [kkevsekk1/AutoX#457]
用adb启动autox的服务器 获取ip地址和端口号 pc连接并发送js代码并运行

**Comment by James4Ever0** [comment]
目前可以通过shortcut启动 具体如下

```bash
am start -n org.autojs.autoxjs.v6/org.autojs.autojs.external.shortcut.ShortcutActivity -a android.intent.action.MAIN -e path "/storage/emulated/0/脚本/show_toast.js"
```

**Comment by James4Ever0** [comment]
连接电脑的代码在[这里](https://github.com/kkevsekk1/AutoX/blob/5172fd92fbf778509b76e1a11bbfc9f5fdfaaf0c/app/src/main/java/org/autojs/autojs/ui/main/drawer/DrawerPage.kt 需要修改才能通过intent传入websocket的服务器地址

**Comment by ihrskyfish** [comment]
> 用adb启动autox的服务器 获取ip地址和端口号 pc连接并发送js代码并运行

我记得autojs6中,电脑可以作为客户端连接  作为服务端的autojs ,不过不是通过adb,而是一种普通的网络连接,在autoxjs中是被删除了,还是被隐藏了,因为我看到这个项目中https://github.com/ys1231/pyautoxjs/  中.提到vscode插件可以主动链接autoxjs.
