### ISSUE TITLE
关于控件缓存的问题

### ISSUE THREAD

**Issue by developer-wlj** [kkevsekk1/AutoX#458]
1. Autox.js 版本：634
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases/tag/6.3.5
3. Android 版本：Android 12
4. Android 机型：红米k30pro
5. Android 系统类别：MIUI13
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：id('xxx').findOne().text()  抖音上获取的是上一页的数据,无论是否加上  auto(); 或 auto('normal'); 或 auto.setMode('normal') 都是获取的上一页的数据 
8. 报错日志（可选）：无报错
9. 屏幕截图（可选）：

**Comment by yf-web** [comment]
问题同上，有没有解决方案？谢谢！

**Comment by kkevsekk1** [comment]
你再研究一下，应该缓存，像抖音这种本身有预加载，有看不见的节点存在的……



发送自我的盖乐世



-------- 原始信息 --------
发件人： alan2yang ***@***.***>
日期: 2022/11/12 18:53 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 关于控件缓存的问题 (Issue #458)


问题同上，有没有解决方案？谢谢！

―

**Comment by yf-web** [comment]
换方案，可以使用bounds。id目前没有找到解决方案。

**Comment by developer-wlj** [comment]
> 问题同上，有没有解决方案？谢谢！

要换下思路  用id('xxx').find().length  可以看到2-3节点  为啥不是固定的 因为第一次进入  app会缓存当前页和下一页的数据 可以看到是2个节点  刷的第二个视频 会变成3个节点  因为第二个视频会包含上一页  当前页和下一页的数据 所以 大部分用(id('xxx').find())[1].text() 就可以获取正确的数据 只有刚进app时 要处理下 获取数组下标为0 的数据即可

**Comment by anenn** [comment]
这种情况是不是可以加个 visibleToUser 来过滤，即 id('xxx').visibleToUser(true).findOne().text()。
