### ISSUE TITLE
布局范围分析无法关闭

### ISSUE THREAD

**Issue by e1399579** [kkevsekk1/AutoX#462]
1. Autox.js 版本：6.3.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：Sony Xperia 5
5. Android 系统类别：官方，原生
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
- 布局范围分析打开之后，那个悬浮窗在界面底部，点不到，无法关闭。原版似乎是按音量-关闭。
- 常按控件，也没有信息查看。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by wilinz** [comment]
点击控件弹出菜单有退出悬浮窗选项

**Comment by e1399579** [comment]
> 点击控件弹出菜单有退出悬浮窗选项

长按、点按控件没反应，没有菜单

**Comment by wilinz** [comment]
录个视频看看

**Comment by e1399579** [comment]
[录屏（阿里云盘）](https://www.aliyundrive.com/s/NVnLV9ZL3uv)
