### ISSUE TITLE
toast不显示

### ISSUE THREAD

**Issue by kevin3061** [kkevsekk1/AutoX#463]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：oppo reno4
5. Android 系统类别：coloros V12.1
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：toast经常出现不显示，如果调用比较频繁的话，前边显示几下，后边的都不显示了。另外对于打包后如果配置的不显示日志，则toast直接失效
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这玩意是小米这类系统的问题，用三星，Google不会出现



发送自我的盖乐世



-------- 原始信息 --------
发件人： kevin3061 ***@***.***>
日期: 2022/11/17 15:31 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] toast不显示 (Issue #463)


  1.  Autox.js 版本：635
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：oppo reno4
  5.  Android 系统类别：coloros V12.1
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：toast经常出现不显示，如果调用比较频繁的话，前边显示几下，后边的都不显示了。另外对于打包后如果配置的不显示日志，则toast直接失效
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by anenn** [comment]
有没遇到过，用 adb 安装软件，Toast能正常显示。但如果是软件下载或存储到手机，在手机点击安装，就弹不出来。一直无解！

**Comment by Tsyshiu** [comment]
华为上也有这个问题，toast仅当autojs在前台运行时才能显示

**Comment by TommyShing** [comment]
实测澎湃不加延时时最多坚持到第五个toast, 1秒延时坚持到第八个开始跳着toast, 如果调到toast持续时间以上的延时程序就可以继续正常运行😶
