### ISSUE TITLE
Google ML kIT OCR打包为APP无法正常使用

### ISSUE THREAD

**Issue by youyusi** [kkevsekk1/AutoX#470]
1. Autox.js 版本：634,635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. 问题描述：Google ML kIT OCR功能在打包APP后无法正常使用,gmlkit.ocr返回null,打包前有勾选Google ML kIT OCR模块

**Comment by wilinz** [comment]
模拟器用不了

**Comment by youyusi** [comment]
在手机上编译的，不是模拟器

**Comment by youyusi** [comment]
> 模拟器用不了

是在手机上打包的APP，使用的型号有荣耀8,IQOO U3的机型测试的

**Comment by czy-moyu** [comment]
> 

所有的ocr模拟器都用不了？

**Comment by czy-moyu** [comment]
> 模拟器用不了

所有的ocr模拟器都用不了？

**Comment by czy-moyu** [comment]
模拟器文字识别正常，但是坐标不对。
