### ISSUE TITLE
可以问一下，这个项目现在还好吗？主页上有好几个issue好像都无法解决的样子……

### ISSUE THREAD

**Issue by ghost** [kkevsekk1/AutoX#471]
> 实在看不下去了，有完没完，近期的几个争论都是你挖好的坑，现在又跳出来说三道四。 捐助是单方自愿行为，无附带条件。

@CuteLicense 当时作者甚至提出了严厉指责和限期修复的命令，当时这边一看整个人气得不行，再加上随后旧疾复发就在医院里躺了好几天才勉强恢复，这也是为什么当时没有及时回复的原因，个人也不想太过追究这方面的问题，医院也有相关的住院证明，想查随时都有，但真的请不要再无端指责了……

_Originally posted by @LZX284 in https://github.com/kkevsekk1/AutoX/issues/395#issuecomment-1214317335_

**Comment by LZX2840** [comment]
曾经是这个项目的一个贡献者，之前也是为了想让这个项目更好，但有时可能没注意到自己做事的方式方法，导致和作者之间产生了不少误会。自己也尝试过解释误会实现和解，但作者现在似乎什么话都听不进去，自己真的是不希望变成这样，算了，现在说什么也没用了，还是几句话说完就走吧……

**Comment by LZX2840** [comment]
> 实在看不下去了，有完没完，近期的几个争论都是你挖好的坑，现在又跳出来说三道四。 捐助是单方自愿行为，无附带条件。
> 

对于这里提到的捐助是否违反开源协议的问题，自己确实犯过一些错误，当时比较单纯，认为规定就是规定，autoxjs作为一个开源项目随便违反原作者的协议条款是不好的，当时自己直接就把问题提了出来，但没想到这样可能会对这个项目造成伤害，对此我感到十分抱歉。

**Comment by LZX2840** [comment]
> 实在看不下去了，有完没完，近期的几个争论都是你挖好的坑，现在又跳出来说三道四。 捐助是单方自愿行为，无附带条件。

至于说这项目之前所有问题“都是你挖好的坑”，以及之前[TBS相关问题帖子](https://github.com/kkevsekk1/AutoX/issues/366)作者也说了，
![屏幕截图 2022-12-06 112731](https://user-images.githubusercontent.com/113951036/205805831-5b4b0215-5a5f-494e-9556-224fef19df11.png)

真的不是这样。之前也许有过一些问题，但我自己做错的事我自己承认，并且也会想办法尽力弥补，TBS可能侵权的问题是我的疏忽，补丁自己也提交并被合并了，这些和我有关的问题至少我都尽力去解决问题了，不能说什么“你跟其他团队合作也这样搞，代码一提交锅都是别人的……”

**Comment by LZX2840** [comment]
就这样吧。我为我之前做错的事及对这个项目可能的伤害道歉，我不应该那样做，希望这些不会给作者及这个项目的用户们带来困扰，希望大家一切都好，就这样，再见吧……
