### ISSUE TITLE
作者说"最近 邮件 系统坏了"，那现在作者能不能出来谈一谈？处理一下Release 6.2.0通告中挂人的事情？

### ISSUE THREAD

**Issue by ghost** [kkevsekk1/AutoX#474]
[PR以及找作者和谈](https://github.com/kkevsekk1/AutoX/pull/465)
![屏幕截图 2022-12-15 1](https://user-images.githubusercontent.com/120650790/207864285-b05c8b8a-ab14-4191-9f6d-8f4e250cd953.png)

[作者说 最近 邮件 系统坏了](https://github.com/kkevsekk1/AutoX/pull/466)

![屏幕截图 2022-12-15 2](https://user-images.githubusercontent.com/120650790/207864319-15b1986a-2bc3-4e15-9f70-9dc1181bdb0e.png)

[针对TBS问题的再度澄清：真不想把事情闹大，但你们总不能这样无底线抹黑别人吧……](https://github.com/kkevsekk1/AutoX/issues/435)

**Comment by lzx28400** [comment]
![屏幕截图 2022-12-15 3](https://user-images.githubusercontent.com/120650790/207865261-b29a4203-93ec-4754-b095-d492e14e55e5.png)
整改别人不侵权的代码？这怎么说都有点不合适吧？！
PR都合并了，作者还坚持把这些东西保留这么久，真让人想不通，难不成是想让这个项目的所有用户都知道作者对于贡献者犯错的严厉态度吗？！
@kkevsekk1 这其实对这个项目以及这个项目的用户们也不是什么好事情吧？事情都过去这么久了，大家协商一下解决这个问题不好吗？

**Comment by lzx28400** [comment]
算了，现在任谁都能看出来，作者就是故意的，哪怕这边再怎么申诉，作者也是绝不会把通告中的恶意内容撤销掉的，那说这么多还有什么用？！算了，你们爱咋整，咋整吧……

**Comment by lzx28400** [comment]
> 装模作样花式换小号说了多少次"再见、算了、就这样"之类，当然，以你如此做作的行事风格，以后再出现我也毫不意外。

莫非你真的是耐心等我不再出现才出来回复的吗？真是用心良苦，可你要知道，当时是以为你故意不回复的我才那么说的，但如果你真的是邮件系统坏了那一切就都不一样了，至少我不想再一次因为误会把事情搞糟……

**Comment by lzx28400** [comment]
> 装模作样花式换小号说了多少次"再见、算了、就这样"之类，当然，以你如此做作的行事风格，以后再出现我也毫不意外。

说话之前忘了先请教一下了，您到底是哪位？您是 @kkevsekk1 请来的救兵吗？屡次三番，作者自己敢挂人却不敢出来面对，就一次次找人出面到底是什么意思？你们在背后搞什么我不管，但这个项目真不是我搞坏的，所以还请不要处处针对我……

**Comment by lzx28400** [comment]
@kkevsekk1 又要一个星期过去了，这样都没回复那大家就都知道你不是真的"邮件 系统坏了"……
真的，能不能不要再玩这种藏着躲着不回复、不理会的把戏？这肯定又是某人给你出的主意吧？
说真的，你不愿意出面也行，我只能把该说的话说完，而身为这个项目的作者，问题能不能解决其实都只能取决于你……
