### ISSUE TITLE
微信经常会无法布局分析？

### ISSUE THREAD

**Issue by wingswing1** [kkevsekk1/AutoX#476]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K50
5. Android 系统类别：MIUI13
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：微信经常会无法布局分析，微信版本是最新的8.0.31
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这种只能自己排查，具体问题具体分析



发送自我的盖乐世



-------- 原始信息 --------
发件人： wingswing1 ***@***.***>
日期: 2022/12/26 09:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 微信经常会无法布局分析？ (Issue #476)


  1.  Autox.js 版本：635
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：红米K50
  5.  Android 系统类别：MIUI13
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
  7.  问题描述：微信经常会无法布局分析，微信版本是最新的8.0.31
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―
