### ISSUE TITLE
ui模式下请求截屏权限卡死

### ISSUE THREAD

**Issue by Holywuya** [kkevsekk1/AutoX#478]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by wangchuang168** [comment]
在UI模式下，把这个权限申请，用threads 创建一个线程，放到线程里执行就可以了
