### ISSUE TITLE
ReferenceError: "module" is not defined.

### ISSUE THREAD

**Issue by Holywuya** [kkevsekk1/AutoX#479]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
如标题

9. 报错日志（可选）：
10. 屏幕截图（可选）：
const PI = Math.PI;
 var circle = {};
  circle.area = function (r) { return PI * r * r; };
   circle.circumference = (r) => 2 * PI * r; 
   module.exports = circle;

**Comment by kkevsekk1** [comment]
这个确实搞丢了，你用webpack编译js，用js的能力引用其他模块，替代这种方案



发送自我的盖乐世



-------- 原始信息 --------
发件人： Holywuya ***@***.***>
日期: 2022/12/29 02:11 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] ReferenceError: "module" is not defined. (Issue #479)


  1.  Autox.js 版本：629

  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases

  3.  Android 版本：Android 10

  4.  Android 机型：小米10

  5.  Android 系统类别：MIUI

  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：

  7.  问题描述：
如标题

  8.  报错日志（可选）：

  9.  屏幕截图（可选）：
const PI = Math.PI;
var circle = {};
circle.area = function (r) { return PI * r * r; };
circle.circumference = (r) => 2 * PI * r;
module.exports = circle;

―

**Comment by will-bug** [comment]
请问最新的版本是否修复了这个问题呢, 现在好像还是会报错
