### ISSUE TITLE
关于手机编辑器问题

### ISSUE THREAD

**Issue by LYS86** [kkevsekk1/AutoX#480]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：非正常退出文件会被保留，例如打开a脚本后，把软件切到后台再切回来，软件会退回主页，此时再打开任意脚本，例如b脚本，进入的必是a脚本，需要退出a再进b才能正确打开b脚本。这个文件保留功能优化下呗，或者加个开关给用户自行选择是否保留。另外，进行大量粘贴操作时，好像超过一定行数后就不会自动跳转到尾部
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这个是有这个bug，不建议在手机上编程，手机上顶多用来临时调试，实现简单的想法

________________________________
发件人: LYS ***@***.***>
发送时间: 2023年1月3日 12:34
收件人: kkevsekk1/AutoX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kkevsekk1/AutoX] 关于手机编辑器问题 (Issue #480)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：非正常退出文件会被保留，例如打开a脚本后，把软件切到后台再切回来，软件会退回主页，此时再打开任意脚本，例如b脚本，进入的必是a脚本，需要退出a再进b才能正确打开b脚本。这个文件保留功能优化下呗，或者加个开关给用户自行选择是否保留。另外，进行大量粘贴操作时，好像超过一定行数后就不会自动跳转到尾部
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by LYS86** [comment]
电脑编写体验的确更好，但一般的小脚本基本都是在手机编写
