### ISSUE TITLE
签名异常

### ISSUE THREAD

**Issue by O5command** [kkevsekk1/AutoX#481]
1. Autox.js 版本：6.3.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：荣耀50SE
5. Android 系统类别：Magic UI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：使用除默认签名外的签名打包，显示无法解析安装包
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
是不是设置问题？



发送自我的盖乐世



-------- 原始信息 --------
发件人： O5command ***@***.***>
日期: 2023/1/6 15:39 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 签名异常 (Issue #481)


  1.  Autox.js 版本：6.3.5
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：荣耀50SE
  5.  Android 系统类别：Magic UI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
  7.  问题描述：使用除默认签名外的签名打包，显示无法解析安装包
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―
