### ISSUE TITLE
autojs问题

### ISSUE THREAD

**Issue by TommyTang20051207** [kkevsekk1/AutoX#482]
1. Autox.js 版本：636
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：redmi note11pro
5. Android 系统类别：MIUI14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：

8. 问题描述：1.贪吃蛇和贪吃蛇重力感应版报错
                      2.打包的Apk软件经常闪退，无法兼容

9. 报错日志（可选）：
10. 屏幕截图（可选）：
![Screenshot_2023-01-08-17-54-21-357_org autojs autoxjs v6](https://user-images.githubusercontent.com/61679336/211190144-9f19c32c-287f-4585-921b-59cf106b0d40.jpg)

**Comment by kkevsekk1** [comment]
这些解决方法是提高代码的可靠性



发送自我的盖乐世



-------- 原始信息 --------
发件人： TommyTang20051207 ***@***.***>
日期: 2023/1/8 18:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] autojs问题 (Issue #482)


  1.  Autox.js 版本：636

  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases

  3.  Android 版本：Android 13

  4.  Android 机型：redmi note11pro

  5.  Android 系统类别：MIUI14

  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：

  7.  问题描述：1.贪吃蛇和贪吃蛇重力感应版报错
2.打包的Apk软件经常闪退，无法兼容

  8.  报错日志（可选）：

  9.  屏幕截图（可选）：
[Screenshot_2023-01-08-17-54-21-357_org autojs autoxjs v6]<https://user-images.githubusercontent.com/61679336/211190144-9f19c32c-287f-4585-921b-59cf106b0d40.jpg>

―

**Comment by chengs2035** [comment]
这是你自己代码的问题🤗
