### ISSUE TITLE
macos autox.js 连接电脑 握手失败

### ISSUE THREAD

**Issue by xinpiaoyuanfang** [kkevsekk1/AutoX#483]
1. Autox.js 版本：6.3.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：Genymotion模拟器 Google Pix
5. Android 系统类别：google
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v0.3.8
7. 问题描述：mac os，vscode 插件服务已经启动，模拟器上 “连接手机” 显示 “握手失败”
8. 报错日志（可选）：
9. 屏幕截图（可选）：
<img width="562" alt="image" src="https://user-images.githubusercontent.com/38042291/212356563-6dc4064f-7b66-43c2-9112-05daafc3fb8f.png">
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/38042291/212356727-03b7bca3-a0c2-4a62-bec6-f91047aecad6.png">

**Comment by wilinz** [comment]
插件太旧了，更新插件

**Comment by xinpiaoyuanfang** [comment]
> 

原来如此

**Comment by xinpiaoyuanfang** [comment]
插件换一个

**Comment by cjl628-cjl** [comment]
插件不就这一个嘛，还能怎么换？

**Comment by eve2ptp** [comment]
> 插件不就这一个嘛，还能怎么换？

![image](https://user-images.githubusercontent.com/42791572/220608820-1baaa694-ce73-4605-9d4c-e3905677fd15.png)

**Comment by kkevsekk1** [comment]
防火墙，ip，网段，网关，跟插件都没多少关系



发送自我的盖乐世



-------- 原始信息 --------
发件人： eve2ptp ***@***.***>
日期: 2023/2/22 19:35 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] macos autox.js 连接电脑 握手失败 (Issue #483)


插件不就这一个嘛，还能怎么换？

[image]<https://user-images.githubusercontent.com/42791572/220608820-1baaa694-ce73-4605-9d4c-e3905677fd15.png>

―

**Comment by cbg8848** [comment]
是插件问题，重新启用一下就连上了
