### ISSUE TITLE
随便就试出两个bug

### ISSUE THREAD

**Issue by 2980077544** [kkevsekk1/AutoX#484]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：MIUI 12.5.8
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
问题一：长按运行崩溃
问题二：运行一个脚本返回打开另一个脚本仍是之前脚本内容

https://user-images.githubusercontent.com/47817223/213608476-f9f14a05-781e-4798-9a77-48457504a7e0.mp4

9. 报错日志（可选）：Version: 635
Android: 30
java.lang.NullPointerException: 
java.lang.RuntimeException:Unable to destroy activity {org.autojs.autoxjs.v6/com.stardust.autojs.execution.ScriptExecuteActivity}: java.lang.NullPointerException
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5245)
......
Caused by:
java.lang.NullPointerException:
java.util.Objects.requireNonNull(Objects.java:220)
com.stardust.autojs.runtime.ScriptRuntime.onExit(ScriptRuntime.java:424)
com.stardust.autojs.engine.JavaScriptEngine.destroy(JavaScriptEngine.java:59)
com.stardust.autojs.engine.RhinoJavaScriptEngine.destroy(RhinoJavaScriptEngine.kt:100)
com.stardust.autojs.engine.LoopBasedJavaScriptEngine.destroy(LoopBasedJavaScriptEngine.java:91)
com.stardust.autojs.execution.ScriptExecuteActivity.onDestroy(ScriptExecuteActivity.kt:126)
android.app.Activity.performDestroy(Activity.java:8429)
android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1343)
android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5230)
android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5274)
android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loop(Looper.java:233)
android.app.ActivityThread.main(ActivityThread.java:8052)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

10. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
不好解决
