### ISSUE TITLE
无障碍服务 可以修改名字？

### ISSUE THREAD

**Issue by songjiang951130** [kkevsekk1/AutoX#487]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：荣耀50
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
我在使用学x强国app的时候，只要开启无障碍服务就会有个检查提示，注册无障碍服务的时候可以修改名字，包名之类的？
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by songjiang951130** [comment]
> 警察告诉你，不可以抢银行，你回来问，银行可以改名字嘛？改成银航，抢银航，就是不是抢银行了。

首先这不抢银行。肯定是上了什么黑名单了，就是要看看是根据啥上的，换个马甲不就行了嘛

**Comment by chengs2035** [comment]
可以自己编译一个，然后改下名字看下？
