### ISSUE TITLE
有什么方案可以用vscode连接远程主机上的模拟器吗？

### ISSUE THREAD

**Issue by naiyouweibaomihua** [kkevsekk1/AutoX#489]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：rt
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by Hermes981128** [comment]
使用zerotier搭建一个局域网环境然后连接应该可以，你可以试试
