### ISSUE TITLE
dialogs.build的input事件报错

### ISSUE THREAD

**Issue by Cryogenic-yosa** [kkevsekk1/AutoX#491]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. 报错日志
04:03:34.340/E: TypeError: Cannot call method "emit" of null (file:///android_asset/modules/__dialogs__.js#158)
TypeError: Cannot call method "emit" of null
    at file:///android_asset/modules/__dialogs__.js:158:0
    at file:///android_asset/modules/__dialogs__.js:136:0
    at file:///android_asset/modules/__ui__.js:89:0

代码是直接复制的文档里
dialogs.build({
    title: "请输入",
    positive: "确定",
    negative: "取消",
    inputPrefill: ""
}).on("input", (text, dialog) => {
    toast("你输入的是" + text);
}).show();
但是无法使用

**Comment by LevonLu** [comment]
遇到了同样的问题

**Comment by LYS86** [comment]
该模块有关‘emit’的报错是160行的‘.alwaysCallInputCallback();’引起的，可通过注释该行解决
```
// 导入内置对话框模块
let dialogs = require('__dialogs__');
// 删除相关代码
let str = dialogs.toString().replace(/\.alwaysCallInputCallback\(\)/, '');
// 写入到 './dialogs.js' 文件
files.write('./dialogs.js', 'module.exports =' + str);
// 重新导入处理后的对话框模块
dialogs = require('./dialogs.js')(this.runtime, this);
dialogs.build({
    title: "请输入您的年龄",
    inputPrefill: "18"
}).show();

```
#751 #749 #354 #491

**Comment by Cryogenic-yosa** [comment]
> 该模块有关‘emit’的报错是160行的‘.alwaysCallInputCallback();’引起的，可通过注释该行解决
> 
> ```
> // 导入内置对话框模块
> let dialogs = require('__dialogs__');
> // 删除相关代码
> let str = dialogs.toString().replace(/\.alwaysCallInputCallback\(\)/, '');
> // 写入到 './dialogs.js' 文件
> files.write('./dialogs.js', 'module.exports =' + str);
> // 重新导入处理后的对话框模块
> dialogs = require('./dialogs.js')(this.runtime, this);
> dialogs.build({
>     title: "请输入您的年龄",
>     inputPrefill: "18"
> }).show();
> ```
> 
> #751 #749 #354 #491 #558

感谢🙏这个问题以后会修复吗

**Comment by LYS86** [comment]
应该不会，这问题在4.1版本就已经存在，只能尝试自己解决然后提个pr。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月3日(周日) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] dialogs.build的input事件报错 (Issue #491)




  
该模块有关‘emit’的报错是160行的‘.alwaysCallInputCallback();’引起的，可通过注释该行解决
 // 导入内置对话框模块 let dialogs = require('__dialogs__'); // 删除相关代码 let str = dialogs.toString().replace(/\.alwaysCallInputCallback\(\)/, ''); // 写入到 './dialogs.js' 文件 files.write('./dialogs.js', 'module.exports =' + str); // 重新导入处理后的对话框模块 dialogs = require('./dialogs.js')(this.runtime, this); dialogs.build({     title: "请输入您的年龄",     inputPrefill: "18" }).show();  
#751 #749 #354 #491 #558
  
感谢🙏这个问题以后会修复吗
