### ISSUE TITLE
console.setSize函数设置的矩形区域尺寸不准确

### ISSUE THREAD

**Issue by ximengxuan** [kkevsekk1/AutoX#493]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：小米8青春版
5. Android 系统类别：MIUI 11.0.4
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.111.0
7. 问题描述：
device.width, device.height获取的分辨率，是正确的。值为1080*2280

console.setSize(device.width / 2, device.height / 2);   //设置控制台尺寸
console.show();   //显示控制台

执行以上代码，显示出来的控制台，尺寸并不正确。

**Comment by ximengxuan** [comment]
console.show();
console.log("");
console.setSize(device.width / 2, device.height / 2);

代码改成这样，控制台的尺寸显示就正常了。
show之后，需要打印一个日志内容。
然后调用setSize，才能设置正确的尺寸。
猜测是setSize刷新的问题，麻烦看看能不能修复。

**Comment by kkevsekk1** [comment]
😂



发送自我的盖乐世



-------- 原始信息 --------
发件人： feiyun ***@***.***>
日期: 2023/2/15 18:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] console.setSize函数设置的矩形区域尺寸不准确 (Issue #493)


console.show();
console.log("");
console.setSize(device.width / 2, device.height / 2);

代码改成这样，控制台的尺寸显示就正常了。
show之后，需要打印一个日志内容。
然后调用setSize，才能设置正确的尺寸。
猜测是setSize刷新的问题，麻烦看看能不能修复。

**Comment by ximengxuan** [comment]
暂时通过冗余代码解决了

// 重定义控制台样式(autoX.js)
function setConsole() {
    console.show(true);   //程序结束自动 隐藏控制台
    console.log("");   //刷新显示，解决尺寸无法无法刷新的问题

    console.setSize(device.width / 2, device.height / 2);   //设置控制台尺寸

    console.setTitle('www.feiyunjs.com', "#1e9fff", 40);
    // console.log("");   //刷新显示，解决尺寸无法无法刷新的问题

    console.setLogSize(10);  //设置主体内容字号(需要在显示控制台之后才能设置，否则空指针)
    console.setCanInput(false);  //隐藏确定按钮
    console.clear();  //清除空行
}
