### ISSUE TITLE
开发插件停止服务后，会出现新的连接地址

### ISSUE THREAD

**Issue by ximengxuan** [kkevsekk1/AutoX#494]
Autox.js 版本：635
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 9
Android 机型：小米8青春版
Android 系统类别：MIUI 11.0.4
VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.111.0
问题描述：

开发插件停止服务后，再启动服务，会出现新的域名和端口。
再操作一次，就另外出现一个端口。
操作3次，提示如下：
Auto.js Autox.js server running on 192.168.3.12:9317 or 192.168.137.1:9317 or 192.168.160.1:9317
不知道是不是bug？

**Comment by kkevsekk1** [comment]
3.12
这个应该是不会变的。你有电脑有虚拟网卡吧

发送自我的盖乐世



-------- 原始信息 --------
发件人： feiyun ***@***.***>
日期: 2023/2/17 20:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 开发插件停止服务后，会出现新的连接地址 (Issue #494)


Autox.js 版本：635
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 9
Android 机型：小米8青春版
Android 系统类别：MIUI 11.0.4
VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.111.0
问题描述：

开发插件停止服务后，再启动服务，会出现新的域名和端口。
再操作一次，就另外出现一个端口。
操作3次，提示如下：
Auto.js Autox.js server running on 192.168.3.12:9317 or 192.168.137.1:9317 or 192.168.160.1:9317
不知道是不是bug？

―

**Comment by ximengxuan** [comment]
我用的macbook pro 2019，macOS12.6，应该没有虚拟网卡啊？
