### ISSUE TITLE
promise 无法正常工作

### ISSUE THREAD

**Issue by fallshuang** [kkevsekk1/AutoX#496]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：

promise `无法正常工作：`

```
function mysleep(ms) {
    return new Promise((resolve, reject)=> setTimeout(resolve, ms) );
}

function foo(k) {
    console.log("foo done=" + k)
}

let chain = Promise.resolve()
for( let n = 1; n< 10000; n++) 
{
    chain = chain.then(()=> {
        foo(n) 
    }).then(()=>{
        return mysleep(1000)
    })
}
```
上面这段代码理论上应该不停打印 foo done ， 用nodejs 运行上面的代码会不停打印 foo done
但是autojsx 里 实际上打印几次就退出了

00:37:19.436/V: 开始运行[[remote]main.js]
00:37:20.143/D: foo done=1
00:37:21.151/D: foo done=2
00:37:22.158/D: foo done=3
00:37:23.167/D: foo done=4
00:37:24.177/D: foo done=5
00:37:25.192/D: foo done=6
00:37:26.213/V: 
 ------------ 
 [ [remote]main.js ]运行结束，用时6.773000秒

9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这不是运行在nodejs上得，肯定有差异，有sleep吧



发送自我的盖乐世



-------- 原始信息 --------
发件人： Sank Hwang ***@***.***>
日期: 2023/2/19 00:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] promise 无法正常工作 (Issue #496)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：

promise 无法正常工作：

function mysleep(ms) {

    return new Promise((resolve, reject)=> setTimeout(resolve, ms) );

}



function foo(k) {

    console.log("foo done=" + k)

}



let chain = Promise.resolve()

for( let n = 1; n< 10000; n++)

{

    chain = chain.then(()=> {

        foo(n)

    }).then(()=>{

        return mysleep(1000)

    })

}



上面这段代码理论上应该不停打印 foo done ， 用nodejs 运行上面的代码会不停打印 foo done
但是autojsx 里 实际上打印几次就退出了

00:37:19.436/V: 开始运行[[remote]main.js]
00:37:20.143/D: foo done=1
00:37:21.151/D: foo done=2
00:37:22.158/D: foo done=3
00:37:23.167/D: foo done=4
00:37:24.177/D: foo done=5
00:37:25.192/D: foo done=6
00:37:26.213/V:

[ [remote]main.js ]运行结束，用时6.773000秒

  1.  报错日志（可选）：
  2.  屏幕截图（可选）：

―

**Comment by kkevsekk1** [comment]
这是运行在java里的，很多java特性是可以用的



发送自我的盖乐世



-------- 原始信息 --------
发件人： Sank Hwang ***@***.***>
日期: 2023/2/19 00:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] promise 无法正常工作 (Issue #496)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：

promise 无法正常工作：

function mysleep(ms) {

    return new Promise((resolve, reject)=> setTimeout(resolve, ms) );

}



function foo(k) {

    console.log("foo done=" + k)

}



let chain = Promise.resolve()

for( let n = 1; n< 10000; n++)

{

    chain = chain.then(()=> {

        foo(n)

    }).then(()=>{

        return mysleep(1000)

    })

}



上面这段代码理论上应该不停打印 foo done ， 用nodejs 运行上面的代码会不停打印 foo done
但是autojsx 里 实际上打印几次就退出了

00:37:19.436/V: 开始运行[[remote]main.js]
00:37:20.143/D: foo done=1
00:37:21.151/D: foo done=2
00:37:22.158/D: foo done=3
00:37:23.167/D: foo done=4
00:37:24.177/D: foo done=5
00:37:25.192/D: foo done=6
00:37:26.213/V:

[ [remote]main.js ]运行结束，用时6.773000秒

  1.  报错日志（可选）：
  2.  屏幕截图（可选）：

―

**Comment by fallshuang** [comment]
多谢。我懂你意思了。
因为我保持了 js 开发的习惯， js 里都是用 promise 去sleep 的。 看来这些习惯要改下
