### ISSUE TITLE
报错：identifier is a reserved word: class

### ISSUE THREAD

**Issue by Gabirel** [kkevsekk1/AutoX#498]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10以下，具体版本未知
4. Android 机型：模拟器
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：

```javascript
class Test() {
   xxxxx;
}
```

在代码执行中，会报以下错误：
```
identifier is a reserved word: class
```

Rhino引擎不支持脚本写 class 吗？如果不支持，后续是否考虑会添加呢？

9. 报错日志（可选）：无需
10. 屏幕截图（可选）：无需

**Comment by kingpeak** [comment]
同样遇到了这个问题
2024-5-21 09:46:11
