### ISSUE TITLE
加载 android-mail-1.6.4.jar 会识别不出class

### ISSUE THREAD

**Issue by 710850609** [kkevsekk1/AutoX#5]
如题引入 [android-mail-1.6.4.jar ](http://archiva-maven-storage-prod.oss-cn-beijing.aliyuncs.com/repository/jcenter/com/sun/mail/android-mail/1.6.5/android-mail-1.6.5.jar?Expires=1600351387&OSSAccessKeyId=LTAIfU51SusnnfCC&Signature=gECXmmONC8KQyDUIArzyOawlBs4%3D)
加载里面的class 不能识别，使用pro8就可以

**Comment by kkevsekk1** [comment]
我很少上邮箱，加群可能更方便点，
不太明白你说的







在 2020-09-17 20:14:20，"BoB" <notifications@github.com> 写道：

如题引入 android-mail-1.6.4.jar
加载里面的class 不能识别，使用pro8就可以

**Comment by 710850609** [comment]
> 我很少上邮箱，加群可能更方便点， 不太明白你说的 在 2020-09-17 20:14:20，"BoB" <notifications@github.com> 写道： 如题引入 android-mail-1.6.4.jar 加载里面的class 不能识别，使用pro8就可以 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那个群？

**Comment by 710850609** [comment]
> 我很少上邮箱，加群可能更方便点， 不太明白你说的 在 2020-09-17 20:14:20，"BoB" <notifications@github.com> 写道： 如题引入 android-mail-1.6.4.jar 加载里面的class 不能识别，使用pro8就可以 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

具体重现可以下载jar -> 引入 -> 加载 ，就能重现。下面是加载javax的一个邮件相关的jar，也是一样
![image](https://user-images.githubusercontent.com/9523566/93586844-84d61c80-f9db-11ea-86cf-4a72d5c6d96b.png)

**Comment by kkevsekk1** [comment]
这个你先尝试 将 jar转换为dex， 用runtime.loadDex() 加载，我估计是这个jar 转换 dex 有问题，

**Comment by kkevsekk1** [comment]
autoxjs --http--web服务器，api---发送邮件



发送自我的盖乐世



-------- 原始信息 --------
发件人： wuwenrufeng ***@***.***>
日期: 2022/10/2 10:34 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, State change ***@***.***>
主题： Re: [kkevsekk1/AutoX] 加载 android-mail-1.6.4.jar 会识别不出class (#5)


这个你先尝试 将 jar转换为dex， 用runtime.loadDex() 加载，我估计是这个jar 转换 dex 有问题，

我试过拿别人可以用的dex，也是识别不了class， 不知道是不是我自己的手机问题，还是aj问题

大佬 这个问题解决了吗？目前也想实现后台发邮件

―
