### ISSUE TITLE
getClip函数无法使用

### ISSUE THREAD

**Issue by plutonium-94** [kkevsekk1/AutoX#500]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：Redmi K50 Ultra
5. Android 系统类别：MIUI 13
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
`getClip`函数无法使用，例如`console.log(getClip());`只能产生空结果。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by zhseren** [comment]
安卓12 禁止软件后台读取剪贴板了吧

**Comment by ttidsn84320** [comment]
安卓10以上后台获取剪贴板都获取不到，有办法处理吗

**Comment by jiumengs** [comment]
安卓10以上后台获取剪贴板都获取不到，有办法处理吗
