### ISSUE TITLE
协程示例代码报错

### ISSUE THREAD

**Issue by Rukawalee** [kkevsekk1/AutoX#502]
1. Autox.js 版本：636
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米10s
5. Android 系统类别：MIUI14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
`17:55:58.782/E: Wrapped java.lang.IllegalStateException: Cannot capture continuation from JavaScript code not called directly by executeScriptWithContinuations or callFunctionWithContinuations (file:///android_asset/modules/__continuation__.js#12)
Wrapped java.lang.IllegalStateException: Cannot capture continuation from JavaScript code not called directly by executeScriptWithContinuations or callFunctionWithContinuations
    at file:///android_asset/modules/__continuation__.js:12:0
    at delay (/data/user/0/org.autojs.autoxjs.v6/files/sample/协程/协程HelloWorld/main.js:10:0)
    at /data/user/0/org.autojs.autoxjs.v6/files/sample/协程/协程HelloWorld/main.js:42:0
`
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
多次调用截图请求所致



发送自我的盖乐世



-------- 原始信息 --------
发件人： RukawaLee ***@***.***>
日期: 2023/2/25 17:59 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 协程示例代码报错 (Issue #502)


  1.  Autox.js 版本：636
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13
  4.  Android 机型：小米10s
  5.  Android 系统类别：MIUI14
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
17:55:58.782/E: Wrapped java.lang.IllegalStateException: Cannot capture continuation from JavaScript code not called directly by executeScriptWithContinuations or callFunctionWithContinuations (file:///android_asset/modules/__continuation__.js#12) Wrapped java.lang.IllegalStateException: Cannot capture continuation from JavaScript code not called directly by executeScriptWithContinuations or callFunctionWithContinuations at file:///android_asset/modules/__continuation__.js:12:0 at delay (/data/user/0/org.autojs.autoxjs.v6/files/sample/协程/协程HelloWorld/main.js:10:0) at /data/user/0/org.autojs.autoxjs.v6/files/sample/协程/协程HelloWorld/main.js:42:0
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by Rukawalee** [comment]
> 我没有调用截图，是app里面的 “示例/协程” 直接执行就报错了。
