### ISSUE TITLE
如果界面有多个id，能否也支持按id查找

### ISSUE THREAD

**Issue by linliyuan** [kkevsekk1/AutoX#504]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
看文档是不行的，但是其他类似的工具是可以做到的，比如easyclick是可以做到的。就是使用 id("xxxx").find() 找出多个，我觉得这个逻辑也没问题，这样子方便很多，不然有些节点信息没有其他标识信息可言的。

9. 报错日志（可选）：
10. 屏幕截图（可选）：、

**Comment by kkevsekk1** [comment]
这是什么问题？这都不支持还搞什么



发送自我的盖乐世



-------- 原始信息 --------
发件人： linliyuan ***@***.***>
日期: 2023/2/28 23:55 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 如果界面有多个id，能否也支持按id查找 (Issue #504)


  1.  Autox.js 版本：629

  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases

  3.  Android 版本：Android 10

  4.  Android 机型：小米10

  5.  Android 系统类别：MIUI

  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：

  7.  问题描述：
看文档是不行的，但是其他类似的工具是可以做到的，比如easyclick是可以做到的。就是使用 id("xxxx").find() 找出多个，我觉得这个逻辑也没问题，这样子方便很多，不然有些节点信息没有其他标识信息可言的。

  8.  报错日志（可选）：

  9.  屏幕截图（可选）：、

―
