### ISSUE TITLE
打包后安装显示安装包已损坏

### ISSUE THREAD

**Issue by linliyuan** [kkevsekk1/AutoX#507]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：realme GT、一加7
5. Android 系统类别：OPPO
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
    打包后安装显示安装包已损坏，但是直接执行是正常执行完成的
8. 报错日志（可选）：
9. 屏幕截图（可选）：

![image](https://user-images.githubusercontent.com/37769385/222418495-d7a43e38-a041-42ff-a138-615f782e3082.png)

**Comment by kkevsekk1** [comment]
这种不好搞



发送自我的盖乐世



-------- 原始信息 --------
发件人： linliyuan ***@***.***>
日期: 2023/3/2 19:40 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 打包后安装显示安装包已损坏 (Issue #507)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：realme GT、一加7
  5.  Android 系统类别：OPPO
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
打包后安装显示安装包已损坏，但是直接执行是正常执行完成的
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

[image]<https://user-images.githubusercontent.com/37769385/222418495-d7a43e38-a041-42ff-a138-615f782e3082.png>

―

**Comment by linliyuan** [comment]
有什么方案排查吗？我好像只是加了随机时间，接着就不行了，好奇怪，这打包有时可以打正常包，有时不行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 晚上7:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kkevsekk1/AutoX] 打包后安装显示安装包已损坏 (Issue #507)





 这种不好搞 
 
 
 
 发送自我的盖乐世 
 
 
 
 -------- 原始信息 -------- 
 发件人： linliyuan ***@***.***&gt; 
 日期: 2023/3/2 19:40 (GMT+08:00) 
 收件人： kkevsekk1/AutoX ***@***.***&gt; 
 抄送： Subscribed ***@***.***&gt; 
 主题： [kkevsekk1/AutoX] 打包后安装显示安装包已损坏 (Issue #507) 
 
 
   1.  Autox.js 版本：629 
   2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases 
   3.  Android 版本：Android 12 
   4.  Android 机型：realme GT、一加7 
   5.  Android 系统类别：OPPO 
   6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）： 
   7.  问题描述： 
 打包后安装显示安装包已损坏，但是直接执行是正常执行完成的 
   8.  报错日志（可选）： 
   9.  屏幕截图（可选）： 
 
 [image]<" rel="noopener" target="_blank">https://user-images.githubusercontent.com/37769385/222418495-d7a43e38-a041-42ff-a138-615f782e3082.png&gt;; 
 
 ―

**Comment by linliyuan** [comment]
这个找到原因了，目前打包包名不能加数字，不然打包会失败。

**Comment by kkevsekk1** [comment]
第一位不能加，还是任何位置都不能


发送自我的盖乐世



-------- 原始信息 --------
发件人： linliyuan ***@***.***>
日期: 2023/3/3 10:42 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 打包后安装显示安装包已损坏 (Issue #507)


这个找到原因了，目前打包包名不能加数字，不然打包会失败。

―

**Comment by stone009** [comment]
> 这个找到原因了，目前打包包名不能加数字，不然打包会失败。

我也是，搞了好久才发现~~

**Comment by Universe-hy** [comment]
为什么我删了数字还是没用

**Comment by Max20-23** [comment]
为什么我删了数字还是没用
