### ISSUE TITLE
Google play保护机制直接给卸载了

### ISSUE THREAD

**Issue by KamenRevice** [kkevsekk1/AutoX#508]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米MIX4
5. Android 系统类别：MIUI14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：直接被Google play商店保护机制卸载掉了，怎么解决
8. 报错日志（可选）：暂无日志
9. 屏幕截图（可选）：
![Screenshot_2023-03-02-20-22-28-090_com android vending](https://user-images.githubusercontent.com/36665957/222427883-6eac0909-a5a2-427e-b396-890ffe35609d.jpg)

**Comment by ObcbO** [comment]
刚才也直接把我的也给卸载了（ 于是我选择关闭play保护机制

**Comment by citronsky** [comment]
遇到了同样的问题
