### ISSUE TITLE
线程中无法进行找色

### ISSUE THREAD

**Issue by Alice000333** [kkevsekk1/AutoX#510]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：雷电模拟器9
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：不在线程中是正常的，在线程中找色会报错
8. 报错日志（可选）：
9. 00:52:14.456/E: Thread[ScriptThread-0[main.js] (Spawn-0),5]: No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:23)
	at com.stardust.autojs.core.opencv.Mat.<init>(Mat.java:37)
10. 屏幕截图（可选）：

**Comment by Alice000333** [comment]
是打包后无法在线程中执行，不打包的话是正常的。

**Comment by kkevsekk1** [comment]
模板app的sdk不支持



发送自我的盖乐世



-------- 原始信息 --------
发件人： Alice000333 ***@***.***>
日期: 2023/3/4 01:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 线程中无法进行找色 (Issue #510)


是打包后无法在线程中执行，不打包的话是正常的。

―

**Comment by zanxiaoyu** [comment]
> 是打包后无法在线程中执行，不打包的话是正常的。

@Alice000333 请问这个问题解决了吗？

**Comment by yuanlei-shishi** [comment]
有啥解决办法吗

**Comment by laugoon** [comment]
问题仍然存在
