### ISSUE TITLE
使用快速找图findImageInRegion，opencv报错

### ISSUE THREAD

**Issue by xuyuanbao** [kkevsekk1/AutoX#511]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：中兴努比亚Z40SPro
5. Android 系统类别：MyOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用快速找图findImageInRegion，opencv报错
8. 报错日志（可选）：
Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/core/src/matrix.cpp:250: error: (-215:Assertion failed) s >= 0 in function 'setSize'
] (file:///android_asset/modules/__images__.js#410)
Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/core/src/matrix.cpp:250: error: (-215:Assertion failed) s >= 0 in function 'setSize'
]
    at file:///android_asset/modules/__images__.js:410:0
10. 屏幕截图（可选）：

**Comment by x64life** [comment]
一样的问题，本机运行ok，云手机运行报这个问题
