### ISSUE TITLE
获取定时器失败

### ISSUE THREAD

**Issue by Greenplumwine** [kkevsekk1/AutoX#512]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米 MIX2
5. Android 系统类别：lineage 11
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
执行定时任务报错
"org.autojs.autojs.timing.TimedTaskManager" has no public instance field or method named "getInstance"
auto.js执行这个地方不会报错，但是使用autox.js执行报错，麻烦问一下这个这替换成什么
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/28561772/223043932-4d0df2e1-750b-4b18-9675-8f6a809cee14.png">

**Comment by knightofbatons** [comment]
~~var TimedTaskManager = is_pro ? timing.TimedTaskManager.Companion.getInstance() : timing.TimedTaskManager.getInstance();~~

var TimedTaskManager = timing.TimedTashTashManager.INSTANCE

（AutoX 的 TimedTaskManager 在 org.autojs.autojs.timing.TimedTaskManager）
