### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by gjmhmm8** [kkevsekk1/AutoX#514]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
Version: 635
Android: 31
java.lang.IndexOutOfBoundsException: 
android.graphics.BaseRecordingCanvas.drawText(BaseRecordingCanvas.java:716)
org.autojs.autojs.ui.edit.editor.CodeEditText.drawText(CodeEditText.java:288)
org.autojs.autojs.ui.edit.editor.CodeEditText.onDraw(CodeEditText.java:127)
android.view.View.draw(View.java:23450)
android.view.View.updateDisplayListIfDirty(View.java:22284)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
android.view.ViewRootImpl.draw(ViewRootImpl.java:5673)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5396)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4364)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2828)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10653)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
android.view.Choreographer.doCallbacks(Choreographer.java:1115)
android.view.Choreographer.doFrame(Choreographer.java:1004)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1362)
android.os.Handler.handleCallback(Handler.java:966)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:293)
android.app.ActivityThread.main(ActivityThread.java:9596)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**Comment by kkevsekk1** [comment]
用来绘图？你们用这个干什么？不是搞自动化，搞钱？



发送自我的盖乐世



-------- 原始信息 --------
发件人： gjmhmm8 ***@***.***>
日期: 2023/3/7 23:19 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 崩溃 (Issue #514)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
Version: 635
Android: 31
java.lang.IndexOutOfBoundsException:
android.graphics.BaseRecordingCanvas.drawText(BaseRecordingCanvas.java:716)
org.autojs.autojs.ui.edit.editor.CodeEditText.drawText(CodeEditText.java:288)
org.autojs.autojs.ui.edit.editor.CodeEditText.onDraw(CodeEditText.java:127)
android.view.View.draw(View.java:23450)
android.view.View.updateDisplayListIfDirty(View.java:22284)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
android.view.View.updateDisplayListIfDirty(View.java:22228)
android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
android.view.ViewRootImpl.draw(ViewRootImpl.java:5673)
android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5396)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4364)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2828)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10653)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
android.view.Choreographer.doCallbacks(Choreographer.java:1115)
android.view.Choreographer.doFrame(Choreographer.java:1004)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1362)
android.os.Handler.handleCallback(Handler.java:966)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loopOnce(Looper.java:205)
android.os.Looper.loop(Looper.java:293)
android.app.ActivityThread.main(ActivityThread.java:9596)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

―
