### ISSUE TITLE
636的下载地址访问不了呀！在哪下载呀

### ISSUE THREAD

**Issue by xicong** [kkevsekk1/AutoX#517]

**Comment by egerardoqd** [comment]
Seems like all the 636 tagged versions are pointing to the 635 version. I'm looking for this version too.

**Comment by kkevsekk1** [comment]
下载的就是636只是程序内部显示的6.3.5



发送自我的盖乐世



-------- 原始信息 --------
发件人： Erik Quispe ***@***.***>
日期: 2023/3/15 21:07 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 636的下载地址访问不了呀！在哪下载呀 (Issue #517)


Seems like all the 636 tagged versions are pointing to the 635 version. I'm looking for this version too.

―

**Comment by xicong** [comment]
了解了，谢谢
