### ISSUE TITLE
通过 id 选择器读取控件时常失效，exists() 方法返回false ，但是页面点一下布局分析后，又能正常找到。  但是通过text选择器是随时可以找到，不清楚id 选择器是否有bug

### ISSUE THREAD

**Issue by 15035162747** [kkevsekk1/AutoX#521]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by 15035162747** [comment]
把id 值传成 fullid的值就稳定了。 一步一坑

**Comment by kkevsekk1** [comment]
很多类似问题，多写，多分析就知道怎么处理了，一步分析问题，解决问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： www ***@***.***>
日期: 2023/3/14 18:11 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 通过 id 选择器读取控件时常失效，exists() 方法返回false ，但是页面点一下布局分析后，又能正常找到。 但是通过text选择器是随时可以找到，不清楚id 选择器是否有bug (Issue #521)


把id 值传成 fullid的值就稳定了。 一步一坑

―

**Comment by arkilis** [comment]
@15035162747 大佬分享一下如何选择一个控件，文档里面找不到

**Comment by kkevsekk1** [comment]
找教程示范



发送自我的盖乐世



-------- 原始信息 --------
发件人： Ben ***@***.***>
日期: 2023/4/26 10:44 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 通过 id 选择器读取控件时常失效，exists() 方法返回false ，但是页面点一下布局分析后，又能正常找到。 但是通过text选择器是随时可以找到，不清楚id 选择器是否有bug (Issue #521)


@15035162747<https://github.com/15035162747> 大佬分享一下如何选择一个控件，文档里面找不到

―

**Comment by arkilis** [comment]
@kkevsekk1 网上的教程跟跟这个AutoX好像不适用，比如这个：

```js
while(packageName("com.ss.android.ugc.aweme").text("Profile").exists()){
    toast("app started!")
};
```

**Comment by deep-project** [comment]
@arkilis 友情提示，那个id是会变的，所以你要换策略。

**Comment by wingswing1** [comment]
> @kkevsekk1 网上的教程跟跟这个AutoX好像不适用，比如这个报错：
> 
> ```js
> while(!(packageName("com.ss.android.ugc.aweme").id("afj").exists())){
> };
> ```

id代替为idEndsWith

**Comment by pharaoh2012** [comment]
将fullId显示的值作为id方法的参数调用。
`id("afj").exists()` 更改为：
`id("com.ss.android.ugc.aweme:id/afj")`
效果和 idEndsWith 一样。

**Comment by telppa** [comment]
我也遇到了，真是把人坑死……
