### ISSUE TITLE
连接autojs web control 报client close

### ISSUE THREAD

**Issue by hongyits** [kkevsekk1/AutoX#522]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：荣耀v30 pro
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：连接autojs web control一直报websock.Client close ip
8. 报错日志（可选）：
websock.Client close ip -> 1011 message->client failure

9. 屏幕截图（可选）：

**Comment by hongyits** [comment]
手机端是握手失败

**Comment by hongyits** [comment]
[5.7.7](https://github.com/kkevsekk1/AutoX/releases/tag/5.7.7) 这个版本就可以正常连接，最新版不行

**Comment by FlickerMi** [comment]
> [5.7.7](https://github.com/kkevsekk1/AutoX/releases/tag/5.7.7) 这个版本就可以正常连接，最新版不行

俺也一样，最新版还未解决

**Comment by mari1995** [comment]
没解决把

**Comment by mari1995** [comment]
> > [5.7.7](https://github.com/kkevsekk1/AutoX/releases/tag/5.7.7) 这个版本就可以正常连接，最新版不行
> 
> 俺也一样，最新版还未解决

现在解决了吗
