### ISSUE TITLE
发送系统广播没有效果

### ISSUE THREAD

**Issue by zaqai** [kkevsekk1/AutoX#526]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米mix2s
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：我需要发送系统广播来实现其他功能, 在autox中, 运行`app.sendBroadcast("light")`没有达到预期效果, 但是如果直接执行shell命令`am broadcast -a light`就可以达到预期效果. 所以是不是autox的发送系统广播存在bug, 还是我的写法不对?
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by zaqai** [comment]
ps: 我是用的termux执行的shell, 正常
用autox自带的shell命令执行提示权限不够, adb授予权限说autox没有请求这个权限(当然root执行正常)

11:26:53.959/D: ShellResult{code=255, error='Security exception: Permission Denial: broadcast asks to run as user -2 but is calling from uid u0a235; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS

Exception occurred while executing 'grant':
java.lang.SecurityException: Package org.autojs.autoxjs.v6 has not requested permission android.permission.INTERACT_ACROSS_USERS

**Comment by aiselp** [comment]
确实是权限不够，可我看termux也没声明这个权限呀

**Comment by nymanyim** [comment]
@kkevsekk1 版本658 通过app.sendbroadcast无法发送广播

**Comment by nymanyim** [comment]
@aiselp 发现新BUG，无法广播是因为在autojs默认会将广播的action前缀设置为android.intent.action.XXX，所以当我将action设置为一个name但是没有在其他应用或者接收器添加默认前缀，就无法接收到。其实这里的前缀没有必要，因为当action设置为一个自定义name时，是没有安卓前缀的，加上去反而会搞错

**Comment by nymanyim** [comment]
另外，通过广播启动的定时任务，无论怎样都会执行两次，这是bug还是什么情况吗，能否调整默认只执行一次
