### ISSUE TITLE
什么时候增加数据库功能

### ISSUE THREAD

**Issue by zhaoyanjoin** [kkevsekk1/AutoX#530]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：autojs中的数据库功能非常好用，什么时候可以调用过来呢。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by ximengxuan** [comment]
如果是操作mysql，可以使用后台语言，来编写api接口，供autox调用。直接操作数据库，是不安全的。

**Comment by zsg4399** [comment]
js要操作数据库也是用nodejs写服务端，然后你在调服务端来操作数据库的，把数据库直接暴露给客户端是极其不安全的行为
