### ISSUE TITLE
websocket 接收不到消息

### ISSUE THREAD

**Issue by fmxiaoke** [kkevsekk1/AutoX#534]
1. Autox.js 版本：636
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：websocket 接收不到消息
7. 问题描述：websocket 接收不到消息
8. 报错日志（可选）：websocket 接收不到消息
9. 屏幕截图（可选）：websocket 接收不到消息

**Comment by epiphyllum** [comment]
onMessage callback  never invoked.
