### ISSUE TITLE
files.create读取文件问题

### ISSUE THREAD

**Issue by chanben2005** [kkevsekk1/AutoX#536]
源码
```
console.show()
let save = files.create('/sdcard/aaa.txt')
console.log(save)
```

不论目录下**有没有该文件**，也只显示**true**

另外下载最新版本
https://github.com/kkevsekk1/AutoX/releases/tag/6.3.7
更新后的版本也是6.3.5这个是正常的?

谢谢

**Comment by kkevsekk1** [comment]
还是6.3.5？我改了配置啊！！！



发送自我的盖乐世


-------- 原始信息 --------
发件人： chanben2005 ***@***.***>
日期: 2023/4/10 03:17 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] files.create读取文件问题 (Issue #536)


源码

console.show()
let save = files.create('/sdcard/aaa.txt')
console.log(save)


不论目录下有没有该文件，也只显示true

另外下载最新版本
https://github.com/kkevsekk1/AutoX/releases/tag/6.3.7
更新后的版本也是6.3.5这个是正常的?

xx

―

**Comment by chanben2005** [comment]
我是从这个位置下载
![0eaff4541e662c3a32b5d17f2d86db7](https://user-images.githubusercontent.com/34121011/230809906-3448f70e-bdb2-4419-b39d-402be3b68cd6.jpg)


但版本号仍然是6.3.5
![b59529943205efeb3651440fac50e91](https://user-images.githubusercontent.com/34121011/230809912-23cb94ff-b09b-4e7c-ae28-92b4459f906f.jpg)

**Comment by kkevsekk1** [comment]
可能文件没改对，内容是已经升级过的了



发送自我的盖乐世



-------- 原始信息 --------
发件人： chanben2005 ***@***.***>
日期: 2023/4/10 09:53 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] files.create读取文件问题 (Issue #536)


我是从这个位置下载
[0eaff4541e662c3a32b5d17f2d86db7]<https://user-images.githubusercontent.com/34121011/230809906-3448f70e-bdb2-4419-b39d-402be3b68cd6.jpg>

但版本号仍然是6.3.5
[b59529943205efeb3651440fac50e91]<https://user-images.githubusercontent.com/34121011/230809912-23cb94ff-b09b-4e7c-ae28-92b4459f906f.jpg>

―
