### ISSUE TITLE
为什么我从你们提供的地址下载的最新版本都是显示6.3.5版本?

### ISSUE THREAD

**Issue by mogoyu** [kkevsekk1/AutoX#537]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：red mi note9 pro
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：为什么从你们提供的下载地址下载最新版本显示都是635就算是下637的安装后也是635是你们没有改版本号还是什么问题,我已经重复下载几次,并且都是删除原安装的版本在安装也是635,对了我是装在雷电模拟器的4的几的版本
![3333333333](https://user-images.githubusercontent.com/38188060/231039019-bf25534f-e81a-4b71-a5f1-e83e2c084296.png)

8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by nsy9601** [comment]
我也一样，下载6.3.6和6.3.7安装后还是6.3.5
