### ISSUE TITLE
悬浮窗中的按钮点击事件中 setInterval导致autojs卡死失效,只能停止autojs

### ISSUE THREAD

**Issue by 903352754** [kkevsekk1/AutoX#539]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases/download/6.3.7/app-v6-arm64-v8a-release-unsigned-signed.apk
3. Android 版本：Android 9
4. Android 机型：OPPO R11 Plus(夜神模拟器安卓9)
5. Android 系统类别：Android
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：悬浮窗中的按钮点击事件中 setInterval导致autojs卡死失效,只能停止autojs
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![image](https://user-images.githubusercontent.com/78247179/231345381-a8410436-ded0-48cf-a37f-2ee9d0fd8ccd.png)
![image](https://user-images.githubusercontent.com/78247179/231346290-f3b7d856-1550-4912-bbe5-59946a8689f7.png)

**Comment by aiselp** [comment]
那些事件回调都是在ui线程，建议另开线程弄别的操作
