### ISSUE TITLE
大神能不能对安卓11优化一下 

### ISSUE THREAD

**Issue by flashanky** [kkevsekk1/AutoX#54]
对安卓11完全支持不好 从悬浮菜单那打开控件完全是乱七八糟

**Comment by kkevsekk1** [comment]
? 没有测试过11 的机器

**Comment by flashanky** [comment]
就是控件布局分析那 试了试pro也是问题很多  主要是：
1。布局画的很乱
2. 经常卡死在那了
找出我的老手机试了试没什么问题，以后新手机都是安卓11了，期待后续版本越来越好

**Comment by kkevsekk1** [comment]
那，要后面 来调整
