### ISSUE TITLE
运行时间长了。device.width 返回0.重启后正常。

### ISSUE THREAD

**Issue by wgf4242** [kkevsekk1/AutoX#542]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：一加8T
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：

运行个几天就这样。其他功能正常。

**Comment by aiselp** [comment]
存到变量里不就好了吗

**Comment by polsnet** [comment]
我也遇到了同样的问题，除了自己存变量里。
可以彻底解决一下这个问题吗？应该好久的问题了，前几个月才发现，更新了几个版本发现这个问题一直存在。
