### ISSUE TITLE
打包不了

### ISSUE THREAD

**Issue by xiongjia2000** [kkevsekk1/AutoX#55]
能不能把打包的运行配置设为默认呢≥﹏≤

**Comment by kkevsekk1** [comment]
可以，你先用正式版，最近发上线新版本，包含默认设置



发送自我的盖乐世



-------- 原始信息 --------
发件人： xiongjia2000 ***@***.***>
日期: 2021/4/28 23:44 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 打包不了 (#55)


能不能把打包的运行配置设为默认呢≥n≤

―
