### ISSUE TITLE
使用storages put报错

### ISSUE THREAD

**Issue by ykf87** [kkevsekk1/AutoX#553]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用storages put报错。
Wrapped java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations
    at str (file:///android_asset/modules/__json2__.js:234:0)
    at file:///android_asset/modules/__storages__.js:20:0
    at /storage/emulated/0/脚本/av/main.js:30:0
    at file:///android_asset/modules/__bridges__.js:10:0
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by ykf87** [comment]
原因是 ui.url.getText() 获取的内容直接storages.put会报错
解决方法是：String(ui.url.getText()), 使用String后可以正常put了

**Comment by aiselp** [comment]
正常，json没法序列化java对象
