### ISSUE TITLE
Unresolved reference: ProjectConfigActivity_

### ISSUE THREAD

**Issue by ishangxue** [kkevsekk1/AutoX#555]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用andriod studio 构建项目时 报错 Unresolved reference: ProjectConfigActivity_，发现缺少这个文件啊，初次使用，求帮助 具体截图如下
9. 报错日志（可选）：
10. 屏幕截图（可选）：
![360截图20230427090228662](https://user-images.githubusercontent.com/36391679/234733857-de1ba519-444a-4d2d-b242-09c00a619b52.jpg)

**Comment by kkevsekk1** [comment]
这是自动生成的，你编译环境没搞好



发送自我的盖乐世



-------- 原始信息 --------
发件人： ishangxue ***@***.***>
日期: 2023/4/27 09:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] Unresolved reference: ProjectConfigActivity_ (Issue #555)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：使用andriod studio 构建项目时 报错 Unresolved reference: ProjectConfigActivity_，发现缺少这个文件啊，初次使用，求帮助 具体截图如下
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
[360截图20230427090228662]<https://user-images.githubusercontent.com/36391679/234733857-de1ba519-444a-4d2d-b242-09c00a619b52.jpg>

―

**Comment by ishangxue** [comment]
编译一次后解决，谢谢
