### ISSUE TITLE
runtime.loadDex() 对很多dex文件都不生效

### ISSUE THREAD

**Issue by happyme531** [kkevsekk1/AutoX#557]
1. Autox.js 版本：6.3.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：红魔5s
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本：nan
7. 问题描述：如题, runtime.loadDex() 对很多dex文件都不生效  
我在做一个项目，其中需要解析midi文件，这个用js实现似乎很麻烦所以考虑用java实现，但是测试过一些java开源库其中只有一个可以成功使用AutoXjs的runtime.loadDex()加载  
测试过的文件: [dex们.zip](https://github.com/kkevsekk1/AutoX/files/11359436/dex.zip)  
其中:  
android-midi-lib.dex(https://github.com/LeffelMania/android-midi-lib): 不生效  
javax.sound.midi.dex(https://github.com/kshoji/javax.sound.midi-for-Android): 不生效  
MidiReader.dex(https://github.com/bhaeussermann/MidiReader): 生效  
直接加载jar结果也是一样的  

8. 报错日志：adb logcat看不到任何报错(这很奇怪)  
9. 屏幕截图：null

已经有一些issue(如下)提到这个问题了，但至今没有问题明确的产生原因和解决方案。  

#492 
#5

**Comment by happyme531** [comment]
> 我来告诉你为什么，高于jdk1.8开发的jar包都不能使用，你可以找些老版本开发的jar包来用，这个只能等大佬后续更新了

我也考虑到了可能是Java版本不对造成的问题。所以修改配置把兼容性改成1.6  
```groovy
    compileOptions {
        sourceCompatibility "6"
        targetCompatibility "6"
    }
```
结果编译出来的jar包仍然不能用。  

测试时使用JDK1.8。也许真的一定需要低版本JDK？

**Comment by DspringL** [comment]
什么问题呀，真是必须是jdk1.8吗
