### ISSUE TITLE
打包app的建议

### ISSUE THREAD

**Issue by draw520** [kkevsekk1/AutoX#560]
可以优化一下打包让ui在splashActivity里运行吗，和pro一样，不然打开应用会跳转一下。还有希望打包提供不加密选项，有时候用apk编辑器改一些小bug方便一些，希望采纳，谢谢~
另外前几天提的[issue](https://github.com/kkevsekk1/AutoX/issues/558)实测了确实是一个bug

**Comment by kkevsekk1** [comment]
打包和加密没必然联系，你可以再研究一下，用webpack 也不是加密，是编译成一个文件，当然也支持多文件

**Comment by kkevsekk1** [comment]
打包和加密没必然联系，你可以再研究一下，用webpack 也不是加密，是编译成一个文件，当然也支持多文件

**Comment by draw520** [comment]
> 打包和加密没必然联系，你可以再研究一下，用webpack 也不是加密，是编译成一个文件，当然也支持多文件

![Screenshot_2023-05-06-21-38-49-093_bin.mt.plus-edit.jpg](https://user-images.githubusercontent.com/84522827/236627797-45c1f59a-e7b7-4a2f-ac4e-cb7e9e7ec208.jpg)

我说的不是webpack打包。截图是打包成apk里的项目文件，改成源代码运行不了，所以是加密而不是混淆吧。
