### ISSUE TITLE
打包后按钮的样式失效，示例”按钮控件“打包出来也没有样式。

### ISSUE THREAD

**Issue by byteslaves** [kkevsekk1/AutoX#565]
1. Autox.js 版本：6.3.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：按钮的三个样式都用不了，开始还以为我代码问题，但示例代码里面的”按钮控件“我打包出来也没有样式。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by yqchilde** [comment]
有同样的问题

**Comment by yqchilde** [comment]
> 有同样的问题

换到6.3.7暂时解决该问题
