### ISSUE TITLE
setClip无法使用

### ISSUE THREAD

**Issue by selene-y** [kkevsekk1/AutoX#566]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用方法setClip('test')后，没有错误提示，但是设置剪贴板不成功，但是getClip是可以正常获取到的

**Comment by kkevsekk1** [comment]
这个概率很低，或许是高版本手机？



发送自我的盖乐世



-------- 原始信息 --------
发件人： Selene ***@***.***>
日期: 2023/5/16 22:25 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] setClip无法使用 (Issue #566)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：使用方法setClip('test') 后，没有错误提示，但是设置剪贴板不成功

―

**Comment by jiumengs** [comment]
安卓10以上后台获取剪贴板都获取不到，有办法处理吗
