### ISSUE TITLE
RootAutomator()10系统无效

### ISSUE THREAD

**Issue by 5569866** [kkevsekk1/AutoX#569]
1. Autox.js 版本：[6.3.8]
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米6
5. Android 系统类别：魔趣
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. var ra = new RootAutomator();
//让"手指1"点击位置(100, 100)
ra.tap(100, 100, 1);
//让"手指2"点击位置(200, 200);
ra.tap(200, 200, 2);
ra.exit();

已给root权限。在10系统执行不点击。，试了不同手机结果一样。 RootAutomator.touchDown  RootAutomator.touchMove RootAutomator.touchUp 都没反应。 

9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by vipterry** [comment]
我也是同样小米6x的安卓10执行后没有反应，但是小米9的android11倒是可以，有解决到吗？

**Comment by Bob8259** [comment]
看看这个帖子，直接使用shell发送命令就可以。https://github.com/kkevsekk1/AutoX/issues/1207

**Comment by Bob8259** [comment]
可以参考这个issue，https://github.com/kkevsekk1/AutoX/issues/1207

**Comment by vipterry** [comment]
> 可以参考这个issue，#1207

非常感谢🙏
