### ISSUE TITLE
执行demo脚本的时候，脚本内不能引用其他脚本吗？

### ISSUE THREAD

**Issue by hallejuyahaha** [kkevsekk1/AutoX#57]
21:21:16.468/E: Error: Can't resolve relative module ID "./common.js" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./common.js" when require() is used outside of a module
    at Require (file:///android_asset/modules/jvm-npm.js:89:0)
    at [remote]main.js:2:0

**Comment by kkevsekk1** [comment]
可以，你的路径有问题，用webpack编译，编译后为单文件，或者将路径设置正确



发送自我的盖乐世



-------- 原始信息 --------
发件人： hallejuyahaha ***@***.***>
日期: 2021/5/2 21:24 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 执行demo脚本的时候，脚本内不能引用其他脚本吗？ (#57)


21:21:16.468/E: Error: Can't resolve relative module ID "./common.js" when require() is used outside of a module (file:///android_asset/modules/jvm-npm.js#89)
Error: Can't resolve relative module ID "./common.js" when require() is used outside of a module
at Require (file:///android_asset/modules/jvm-npm.js:89:0)
at [remote]main.js:2:0

―

**Comment by selene-y** [comment]
@hallejuyahaha 请问你的问题解决了吗，同样用这个方法`require('./xx.js')`引入同一目录下的其他文件报错。

**Comment by ishangxue** [comment]
@hallejuyahaha @kkevsekk1 @selene-y 请问解决了吗，我也出现了同样的错误，我是新建了一个项目，项目内同级目录引用，请教如何解决啊

**Comment by kkevsekk1** [comment]
这个可以确定是可以的，你检查路径



发送自我的盖乐世



-------- 原始信息 --------
发件人： ishangxue ***@***.***>
日期: 2023/4/10 17:19 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 执行demo脚本的时候，脚本内不能引用其他脚本吗？ (#57)


@hallejuyahaha<https://github.com/hallejuyahaha> @kkevsekk1<https://github.com/kkevsekk1> @selene-y<https://github.com/selene-y> 请问解决了吗，我也出现了同样的错误，我是新建了一个项目，项目内同级目录引用，请教如何解决啊

―

**Comment by zszzss** [comment]
请问你们怎么解决的，我也遇到了同样的问题

**Comment by kkevsekk1** [comment]
编译成一个



发送自我的盖乐世



-------- 原始信息 --------
发件人： zszzss ***@***.***>
日期: 2023/6/12 15:09 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] 执行demo脚本的时候，脚本内不能引用其他脚本吗？ (#57)


请问你们怎么解决的，我也遇到了同样的问题

―
