### ISSUE TITLE
ui.emitter.on生命周期监听

### ISSUE THREAD

**Issue by onlyWYY** [kkevsekk1/AutoX#571]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
使用ui.emitter.on时，无法监听activity的onDestroy生命周期事件，是否可以考虑在UI的onDestroy生命周期中添加emit("destroy")
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
什么场景这样用？我感觉没有必要
