### ISSUE TITLE
Android 13 每次截屏都弹窗询问，怎么实现点击开始后隔5秒截一张图？

### ISSUE THREAD

**Issue by binglingziyu** [kkevsekk1/AutoX#572]
1. Autox.js 版本：638
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米Pad 5
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

![Screenshot_2023-05-24-18-36-56-079_com android systemui](https://github.com/kkevsekk1/AutoX/assets/6101838/416564b9-7af3-4501-b8c6-cff5286546c3)

**Comment by kkevsekk1** [comment]
高版本系统没办法



发送自我的盖乐世



-------- 原始信息 --------
发件人： binglingziyu ***@***.***>
日期: 2023/5/24 18:40 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] Android 13 每次截屏都弹窗询问，怎么实现定时截图？ (Issue #572)


  1.  Autox.js 版本：638
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13
  4.  Android 机型：小米Pad 5
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

[Screenshot_2023-05-24-18-36-56-079_com android systemui]<https://user-images.githubusercontent.com/6101838/240577275-416564b9-7af3-4501-b8c6-cff5286546c3.jpg>

―

**Comment by MkSui** [comment]
You can also use adb to manually give input permission prior to app start via adb shell settings put secure enabled_accessibility_services net.christianbeier.droidvnc_ng/.InputService:$(adb shell settings get secure enabled_accessibility_services).
