### ISSUE TITLE
手机横屏截屏坐标的问题

### ISSUE THREAD

**Issue by zanxiaoyu** [kkevsekk1/AutoX#576]
我的手机分辨率1080*2400
手机横屏时调用click传入的坐标是2400*1080分辨率下的，但是调用images.captureScreen()，截图还是1080*2400的。
比如我要写横屏手游的脚本，要用区域找色，我在横屏下的区域坐标和宽高，在截图中找会出问题，这如何解决？
通过调用images.captureScreen()保存的截图是1080*2400px的，手机截图的是2400*1080px。怎么处理？

**Comment by kkevsekk1** [comment]
接口有参数控制



发送自我的盖乐世



-------- 原始信息 --------
发件人： zanxiaoyu ***@***.***>
日期: 2023/6/2 18:23 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 手机横屏截屏坐标的问题 (Issue #576)


我的手机分辨率10802400
手机横屏时调用click传入的坐标是24001080分辨率下的，但是调用images.captureScreen()，截图还是10802400的。
比如我要写横屏手游的脚本，要用区域找色，我在横屏下的区域坐标和宽高，在截图中找会出问题，这如何解决？
通过调用images.captureScreen()保存的截图是10802400px的，手机截图的是2400*1080px。怎么处理？

―

**Comment by zanxiaoyu** [comment]
@kkevsekk1 请问是哪个参数？我看captureScreen方法只能传path参数

**Comment by kkevsekk1** [comment]
申请权限的时候
________________________________
发件人: zanxiaoyu ***@***.***>
发送时间: 2023年6月2日 11:29
收件人: kkevsekk1/AutoX ***@***.***>
抄送: aaron ***@***.***>; Mention ***@***.***>
主题: Re: [kkevsekk1/AutoX] 手机横屏截屏坐标的问题 (Issue #576)


@kkevsekk1<https://github.com/kkevsekk1> 请问是哪个参数？我看captureScreen方法只能传path参数

―

**Comment by cerolluo** [comment]
@kkevsekk1 申请截图权限时使用横屏，但是如果被操作的软件横竖屏都会用到，这时竖屏图就不行了，这种有办法吗
