### ISSUE TITLE
小米8 运行home() 后返回APP被动刷新了

### ISSUE THREAD

**Issue by GitHub-ZYP** [kkevsekk1/AutoX#578]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米8
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：主程序APP，首先运行home()；然后去跑其他APP，运行之后返回，主程序的APP会更新，查了下资料；说是要修改androidmanifest.xml => android:allowTaskReparenting="true" . autopro之前可以通过project.json 进行配置，autox看文档找不到接口，请问是还没开放接口出来还是可以直接用autopro 的配置

**Comment by GitHub-ZYP** [comment]
@kkevsekk1 博主，我后来又看了文档，说是apk编辑器，手动给权限，我反编译后重新打包签名，可以安装，但是打不开...

![46bd95e0181f33dbff4f2af3ab01a5e](https://github.com/kkevsekk1/AutoX/assets/31816277/0c282e47-b456-42cb-ba47-07eeb07fc7a3)

**Comment by ximengxuan** [comment]
我也遇到这个问题，home后，打包的程序会重启...怎么破？

**Comment by GitHub-ZYP** [comment]
提示用户把APP放在home页面，或者下方快捷栏，然后打开的话就不会重启了~ 一个解决方案
