### ISSUE TITLE
Integrate with socket.io?

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#58]
Hi, could I use websocket with socket.io?

**Comment by kkevsekk1** [comment]
with okhttp



发送自我的盖乐世



-------- 原始信息 --------
发件人： anhnhoktvn ***@***.***>
日期: 2021/5/4 01:20 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] Integrate with socket.io? (#58)


Hi, could I use websocket with socket.io?

―
