### ISSUE TITLE
0.2加0.1等于 0.30000000000000004?

### ISSUE THREAD

**Issue by YINGXINGHUA** [kkevsekk1/AutoX#581]
1. Autox.js 版本：638
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：雷电9
4. Android 机型：雷电9
5. Android 系统类别：雷电9
6. 问题描述：我不是故意，我只不是很理解，0.2加0.1等于 0.30000000000000004?这个细节在我设置cardElevation值时会闪退。
7. 调试代码：
var i=0
while(i<1){
    console.log(i)
    sleep(200)
    i+=0.1
}
8. 报错日志：
22:38:14.081/V: 开始运行[[remote]test1.js]
22:38:14.083/D: 0
22:38:14.291/D: 0.1
22:38:14.499/D: 0.2
22:38:14.728/D: 0.30000000000000004
22:38:14.956/D: 0.4
22:38:15.237/D: 0.5
22:38:15.439/D: 0.6
22:38:15.736/D: 0.7
22:38:15.970/D: 0.7999999999999999
22:38:16.258/D: 0.8999999999999999
22:38:16.558/D: 0.9999999999999999

**Comment by yezie** [comment]
javascript语言就是这样，哈哈，需要自己Math.round

**Comment by aboutZZ** [comment]
建议先学习下编程基础
