### ISSUE TITLE
建议：提供通过scheme运行指定脚本文件的功能。

### ISSUE THREAD

**Issue by pharaoh2012** [kkevsekk1/AutoX#582]
可以通过scheme运行指定的脚本文件，外部程序或网页可以通过类似下列链接执行某一脚本，便于与其他工具配合。
示例下列链接：
`autoxrun://sdcard/autox/script.js?a=b&c=d`
实现下列脚本的功能。
```js
engines.execScriptFile('/sdcard/autox/script.js',{
  arguments:{
    a:"b",
    c:"d"
  }
})
```

技术上应该没问题，下面是一个简单参考：
[Android 使用URL链接打开App](https://www.jianshu.com/p/4308a523a941)

**Comment by kkevsekk1** [comment]
用广播，intent 直接启动，比你说的好用

**Comment by pharaoh2012** [comment]
* 新版本我用intent启动出错，见：
<https://github.com/kkevsekk1/AutoX/issues/585#issue-1754956963>
* scheme是可以在网页中通过浏览器打开的，intent 在这些场景是无法实现的。

**Comment by kkevsekk1** [comment]
场景，不是说功能



发送自我的盖乐世



-------- 原始信息 --------
发件人： pharaoh2012 ***@***.***>
日期: 2023/6/19 14:09 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, State change ***@***.***>
主题： Re: [kkevsekk1/AutoX] 建议：提供通过scheme运行指定脚本文件的功能。 (Issue #582)


  *   新版本我用intent启动出错，见：
#585 (comment)<https://github.com/kkevsekk1/AutoX/issues/585#issue-1754956963>
  *   scheme是可以在网页中通过浏览器打开的，intent 在这些场景是无法实现的。

―

**Comment by pharaoh2012** [comment]
我写了一个简单的示例，在手机上用浏览器访问示例链接，可以直接调用支付宝的各种功能。
我希望也能通过链接调用autox运行脚本，例如618，我写了个`京东618.js`的脚本，可以很方便的添加到这个页面中，
618过了，我直接将html中内容注释了即可，js脚本文件可以留着下次活动修改一下运行。

* [示例](https://htmlpreview.github.io/?https://github.com/pharaoh2012/test/blob/master/test.html)
  
* [示例源代码](https://raw.githubusercontent.com/pharaoh2012/test/master/test.html)

实际上RunIntentActivity本来就用的scheme方式，只是file和content太通用了，很多软件都实现了，不指定packagename，会让你选择一个软件运行，在`AndroidManifest.xml`中添加`<data android:scheme="autoxrun" />`就行了，只是我这里没有android的编译环境，没办法测试。
![1687160099473](https://github.com/kkevsekk1/AutoX/assets/2225220/e724acbf-2040-4717-a488-1dc91a8e15b5)

**Comment by kkevsekk1** [comment]
你可以自己测试，通过url传一段复杂js过去，看看效果，再说



发送自我的盖乐世



-------- 原始信息 --------
发件人： pharaoh2012 ***@***.***>
日期: 2023/6/19 15:42 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, State change ***@***.***>
主题： Re: [kkevsekk1/AutoX] 建议：提供通过scheme运行指定脚本文件的功能。 (Issue #582)


我写了一个简单的示例，在手机上用浏览器访问示例链接，可以直接调用支付宝的各种功能。
我希望也能通过链接调用autox运行脚本，例如618，我写了个京东618.js的脚本，可以很方便的添加到这个页面中，
618过了，我直接将html中内容注释了即可，js脚本文件可以留着下次活动修改一下运行。

  *   示例<https://htmlpreview.github.io/?https://github.com/pharaoh2012/test/blob/master/test.html>

  *   示例源代码<https://raw.githubusercontent.com/pharaoh2012/test/master/test.html>

实际上RunIntentActivity本来就用的scheme方式，只是file和content太通用了，很多软件都实现了，不指定packagename，会让你选择一个软件运行，在AndroidManifest.xml中添加<data android:scheme="autoxrun" />就行了，只是我这里没有android的编译环境，没办法测试。
[1687160099473]<https://user-images.githubusercontent.com/2225220/246759156-e724acbf-2040-4717-a488-1dc91a8e15b5.jpg>

―

**Comment by kkevsekk1** [comment]
如果你说的传个文件名过去，文件都能搞进去了，还搞这么复杂？



发送自我的盖乐世



-------- 原始信息 --------
发件人： pharaoh2012 ***@***.***>
日期: 2023/6/19 15:42 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, State change ***@***.***>
主题： Re: [kkevsekk1/AutoX] 建议：提供通过scheme运行指定脚本文件的功能。 (Issue #582)


我写了一个简单的示例，在手机上用浏览器访问示例链接，可以直接调用支付宝的各种功能。
我希望也能通过链接调用autox运行脚本，例如618，我写了个京东618.js的脚本，可以很方便的添加到这个页面中，
618过了，我直接将html中内容注释了即可，js脚本文件可以留着下次活动修改一下运行。

  *   示例<https://htmlpreview.github.io/?https://github.com/pharaoh2012/test/blob/master/test.html>

  *   示例源代码<https://raw.githubusercontent.com/pharaoh2012/test/master/test.html>

实际上RunIntentActivity本来就用的scheme方式，只是file和content太通用了，很多软件都实现了，不指定packagename，会让你选择一个软件运行，在AndroidManifest.xml中添加<data android:scheme="autoxrun" />就行了，只是我这里没有android的编译环境，没办法测试。
[1687160099473]<https://user-images.githubusercontent.com/2225220/246759156-e724acbf-2040-4717-a488-1dc91a8e15b5.jpg>

―

**Comment by pharaoh2012** [comment]
我一直用intent实现的相关功能，只是新版本用intent出错了，我继续用老版本就行了。
