### ISSUE TITLE
org.mozilla.javascript.EvaluatorException: illegal character: � (/data/user/0/com.dke/files/project/service/heartBeat.js#1)

### ISSUE THREAD

**Issue by miniphper** [kkevsekk1/AutoX#586]
1. Autox.js 版本：641
2. Autox.js 下载渠道：自己打包的
3. Android 版本：Android 12
4. Android 机型：华为荣耀
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：app打包之后，无法启动。（637和638版本都正常）
8. 报错日志（可选）：org.mozilla.javascript.EvaluatorException: illegal character: � (/data/user/0/com.dke/files/project/service/heartBeat.js#1)
9. 屏幕截图（可选）：

**Comment by miniphper** [comment]
应该是生成的template.apk文件有问题。我尝试了637版本，然后使用的641版本生成的template.apk。还是存在闪退问题。未打包的情况下，都是可以正常运行的。

**Comment by onlyWYY** [comment]
之前在群里问过这个问题，有大佬知道怎么修复一下吗？
