### ISSUE TITLE
6.4.1版本编译运行后闪退，6.3.7版本一切正常

### ISSUE THREAD

**Issue by andyhuu666** [kkevsekk1/AutoX#588]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
5. 问题描述：
同样的代码用新版6.4.1在app里运行正常，但编译安装后运行，闪退。6.3.7版本一切正常。后发现是运行到：require('abc.js')闪退，试了改路径，还是闪退。请问是啥情况？

**Comment by kkevsekk1** [comment]
可能在编译打包的apk里没有实现对于api
________________________________
发件人: andyhuu666 ***@***.***>
发送时间: 2023年6月14日 2:34
收件人: kkevsekk1/AutoX ***@***.***>
抄送: Subscribed ***@***.***>
主题: [kkevsekk1/AutoX] 6.4.1版本编译运行后闪退，6.3.7版本一切正常 (Issue #588)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  5.  问题描述：
同样的代码用新版6.4.1在app里运行正常，但编译安装后运行，闪退。6.3.7版本一切正常。后发现是运行到：require('abc.js')闪退，试了改路径，还是闪退。请问是啥情况？

―

**Comment by andyhuu666** [comment]
谢谢你的回答。不是太明白你的意思，你的意思就是：6.4.1版编译不支持 require 吗？
另，我的代码里有许多 require，用前面的版本编译成Apk并安装后，运行都正常。用以前的 AutoJs8 也正常。

**Comment by aiselp** [comment]
已经查明原因是因为打包后的js文件默认处于加密状态，新的模块加载器未考虑到文件加密的情况而导致，将会尽快修复

**Comment by andyhuu666** [comment]
感谢！

**Comment by andyhuu666** [comment]
感谢！

**Comment by andyhuu666** [comment]
//==============================================================

main.js内容如下：

toast('aaaaaaaaaaaa')
log('1111111')

let objAbc = require('abc')

toast('bbbbbbbbbbbbb')
log('222222')

objAbc.callAbc()

toast('ccccccccccccccc')
log('333333333')

//==========================================

abc.js内容如下：

let callAbc = () => {
  toast('this is abc.js')
  log('this is abc.js')
}


let abc = {
  callAbc: callAbc
}
module.exports = abc

//====================================

6.4.1版本在 MIUI12 Android 11的机器上可，最后Log显示是：333333333
；但在Android 10 Mokee，还是老样子，不行，最后Log显示是：1111111

**Comment by andyhuu666** [comment]
新开个Issue

**Comment by andyhuu666** [comment]
新开个Issue
