### ISSUE TITLE
打包之后，启动app会有一个闪退的现象，不知道能不能处理一下

### ISSUE THREAD

**Issue by miniphper** [kkevsekk1/AutoX#589]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：点击打包后的app，启动的时候会有一个闪退现象。这个现象各个版本都有，不知道是否能够解决
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by zbrongyaozb** [comment]
试试打包时候自定义个签名
