### ISSUE TITLE
华为报病毒“a.gray.GmPluginTools”

### ISSUE THREAD

**Issue by miniphper** [kkevsekk1/AutoX#594]
1. Autox.js 版本：643
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：鸿蒙3.0.0
4. Android 机型：华为 荣耀 x10
5. Android 系统类别：华为
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：打包的app被华为报病毒“a.gray.GmPluginTools”，切换到637版本打包正常
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by jkqxl** [comment]
同样的问题。
从库安上找了个 6.3.8 的安装包没问题，然后从 Github下载更新了最新的 4.6.3 就出现问题了

网上查了下，有些人说是 腾讯误报，本人未验证，其解决办法是 到腾讯那里申诉下（治标）：
https://m.qq.com/complaint?code=E6F7DDC2B442E90519ED37755CD35595&state=mqq
具体流程：https://www.zhihu.com/question/457157256

电脑报毒，知根知底的无视即可，但手机报毒，就很麻烦了，很多时候不只是无法安装的问题，经常会弹窗提示，巨烦人。
可能是腾讯抽风，要是作者嫌麻烦，那等待下个版本再看看吧，一两个版本影响也不大。

**Comment by idiomer** [comment]
xiaomi同样报毒，当前最新的643和642都试了，最终还是安装了637

**Comment by kkevsekk1** [comment]
这个意思就是你装的是，灰产工具，那你觉得呢？



发送自我的盖乐世



-------- 原始信息 --------
发件人： idiomer ***@***.***>
日期: 2023/6/30 10:02 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 华为报病毒“a.gray.GmPluginTools” (Issue #594)


xiaomi同样报毒，当前最新的643和642都试了，最终还是安装了637

―

**Comment by idiomer** [comment]
peace，没有其它意思，就是备份记录下安装过程的版本选择而已
