### ISSUE TITLE
客户端报错E: Function importClass must be called with a class; had "[JavaPackage java.util.concurrent.CompletableFuture]" instead. 

### ISSUE THREAD

**Issue by idersec** [kkevsekk1/AutoX#597]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 6
4. Android 机型：VIVO
5. Android 系统类别：funtouch
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：什么都运行不了，直接报错。电脑上vscode执行不了，后来在app上新建一个文件，运行toast("hello")，也报错
E: Function importClass must be called with a class; had "[JavaPackage java.util.concurrent.CompletableFuture]" instead. (<init>#14)
Function importClass must be called with a class; had "[JavaPackage java.util.concurrent.CompletableFuture]" instead.
    at <init>:14:0
    at /android_asset/modules/npm/stream.js:5:0
    at /android_asset/modules/npm/event-stream.js:954:0
    at __nccwpck_require__ (/android_asset/modules/npm/event-stream.js:988:0)
    at /android_asset/modules/npm/event-stream.js:119:0
    at __nccwpck_require__ (/android_asset/modules/npm/event-stream.js:988:0)
    at /android_asset/modules/npm/event-stream.js:9:0
    at __nccwpck_require__ (/android_asset/modules/npm/event-stream.js:988:0)
    at /android_asset/modules/npm/event-stream.js:1008:0
    at /android_asset/modules/npm/event-stream.js:1:0
    at /android_asset/modules/npm/process.js:4:0
    at <init>:59:0
    at <init>:5:0
9. 报错日志（可选）：日志里也是这样的
10. 屏幕截图（可选）：

**Comment by ghj1976** [comment]
我用MuMu模拟器，也碰到这个错误了， 最新的 6.4.3
