### ISSUE TITLE
bug.k40g自动关机

### ISSUE THREAD

**Issue by daoif** [kkevsekk1/AutoX#603]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：k40g
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：给了root权限，开机后第一次解锁屏幕，在10秒内，黑屏，出现转圈，自动关机。
8. 反复尝试多次，依然如此，即使禁用了root权限，还是没效果。
9. 最后趁着这10秒时间卸载掉了autoxjs，再一次启动后手机恢复正常。在安装autoxjs之前，从未出现过这种情况，过去也曾安装过低版本autojs，没有问题。
10. 报错日志（可选）：
11. 屏幕截图（可选）：

**Comment by daoif** [comment]
补充:安装这个版本后,NFC也出现了问题,在此之前也是从未出现过这种情况.
卸载后重启,NFC恢复正常.

**Comment by maki-nagisa** [comment]
我也发生过nfc问题 安卓版本低 通过安装旧版本解决的
