### ISSUE TITLE
captureScreen()函数频繁堵塞

### ISSUE THREAD

**Issue by xjqm-tao** [kkevsekk1/AutoX#611]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：红米note 11t pro
5. Android 系统类别：MIUI 14.0.3
7. 问题描述：
captureScreen()函数频发堵塞，一旦发生，结束脚本重运行脚本也不能恢复，继续堵塞。除非结束Autox.js的运行再打开Autox.js才有一定几率恢复正常。在一加6t（安卓10）上没这个问题

**Comment by lll862** [comment]
调试过程中遇到过，用的vscode，只有在手机端断开连接，再重新连接后才能继续正常执行
