### ISSUE TITLE
本可以找到的控件，会出现偶尔找不到的情况

### ISSUE THREAD

**Issue by lll862** [kkevsekk1/AutoX#612]
1. Autox.js 版本：628
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 7
4. Android 机型：华为p10
5. Android 系统类别：EMUI 9.1.0
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
部分控件会出现时而找的到时而找不到的奇幻现象。
如果这个控件突然找不到了，这个时候我使用手机auto悬浮窗——布局范围分析，之后再运行脚本，这个控件又能够正常找到了？？？有什么方式在脚本内执行类似悬浮窗的布局范围分析吗？或者避免这样的问题呢？

**Comment by TKWei** [comment]
app.sendBroadcast("inspect_layout_bounds");
试试这样？

**Comment by S-lonng** [comment]
我也遇到了这种情况，求解

**Comment by tonghuanming** [comment]
同样遇到这种情况，这个广播可以除法布局分析，重新刷新控件列表么？

> app.sendBroadcast("inspect_layout_bounds"); 试试这样？

**Comment by tonghuanming** [comment]
> app.sendBroadcast("inspect_layout_bounds");

测试过确实可用 但是每次布局刷新前 要触发一次布局分析广播 再back()取消掉  有点费事  不过总算暂时能解决
