### ISSUE TITLE
唤醒屏幕并解锁的定时脚本需要手动解锁解锁屏幕以后才运行

### ISSUE THREAD

**Issue by 0cafe** [kkevsekk1/AutoX#614]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米8Lite
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：写了一个脚本大致功能是：唤醒并上滑解锁屏幕然后继续一系列操作，autoxjs应用里给这个脚本设置了定时任务，两三个小时的能够正确自动解锁并执行，但是时间过比较久的话就不会执行了，我把手机手动解锁以后那个定时任务才开始执行。这个是问题帮忙看看。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
你用谷歌正版系统就没有这个问题😂



发送自我的盖乐世



-------- 原始信息 --------
发件人： 0cafe ***@***.***>
日期: 2023/6/29 11:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 唤醒屏幕并解锁的定时脚本需要手动解锁解锁屏幕以后才运行 (Issue #614)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米8Lite
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：写了一个脚本大致功能是：唤醒并上滑解锁屏幕然后继续一系列操作，autoxjs应用里给这个脚本设置了定时任务，两三个小时的能够正确自动解锁并执行，但是时间过比较久的话就不会执行了，我把手机手动解锁以后那个定时任务才开始执行。这个是问题帮忙看看。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

**Comment by 0cafe** [comment]
> 

只有这个方法了吗，大佬

**Comment by aabolo** [comment]
我也碰到这个问题了，之前用着都正常的，可以亮屏。
换了个手机之后，现在没法用了，这导致没法自动解锁手机了，麻烦。

**Comment by aabolo** [comment]
经过我的摸索，发现可以使用tasker实现亮屏，接下来的操作使用autojs实现即可。

**Comment by zlhdd108** [comment]
> 你用谷歌正版系统就没有这个问题😂 

大佬，问一下，我用三星的S10+国行，OneUI4.1，Android 12，也是这个问题；如果是息屏（锁屏）1~2小时内可以正常亮屏+解锁的；时间再长了，就无法亮屏了，可以看到定时任务里面的积压，亮屏后就可以继续执行了。看到定时任务有三种调度方式，是不是需要修改调度方式呢？

**Comment by kkevsekk1** [comment]
可以配置，白名单，电量策略。这是很常见的问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： LonelyHao ***@***.***>
日期: 2024/2/21 13:40 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 唤醒屏幕并解锁的定时脚本需要手动解锁解锁屏幕以后才运行 (Issue #614)


你用谷歌正版系统就没有这个问题😂

大佬，问一下，我用三星的S10+国行，OneUI4.1，Android 12，也是这个问题；如果是息屏（锁屏）1~2小时内可以正常亮屏+解锁的；时间再长了，就无法亮屏了，可以看到定时任务里面的积压，亮屏后就可以继续执行了。看到定时任务有三种调度方式，是不是需要修改调度方式呢？

**Comment by zlhdd108** [comment]
> 可以配置，白名单，电量策略。这是很常见的问题 发送自我的盖乐世
电量配置已经设置为“无限制”并且开启“自动启动”了

**Comment by ZJRui** [comment]
> > 你用谷歌正版系统就没有这个问题😂
> 
> 大佬，问一下，我用三星的S10+大陆行，OneUI4.1，Android 12，也是这个问题；如果是息屏（锁屏）1~2小时内可以正常亮屏+解锁的；时间再长了，就无法亮屏了，可以看到定时任务里面的积压，亮屏后就可以继续执行了。看到定时任务有三种调度方式，是不是需要修改调度方式呢？ 我的屏幕唤醒用的是`device.wakeUp()`


你这个问题解决了吗？ 我也是WorkManager 每天预定时间点执行任务， 息屏状态下定时任务没有执行，一旦唤醒屏幕，任务就开始执行解锁和正常操作。

**Comment by zlhdd108** [comment]
没办法，试了好多；定多个任务，有时间后面的能执行，比如8点，8:15，8:30，可能8:15和8:30的能执行，但是第一个不行，看日志能看到卡住了

sachin ***@***.***> 于 2024年3月2日周六 12:34写道：

**Comment by zlhdd108** [comment]
> > > 你用谷歌正版系统就没有这个问题😂
> > 
> > 
> > 大佬，问一下，我用三星的S10+大陆行，OneUI4.1，Android 12，也是这个问题；如果是息屏（锁屏）1~2小时内可以正常亮屏+解锁的；时间再长了，就无法亮屏了，可以看到定时任务里面的积压，亮屏后就可以继续执行了。看到定时任务有三种调度方式，是不是需要修改调度方式呢？ 我的屏幕唤醒用的是`device.wakeUp()`
> 
> 你这个问题解决了吗？ 我也是WorkManager 每天预定时间点执行任务， 息屏状态下定时任务没有执行，一旦唤醒屏幕，任务就开始执行解锁和正常操作。

ADB关闭“打盹模式”，目前看是正常的，还是三星的国航操作的

**Comment by asqwe1** [comment]
通过macrodroid定时亮屏，发送intent，调动autoxjs的广播任务
