### ISSUE TITLE
APP崩溃，日志如下

### ISSUE THREAD

**Issue by RajanZhan** [kkevsekk1/AutoX#618]
1. Autox.js 版本：643
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米9
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
 
APP的崩溃日志
Version: 643
Android: 30
java.lang.IllegalStateException: Fragment ScriptListFragment{73ae8af} (c7823ad0-cca9-461a-be5a-a5846daa724e) not attached to a context.
androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
org.autojs.autojs.ui.main.scripts.ScriptListFragment$explorerView$2.invoke(ScriptListFragment.kt:55)
org.autojs.autojs.ui.main.scripts.ScriptListFragment$explorerView$2.invoke(ScriptListFragment.kt:55)
kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
org.autojs.autojs.ui.main.scripts.ScriptListFragment.getExplorerView(ScriptListFragment.kt:55)
org.autojs.autojs.ui.main.MainActivity$onCreate$1$1$1$permission$1.invoke(MainActivity.kt:89)
org.autojs.autojs.ui.main.MainActivity$onCreate$1$1$1$permission$1.invoke(MainActivity.kt:87)
org.autojs.autojs.ui.main.MainActivityKt$rememberExternalStoragePermissionsState$1.invoke(MainActivity.kt:244)
org.autojs.autojs.ui.main.MainActivityKt$rememberExternalStoragePermissionsState$1.invoke(MainActivity.kt:238)
com.google.accompanist.permissions.MutableMultiplePermissionsStateKt$rememberMutableMultiplePermissionsState$launcher$1.invoke(MutableMultiplePermissionsState.kt:61)
com.google.accompanist.permissions.MutableMultiplePermissionsStateKt$rememberMutableMultiplePermissionsState$launcher$1.invoke(MutableMultiplePermissionsState.kt:57)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.invoke$lambda-0(ActivityResultRegistry.kt:106)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.$r8$lambda$dCDOHypJPJiF_gC4kcw2C1QNWFU(Unknown Source:0)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:2)
androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:406)
androidx.activity.ComponentActivity$2$1.run(ComponentActivity.java:188)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:236)
android.app.ActivityThread.main(ActivityThread.java:8060)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

麻烦大神解决

9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by wanZzz6** [comment]
遇到了同样的问题，不太懂Andriod，AI的给的解决办法是如下，不知道对不对

```kotlin
class ScriptListFragment : Fragment() {
    // ...
    override fun onDestroy() {
        super.onDestroy()
        
        if (isAdded()) {
            requireContext().unbindService(this)
            requireContext().stopService(this)
            detach()
        }
    }
    // ...
}
```

**Comment by LYS86** [comment]
设备信息: 
App version: 6.5.5
App version code: 655
Android build version: V12.0.1.0.PCHCNXM
Android release version: 9
Android SDK version: 28
Android build ID: PKQ1.181007.001
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: jason
Device model: Mi Note 3
Device product name: jason
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
java.lang.IllegalStateException: Fragment ScriptListFragment{2219088} (61a6da6e-ed16-4d4c-bc33-6ee93d76afe3) not attached to a context.
androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
org.autojs.autojs.ui.main.scripts.ScriptListFragment$explorerView$2.invoke(ScriptListFragment.kt:58)
org.autojs.autojs.ui.main.scripts.ScriptListFragment$explorerView$2.invoke(ScriptListFragment.kt:58)
kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
org.autojs.autojs.ui.main.scripts.ScriptListFragment.getExplorerView(ScriptListFragment.kt:58)
org.autojs.autojs.ui.main.MainActivity$onCreate$1$1$1$permission$1.invoke(MainActivity.kt:91)
org.autojs.autojs.ui.main.MainActivity$onCreate$1$1$1$permission$1.invoke(MainActivity.kt:89)
org.autojs.autojs.ui.main.MainActivityKt$rememberExternalStoragePermissionsState$1.invoke(MainActivity.kt:246)
org.autojs.autojs.ui.main.MainActivityKt$rememberExternalStoragePermissionsState$1.invoke(MainActivity.kt:240)
com.google.accompanist.permissions.MutableMultiplePermissionsStateKt$rememberMutableMultiplePermissionsState$launcher$1.invoke(MutableMultiplePermissionsState.kt:61)
com.google.accompanist.permissions.MutableMultiplePermissionsStateKt$rememberMutableMultiplePermissionsState$launcher$1.invoke(MutableMultiplePermissionsState.kt:57)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.invoke$lambda-0(ActivityResultRegistry.kt:106)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1.$r8$lambda$dCDOHypJPJiF_gC4kcw2C1QNWFU(Unknown Source:0)
androidx.activity.compose.ActivityResultRegistryKt$rememberLauncherForActivityResult$1$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:2)
androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:406)
androidx.activity.ComponentActivity$2$1.run(ComponentActivity.java:188)
android.os.Handler.handleCallback(Handler.java:873)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:201)
android.app.ActivityThread.main(ActivityThread.java:6810)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
