### ISSUE TITLE
获取当前活动异常。

### ISSUE THREAD

**Issue by himno** [kkevsekk1/AutoX#62]
这个问题从原作者的时候就遗留下来了。悬浮按钮点开后，有个齿轮图标，可以查看当前活动的名字。在4.0版本及之前都可以正确显示，但到了4.1版本之后，就只会显示android.widget.FrameLayout了。
请问大佬4.1之后获取当前活动的方式是改变了吗？
还有最近我用Tasker插件启动脚本，currentActivity函数有时候也无法返回正确结果，手动运行又一切正常，不知道是怎么回事啊。

**Comment by kkevsekk1** [comment]
这个我的理解本身就是不准确的，你可以先尝试用安卓的activity栈，用java代码解决一下，我也尝试修复一下现在的获取机制



发送自我的盖乐世



-------- 原始信息 --------
发件人： himno ***@***.***>
日期: 2021/5/12 10:34 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 获取当前活动异常。 (#62)


这个问题从原作者的时候就遗留下来了。悬浮按钮点开后，有个齿轮图标，可以查看当前活动的名字。在4.0版本及之前都可以正确显示，但到了4.1版本之后，就只会显示android.widget.FrameLayout了。
请问大佬4.1之后获取当前活动的方式是改变了吗？
还有最近我用Tasker插件启动脚本，currentActivity函数有时候也无法返回正确结果，手动运行又一切正常，不知道是怎么回事啊。

―

**Comment by gq1378** [comment]
我这两天刚用这个，也碰到这个问题了，4.1.0可以99%正确得到，4.1.1以上很多都会出错，先回4.1.0了

**Comment by kkevsekk1** [comment]
最新 dev 版本，尝试调整这个问题
