### ISSUE TITLE
控制台无法调整大小

### ISSUE THREAD

**Issue by msccreater** [kkevsekk1/AutoX#620]
1. Autox.js 版本：643
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米11Pro
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：控制台设置大小无效果, 用的是自带示例, 修改控制台大小和位置
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![}OMZZ`{EXLSX9 BGLR _AX](https://github.com/kkevsekk1/AutoX/assets/1811267/626472dd-bb13-4752-8712-491be1ce95d9)

**Comment by msccreater** [comment]
![XZZT2P5ITDI0L8$ZA{0NI%8](https://github.com/kkevsekk1/AutoX/assets/1811267/391cfea2-1528-42c7-a24f-654f1ea2a4fb)

**Comment by bjcwjtg7uc** [comment]
// console.setPosition(device.width / 4, 0);
// console.setSize(device.width / 3, device.height / 3-100);

**Comment by msccreater** [comment]
![P49ZR}`THFXA(CG$M) T4H](https://github.com/kkevsekk1/AutoX/assets/1811267/b497b567-6ce0-4a0e-8f2d-e6ae2018ba8b)


> 

看截图里的代码,没有变化, 确认过的确是BUG

**Comment by kkevsekk1** [comment]
这个，先显示 console log界面，再延迟一下，调整位置，大小即可
