### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by Tangerine-TBE** [kkevsekk1/AutoX#622]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 这边的业务是，每一次运行脚本都会用到Autoxjs框架。每次脚本运行大概30-50分钟，之后会结束这个脚本任务，运行下一个脚本任务。脚本开始执行会进行引擎的初始化，脚本运行结束后会退出引擎。
但是这样发现重复 对引擎的初始化，退出，会出现内存溢出，每次大概会有5m。

我这边是这样解决的，改造了一次LoopedBaseEngine 他只会在第一次时new出来，其他时候都会进行复用，并传递对应的ScriptSource
这样对于TopLevelScope来说每一次都不会进行创建了。这样做确实是发现内存溢出量减少了，但还是会有内存溢出。

之后发现可能是ScriptRuntime出现了内存溢出，那么秉着换汤不换药的原则，也对ScriptRuntime进行一个单例改造。

但是运行脚本发现第一个脚本没问题，但是跑第二个脚本时会出现handler尝试发送一个消息到已经死亡的线程上。

我不清楚为什么会这样，是因为SciptRutime做成单例后，就不需要对内部的一些成员变量进行释放了么。

类似这个fangfa:
    public void exit() {
        mThread.interrupt();
        engines.myEngine().forceStop();
        threads.exit();
        onExit();
        if (Looper.myLooper() != Looper.getMainLooper()) {
            throw new ScriptInterruptedException();
        }
    }
是不需要进行threads.exit()方法么？

希望能很快得到您的答复谢谢。

12. 报错日志（可选）：
13. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
是不是单例，跟溢出没直接关系



发送自我的盖乐世



-------- 原始信息 --------
发件人： Tangerine ***@***.***>
日期: 2023/7/11 21:09 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 内存溢出问题 (Issue #622)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  这边的业务是，每一次运行脚本都会用到Autoxjs框架。每次脚本运行大概30-50分钟，之后会结束这个脚本任务，运行下一个脚本任务。脚本开始执行会进行引擎的初始化，脚本运行结束后会退出引擎。
但是这样发现重复 对引擎的初始化，退出，会出现内存溢出，每次大概会有5m。

我这边是这样解决的，改造了一次LoopedBaseEngine 他只会在第一次时new出来，其他时候都会进行复用，并传递对应的ScriptSource
这样对于TopLevelScope来说每一次都不会进行创建了。这样做确实是发现内存溢出量减少了，但还是会有内存溢出。

之后发现可能是ScriptRuntime出现了内存溢出，那么秉着换汤不换药的原则，也对ScriptRuntime进行一个单例改造。

但是运行脚本发现第一个脚本没问题，但是跑第二个脚本时会出现handler尝试发送一个消息到已经死亡的线程上。

我不清楚为什么会这样，是因为SciptRutime做成单例后，就不需要对内部的一些成员变量进行释放了么。

类似这个fangfa:
public void exit() {
mThread.interrupt();
engines.myEngine().forceStop();
threads.exit();
onExit();
if (Looper.myLooper() != Looper.getMainLooper()) {
throw new ScriptInterruptedException();
}
}
是不需要进行threads.exit()方法么？

希望能很快得到您的答复谢谢。

  1.  报错日志（可选）：
  2.  屏幕截图（可选）：

―

**Comment by Tangerine-TBE** [comment]
你能告诉我，你发现的内存溢出的点么
