### ISSUE TITLE
微信 QQ等软件进行截图的图片是模糊的

### ISSUE THREAD

**Issue by cerolluo** [kkevsekk1/AutoX#623]
1. Autox.js 版本：[6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米11
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：我是新手才开始学习，咨询一下使用captureScreen函数在微信或者QQ等软件界面上进行截图，图片是模糊的，在桌面，手机设置里面截图是正常的，请问是我手机问题，还是微信等软件有限制呢，谢谢！！！
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![53457e9f76c0ca3db9194e3c703419f](https://github.com/kkevsekk1/AutoX/assets/86531140/cfde3ca0-3c9c-46d6-bc22-56dbb2ddf058)
![09094d321cc5866e4506864f7794268](https://github.com/kkevsekk1/AutoX/assets/86531140/d2d311f2-9833-4d5d-a66e-d4b866f77615)

代码：
//请求截图
if (!requestScreenCapture()) {
    toast("请求截图失败");
    exit();
}
sleep(3000);
var name=random(10000,99999)+"test.jpg"
images.captureScreen(name)

**Comment by kkevsekk1** [comment]
这种情况肯定是微信限制



发送自我的盖乐世



-------- 原始信息 --------
发件人： cerolluo ***@***.***>
日期: 2023/7/12 19:09 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 微信 QQ等软件进行截图的图片是模糊的 (Issue #623)


  1.  Autox.js 版本：[6.4.3
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 12
  4.  Android 机型：小米11
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：我是新手才开始学习，咨询一下使用captureScreen函数在微信或者QQ等软件界面上进行截图，图片是模糊的，在桌面，手机设置里面截图是正常的，请问是我手机问题，还是微信等软件有限制呢，谢谢！！！
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
[53457e9f76c0ca3db9194e3c703419f]<https://user-images.githubusercontent.com/86531140/252948577-cfde3ca0-3c9c-46d6-bc22-56dbb2ddf058.jpg>
[09094d321cc5866e4506864f7794268]<https://user-images.githubusercontent.com/86531140/252948692-d2d311f2-9833-4d5d-a66e-d4b866f77615.jpg>

代码：
//请求截图
if (!requestScreenCapture()) {
toast("请求截图失败");
exit();
}
sleep(3000);
var name=random(10000,99999)+"test.jpg"
images.captureScreen(name)

―

**Comment by cerolluo** [comment]
> 还真的是这个电诈防护，谢谢了
![image](https://github.com/kkevsekk1/AutoX/assets/86531140/e6a14ad4-7d0f-4f4b-8b33-59bbd9a2f99d)

**Comment by Le-u** [comment]
> @cerolluo 看看是不是这个问题 部分设备升级MIUI14之后，脚本在支付宝中获取的截图是模糊的，导致无法识别能量球。请自行关闭电诈防护 设置-安全-电诈防护-屏幕共享防护 关闭 引用：[TonyJiangWJ/Ant-Forest#197](https://github.com/TonyJiangWJ/Ant-Forest/issues/197)

找半天没找到关的地方，这次终于找到了

**Comment by predream** [comment]
原来是MIUI自己搞的，找了好久不知道是啥原因
