### ISSUE TITLE
无法格式化代码(〒﹏〒)

### ISSUE THREAD

**Issue by MisakaNo23300** [kkevsekk1/AutoX#626]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：vivo y31s 标准版
5. Android 系统类别：OriginOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：无法使用自带的格式化代码，点击后代码无变化！
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![Screenshot_2023_0715_102037](https://github.com/kkevsekk1/AutoX/assets/89892822/755adaa8-9661-4d7a-8506-da7a25c6d91c)

**Comment by aiselp** [comment]
新的编辑器正在开发中，完成后将尝试嵌入autox，工作较忙，可能还需要较长的时间
