### ISSUE TITLE
6.4.3版本游戏截图时总会闪动屏幕导致截的图片上方有白条

### ISSUE THREAD

**Issue by lchpersonal** [kkevsekk1/AutoX#627]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9以及夜深安卓模拟器
4. Android 机型：荣耀8和夜深安卓模拟器
5. Android 系统类别：安卓
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：在游戏截图时，屏幕总会往下闪动一下，手机上和模拟器都会闪动，但是手机上截取的图片没问题，安卓模拟器截的图上面会多一个白色条，导致脚本无法兼容。
8. 报错日志（可选）：无报错
9. 屏幕截图（可选）：
![微信图片_20230715161058](https://github.com/kkevsekk1/AutoX/assets/12620558/bd71404d-7beb-4f99-ac70-444eaa2adaaf)

**Comment by lanmingle** [comment]
我用雷电模拟器和雷电云没有问题，对了，你这个是啥游戏啥类型？能搬不？

**Comment by Le-u** [comment]
有没有可能上面是状态栏

**Comment by lchpersonal** [comment]
> 有没有可能上面是状态栏

不是状态栏，用手机自带的截图工具就没这个

**Comment by lchpersonal** [comment]
> 我用雷电模拟器和雷电云没有问题，对了，你这个是啥游戏啥类型？能搬不？

搬不了

**Comment by Le-u** [comment]
> > 有没有可能上面是状态栏
> 
> 不是状态栏，用手机自带的截图工具就没这个

自带的肯定没有问题，你就在桌面截个图保存起来，上面的状态栏是无法显示的

**Comment by Le-u** [comment]
> > 有没有可能上面是状态栏
> 
> 不是状态栏，用手机自带的截图工具就没这个

确定了这个就是状态栏，上次没看到图片，我刚刚看到了，这个白条就是状态栏，我遇到过

**Comment by lanmingle** [comment]
搬不了啊！浪费人力
