### ISSUE TITLE
手机重启无障碍权限显示：无法运行。点按即可查看相关信息。

### ISSUE THREAD

**Issue by zhyxxxxxx** [kkevsekk1/AutoX#630]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米12
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：手机重启无障碍权限失效，并显示：无法运行。点按即可查看相关信息。点进去显示：此服务出现故障。每次手机重启都得重新把无障碍关了再打开才行。
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![1689991697990(1)](https://github.com/kkevsekk1/AutoX/assets/63797856/40869efd-6177-48c4-bb02-97bb522bb287)
![1689991715029](https://github.com/kkevsekk1/AutoX/assets/63797856/f6f5d6af-f64e-46ab-8f5b-7c8f9c95c9d9)

**Comment by Charlotte3240** [comment]
再次开关一下这个无障碍权限开关 ，感觉像是系统问题
