### ISSUE TITLE
使用脚本引擎执行脚本，在新的脚本中无法使用  require(),报错：Cannot call method "getResource" of null

### ISSUE THREAD

**Issue by Le-u** [kkevsekk1/AutoX#633]
1. Autox.js 版本：6.4.3
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米13p
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用脚本引擎执行脚本，在新的脚本中无法使用  require(),报错：Cannot call method "getResource" of null
9. 报错日志（可选）：
10. 屏幕截图（可选）：
11. 
目录：

- project.json
- main.js
- newscript.js
- utils
  -  utils.js

main.js
`engines.execScriptFile('./newscript.js', {
  path: files.cwd()
})
`

newscript.js
` 
  const methodsObj = require('./utils/utils.js')
`

报错 Cannot call method "getResource" of null

**Comment by Le-u** [comment]
## 补充
文档中  path {Array} | {string} 指定脚本运行的目录。这些路径会用于 require 时寻找模块文件。
对于找图  `images.read()` 是可以使用的，require 无法使用

**Comment by Le-u** [comment]
> 经过测试一切正常，请检查错误是否由你模块中的代码抛出

我刚刚又测了一遍，确实没问题，又排查了一遍在使用 `HTML  - JsBridge` 时出现了问题，`ui.web.jsBridge.registerHandler('AndroidStartScript', (data, callBack) => {
  engines.execScriptFile('./newscript.js')
})`
把 ` engines.execScriptFile('./newscript.js')` 放在监听函数外面，就可以使用 `require()`

**Comment by aiselp** [comment]
试了下这样确实会报错，因为回调执行的环境有些差异导致，可通过把代码放入ui.post或放入定时器中解决。有时间再优化一下

**Comment by Zic-0445** [comment]
### 单独使用脚本引擎时同样会触发```Error: Module "common" not found.```问题
![image](https://github.com/kkevsekk1/AutoX/assets/130950893/12442065-99be-4c29-a08c-10bfebb548c6)
___
### ```main.js```内容如下：
 ```
events.broadcast.on("startRun", ()=>{toastLog("开始运行")})

setTimeout(()=>{
    log(require("common"))
},3000)
```
