### ISSUE TITLE
新手求救录制无法运行

### ISSUE THREAD

**Issue by dakezuo** [kkevsekk1/AutoX#636]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：雷电模拟器
7. 问题描述：新手，尝试使用录制功能，然后看代码，但是录制完成以后运行，只提示已授予root权限，然后就没了，用编辑脚本功能打开录制的那个脚本，里面全是乱码，有没有大佬指教一下

**Comment by SuJack** [comment]
1. 点击  设置 <img width="190" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/3007627/2060af09-db5f-46d9-b07b-9751b8014a09">
2.录制脚本 ---> Root 录制生成文件类型  ---> 选择 可编辑的js文件
<img width="577" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/3007627/ededa75d-03d5-410e-83fe-bdef97805c51">

**Comment by dakezuo** [comment]
@SuJack 按照这么设置，确实不乱码了，但还行不正常，录制完的里面代码全是sleep,比如：var ra = new RootAutomator();
ra.setScreenMetrics(960, 540);
sleep(119);
sleep(1353);
sleep(118);
sleep(1920);
sleep(72);
sleep(2920);
sleep(102);
ra.exit();
