### ISSUE TITLE
希望赶紧支持刘海屏挖孔屏

### ISSUE THREAD

**Issue by LJHQWA** [kkevsekk1/AutoX#641]
新版本旧版本找图找色命令只能在状态栏区域才能找到相应的东西
状态栏以外的屏幕无法实现找图找色有一定概率报错或者闪退直接退出应用

**Comment by kkevsekk1** [comment]
这个需求，完全可以用高效的坐标实现把？再这个区域找什么？

**Comment by maskj4** [comment]
Paint.Style.STROKE 文档里Style时大写的
