### ISSUE TITLE
有没有关闭APP(关后台)的方法，或者重启APP的方法？

### ISSUE THREAD

**Issue by 0cafe** [kkevsekk1/AutoX#644]
有没有关闭APP(关后台)的方法，或者重启APP的方法？

**Comment by kkevsekk1** [comment]
这不很很简单吗，你人工怎么弄关，这就怎么关



发送自我的盖乐世



-------- 原始信息 --------
发件人： 0cafe ***@***.***>
日期: 2023/8/25 13:59 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 有没有关闭APP(关后台)的方法，或者重启APP的方法？ (Issue #644)


有没有关闭APP(关后台)的方法，或者重启APP的方法？

―

**Comment by 0cafe** [comment]
我是指类似app.launch的这种代码控制APP的方法

**Comment by lll862** [comment]
> 有没有关闭APP(关后台)的方法，或者重启APP的方法？

`//遇到问题，关闭app再打开
function restartApp(appName) {
    let forcedStopStr = ["结束", "停", "强"];
    let packageName = app.getPackageName(appName);//获取应用包名 通过软件名
    if (packageName) {
        app.openAppSetting(packageName);//进入应用设置信息
        text(appName).waitFor();//等待查询到名字出现
        log('软件名称出现')
        for (var i = 0; i < forcedStopStr.length; i++) {
            if (textContains(forcedStopStr[i]).exists()) {//判定关键字是否存在
                log('关键词存在')
                sleep(500);
                let forcedStop = textContains(forcedStopStr[i]).findOne();
                forcedStop.click() //点击强行停止
                text('取消').waitFor();//等待二次确认停止框的‘取消’出现
                text('强行停止').click() //如果不起效，说明控件不支持点击，click(‘xxx’)这种是全屏找字，直接点击字的坐标来进行点击！可以查找控件坐标位子，直接点击这个坐标来点击1
                sleep(random(5000,10000))
                launch(packageName)
                break
            }
        }
    }
}`

网上有现成的，改动了一点点，适合我这边的情况。

**Comment by fanlushuai** [comment]
这个直接用

``` js
killApp("快手");

//app应用关闭
function killApp(name) {
  // 所以，填写包名或app名称都可以
  var packageName = getPackageName(name) || getAppName(name);
  if (!packageName) {
    log("找不到packageName"+packageName);
    return;
  }

  // 打开系统级应用设置
  app.openAppSetting(packageName);
  sleep(random(1000, 2000));
  text(app.getAppName(packageName)).waitFor();

  // 执行盲点流程 （多点几次不过分。都是非阻塞的。）
  var times = 3; // 多点几次，应对页面上存在一些其他tips文字，干扰流程。
  do {
    stop();
    times--;
  } while (times);

  sleep(random(1000, 1500));
  back();
}

// 盲点
function stop() {
  var is_sure = textMatches(
    /(.{0,3}强.{0,3}|.{0,3}停.{0,3}|.{0,3}结.{0,3}|.{0,3}行.{0,3})/
  ).findOnce();
  if (is_sure) {
    is_sure.click();
    sleep(random(500, 1000));
  }

  var b = textMatches(/(.*确.*|.*定.*)/).findOnce();
  if (b) {
    b.click();
    sleep(random(500, 1000));
  }
}

```
