### ISSUE TITLE
是否願意增加 WebRTC 的功能?

### ISSUE THREAD

**Issue by jiangjiangdev** [kkevsekk1/AutoX#645]
您好我是台灣的愛用者
首先很感謝您持續維護這麼好用的工具
但最近有個需求會在腳本中增加 WebRTC 的功能來傳輸視訊
不曉得作者之後有沒有打算增加這個功能
或者是有什麼可以實現的思路可以分享?

**Comment by kkevsekk1** [comment]
没有这个计划



发送自我的盖乐世



-------- 原始信息 --------
发件人： JiangDev ***@***.***>
日期: 2023/8/26 03:07 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 是否意增加 WebRTC 的功能? (Issue #645)


您好我是台车塾谜
首先很感x您持mSo@N好用的工具
但最近有需求谀_本中增加 WebRTC 的功能鬏
不缘米髡咧嵊]有打算增加@功能
或者是有什N可以F的思路可以分享?

―
