### ISSUE TITLE
同一个控件，偶尔会报错：TypeError: Cannot call method "bounds" of null 但布局范围分析中是有bounds数值的

### ISSUE THREAD

**Issue by lll862** [kkevsekk1/AutoX#646]
同一个控件，偶尔会报错：TypeError: Cannot call method "bounds" of null 但布局范围分析中是有bounds数值的
请问各位大神，如何处理呢？
有时正常获取，偶尔会报错。。

**Comment by tonghuanming** [comment]
不止是bounds遇到错误  在查找其他控件时候也会遇到控件列表好像暂时没刷新一样，显示的还是老的控件位置和信息，造成找不到新的控件，甚至布局分析器探测到的也是老的控件，绿框位置都不对，暂时没搜到好的解决办法
