### ISSUE TITLE
captureScreen 截图阻塞运行

### ISSUE THREAD

**Issue by 17537932** [kkevsekk1/AutoX#653]
1. Autox.js 版本：6.3.4
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：红米note 12
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用captureScreen方法时偶尔会阻塞代码也无任何报错
8. 报错日志（可选）：无
9. 屏幕截图（可选）：无

**Comment by wstee** [comment]
因为电诈防护吧

**Comment by wingswing1** [comment]
> 因为电诈防护吧

不是，关了一样
