### ISSUE TITLE
[需求]请增加com.termux.permission.RUN_COMMAND权限

### ISSUE THREAD

**Issue by poweryu** [kkevsekk1/AutoX#655]
需求目的：用于通过Intent调用temrux执行adb命令
实现方式：在AndroidManifest.xml增加权限com.termux.permission.RUN_COMMAND，详细请参考https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

**Comment by kkevsekk1** [comment]
只是加个权限不做其他配置，可能加，提上来就可以



发送自我的盖乐世



-------- 原始信息 --------
发件人： poweryu ***@***.***>
日期: 2023/9/3 12:56 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] [需求]请增加com.termux.permission.RUN_COMMAND权限 (Issue #655)


需求目的：用于通过Intent调用temrux执行adb命令
实现方式：在AndroidManifest.xml增加权限com.termux.permission.RUN_COMMAND，详细请参考https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent

―
