### ISSUE TITLE
更新6.5.1后，VSCode插件中关于项目的操作全部无效

### ISSUE THREAD

**Issue by Zic-0445** [kkevsekk1/AutoX#656]
1. Autox.js 版本：6.5.1
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 7(32 bit)
4. Android 机型：夜神模拟器【版本：7.0.5.8001-7.1.2700230529】
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.111.0
7. 问题描述：更新6.5.1后，VSCode插件中关于项目的操作全部无效
8. 报错日志（可选）：无
9. 屏幕截图（可选）：查看下方录屏
https://github.com/kkevsekk1/AutoX/assets/130950893/3169932c-bec6-4693-aa00-4a8b595df3a3
___
### 详细说明：
2023-09-02日使用时无异常，2023-09-04早使用时出现 ***“保存项目到设备”、“运行项目”*** 两项操作无响应的问题，随后使用夜神模拟器开启多个安卓系统版本尝试，均无效；使用 ___小米5C【安卓版本：7.1.2；MIUI版本：11.0.3稳定版】___ 亦无响应。

**Comment by maskj4** [comment]
请问解决好了吗

**Comment by Zic-0445** [comment]
不是插件的问题，是项目文件夹中不能存放.git文件夹，不然就会导致项目类型操作失败
