### ISSUE TITLE
webview中vue进行路由跳转会闪退

### ISSUE THREAD

**Issue by yikus-tjq** [kkevsekk1/AutoX#659]
![Screenshot_2023-09-06-11-08-53-203_com miui bugreport](https://github.com/kkevsekk1/AutoX/assets/38431925/4dd61ae2-c340-4f74-8a59-104b622451ce)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/cepheus/cepheus:10/QKQ1.190825.002/20.12.9:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-09-06 11:08:38+0800
pid: 14392, tid: 14392, name: tojs.autoxjs.v6  >>> org.autojs.autoxjs.v6 <<<
uid: 10512
signal 5 (SIGTRAP), code 0 (SI_USER), fault addr --------
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    x0  0000000000000000  x1  0000000000000081  x2  000000007fffffff  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
    x12 0000007c56cf3ee0  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 0000007c54d40958  x17 0000007c54cca320  x18 0000007c577f6000  x19 0000007fc0d519b0
    x20 0000007fc0d519b8  x21 0000007fc0d519c0  x22 000000000000004f  x23 0000007c54d3a578
    x24 0000007b7a174000  x25 0000007c56d07018  x26 0000007b3c9bdc00  x27 0000007fc0d51500
    x28 0000007b7a174000  x29 0000007fc0d51950
    sp  0000007fc0d514f0  lr  0000007b77b1c8b8  pc  0000007b77b1cab8

backtrace:
      #00 pc 00000000018abab8  /system/product/app/WebViewGoogle/WebViewGoogle.apk!libmonochrome.so (offset 0x1a2000) (BuildId: cc7acff7318036c7fbae10b98fe0aabd95a163b0)

代码：
`/* eslint-disable */
'ui';
// 一. 开发使用本地地址调试
initUi('http://xxxx')

// 二.上线
// initUi('http://xx.com/#/')

/**
 * 初始化 UI
 * @param {string} htmlPath html文件的地址
 */
function initUi (htmlPath) {
  ui.layout('<webview id="web" h="*" w="*"  />')
  webViewExpand_init(ui.web)

  if (htmlPath.indexOf('http') === 0) {
    ui.web.loadUrl(htmlPath)
  } else {
    let path = 'file:' + files.path(htmlPath)
    ui.web.loadUrl(path)
  }
}

/**
 * 执行 js
 * @template T
 * @param {*} webViewWidget webview对象
 * @param {string} script 脚本
 * @param {(data:T)=>void} callback 回调函数
 */
function callJavaScript (webViewWidget, script, callback) {
  try {
    console.assert(webViewWidget != null, 'webView控件为空')
    // runtimeLog(script.toString())
    webViewWidget.evaluateJavascript(
      'javascript:' + script,
      new JavaAdapter(android.webkit.ValueCallback, {
        onReceiveValue: (val) => {
          if (callback) {
            callback(val)
          }
        },
      }),
    )
  } catch (e) {
    console.error('执行JavaScript失败')
    console.trace(e)
  }
}

/**
 * 执行 js
 * @template T
 * @param {string} code 欲执行的js代码
 * @param {(data:T)=>void} callback 回调函数
 */
function callJs (code, callback) {
  callJavaScript(ui.web, code, callback)
}

function bridgeHandler_handle (cmd, args) {
  let ret

  // 执行 js代码
  if (args == '[code]') {
    ret = eval(cmd)
  } else {
    // 调用方法
    /** @type {Function} */
    let fun = this[cmd]
    if (!fun) {
      throw new Error('cmd= ' + cmd + ' 没有定义实现')
    }

    // 判断参数类型
    if (Array.isArray(args)) {
      ret = fun.apply(this, args)
    } else {
      ret = fun.call(this, args)
    }
  }

  return ret
}

function webViewExpand_init (webview) {
  webview.webViewClient = new JavaAdapter(android.webkit.WebViewClient, {
    /** 页面开始加载, 此时还没有加载 index.html 中的代码 */
    onPageStarted: (webView, url, favicon) => {
    },
    /** 页面加载完成, 在 window.onload 之后触发 */
    onPageFinished: (webView, curUrl) => {
    },
    onReceivedError: (webView, webResourceRequest, webResourceError) => {
      let url = webResourceRequest.getUrl()
      let errorCode = webResourceError.getErrorCode()
      let description = webResourceError.getDescription()
      console.trace(errorCode + ' ' + description + ' ' + url)
    },
  })

  webview.webChromeClient = new JavaAdapter(android.webkit.WebChromeClient, {
    /** 拦截 web console 消息 */
    onConsoleMessage: (consoleMessage) => {
      /** @type {string} */
      let msg = consoleMessage.message()
      let sourceId = consoleMessage.sourceId().split('/')
      let sourceIdStr = sourceId[sourceId.length - 1]
      let lineNumber = consoleMessage.lineNumber()
      let msgLevel = consoleMessage.messageLevel()

      if (msg.indexOf('jsbridge://') == 0) {
        let uris = msg.split('/')

        /** @type {{cmd:string, callId:number, args:any}} */
        let data = JSON.parse(java.net.URLDecoder.decode(uris[2], 'UTF-8'))

        let cmd = data.cmd
        let callId = data.callId
        let args = data.args

        runtimeLog('⭐ AJ 收到调用请求:', JSON.stringify(data).slice(0, 50))
        let result = null
        try {
          result = bridgeHandler_handle(cmd, args)
        } catch (e) {
          console.trace(e)
          result = {
            message: e.message,
          }
        }

        let callbackArgs = {
          callId: callId,
          args: result,
        }

        // 调用 web , 完成回调
        callJs(['auto.callback(', JSON.stringify(callbackArgs), ')'].join(''))
      } else {
        runtimeLog('📖 浏览器日志: %s [%s:%s] %s ', msgLevel, sourceIdStr, lineNumber, msg)
      }
    },
  })
}

/**
 * 框架 log
 * @description 注释方法中的代码就可以关闭所有的框架日志了.
 */
function runtimeLog () {
  console.log.apply(this, arguments)
}
`

这个在autojs6中 是可以正常运行的 ，在autox就会闪退 ，用的是 vue3做的 进行路由跳转就会闪退

autox版本：6.5.1

**Comment by aiselp** [comment]
要复现这个问题有点难，你试试在旧版会不会闪退？
