### ISSUE TITLE
JsBridge不支持WEUI+的某些组件。调试是正常的，打包就不行了

### ISSUE THREAD

**Issue by ximengxuan** [kkevsekk1/AutoX#663]
1. Autox.js 版本：651
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：小米8Lite
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：

前端页面使用weui+ 6.10 实现的
项目地址https://github.com/logoove/weui
调试的时候一切正常。但是打包后，一些弹出的组件，比如ActionSheet，就会失灵。无法弹出。
加载这个UI框架的Demo，发现首页的内容打包后也是无法展开的。
测试其他的前端UI框架，比如MUI框架，也存在此问题。许多组件，打包后就失效了。
是不是因为打包的时候，没有携带某些so库，或者其他的原因呢？

有没有办法修复这个问题呢？

**Comment by aiselp** [comment]
打包后项目内所有js文件默认都被加密，导致webview无法读取js文件。

**Comment by ximengxuan** [comment]
> 打包后项目内所有js文件默认都被加密，导致webview无法读取js文件。

难怪呢！我把autox自带的18个so文件，一起打包，也没解决。
有什么办法处理这个加密问题呢？原则上来说，打包后的程序运行后，应该自动解密js文件啊？
如果不能自动解密，那么打包的时候，能不能给个选项，就是勾选是否自动加密js文件？
这样才不至于让webview成为鸡肋啊？

**Comment by aiselp** [comment]
打包界面是其他开发者编写的，相关代码对我来说还有点难以理解，不好改
