### ISSUE TITLE
[需求] 增加timerTask

### ISSUE THREAD

**Issue by mrjesen** [kkevsekk1/AutoX#674]
1. Autox.js 版本：651
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：hongshouzhi
5. Android 系统类别：android
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：希望增加timer定时器
8. 报错日志（可选）：
9. 屏幕截图（可选）：

主要是setInterval和setTimeout经常被while循环阻塞，所以提此需求，
目前我是通过以下代码实现的，但是不够优雅而且有很多bug：
```js
new java.util.Timer().schedule(new java.util.TimerTask({
    run: () => {
        log(new Date())
        exit()
    },
}), new Date());
```

**Comment by mrjesen** [comment]
最重要是不被setInterval阻塞，但是还有一个bug那就是不受程序控制，脚本停止这个timer也不停止

**Comment by aiselp** [comment]
aj子线程api中是可以使用setTimeout等函数的，可用子线程解决阻塞问题
