### ISSUE TITLE
触摸监听失效

### ISSUE THREAD

**Issue by 31411** [kkevsekk1/AutoX#684]
1. Autox.js 版本：6.5.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：realme Q5pro
5. Android 系统类别：realme UI(colorOS)
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用触摸监听失效
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by aiselp** [comment]
要root的，你这个机型8成就没有
