### ISSUE TITLE
[Bug] jsBridge.callHandler not work in floaty (in normal mode, but work in 'ui'; mode ')

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#686]
1. Autox.js version: 6.5.2
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 10
4. Android model:  10
5. Android system category: Oppo F11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:
```
let T = {}

ui.run(function () {
  T.ui = floaty.rawWindow(`
    <vertical>
        <webview id="web" h="*"/>
    </vertical>`)
  T.ui.web.loadUrl('...[my_url_here]')
  setTimeout(() => {
    T.ui.web.jsBridge.callHandler('test', '123', (data) => {
      toastLog('web回调,data:' + data) // <--------- not run
    })
  }, 2000)
})
setInterval(() => {}, 1000)

```

8. Error log (optional):
9. Screenshot (optional):

**Comment by aiselp** [comment]
已确认问题，之后更新将尝试修复
