### ISSUE TITLE
[Bug] [webview] crash debug server vscode (only debug server)  when send string too long via webview callHandler function 

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#687]
1. Autox.js version: 6.5.2
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 10
4. Android model:  10
5. Android system category: Oppo F11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:

with html
```
...
$autox.registerHandler('echo',  (data, callBack) => {
  callBack(JSON.stringify(data))
})
...
```
with Autox
```
...
    T.ui.web.jsBridge.callHandler('echo', 'hello'.repeat(100000), (data) => { // <--------- crash vscode debug server
      toastLog('web回调,data:' + data) 
    })
  }, 2000)
})
...
```

8. Error log (optional):
9. Screenshot (optional):

**Comment by aiselp** [comment]
我不明白debug server vscode是指什么，这个问题恐怕难以修复

**Comment by anhnhoktvn** [comment]
![image](https://github.com/kkevsekk1/AutoX/assets/2435820/8d47d999-e863-44e0-ae97-4b91afcb8b6b)
Sorry for not make it clear, it the 'start server' menu in vscode. I use it to debug code.

**Comment by anhnhoktvn** [comment]
still happen even not using console.log
