### ISSUE TITLE
autojsx 连接电脑的问题

### ISSUE THREAD

**Issue by Faryi** [kkevsekk1/AutoX#69]
我连接电脑时或者公网IP时,手机的外网IP或内网IP发生变化时,连接电脑的功能就自动断开了,作者大大能优化这个功能吗?当断开连接时自动重新连接.

**Comment by kkevsekk1** [comment]
云控啊？

**Comment by Faryi** [comment]
嗯,连接电脑的问题,可以实现云控的功能

**Comment by kkevsekk1** [comment]
捐点款嘛

**Comment by Faryi** [comment]
可以捐款,需要多少

**Comment by Faryi** [comment]
怎么样???@kkevsekk1

**Comment by kkevsekk1** [comment]
捐个5位数嘛

**Comment by Faryi** [comment]
大哥真会开玩笑😂,我就是向捣鼓捣鼓我的手机

**Comment by kkevsekk1** [comment]
O(∩_∩)O哈哈~

**Comment by kkevsekk1** [comment]
要保活，重启后重连，要是服务器一直不再呢？手机耗电高的一逼，这是一个哲学问题

**Comment by Faryi** [comment]
刚刚网络波动了一下
不考虑手机耗电的情况，保活进行重连，设定一个规则重连次数10次，一次10秒，超出10次后就不在进行重连，这样就避免服务器不在的情况。
或者
连接时增加有一个开关,开关控制保活,或在设置里面增加这个选项.  告知用户这个作用会导致手机增加耗电量.

**Comment by 1965514404** [comment]
可以用云手机的链接方式,用蒲公英组内网

**Comment by kkevsekk1** [comment]
可以，下周发布



发送自我的盖乐世



-------- 原始信息 --------
发件人： icesvalley ***@***.***>
日期: 2021/6/4 18:15 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Mention ***@***.***>
主题： Re: [kkevsekk1/AutoX] autojsx 连接电脑的问题 (#69)


可以用云手机的链接方式,用蒲公英组内网

―

**Comment by Faryi** [comment]
感谢作者,Alipay还是WeChat,我可以小小帮助一下❤️

**Comment by Faryi** [comment]
作者大大,还记得吗

**Comment by kkevsekk1** [comment]
技术研发中,O(∩_∩)O哈哈~

**Comment by Faryi** [comment]
🥺作者大大加油ヾ(◍°∇°◍)ﾉﾞ,身体最重要

**Comment by kkevsekk1** [comment]
头发都掉完了 o(*￣︶￣*)o

**Comment by Faryi** [comment]
KK NB (大声呐喊), AutojsX QQ群加了好久,现在还没有通过

**Comment by kkevsekk1** [comment]
不可能啊，你好吗肯定输错了

**Comment by Faryi** [comment]
QQ群 895775483  我刚刚又申请加入了

**Comment by kkevsekk1** [comment]
895775483

**Comment by Faryi** [comment]
我刚刚申请加入了

**Comment by kkevsekk1** [comment]
加qq 470722660

**Comment by Faryi** [comment]
我刚刚加你了
