### ISSUE TITLE
[求助]如何同步进行网络请求并设置timeout

### ISSUE THREAD

**Issue by dsgler** [kkevsekk1/AutoX#690]
http.get()没有timeout参数。
使用axios无法用await将Promise转为Object。
我需要获取结果传入下一个函数，有没有什么好的解决方法。

**Comment by kkevsekk1** [comment]
深入研究http对应的okhttp就知道了，你用另一个也不是问题😁
多研究即可


发送自我的盖乐世



-------- 原始信息 --------
发件人： dsgler ***@***.***>
日期: 2023/10/7 23:21 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] [求助]如何同步进行网络请求并设置timeout (Issue #690)


http.get()没有timeout参数。
使用axios无法用await将Promise转为Object。
我需要获取结果传入下一个函数，有没有什么好的解决方法。

**Comment by lanmingle** [comment]
哈哈哈
