### ISSUE TITLE
[Bug] crash vscode server when console.log long string

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#691]
1. Autox.js version: 6.5.2
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 10
4. Android model:  10
5. Android system category: Oppo F11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:

crash vscode server when console.log  long string

step to reproduce: 
- start vscode server: (Ctrl+Shitft+P)  Auto.js autoxjs: 开启服务(Start Server), 如有多个同类插件,请禁用其他或本插件
- connect a device to the server
- create a new file (js) in vscode
- run this code (press F5)
```
console.log('hello'.repeat(100000))
```
- got crash server

8. Error log (optional):
9. Screensh
![273382566-8d47d999-e863-44e0-ae97-4b91afcb8b6b](https://github.com/kkevsekk1/AutoX/assets/2435820/df9db049-41f1-49ff-849e-31e772acdfd9)
ot (optional):

**Comment by aiselp** [comment]
实际上在手机上直接运行也会崩溃，是一个可以优化的问题
