### ISSUE TITLE
parent().indexInParent()获取的错误

### ISSUE THREAD

**Issue by wingswing1** [kkevsekk1/AutoX#692]
1. Autox.js 版本：652
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：红米K50
5. Android 系统类别：MIUI14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
某控件使用findOnce().parent().indexInParent()获得的值是-1，正确应该是2。
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by mhsjzsq** [comment]
我也遇到了
