### ISSUE TITLE
AutoX崩溃

### ISSUE THREAD

**Issue by xjqm-tao** [kkevsekk1/AutoX#693]
1. Autox.js 版本：652
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：Redmi Note 11T Pro
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
运行着，突然奔溃，非必现，运行的脚本需要长时间进行搜索图片。

9. 报错日志（可选）：
`Version: 652
Android: 33
SIGABRT: 
#00    pc 000000000008cc74    /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) [arm64-v8a::e17f03d82d277eb8d7c51ca3961f4cf9]
#01    pc 000000000062f3b0    /apex/com.android.art/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+1168) [arm64-v8a::1b179f250754dbbf3eaec59393e8b1d6]
#02    pc 0000000000017520    /apex/com.android.art/lib64/libbase.so [arm64-v8a::805c1dfe4ea9454d03b5d1626665b3f0]
#03    pc 0000000000006f14    /system/lib64/liblog.so (__android_log_assert+308) [arm64-v8a::26e64d9f09bc7b4e36184dbb6381b8d9]
#04    pc 000000000020d94c    /system/lib64/libhwui.so [arm64-v8a::ae70370f4ae6e09f843312e4a2c6dbd5]
#05    pc 00000000001de7ac    /system/framework/arm64/boot-framework.oat [arm64-v8a::5110e1ad7e270c8dd0f0e12114ba6457]
java:
[Failed to get Java stack]`

**Comment by yefen** [comment]
兄弟找到解决办法了

**Comment by yefen** [comment]
我长时间运行shell截图并read、模拟器崩溃、我用的mumu
