### ISSUE TITLE
能否新增ADB调试，自行编译在真机和模拟器上点击链接电脑就闪退

### ISSUE THREAD

**Issue by RFSN** [kkevsekk1/AutoX#7]
能否新增ADB调试，自行编译在真机和模拟器上点击链接电脑就闪退

**Comment by kkevsekk1** [comment]
android开发环境中，可以查看具体的错误日志

**Comment by RFSN** [comment]
哦，好的，我换回仓库编译好的就没有问题，自己编译的就不行，先用着仓库编译好的吧。

**Comment by RFSN** [comment]
感谢作者的辛苦维护！！！
