### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by lingsixuan** [kkevsekk1/AutoX#701]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：项目中有从120.25.164.233:8081下载依赖，但是120.25.164.233:8081的SSL不正常，无法正常使用。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by aiselp** [comment]
你可以改成http://120.25.164.233:8080
或者尝试移除这一行，将自动切换其他库下载
