### ISSUE TITLE
怎么文档没说怎么运行脚本的

### ISSUE THREAD

**Issue by aogg** [kkevsekk1/AutoX#705]
到底是只能通过vscode运行脚本，还是必须打包apk才能运行

不能用node main.js这样运行吗？
不能docker运行吗？

文档没说，其他教程也没说，代码示例只有启动app能看懂，其他没地方指定要连哪台手机，usb连接好像也没说

**Comment by kkevsekk1** [comment]
有一个视频教程



发送自我的盖乐世



-------- 原始信息 --------
发件人： aogg ***@***.***>
日期: 2023/10/26 18:45 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 怎么文档没说怎么运行脚本的 (Issue #705)


到底是只能通过vscode运行脚本，还是必须打包apk才能运行

不能用node main.js这样运行吗？
不能docker运行吗？

文档没说，其他教程也没说，代码示例只有启动app能看懂，其他没地方指定要连哪台手机，usb连接好像也没说

―

**Comment by gxdyxh** [comment]
> 到底是只能通过vscode运行脚本，还是必须打包apk才能运行
> 
> 不能用node main.js这样运行吗？ 不能docker运行吗？
> 
> 文档没说，其他教程也没说，代码示例只有启动app能看懂，其他没地方指定要连哪台手机，usb连接好像也没说


vscode**安装插件**后 连接了手机以后 可以F5直接执行脚本的。

如何**连接手机**和插件的使用 
可以看看使用说明 https://github.com/wilinz/Auto.js-VSCode-Extension

**vscode 插件快捷键**
![image](https://github.com/kkevsekk1/AutoX/assets/33820361/d74c034c-1063-4cf6-9b86-ebb27bbe9d70)
