### ISSUE TITLE
openAppSetting响应true，但是并没有打开设置页面

### ISSUE THREAD

**Issue by gxdyxh** [kkevsekk1/AutoX#706]
1. Autox.js 版本：653
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：K60
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：Auto.js-Autox.js-VSCodeExt-Wilinz v1.111.0
7. 问题描述：openAppSetting响应true，但是并没有打开设置页面
8. 报错日志（可选）：
9. 屏幕截图（可选）：
10.部分代码：

`
let packageName = currentPackage();
console.log(packageName);
let res = openAppSetting(packageName);
console.log('打开设置',res)
sleep(3000)
//text(app.getAppName(packageName)).waitFor(); //因为打不开设置页面 会卡在这里

let is_sure = text("结束运行").findOne(2000);//在app的应用设置界面找寻包含“强”，“停”，“结”，“行”的控件
if (is_sure && is_sure.enabled()) {//判断控件是否已启用（想要关闭的app是否运行）
    is_sure.parent().click();//结束应用的控件如果无法点击，需要在布局中找寻它的父控件，如果还无法点击，再上一级控件，本案例就是控件无法点击
    text('确定').findOne().click();//需找包含“确”，“定”的控件
    log(app.getAppName(packageName) + "应用已被关闭");
    sleep(1000);
    back();
} else {
    log(app.getAppName(packageName) + "应用不能被正常关闭或不在后台运行");
    back();
}
`

**Comment by kkevsekk1** [comment]
设置名称是否正确，activity是否正确


发送自我的盖乐世



-------- 原始信息 --------
发件人： 郭全祯 ***@***.***>
日期: 2023/10/27 11:01 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] openAppSetting响应true，但是并没有打开设置页面 (Issue #706)


  1.  Autox.js 版本：653
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13
  4.  Android 机型：K60
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：Auto.js-Autox.js-VSCodeExt-Wilinz v1.111.0
  7.  问题描述：openAppSetting响应true，但是并没有打开设置页面
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
10.部分代码：

`
let packageName = currentPackage();
console.log(packageName);
let res = openAppSetting(packageName);
console.log('打开设置',res)
sleep(3000)
//text(app.getAppName(packageName)).waitFor(); //因为打不开设置页面 会卡在这里

let is_sure = text("结束运行").findOne(2000);//在app的应用设置界面找寻包含“强”，“停”，“结”，“行”的控件
if (is_sure && is_sure.enabled()) {//判断控件是否已启用（想要关闭的app是否运行）
is_sure.parent().click();//结束应用的控件如果无法点击，需要在布局中找寻它的父控件，如果还无法点击，再上一级控件，本案例就是控件无法点击
text('确定').findOne().click();//需找包含“确”，“定”的控件
log(app.getAppName(packageName) + "应用已被关闭");
sleep(1000);
back();
} else {
log(app.getAppName(packageName) + "应用不能被正常关闭或不在后台运行");
back();
}
`

―

**Comment by gxdyxh** [comment]
> activity是否正确

确认过 是正确的。可以获取到正确的包名。
`
11:33:48.747/V: 开始运行[[remote]shenkongdao.js]
11:33:48.748/D: com.hypergryph.skland
11:33:48.753/D: 打开设置 true
11:33:53.797/D: 森空岛应用不能被正常关闭或不在后台运行
11:33:53.802/V: 
 ------------ 
 [ [remote]shenkongdao.js ]运行结束，用时5.054000秒
`


在应用内 手动执行，响应true 界面无反应
`
let res = openAppSetting('com.hypergryph.skland');
console.log('打开设置',res)
`
不过 在autox.js 界面下执行 ，就可以调用起来设置界面。

**Comment by kkevsekk1** [comment]
直接用adb she'll能打开，这就能



发送自我的盖乐世



-------- 原始信息 --------
发件人： 郭全祯 ***@***.***>
日期: 2023/10/27 11:39 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] openAppSetting响应true，但是并没有打开设置页面 (Issue #706)


activity是否正确

确认过 是正确的。可以获取到正确的包名。
`
11:33:48.747/V: 开始运行[[remote]shenkongdao.js]
11:33:48.748/D: com.hypergryph.skland
11:33:48.753/D: 打开设置 true
11:33:53.797/D: 森空岛应用不能被正常关闭或不在后台运行
11:33:53.802/V:

[ [remote]shenkongdao.js ]运行结束，用时5.054000秒
`

在应用内 手动执行，响应true 界面无反应
let res = openAppSetting('com.hypergryph.skland'); console.log('打开设置',res)
不过 在autox.js 界面下执行 ，就可以调用起来设置界面。

―

**Comment by gxdyxh** [comment]
> 直接用adb she'll能打开，这就能 发送自我的盖乐世
我没有在命令行下 运行 adb shell
是用vscode运行的 
分别在打开应用<com.hypergryph.skland>与autox.js下运行 
`
let res = openAppSetting('com.hypergryph.skland'); console.log('打开设置',res)
`
在应用<com.hypergryph.skland>下  log返回true  界面无反应
在应用autox.js下 可以打开com.hypergryph.skland的应用设置界面


不知道是不是手机问题，今天晚上我换个手机再试试。

**Comment by chanfengsr** [comment]
“后台弹出界面” 这个权限打开就行了

**Comment by gxdyxh** [comment]
> “后台弹出界面” 这个权限打开就行了

你说的是对的。。。
打开了这个权限就可以弹出设置界面了
