### ISSUE TITLE
Wrong string type

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#707]
1. Autox.js version: 6.5.2
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 10
4. Android model:  10
5. Android system category: Oppo F11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:

wrong type of text class, className(), text(), ...
```
    typeof someEl.className() // === 'object'
    typeof someEl.text() // === 'object'
   // expected  someEl.text() === 'string'
  // or: someEl.className().toString() // === 'object'

```

8. Error log (optional):
9. Screenshot (optional):

**Comment by aiselp** [comment]
在什么样的情况下会出现呢？下方这段测试行为正常
```js
let a = text("其他").findOne()

log(typeof a.text())//string
log(typeof a.className())//string
```

**Comment by anhnhoktvn** [comment]
Sorry, it disappeared. I will report when catch it again
