### ISSUE TITLE
关于console.setSize(w, h)无效的问题

### ISSUE THREAD

**Issue by Coco-Zong2022** [kkevsekk1/AutoX#709]
1. Autox.js 版本：653
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：红米k30u
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：console.setSize(w, h)无效
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
先show再设置



发送自我的盖乐世



-------- 原始信息 --------
发件人： Coco-Zong2022 ***@***.***>
日期: 2023/10/29 17:55 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 关于console.setSize(w, h)无效的问题 (Issue #709)


  1.  Autox.js 版本：653
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 11
  4.  Android 机型：红米k30u
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：console.setSize(w, h)无效
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by fanlushuai** [comment]
同样不起作用

**Comment by fanlushuai** [comment]
需要show之后等待一会！！！！

      let dw = device.width;
      let dh = device.height;
      let cw = (dw * 7) / 10;
      let ch = (dh * 2) / 6;

      console.setTitle("淘宝秒杀");
      console.show(true);
      console.setCanInput(false);
      sleep(100); //等待一会，才能设置尺寸成功
      console.setSize(cw, ch); //需要前面等待一会
      console.setPosition(dw - cw, 0);
      console.setMaxLines(100);
