### ISSUE TITLE
关于images.interval  的一个修改建议

### ISSUE THREAD

**Issue by tmkmk** [kkevsekk1/AutoX#714]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：原功能中第三个参数 interval为0-0xff 之间的一个数,建议改成 0-0xffffffff的数, 其中分别对应 颜色值的 argb 通道的阈值,代码方面呢,对每个通道的范围通道分别使用 0xff 0xff00 .... 位与操作后 的数字进行操作,而非原先的 一股脑使用 interval 这个参数对所有通道进行范围取值; 
8. 最后:希望能增加一个制作对自定义点阵图的查找功能,我目前的实现方式 是 截取点阵图大小的一个区域,全部点设置为黑色,然后针对点阵定义为白色像素点,再进行查找.这样一来的话,效率就要低很多.

**Comment by aiselp** [comment]
看不懂，处理图色要A通道干嘛
