### ISSUE TITLE
打包成应用为什么会有主页面啊

### ISSUE THREAD

**Issue by mebiuscycler** [kkevsekk1/AutoX#719]
设置里面的不显示主页面是不起作用的，不能直接运行脚本吗？

**Comment by kkevsekk1** [comment]
可以

**Comment by mebiuscycler** [comment]
> 可以

那要怎么弄啊，求大神指教😭

**Comment by Laifang** [comment]
打包的时候 把那个选项取消掉即可 
![image](https://github.com/kkevsekk1/AutoX/assets/20664974/acd1d899-4824-4aa9-a85b-d9be4056a3dd)
