### ISSUE TITLE
opencv升级问题

### ISSUE THREAD

**Issue by kangarooCV** [kkevsekk1/AutoX#72]
能否将autojsx内的opencv升级到4.5.2，谢谢

**Comment by kkevsekk1** [comment]
升级容易出现api兼容问题，你是具体有些什么想法？



发送自我的盖乐世



-------- 原始信息 --------
发件人： kangarooCV ***@***.***>
日期: 2021/6/27 08:59 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] opencv升级问题 (#72)


能否将autojsx内的opencv升级到4.5.2，谢谢

―

**Comment by kangarooCV** [comment]
新版本opencv支持更多的api，解封了sift算子和升级了dnn库，想要调用opencv的api进行一些操作

**Comment by kangarooCV** [comment]
或者将opencv-contrib库打包编译进目前的opencv3.4.2版本，也可以达到这样的目的

**Comment by kkevsekk1** [comment]
我最近有点忙，要是着急你可以现在这个源码  把so 文件替换一下应该就可用

**Comment by kangarooCV** [comment]
ok
