### ISSUE TITLE
UiObject对象调用parent().indexInParent()返回-1

### ISSUE THREAD

**Issue by mhsjzsq** [kkevsekk1/AutoX#721]
1. Autox.js 版本：653
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases

使用autojs6能返回正常值

**Comment by msccreater** [comment]
不能直接通过pareng()来获取父节点的indexInParent等相关属性，有可能获取不到正确的值，必须是精确的直接定位到uiObject对象的才可以获取正确的属性，感觉像是在逐级查找目标节点的过程中，父节点或者祖先节点的一些属性被忽略掉了

**Comment by Kiritocyz** [comment]
今天我也遇到这个问题，有什么解决办法吗😱
