### ISSUE TITLE
改的贼难用

### ISSUE THREAD

**Issue by mebiuscycler** [kkevsekk1/AutoX#722]
本来加个自动换行就能让手机编写简洁又方便，等了那么久都没出，添加一些乱七八糟的功能，行数那么宽还占据代码的位子，每行的头一个字点都点不了，真不如autojs的编辑器方便

**Comment by mebiuscycler** [comment]
我的天，连个全选功能都要弄没

**Comment by aiselp** [comment]
目前还处于开发阶段，你可以点击右侧的小图标打开旧编辑器

**Comment by LYS86** [comment]
![关闭全部](https://github.com/kkevsekk1/AutoX/assets/106499400/ad676c3b-0ccf-4c6f-9ff2-8a137d911f16)
![Screenshot_20231111_235118](https://github.com/kkevsekk1/AutoX/assets/106499400/abb38ba4-84e4-4291-a8aa-a91912e86a8d)
![Screenshot_20231111_235059](https://github.com/kkevsekk1/AutoX/assets/106499400/6ef01c35-694d-4941-b033-380f4f6c376b)
![Screenshot_20231111_235019](https://github.com/kkevsekk1/AutoX/assets/106499400/2658ff5e-d240-42bc-b1f5-6d1a442e913a)
![th](https://github.com/kkevsekk1/AutoX/assets/106499400/494aa564-764e-4c1a-9140-22106f598432)

 @aiselp

**Comment by vnpp** [comment]
真的忍不住登下号，这是开源issue，有问题直接贴问题 开源作者 有时间会更新的，人家免费给你肝 说难用为啥不自己fork 自己开源  作者可以搞机器人 没有按问题描述的 可以自动关闭了

**Comment by yoonasy** [comment]
作者没时间吐槽我来吐槽 这些人惯着干嘛 每日每夜开源 初版本来就有问题 哪个不是时间沉淀迭代版本 说话真搞笑 作者不维护了你们自己开源吧   
 @aiselp  可以贴一个团队的咖啡二维码呗

**Comment by utasora** [comment]
基本的礼仪能懂再说话能行不, 又没有人欠你的, 说话能好听点再张嘴, 不行建议退出GitHub.

**Comment by mebiuscycler** [comment]
不要再说了，我错了😭，是我口臭🤢

**Comment by sindon123** [comment]
来源维护不易，理解下大佬

**Comment by msccreater** [comment]
建议用电脑VSCode编辑，aj只用来执行

**Comment by LieYan-Y** [comment]
> 目前还处于开发阶段，你可以点击右侧的小图标打开旧编辑器

我觉得挺好用的

**Comment by LTAND** [comment]
建议作者关闭该issues

**Comment by kkevsekk1** [comment]
虚心接受建议，等发起人关



发送自我的盖乐世



-------- 原始信息 --------
发件人： LTAND ***@***.***>
日期: 2023/11/29 09:55 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 改的贼难用 (Issue #722)


建议作者关闭该issues

―
