### ISSUE TITLE
6.5.4编辑器格式化问题

### ISSUE THREAD

**Issue by hlyzhot** [kkevsekk1/AutoX#724]
会将
``` js
_task_.bottleTask(
    accessTokens[i],
    userNames[i],
    needToSave,
    driveIds[i].resourceDriveId
  );
```
格式化为
``` js
_task_.bottleTask(
  accessTokens[i],
  userNames[i],
  needToSave,
  driveIds[i].resourceDriveId,
);
```

**Comment by aiselp** [comment]
这有啥问题？格式化后明显好看多了

**Comment by hlyzhot** [comment]
> 这有啥问题？格式化后明显好看多了

最后多了个逗号，运行报错

**Comment by aiselp** [comment]
正常情况下有没有逗号是没有区别的，不过本来也有计划添加格式化选项，到时候你可以选择加还是不加

**Comment by hlyzhot** [comment]
> 正常情况下有没有逗号是没有区别的，不过本来也有计划添加格式化选项，到时候你可以选择加还是不加

6.5.5设置javascript没找到相关选项，prettier.trailingComma设置了none，格式化还是会加上逗号，是还需要设置别的吗？
另外，两个问题：
1. 设置页不能左右滑动，长一点的文字显示不全，而且滑动有种卡顿掉帧的感觉，不知道是不是手机问题，我的手机是红米note9 5g，MIUI14，安卓12
2. 打开编辑器有几率触发：划一下就弹出一次输入法

**Comment by aiselp** [comment]
由于碰到了难以解决的问题，这个版本编辑器还没有更新

**Comment by hlyzhot** [comment]
6.5.6里的启用prettier格式化会自动关闭
