### ISSUE TITLE
toast命令离开autoxjs界面后失效

### ISSUE THREAD

**Issue by cnbigtree** [kkevsekk1/AutoX#731]
1. Autox.js 版本：654
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：魅族17pro
5. Android 系统类别：flyme
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：toast在autoxjs的界面时有效，但是到了其他软件的界面上就无效了。我的脚本是操作其他软件，肯定是需要跳到其他软件的。我已经打开了悬浮窗的权限，依然无效。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by xjqm-tao** [comment]
MIUI 14有类似情况，我把AutoX的通知权限打开就正常了，你试试

**Comment by LYS86** [comment]
看下通知权限有没有开启

**Comment by xxl-cc** [comment]
问题依旧
