### ISSUE TITLE
console.show()控制台会挡住屏幕的坐标点击

### ISSUE THREAD

**Issue by cnbigtree** [kkevsekk1/AutoX#733]
1. Autox.js 版本：654
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：魅族17
5. Android 系统类别：flyme
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：console.show()控制台会挡住屏幕的坐标点击
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by mhsjzsq** [comment]
可以试试点击之前隐藏
console.hide()
点击完后
console.show()

**Comment by ximengxuan** [comment]
这个是正常的，可以自己实现一个能穿透点击的日志框。
