### ISSUE TITLE
captureScreen()函数频发阻塞

### ISSUE THREAD

**Issue by xjqm-tao** [kkevsekk1/AutoX#734]
1. Autox.js 版本：654、653……等多个版本
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：Redmi Note 11T Pro
5. Android 系统类别：MIUI 14
7. 问题描述：
captureScreen()函数较大概率阻塞，一旦发生，本次运行生命周期一直堵塞。

脚本测试代码：
`
if (!requestScreenCapture()) { //权限请求(无root)，
    toastLog("请求截图权限失败");
    exit();
} else {
    toastLog("屏幕权限申请成功");
    //测试截屏函数
        toastLog("测试截屏函数…");
        sleep(170);
        let test = false;
        threads.start(function () {
            captureScreen();
            test = true;
        });
        sleep(260);
        if (test) {
            log("截屏函数正常");
        } else {
            dialogs.alert("警告", "截屏函数堵塞");
            exit();
        }
    };
`

**Comment by LYS86** [comment]
#653 #611 #551 
目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题

**Comment by xjqm-tao** [comment]
> 我觉得是你手机问题，这个例子运行了十多次没出现过一次

你的手机安卓系统版本是13吗？
我两部Redmi Note 11T Pro都出现这问题，如果这个测试脚本还含有更多的其他操作代码，发生概率更大。

**Comment by aiselp** [comment]
同样是安卓13但不是miui，看来这个bug是miui14独有的

xjqm-tao ***@***.***> 于 2023年11月20日周一 08:57写道：

**Comment by sindon123** [comment]
我的iqoo7和小米8也经常会遇到😳

**Comment by tmkmk** [comment]
雷电模拟器 captureScreen() 快速连续截图. 不管是否recycle 释放.都会在大概两三次左右 就出现阻塞十来秒的情况

**Comment by LYS86** [comment]
我记得截图有一个问题，连续截取同一画面，会越来越慢，手动点一下又恢复了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 晚上11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] captureScreen()函数频发阻塞 (Issue #734)




 
雷电模拟器 captureScreen() 快速连续截图. 不管是否recycle 释放.都会在大概两三次左右 就出现阻塞十来秒的情况

**Comment by xjqm-tao** [comment]
没有解决
