### ISSUE TITLE
打开编辑器会生成2个后台

### ISSUE THREAD

**Issue by msccreater** [kkevsekk1/AutoX#738]
1. Autox.js 版本：654
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米14
5. Android 系统类别：HyperOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：打开编辑器，后台会有2个
8. 报错日志（可选）：
9. 屏幕截图（可选）：

能只保留一个吗？

**Comment by kkevsekk1** [comment]
6.5.5还有没？截图看看
