### ISSUE TITLE
autox在后台时无法通过广播触发运行脚本

### ISSUE THREAD

**Issue by yyy-forever** [kkevsekk1/AutoX#739]
1. Autox.js 版本：654
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米14
5. Android 系统类别：HyperOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：我将一个脚本的定时任务设置为特定事件（广播）触发，autox位于前台时能触发并正常运行脚本，但当autox在后台时，会显示为运行中脚本但没有效果，图中是tasker发送intent通过广播触发，我试了连接电源触发，也是一样的情况
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![Screenshot_2023-11-22-16-25-59-964_org autojs aut](https://github.com/kkevsekk1/AutoX/assets/52322707/1475bc03-cad2-4ad8-a423-724ff807dba6)

**Comment by 2-3-5-7** [comment]
我是 红米K60 HyperOS 用的 autox 自带的定时执行，更新到 6.5.5 就正常了，6.5.4 没法操作 App

**Comment by yyy-forever** [comment]
> 我是 红米K60 HyperOS 用的 autox 自带的定时执行，更新到 6.5.5 就正常了，6.5.4 没法操作 App

感谢回复，没关注更新，更新完确实没问题了
