### ISSUE TITLE
老用户，登录需要邀请码，你懂的

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [kkevsekk1/AutoX#74]
![Screenshot_20210701_023439.jpg](https://user-images.githubusercontent.com/65865633/124013464-e6b8bd80-da14-11eb-85a2-e608d79db97f.jpg)

**Comment by kkevsekk1** [comment]
57



发送自我的盖乐世



-------- 原始信息 --------
发件人： NMSL-code ***@***.***>
日期: 2021/7/1 02:35 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 老用户，登录需要邀请码，你懂的 (#74)


[Screenshot_20210701_023439.jpg]<https://user-images.githubusercontent.com/65865633/124013464-e6b8bd80-da14-11eb-85a2-e608d79db97f.jpg>

―

**Comment by Autfy** [comment]
这个邀请码, 怎么获取

**Comment by kkevsekk1** [comment]
57



发送自我的盖乐世



-------- 原始信息 --------
发件人： Autfy ***@***.***>
日期: 2021/7/9 02:31 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 老用户，登录需要邀请码，你懂的 (#74)


这个邀请码, 怎么获取

―

**Comment by a4081675** [comment]
邀请码：544

**Comment by ZhengchaoCao** [comment]
邀请码：637
