### ISSUE TITLE
请问有没有蓝牙接收信息的脚本啊？

### ISSUE THREAD

**Issue by mebiuscycler** [kkevsekk1/AutoX#742]
把一个对话框选项的脚本打包安装在我的wearos手表上，然后手表可以通过蓝牙传递选项来执行脚本。
还是说autoxjs本就不支持这样的？

**Comment by kkevsekk1** [comment]
你想办法可以实现



发送自我的盖乐世



-------- 原始信息 --------
发件人： mebiuscycler ***@***.***>
日期: 2023/11/26 20:06 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问有没有蓝牙接收信息的脚本啊？ (Issue #742)


把一个对话框选项的脚本打包安装在我的wearos手表上，然后可以通过蓝牙传递选项来执行脚本。
还是说autoxjs本就不支持这样的？

―
