### ISSUE TITLE
files.appendBytes追加文件数据被覆写

### ISSUE THREAD

**Issue by 239144498** [kkevsekk1/AutoX#745]
1. Autox.js 版本：6.5.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 7.1
4. Android 机型：OPPO
5. Android 系统类别：Android
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用下面代码进行文件二进制追加写入，会导致之前的内容被覆盖，无法实现追加写入功能，麻烦作者大大修复该bug，感谢你的工作，祝你生活愉快。

> var ByteBuffer = java.nio.ByteBuffer;
var buffer = ByteBuffer.allocate(4);
buffer.order(java.nio.ByteOrder.LITTLE_ENDIAN);
buffer.putInt(0x73 & 0xFFFF);
files.appendBytes(inputpath, Array.from(buffer.array()));

9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by aiselp** [comment]
files.appendBytes接收的是java的字节数组，不要用Array.from
