### ISSUE TITLE
运行文档代码"带有输入框的对话框"报错

### ISSUE THREAD

**Issue by Cryogenic-yosa** [kkevsekk1/AutoX#749]
1. Autox.js 版本：655
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：iqoo
5. Android 系统类别：橘子
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：运行文档里的代码
`dialogs.build({
    title: "请输入",
    positive: "确定",
    negative: "取消",
    inputPrefill: ""
}).on("input", (text, dialog)=>{
    toast("你输入的是" + text);
}).show();`
报错，显示
TypeError: Cannot call method "emit" of null (/android_asset/modules/__dialogs__.js#158)
TypeError: Cannot call method "emit" of null
    at /android_asset/modules/__dialogs__.js:158:0
    at /android_asset/modules/__dialogs__.js:136:0
    at /android_asset/modules/__ui__.js:89:0
![IMG_20231130_013717](https://github.com/kkevsekk1/AutoX/assets/60252973/544a7dfa-1fe7-4c90-b9cb-79c31daab379)

![Screenshot_20231130_013251](https://github.com/kkevsekk1/AutoX/assets/60252973/3944d9aa-21f2-497b-a01d-5a33bd48c1c0)

**Comment by bukkumaaku** [comment]
同样也遇到了相同的问题，翻issue似乎很早之前就有这个问题了
