### ISSUE TITLE
每天一次定时任务无法运行。发现都对堆积在运行中脚本没有执行

### ISSUE THREAD

**Issue by cz1980** [kkevsekk1/AutoX#750]
Autox.js 版本：6.5.5
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：鸿蒙3.0
Android 机型：华为mate10
问题描述：运行文档里的代码
if(!isWeekend()){ //非周末
    delayTime = random()*1000*60*5; //随机延时0-5分钟
    //随机等待05-分钟
    //sleep(delayTime)
    //唤醒设备
    var StartUpTime =new Date().toString();
    device.wakeUp()
    sleep(3000)
    auto.waitFor()
    //因为requestScreenCapture每次申请截图权限都会弹出对话框阻塞了脚本的运行。因此需要新开线程
    threads.start(function ()
    {
        sleep(5e3)
        click(787,1769)
    })
    //申请截图权限
    while(!requestScreenCapture());
    app.launchApp("小红书")
   click(540,1800)
   var img  = captureScreen("/sdcard/脚本/sc.png");

}
前面的代码是这样的。计划任务为一天执行一次，好像都没有执行卡住了。一看都还在躺在“运行中的脚本”里面、

**Comment by fanlushuai** [comment]
看你贴的代码，太费神。是不是截图权限的问题。

```js

function once(fn, context) {
  var result;
  // 注意，此处为了防止，并发，加了sync。
  return sync(function () {
    if (fn) {
      log("执行一次");
      result = fn.apply(context || this, arguments);
      fn = null;
    } else {
      // log("已经执行")
    }
    return result;
  });
}

AutojsE={
autoPermisionScreenCapture: once(function () {
    console.log("自动申请截图权限");
    let Thread = threads.start(function () {
      if (auto.service != null) {
        //如果已经获得无障碍权限
        //由于系统间同意授权的文本不同，采用正则表达式
        let Allow = textMatches(/(允许|立即开始|统一)/).findOne(10 * 1000);
        if (Allow) {
          Allow.click();
        }
      } else {
        log("未发现权限服务调用");
      }
    });
    log("申请权限");

    //在一个会话中，调用两次申请截图权限。就会卡死。
    if (!requestScreenCapture(false)) {
      log("请求截图权限失败");
      return false;
    } else {
      Thread.interrupt();
      log("已获得截图权限");
      return true;
    }
  })
}

//使用
AutojsE.autoPermisionScreenCapture()

```
