### ISSUE TITLE
未在Autoxjs主界面或没有开启悬浮窗时，无法执行app.startActivity

### ISSUE THREAD

**Issue by bukkumaaku** [kkevsekk1/AutoX#751]
1. Autox.js 版本：655
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：IQOO 11s
5. Android 系统类别：origin os 3
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：

在以下情况时，无法执行app.startActivity
当主界面不是Autoxjs

在以下情况时，可以执行app.startActivity
1、主界面是Autoxjs
2、打开了Autoxjs的悬浮窗（只赋予悬浮窗权限而不打开悬浮窗是不行的）

但往往是为了美观是不打开悬浮窗使用的，排查了好久才发现这个问题

另外也有dialogs.build里面有inputPrefill就会报错的问题

**Comment by fanlushuai** [comment]
还是打开比较好，看样子，估计是android的问题。

**Comment by aiselp** [comment]
我觉得这是安卓的限制
