### ISSUE TITLE
Java class "com.stardust.autojs.core.image.ImageWrapper" has no public instance field or method named "pixel"

### ISSUE THREAD

**Issue by pxysea** [kkevsekk1/AutoX#752]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：OPPO r15
5. Android 系统类别：Color os
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：Java class "com.stardust.autojs.core.image.ImageWrapper" has no public instance field or method named "pixel"
8. 报错日志（可选）：
9. 屏幕截图（可选）：
`var p = Image.pixel(x,y);
    log(p);`

**Comment by LYS86** [comment]
用法不对
```
let a = Image(100, 100);
let b = a.pixel(50, 50);
log(b);
a.saveTo('/sdcard/测试.png');
```
