### ISSUE TITLE
获取不到大麦选择立即预定的控件

### ISSUE THREAD

**Issue by freeFesei** [kkevsekk1/AutoX#755]
1. Autox.js 版本：655
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：vivo nex
5. Android 系统类别：OriginOS

7. 问题描述：用布局分析的时候没有看到购买的那个控件
8. 问题截图
![image](https://github.com/kkevsekk1/AutoX/assets/37429785/b7b0387e-ca90-442c-8fff-20a9110c4bdc)

**Comment by Liberations** [comment]
他们搞了自定义吧 防无障碍分析

**Comment by Alex-Shang** [comment]
用坐标呗
