### ISSUE TITLE
scrollup，scrolldown ，scrollleft，scrollright的滑动无效

### ISSUE THREAD

**Issue by cnbigtree** [kkevsekk1/AutoX#757]
1. Autox.js 版本：655
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 8
4. Android 机型：魅族16s
5. Android 系统类别：flyme
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：针对控件使用scrollup，scrolldown ，scrollleft，scrollright滑动无效。虽然这个写的是针对集合，但是实际应用上，我们更需要的是针对控件的，可以明确方向并且有布尔返回值的。所以这几个方法让人容易迷惑。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这些是安卓组件本身支持，我们就支持



发送自我的盖乐世



-------- 原始信息 --------
发件人： cnbigtree ***@***.***>
日期: 2023/12/6 10:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] scrollup，scrolldown ，scrollleft，scrollright的滑动无效 (Issue #757)


  1.  Autox.js 版本：655
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 8
  4.  Android 机型：魅族16s
  5.  Android 系统类别：flyme
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：针对控件使用scrollup，scrolldown ，scrollleft，scrollright滑动无效。虽然这个写的是针对集合，但是实际应用上，我们更需要的是针对控件的，可以明确方向并且有布尔返回值的。所以这几个方法让人容易迷惑。
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―
