### ISSUE TITLE
有些软件的按钮无法触发点击事件

### ISSUE THREAD

**Issue by 0cafe** [kkevsekk1/AutoX#758]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米8
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述： 有些软件的按钮无法触发点击事件，试过控件的click()和区域的click(x,y),还有shell("input tap " + x + " " + y, true) 也试过无法触发按钮的点击事件 但是看到按钮有被按下的样式出现，例如大麦APP的”立即预订”按钮。请问大佬们有什么方法可以实现点击？
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
是不是有检测，点击区域，或者在安卓调试中，将指针位置打开，看点击到了哪里。或者加长点击时间。

**Comment by wuwudong** [comment]
我也遇到这个问题了，大麦的app 的立即抢购总是点不动，就是不跳转

**Comment by kkevsekk1** [comment]
肯定是app有检测



发送自我的盖乐世



-------- 原始信息 --------
发件人： wuwudong ***@***.***>
日期: 2023/12/11 13:13 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 有些软件的按钮无法触发点击事件 (Issue #758)


我也遇到这个问题了，大麦的app 的立即抢购总是点不动，就是不跳转

―

**Comment by sindon123** [comment]
有的是检测无障碍点击导致的

**Comment by wahahababaozhou** [comment]
大麦的app 的立即抢购，click坐标点不动，有解决方案吗

**Comment by 1195343015** [comment]
> 有的是检测无障碍点击导致的

APP还可以检测到无障碍点击吗？
