### ISSUE TITLE
编辑器优化建议

### ISSUE THREAD

**Issue by kkevsekk1** [kkevsekk1/AutoX#761]
@aiselp 编辑器最近我好几次程序崩溃了，可能还需要优化一下。
其他人报错的截图，或者优化的意见提上来。搞个标签编辑器问题。最近我们集中升级几个版本。

**Comment by kkevsekk1** [comment]
没有深度使用的少提个性化想法

**Comment by aiselp** [comment]
崩溃大概是因为改了activity启动模式，导致没法保持单实例，下次更新还是改回来

**Comment by aiselp** [comment]
还有大概没法适配旧的设备了，核心依赖使用了无法转换的es2020语法，最低要求Chrome >=87，如果没有手动更新webview，只有安卓11及以上出厂版本才会高于这个
