### ISSUE TITLE
控制台崩溃

### ISSUE THREAD

**Issue by LYS86** [kkevsekk1/AutoX#763]
旧编辑器，从菜单栏打开控制台崩溃，其他-控制台
![image](https://github.com/kkevsekk1/AutoX/assets/106499400/25f30d5d-acb8-4cf3-9039-c2f371351ffb)

**Comment by LYS86** [comment]
![image](https://github.com/kkevsekk1/AutoX/assets/106499400/a365ed01-545f-4978-9963-3236fe2144e9)

**Comment by aiselp** [comment]
报错原因和在ui脚本或ui线程调用console.show类似，旧api设计问题
