### ISSUE TITLE
device.width和device.height获取不到屏幕的像素

### ISSUE THREAD

**Issue by zhangfubao** [kkevsekk1/AutoX#764]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：小米10s，安卓13，获取不到屏幕的像素
9. 屏幕截图（可选）：
![Screenshot_2023-12-12-11-16-53-958_org autojs autoxjs v6](https://github.com/kkevsekk1/AutoX/assets/22114098/5aabc687-d6e3-43cd-938f-fa524b0adef1)
![Screenshot_2023-12-12-11-19-39-521_com android settings](https://github.com/kkevsekk1/AutoX/assets/22114098/1e06df9d-83b4-4055-95f7-95e13f1bcbae)
![Screenshot_2023-12-12-11-19-50-394_com android settings](https://github.com/kkevsekk1/AutoX/assets/22114098/9593bae5-949b-48f8-b3df-41b463c7aef7)

**Comment by stingbo** [comment]
我也碰到这个问题了
