### ISSUE TITLE
JSON.stringify（）函数引用会出现JavaException: java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations

### ISSUE THREAD

**Issue by mlwn-2023** [kkevsekk1/AutoX#766]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android9
4. Android 机型：雷电模拟器
5. Android 系统类别：模拟器
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
function Saveconf() {
    var Path = "/sdcard/autoxjs/conf/config.dat";
    try {
        var env = {
            xsrw: false,
            up3: false,
            hqls: false,
            yjzh: false,
            zhhhc: false,
            yjhc: false,
            hqlscs: "",
            changingConfigurations: 0
        };
        var key;
        var cz1 = ['xsrw', 'up3', 'hqls', 'yjzh', 'zhhhc', 'yjhc', 'hqlscs'];

        for (var i = 0; i < cz1.length; i++) {
            if (i < cz1.length - 1) {
                key = ui[cz1[i]].isChecked();
                env[cz1[i]] = key;
            } else {
                key = ui[cz1[i]].getText();
                env[cz1[i]] = key;
            }
        }

        log(env);
        var jsonString = JSON.stringify(env);
        log(jsonString);

        // 将 JSON 字符串写入文件
        files.write(Path, jsonString);
    } catch (error) {
        toastLog(error);
    }
}

9. 报错日志（可选）：
17:34:22.391/D: { JavaException: java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations
	at /android_asset/modules/__json2__.js:234 (str)
	at /android_asset/modules/__json2__.js:338 (str)
	at /android_asset/modules/__json2__.js:414
	at [remote]UI.js:87 (Saveconf)
	at [remote]UI.js:56

  fileName: '/android_asset/modules/__json2__.js',
  lineNumber: 234 }
11. 屏幕截图（可选）：

**Comment by 905588347** [comment]
function saveConfig() {
    var configFile = "/sdcard/config.json";
    var csstr = ui.lqlscs.getText();
    var configData = {
        //   xsrw: ui.xsrw.isChecked(),
        //   up3: ui.up3.isChecked(),
        lqlscs: csstr, //文本
        hqls: ui.hqls.isChecked(),//布尔值
        yjzh: ui.yjzh.isChecked(),//布尔值
        zhhhc: ui.zhhhc.isChecked(),//布尔值
        yjhc: ui.yjhc.isChecked(),//布尔值

    };
    log(configData)
    try {
        var jsonString = JSON.stringify(configData);
        files.write(configFile, jsonString);
    } catch (error) {
        toastLog("Failed to write config file: " + error);
    }

}

**Comment by 905588347** [comment]
好像是不同类型的数据就要报错JavaException: java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations
