### ISSUE TITLE
无法创建快捷方式

### ISSUE THREAD

**Issue by wunaidejianao** [kkevsekk1/AutoX#767]
1. Autox.js 版本：6.5.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米11
5. Android 系统类别：MIUI
6. 问题描述：无法创建快捷方式，同时会导致桌面重载。

**Comment by 123maple321** [comment]
我升级了澎湃OS，也是这个问题
