### ISSUE TITLE
images.resize 报错，Wrapped java.lang.NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by pxysea** [kkevsekk1/AutoX#768]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：Oppo r15
5. Android 系统类别：Color os
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
`let img1 = images.read("/sdcard/Aladin/ocr_img/ywrs_main1.png");    
 let img = images.resize(img1, [1080, 2280]);`
运行以上代码时报错
8. 报错日志（可选）：
`Wrapped java.lang.NullPointerException: Attempt to read from null array ([remote]test.js#199)
Wrapped java.lang.NullPointerException: Attempt to read from null array`
10. 屏幕截图（可选）：
![微信图片_20231217105017](https://github.com/kkevsekk1/AutoX/assets/3711185/ff1497cb-3f15-4ae2-9954-c21c6eba4ac2)
[
![微信图片_20231217105124](https://github.com/kkevsekk1/AutoX/assets/3711185/33ce2a25-9354-4aa6-8362-5ec25eb2cab0)
](url)

**Comment by LYS86** [comment]
检查代码，无异常
```
let img = Image(100, 100);
img.saveTo('/sdcard/1.png');
img = images.read('/sdcard/1.png');
img = images.resize(img, [1080, 2280]);
img.saveTo('/sdcard/2.png');
```
