### ISSUE TITLE
请问脚本使用的视频教程链接可以发一下吗？在知乎上没有找到

### ISSUE THREAD

**Issue by aIceCola** [kkevsekk1/AutoX#771]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
这个我都不记得了😁和autojs
一样



发送自我的盖乐世



-------- 原始信息 --------
发件人： aIceCola ***@***.***>
日期: 2023/12/18 10:26 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 请问脚本使用的视频教程链接可以发一下吗？在知乎上没有找到 (Issue #771)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：
