### ISSUE TITLE
荣耀手机的magicOS7.2 调用截屏方法captureScreen() 会一直阻塞不能继续执行，调用requestScreenCapture()有反应并且点击了允许

### ISSUE THREAD

**Issue by jilangyangbo** [kkevsekk1/AutoX#773]
1. Autox.js 版本：6.5.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：荣耀100PRO
5. Android 系统类别：MagicOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述： 调用截屏方法captureScreen() 会一直阻塞不能继续执行，调用requestScreenCapture()有反应并且点击了允许
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
requestScreenCapture 初始化调用一次，后续不再且不能再调用

**Comment by jilangyangbo** [comment]
我是只调用了一次requestScreenCapture 的
第一次调用requestScreenCapture() 后再调用captureScreen() 就一直阻塞了

**Comment by LYS86** [comment]
# 多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
```
promise = Promise.resolve(123);
promise .wait()
```
https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22

# captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知
> #653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题

**Comment by jilangyangbo** [comment]
并没有开启安全模式,感觉和andriod13系统有关系,希望大神能帮忙看下 @kkevsekk1

**Comment by wingswing1** [comment]
> # 多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
> ```
> promise = Promise.resolve(123);
> promise .wait()
> ```
> 
> https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22
> 
> # captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知
> > #653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题

请问一下“小米关闭所有安全模式可以解决”具体怎么操作？我是小米MIUI14+安卓13

**Comment by jilangyangbo** [comment]
我的荣耀手机用  autox.js 6.5.7版本 可以正常截图了

**Comment by jilangyangbo** [comment]
> > # 多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
> > ```
> > promise = Promise.resolve(123);
> > promise .wait()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22
> > 
> > # captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知
> > > #653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题
> 
> 请问一下“小米关闭所有安全模式可以解决”具体怎么操作？我是小米MIUI14+安卓13

你可以试试autox.js 6.5.7版本

**Comment by LYS86** [comment]
我关了应用安全验证，安全守护，电诈防护的屏幕共享，风险应用预警，具体是哪个影响的我不知道，你能关的都关了试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] 荣耀手机的magicOS7.2 调用截屏方法captureScreen() 会一直阻塞不能继续执行，调用requestScreenCapture()有反应并且点击了允许 (Issue #773)




  
多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
 promise = Promise.resolve(123); promise .wait()  
https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22
 
captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知
  
#653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题
   
请问一下“小米关闭所有安全模式可以解决”具体怎么操作？我是小米MIUI14+安卓13

**Comment by wingswing1** [comment]
好的谢谢～



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月24日 17:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [kkevsekk1/AutoX] 荣耀手机的magicOS7.2 调用截屏方法captureScreen() 会一直阻塞不能继续执行，调用requestScreenCapture()有反应并且点击了允许 (Issue #773) |

我关了应用安全验证，安全守护，电诈防护的屏幕共享，风险应用预警，具体是哪个影响的我不知道，你能关的都关了试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午3:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] 荣耀手机的magicOS7.2 调用截屏方法captureScreen() 会一直阻塞不能继续执行，调用requestScreenCapture()有反应并且点击了允许 (Issue #773)





多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
promise = Promise.resolve(123); promise .wait()
https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22

captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知

#653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题

请问一下“小米关闭所有安全模式可以解决”具体怎么操作？我是小米MIUI14+安卓13

**Comment by wingswing1** [comment]
> > > # 多次调用requestScreenCapture阻塞由Promise.wait引起，在进入wait前返回resolve()会阻塞
> > > ```
> > > promise = Promise.resolve(123);
> > > promise .wait()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__threads__.js#L22
> > > 
> > > # captureScreen阻塞参考#734，小米关闭所有安全模式可以解决，具体原因未知
> > > > #653 #611 #551 目前已知出问题的都是小米MIUI14+安卓13的，在Android Studio的avd使用安卓13也可以复现该问题
> > 
> > 
> > 请问一下“小米关闭所有安全模式可以解决”具体怎么操作？我是小米MIUI14+安卓13
> 
> 你可以试试autox.js 6.5.7版本

您的手机是安卓13的系统吗？
