### ISSUE TITLE
捕获横屏屏幕，所得图片尺寸错误

### ISSUE THREAD

**Issue by UraraChiya** [kkevsekk1/AutoX#774]
1. Autox.js 版本：6.5.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米平板6 Pro
5. Android 系统类别：MIUI Pad
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：纯白屏幕画面进行截图，尝试获取指定坐标颜色，所得到的颜色总为 #000000
8. 报错日志（可选）：
9. 屏幕截图（可选）：

![Screenshot_2023-12-18-19-57-21-333_com miui gallery](https://github.com/kkevsekk1/AutoX/assets/47343409/a16ed5f9-89de-4455-b6e7-82b123bb4bd6)
![Screenshot_2023-12-18-19-57-36-760_bin mt plus canary](https://github.com/kkevsekk1/AutoX/assets/47343409/9ed4f910-61ca-426d-be03-95fb6e9596b5)

**Comment by aiselp** [comment]
保存到本地看看图片是黑的还是白的？

**Comment by UraraChiya** [comment]
实际保存的图片如图一
![1](https://github.com/kkevsekk1/AutoX/assets/47343409/f0883c8e-414f-4487-9336-91b9c654acb3)
![Screenshot_2023-12-18-23-01-27-711_bin mt plus canary](https://github.com/kkevsekk1/AutoX/assets/47343409/dfabc95b-12ee-4778-ad8c-1b41dec9b9a7)

**Comment by UraraChiya** [comment]
上下具有两个透明区域
![image](https://github.com/kkevsekk1/AutoX/assets/47343409/60462c95-6fe3-41fb-bf02-27e47efa7c9e)

**Comment by aiselp** [comment]
看起来并非api的错误，至于截屏尺寸是和截屏方向有关，自己多看看文档

**Comment by lvq410** [comment]
同遇到相同的问题，同样的机型
requestScreenCapture() true/false都没啥用
事实上这个机型 小米平板6 Pro，横屏时，微信的视频会话的表现也很神奇，和这种上下有空白的图片效果很像
我的解决方式是切图然后做缩放

**Comment by chookg** [comment]
同样的问题，雷电模拟器
