### ISSUE TITLE
获取当前活动异常 v6.5.6

### ISSUE THREAD

**Issue by nashsophie** [kkevsekk1/AutoX#777]
1. Autox.js 版本：6.5.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：三星 s10
5. Android 系统类别
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

获取当前活动异常 v6.5.6

```
// 获取当前正在运行的活动
var currentActivity = currentActivity();
console.log("Current Activity: " + currentActivity);
```

16:13:41.225/E: TypeError: currentActivity is not a function, it is undefined. ([remote]post.js#62)
TypeError: currentActivity is not a function, it is undefined.

**Comment by LYS86** [comment]
currentActivity 函数被覆盖了，检查代码
