### ISSUE TITLE
新编辑器的三个问题

### ISSUE THREAD

**Issue by mebiuscycler** [kkevsekk1/AutoX#779]
1，相比旧编辑器，实在是太卡顿，尤其是点击后经常会显示不出内容，需要重新打开
2，编辑器的设置会自动恢复默认，设置文字大小和自动换行，过一会就会自动恢复原始大小和off，尤其是自动换行
3，由于缺乏关标移动功能导致无法对段落代码进行剪切删除复制，所以要删除剪切某一段代码变得极其麻烦，只能按一行一行的复制

**Comment by LYS86** [comment]
输入法可能没适配，使用下方工具栏进行范围选择
