### ISSUE TITLE
关于tasker联动autox.js的两个问题

### ISSUE THREAD

**Issue by mikasaaaaa14** [kkevsekk1/AutoX#780]
1.Autox.js 版本：655
2.Autox.js 下载渠道：https://githubfast.com/kkevsekk1/AutoX/releases
3.Android 版本：Android 13
4.Android 机型：IQOO6SE
5.Android 系统类别：origin os 3
6.VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7.问题描述：1.用tasker赋予autox.js无障碍权限的时候无法直接赋予，需要在autox.js点击一下"去设置"才可以。
                     2.用tasker启动autox.js脚本时，在tasker的任务界面可以启动，但是当切换到配置界面，设置固定时间脚本时无任何反应。
                    （这个问题在1+6t里面不会出现。）

**Comment by ZJRui** [comment]
同问。

**Comment by ZJRui** [comment]
1.给Autojs APP设置了开通无障碍服务，但是如果AutoJs 一旦被 杀死了，下次启动了Autojs还需要再次打开设置 给AUtojs开通无障碍服务权限。  有没有办法 只需要设置一次赋权 后面不需要重复赋权？

2.  workmanager 设置的每天定时任务，在息屏状态下不会唤醒屏幕 执行脚本。 虽然脚本里面写了device.wakeup和手势解锁，但是定时任务没有执行。  只有在手动屏幕唤醒后 才会 执行已经 到时的定时任务。

**Comment by kkevsekk1** [comment]
用谷歌的安卓系统就没有这个问题，其他都有



发送自我的盖乐世



-------- 原始信息 --------
发件人： sachin ***@***.***>
日期: 2024/3/2 12:44 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 关于tasker联动autox.js的两个问题 (Issue #780)


1.给Autojs APP设置了开通无障碍服务，但是如果AutoJs 一旦被 杀死了，下次启动了Autojs还需要再次打开设置 给AUtojs开通无障碍服务权限。 有没有办法 只需要设置一次赋权 后面不需要重复赋权？

  1.  workmanager 设置的每天定时任务，在息屏状态下不会唤醒屏幕 执行脚本。 虽然脚本里面写了device.wakeup和手势解锁，但是定时任务没有执行。 只有在手动屏幕唤醒后 才会 执行已经 到时的定时任务。

―
