### ISSUE TITLE
autox.js有findText()这个方法吗

### ISSUE THREAD

**Issue by huaidanatu** [kkevsekk1/AutoX#782]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：有找文字的方法吗，找到文字并返回坐标
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by LYS86** [comment]
自行封装函数textMatches和descMatches
