### ISSUE TITLE
编辑器无法正常显示，一片空白！

### ISSUE THREAD

**Issue by wochenjinghe** [kkevsekk1/AutoX#784]
1. Autox.js 版本：6.5.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：酷比魔方iPlay 40 5G（平板）
5. Android 系统类别：原生
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：编辑器无法正常显示，一片空白！应该是VScode太新，而Android System WebView老旧无法渲染，建议使用第三方浏览器显示！

**Comment by rabbitkiller-dev** [comment]
遇到同样的问题, 用的雷电模拟器, 安卓9
