### ISSUE TITLE
engines.all() 方法，再进行脚本切换期间报错。 Wrapped java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by gaomanyi** [kkevsekk1/AutoX#787]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：redmi k30S 至尊纪念版
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：engines.all() 方法，再进行脚本切换期间报错。 Wrapped java.util.ConcurrentModificationException 。 停止指定的脚本，再启动另一个脚本，新旧脚本之间进行切换。导致报错。  需要换成ConcurrentArrayList。或者使用iterator中的remove方法。 

8. 报错日志（可选）：
 [ /storage/emulated/0/脚本/自由调度/测试/main.js ]运行结束，用时5.938000秒

14:49:53.681/E: Wrapped java.util.ConcurrentModificationException (/android_asset/modules/__engines__.js#25)

Wrapped java.util.ConcurrentModificationException

    at /android_asset/modules/__engines__.js:25:0

    at /storage/emulated/0/脚本/自由调度/main.js:29:0
9. 屏幕截图（可选）：

**Comment by 670027822** [comment]
我也遇到了这个问题，不是每次都出现，但是频率不低
