### ISSUE TITLE
dialogs.build input 异常

### ISSUE THREAD

**Issue by kongmaster2016** [kkevsekk1/AutoX#788]
1. Autox.js 版本：6.5.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：雷电模拟器
5. Android 系统类别：
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
```
dialogs.build({
        title: "请输入您的年龄",
        inputPrefill: "18"
    }).on("input", (input)=>{
        var age = parseInt(input);
        toastLog(age);
    }).show();
```
报下图异常
9. 报错日志（可选）：
10. 屏幕截图（可选）：
![image](https://github.com/kkevsekk1/AutoX/assets/19811779/95486601-f605-45c8-a515-173412afe91f)

**Comment by LYS86** [comment]
参考#491 解决方案
https://github.com/kkevsekk1/AutoX/issues/491#issuecomment-1837206501
注释下面代码
https://github.com/kkevsekk1/AutoX/blob/4d00169b3ca016433ca8bb053e42773089f3081b/autojs/src/main/assets/modules/__dialogs__.js#L160
