### ISSUE TITLE
为什么大麦的右下角抢购按钮点击没反应啊，用坐标点击也不行，其他地方点击都没问题

### ISSUE THREAD

**Issue by thegenway** [kkevsekk1/AutoX#789]
只有下方的红色按钮，我自己手点就可以，用脚本点就没反应，是不是大麦APP做了检测，有没有什么其他办法可以处理呢？

**Comment by LoveEocding** [comment]
> 只有下方的红色按钮，我自己手点就可以，用脚本点就没反应，是不是大麦APP做了检测，有没有什么其他办法可以处理呢？

有解决方案吗

**Comment by wahahababaozhou** [comment]
有解决方案了吗？

**Comment by soyons** [comment]
同问

**Comment by zhouzhiqing8426** [comment]
貌似那个按钮只能用adb操作点击，但是adb又要插线，会有更优解吗
