### ISSUE TITLE
通过vscode插件保存项目到设备，设备编辑器中只会显示首次保存的代码

### ISSUE THREAD

**Issue by ListenV** [kkevsekk1/AutoX#790]
1. Autox.js 版本：`6.5.6`
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K30 pro
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本：Autox.js-VSCodeExt `v1.109.0`
7. 问题描述：重复使用插件功能：保存项目到设备，设备中新编辑器打开js文件会显示旧代码（在vscode中修改代码），而用老版编辑器就会显示最新修改的代码，应该是新版编辑器的显示问题，实际运行代码依然为最新代码

**Comment by LYS86** [comment]
和656以前的原编辑器一样，如果不主动关闭脚本，会一直保留。

**Comment by ListenV** [comment]
好吧，或许是我搞错了。
