### ISSUE TITLE
promise库问题

### ISSUE THREAD

**Issue by LYS86** [kkevsekk1/AutoX#791]
promise库内部有多个主动报错，需要多次跳转才能进去断点位置，是否能优化或者换一个库
![Screenshot_2024-01-04-08-59-57-235_org autojs autoxjs](https://github.com/kkevsekk1/AutoX/assets/106499400/e0f59610-c56e-48f9-85ae-7a58bf736d7d)

**Comment by aiselp** [comment]
我觉得这个库挺好的，还会自动捕获未处理的'拒绝'并打印出来，断点调试不适合这种异步代码

**Comment by LYS86** [comment]
主要这个库对断点调试有影响，每一次运行都要跳转5次才可以进入断点位置。如果软件内部不需要依赖这个库，无需内置，用户要使用，自行下载文件加载

**Comment by aiselp** [comment]
别去断点使用了promise的代码

**Comment by LYS86** [comment]
没有使用promise，你打个log(1)，也要进去promise跳五次才出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] promise库问题 (Issue #791)




 
别去断点使用了promise的代码

**Comment by LYS86** [comment]
https://github.com/kkevsekk1/AutoX/assets/106499400/07835243-3ce6-4425-a998-b25bedbf81b6

你看下这个，第一个是原始版本，第二个是Pro的promise库

**Comment by aiselp** [comment]
这应该属于断点调试的bug，不应该在没设置断点的地方暂停，假如你自己的代码中有类似的代码，暂停在未实际抛出错误的位置只会让用户混乱

**Comment by aiselp** [comment]
看了下rhino文档，调试器有一个如下方法使异常时自动中断，aj肯定设置了为true，你可以改为false试试。

`org.mozilla.javascript.tools.debugger.Dim$setBreakOnExceptions`

**Comment by LYS86** [comment]
修改setBreakOnExceptions后不再进入promise

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 晚上10:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] promise库问题 (Issue #791)




 
看了下rhino文档，调试器有一个如下方法使异常时自动中断，aj肯定设置了为true，你可以改为false试试。
 
org.mozilla.javascript.tools.debugger.Dim$setBreakOnExceptions
