### ISSUE TITLE
多次require问题

### ISSUE THREAD

**Issue by zhuanwan** [kkevsekk1/AutoX#795]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. 问题描述：新手求帮忙解惑：
有四个文件：
common.js：   封装较基础的方法
task.js：封装某个app的通用方法，会require("common.js")   
task1.js/task2.js：两个不同的任务脚本

问题：task1.js 、 task2.js 均无法再require("task.js")，请问各位都是怎么解决的，望解答

**Comment by zhuanwan** [comment]
问题描述：新手求帮忙解惑：
有四个文件：
common.js： 封装较基础的方法
task.js：封装某个app的通用方法，会require("common.js")
task1.js/task2.js：两个不同的任务脚本
问题：task1.js 、 task2.js 均无法再require("task.js")，请问各位都是怎么解决的，望解答

**Comment by aiselp** [comment]
加载相对路径的模块始终以 ./ 或 ../ 开头

**Comment by zhuanwan** [comment]
感谢aiselp
