### ISSUE TITLE
无法创建快捷方式（已经开了创建快捷方式的权限）

### ISSUE THREAD

**Issue by 123maple321** [kkevsekk1/AutoX#796]
1. Autox.js 版本：656
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：澎湃OS 1.0.6.0
4. Android 机型：小米13
5. Android 系统类别：澎湃OS 1.0.6.0
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：点击创建快捷方式的确定按钮后，屏幕右侧整体划出一个黑边然后消失，返回到桌面发现重新加载了，并且没有创建出快捷方式。

**Comment by baskgithub** [comment]
同样的问题

**Comment by aogg** [comment]
+1

**Comment by SuperDaodan** [comment]
蹲一个解决方案，如果有大佬解决了，麻烦戳我下~
