### ISSUE TITLE
6.5.7多线程异常

### ISSUE THREAD

**Issue by vtrayy** [kkevsekk1/AutoX#798]
1. Autox.js 版本：657
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米note9 5g
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
``` js
var sum = 0;
//启动子线程计算1加到10000
var thread = threads.start(function(){
    for(var i = 0; i < 10000; i++){
        sum += i;
    }
});
//等待该线程完成
thread.join();
toast("sum = " + sum);
```
线程不会自动结束

**Comment by jawelee** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xjqm-tao** [comment]
我测试发现thread.join()函数好像会阻塞，然后貌似也影响别的线程运行。
结束脚本后含死循环的子线程还在一直运行，除非结束AutoX.js

**Comment by aiselp** [comment]
确实存在该问题，后续版本修复

**Comment by aiselp** [comment]
> 我测试发现thread.join()函数好像会阻塞，然后又不知道什么问题也影响到更多其他的线程运行。 结束脚本后含死循环的子线程还在一直运行，除非结束AutoX.js

这个问题没法复现，可能你的线程由java库创建，这种线程不受脚本框架管理
