### ISSUE TITLE
报毒

### ISSUE THREAD

**Issue by likejing** [kkevsekk1/AutoX#799]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
小米的最新版系统  安装用autox生成的软件会报毒

**Comment by sindon123** [comment]
一直都会报毒，用mt管理器替换下，重新签名就行了

**Comment by likejing** [comment]
您好，我已收到您的邮件，将尽快给您回复。

**Comment by likejing** [comment]
您好，我已收到您的邮件，将尽快给您回复。
