### ISSUE TITLE
无限崩溃啊

### ISSUE THREAD

**Issue by ken515** [kkevsekk1/AutoX#800]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：三星s10e
5. Android 系统类别：one
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：一运行js脚本就立马崩
8. 报错日志（可选）：
9. 屏幕截图（可选）：
设备信息: 
App version: 6.5.7
App version code: 657
Android build version: G970U1UES6GUG1
Android release version: 11
Android SDK version: 30
Android build ID: RP1A.200720.012.G970U1UES6GUG1
Device brand: samsung
Device manufacturer: samsung
Device name: beyond0q
Device model: SM-G970U1
Device product name: beyond0qlteue
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
android.view.InflateException:Binary XML file line #76 in org.autojs.autoxjs.v6:layout/floating_console_expand: Binary XML file line #76 in org.autojs.autoxjs.v6:layout/floating_console_expand: Error inflating class com.stardust.autojs.core.console.ConsoleView

......
Caused by:
java.lang.ClassCastException:android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
com.stardust.autojs.core.console.ConsoleView.init(ConsoleView.kt:63)
com.stardust.autojs.core.console.ConsoleView.<init>(ConsoleView.kt:50)
java.lang.reflect.Constructor.newInstance0(Native Method)
java.lang.reflect.Constructor.newInstance(Constructor.java:343)
android.view.LayoutInflater.createView(LayoutInflater.java:852)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
android.view.LayoutInflater.inflate(LayoutInflater.java:680)
android.view.LayoutInflater.inflate(LayoutInflater.java:532)
android.view.LayoutInflater.inflate(LayoutInflater.java:479)
android.view.View.inflate(View.java:28552)
com.stardust.autojs.core.console.ConsoleFloaty.inflateExpandedView(ConsoleFloaty.java:80)
com.stardust.enhancedfloaty.ResizableExpandableFloatyWindow.inflateWindowViews(ResizableExpandableFloatyWindow.java:160)
com.stardust.enhancedfloaty.ResizableExpandableFloatyWindow.onCreateView(ResizableExpandableFloatyWindow.java:54)
com.stardust.enhancedfloaty.FloatyWindow.onCreateWindow(FloatyWindow.java:29)
com.stardust.enhancedfloaty.FloatyWindow.onCreate(FloatyWindow.java:23)
com.stardust.autojs.core.console.ConsoleImpl$1.onCreate(ConsoleImpl.java:94)
com.stardust.enhancedfloaty.FloatyService.addWindow(FloatyService.java:21)
com.stardust.autojs.core.console.ConsoleImpl.lambda$show$0$com-stardust-autojs-core-console-ConsoleImpl(ConsoleImpl.java:224)
com.stardust.autojs.core.console.ConsoleImpl$$ExternalSyntheticLambda1.run(Unknown Source:2)
android.os.Handler.handleCallback(Handler.java:938)
android.os.Handler.dispatchMessage(Handler.java:99)
android.os.Looper.loop(Looper.java:246)
android.app.ActivityThread.main(ActivityThread.java:8512)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by aiselp** [comment]
意外使用了一个高sdk的api，后续版本将会修复

**Comment by ken515** [comment]
> 意外使用了一个高sdk的api，后续版本将会修复

三星手机s10e安卓11版本。swipe和gesture在无障碍模式下是无效的。永远直接返回false。知道是什么原因吗？

**Comment by ken515** [comment]
> 意外使用了一个高sdk的api，后续版本将会修复

scrollUp()也无效。返回也是flase

**Comment by aiselp** [comment]
不清楚，可能系统有限制
