### ISSUE TITLE
6.5.7无法监听音量下按键

### ISSUE THREAD

**Issue by qq337829302** [kkevsekk1/AutoX#801]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：红米K50至尊
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：6.5.7无法监听音量下按键，6.5.6没有这个问题
8. 报错日志（可选）：
9. 屏幕截图（可选）：

events.observeKey();
events.onKeyDown('volume_down', function (event) {
    console.log('脚本停止')
    quit()
})

**Comment by jilangyangbo** [comment]
应该是新版本代码影响了这块功能,我的荣耀手机 andriod 13 也存在这个问题
