### ISSUE TITLE
在AMD电脑的夜神、雷电模拟器上无法使用root滑动，会报错Houdini failed

### ISSUE THREAD

**Issue by 1061700625** [kkevsekk1/AutoX#803]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：夜神、雷电模拟器
5. Android 系统类别：夜神、雷电模拟器UI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：在Intel的电脑上，装夜神、雷电模拟器可以成功使用rootautomator滑动，但在AMD系统上不行。报错信息主要是Houdini初始化失败以及tmp-mksh not found。经过搜索，tmp-mksh文件确实是存在的，在system同目录下，此外Houdini似乎是Intel专有的库。基于以上问题，似乎打包的apk只能在Intel上运行，请问大佬有AMD的解决方案吗？
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![image](https://github.com/kkevsekk1/AutoX/assets/31002981/da66c8d7-b1fd-4eb0-8c4b-1f6f7988c373)

**Comment by sindon123** [comment]
shell命令滑动试试呢

**Comment by 1061700625** [comment]
> shell命令滑动试试呢

我看UiAutomator源码好像用的就是shell

**Comment by 1061700625** [comment]
![image](https://github.com/kkevsekk1/AutoX/assets/31002981/8d6e85e4-2e53-491f-9bcf-678bdabf5a4c)
shizhegeyuan是这个原因吗？图中显示Houdini的版本是9.0.7，而我用的安卓版本是9.0。
