### ISSUE TITLE
6.5.7打包应用会出现无法使用无障碍模式

### ISSUE THREAD

**Issue by anranq** [kkevsekk1/AutoX#806]
1. Autox.js 版本：657
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：小米11
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：6.5.7打包应用会出现无法使用无障碍模式，导致软件停止运行无法打开，回退656版本打包则可以
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by erdong01** [comment]
我也 oppo. vivo 手机也有碰到这个问题，oppo手机还出现闪退，6.5.6 还没有出现

**Comment by erdong01** [comment]
使用了 UI

**Comment by 4165306** [comment]
我也遇到这个问题了， 我的解决方法是打包的时候不勾选需要无障碍，希望能帮到你
