### ISSUE TITLE
谷歌ocr 无法识别 GoogleMLKitOcrResult(level=0, confidence=-1.0, text=, language=null, bounds=null, children=[])

### ISSUE THREAD

**Issue by DreamerLS1994** [kkevsekk1/AutoX#808]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
官网例子，一直提示
GoogleMLKitOcrResult(level=0, confidence=-1.0, text=, language=null, bounds=null, children=[])
我记得前几天可以用的啊？是我的问题吗？

**Comment by DreamerLS1994** [comment]
6.5.6 没有问题   6.5.7 出现的问题。

**Comment by LYS86** [comment]
#792 我调了ML Kit的版本，我这边可以识别，
机型
```
应用版本名: 6.5.8
安卓发行版本: 13
安卓 SDK 版本: 33
设备品牌: Xiaomi
设备型号: Mi 10
设备产品名称: umi
```
尝试提高文字对比度看看是否能识别，不行就回滚版本
```
let canvas = new Canvas(500, 500);
let paint = new Paint();
paint.setTextSize(100);
paint.setColor(android.graphics.Color.pack(colors.parseColor("#FF963200")));
canvas.drawText("测试文字", 100, 100, paint);
img = canvas.toImage()
//images.save(img, './2.png')
let text = gmlkit.ocr(img, 'zh')
log(text)
```

**Comment by claviering** [comment]
6.5.8 也出现这个问题
