### ISSUE TITLE
如何关闭截图权限

### ISSUE THREAD

**Issue by pharaoh2012** [kkevsekk1/AutoX#809]
在最新的 6.5.7 版本中，有以下优化:
截图逻辑优化，使截图权限在所有脚本共享

申请截图权限后，会一直保留截图权限。
在MIUI系统中，会一直在左上角提示 屏幕共享中的标志。
同时也导致原来收到验证码短信会直接弹出小窗提示，现在不能提示了。

如何返回原来的截图权限逻辑? 或者截图完毕后可以主动关闭截图权限。

![image](https://github.com/kkevsekk1/AutoX/assets/2225220/4d27cce9-5141-4614-8e9e-8a5c19567724)
![image](https://github.com/kkevsekk1/AutoX/assets/2225220/7bc1af94-312e-4bbb-8034-cc009dd96375)

**Comment by aiselp** [comment]
可以先用旧版，这个版本还不完善，后续会添加相关函数和通知按钮以取消截图权限
