### ISSUE TITLE
不是bug，是请教一下有没有兄弟控件的相关函数？

### ISSUE THREAD

**Issue by wingswing1** [kkevsekk1/AutoX#813]
隔壁有offset和sibling，感觉挺好用的

**Comment by Generalize** [comment]
这个v6版和autojs 9区别大吗

**Comment by wingswing1** [comment]
没用过auto9，不清楚



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月25日 16:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [kkevsekk1/AutoX] 不是bug，是请教一下有没有兄弟控件的相关函数？ (Issue #813) |

这个v6版和autojs 9区别大吗
