### ISSUE TITLE
最新版6.5.7打包后的app无法启动

### ISSUE THREAD

**Issue by zwc456baby** [kkevsekk1/AutoX#816]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米14
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：  如题，最新版有问题,我撤回到 6.5.6 打包app正常运行。。最新版本有一段：修复运行ui脚本存在的内存泄漏，应该是这里出现了新问题
8. 报错日志（可选）：
9. 屏幕截图（可选）：

![Screenshot_2024-01-26-20-56-38-208_com.miui.thirdappassistant.jpg](https://github.com/kkevsekk1/AutoX/assets/20961202/5b9e766b-59e1-4e65-9990-c890e29e061e)

**Comment by chenmg2020** [comment]
![Snipaste_2024-02-06_08-51-23](https://github.com/kkevsekk1/AutoX/assets/26603367/19fb8324-5c81-43e9-a0aa-1112d76b4a95)
我打包也是无法启动。
1、Autox.js 版本：6.5.7
2、Android 机型：雷电模拟器

**Comment by chenmg2020** [comment]
![Snipaste_2024-02-06_08-51-23](https://github.com/kkevsekk1/AutoX/assets/26603367/19fb8324-5c81-43e9-a0aa-1112d76b4a95)
我打包也是无法启动。
1、Autox.js 版本：6.5.7
2、Android 机型：雷电模拟器

**Comment by wuil-wang** [comment]
现在还是有怎么解决的啊
