### ISSUE TITLE
是只能从autox.js页面拉起 intent 或者 app 吗？

### ISSUE THREAD

**Issue by kongminhao** [kkevsekk1/AutoX#82]
先问是不是，再问为什么。以及是否有解决办法？

**Comment by kkevsekk1** [comment]
没明白



发送自我的盖乐世



-------- 原始信息 --------
发件人： kongminhao ***@***.***>
日期: 2021/7/14 22:56 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 是只能从autox.js页面拉起 intent 或者 app 吗？ (#82)


先问是不是，再问为什么。以及是否有解决办法？

―

**Comment by kkevsekk1** [comment]
举例说明一下，什么场景做什么



发送自我的盖乐世



-------- 原始信息 --------
发件人： kongminhao ***@***.***>
日期: 2021/7/14 22:56 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 是只能从autox.js页面拉起 intent 或者 app 吗？ (#82)


先问是不是，再问为什么。以及是否有解决办法？

―

**Comment by kongminhao** [comment]
我需要在收到一个websocket信息的时候打开一个app做一些事情，我发现在 miui 系统下似乎只能在 autoxjs 才能拉起这个程序，在其他界面都没有反应。我正在测试其他系统是否可行。

**Comment by kkevsekk1** [comment]
这好像是有个权限，弹出其他应用界面，或运行覆盖

**Comment by kongminhao** [comment]
> 这好像是有个权限，弹出其他应用界面，或运行覆盖

感谢，找到了，在 miui 权限里有一条 运行后台弹出应用。
