### ISSUE TITLE
内含循环的同名文件长时间运行，exit();再开始可能出现missing ) after formal parameters

### ISSUE THREAD

**Issue by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [kkevsekk1/AutoX#824]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：Redmi 9A
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.109.0
7. 问题描述：内含循环的同名文件长时间运行，结束并重新开始可能出现missing ) after formal parameters，修改文件名后解决。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by mingmingshiliyu** [comment]
> 1. Autox.js 版本：6.5.7
> 2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
> 3. Android 版本：Android 11
> 4. Android 机型：Redmi 9A
> 5. Android 系统类别：MIUI
> 6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.109.0
> 7. 问题描述：内含循环的同名文件长时间运行，结束并重新开始可能出现missing ) after formal parameters，修改文件名后解决。
> 8. 报错日志（可选）：
> 9. 屏幕截图（可选）：

什么原因

**Comment by nwyxcnsyty** [comment]
> > 1. Autox.js 版本：6.5.7
> > 2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
> > 3. Android 版本：Android 11
> > 4. Android 机型：Redmi 9A
> > 5. Android 系统类别：MIUI
> > 6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.109.0
> > 7. 问题描述：内含循环的同名文件长时间运行，结束并重新开始可能出现missing ) after formal parameters，修改文件名后解决。
> > 8. 报错日志（可选）：
> > 9. 屏幕截图（可选）：
> 
> 什么原因

因为等一会自己会恢复，我猜测是资源缓存没来得及回收更新。
