### ISSUE TITLE
截图权限共享功能，在有其他软件索取截图权限后，截图函数范围内容为空

### ISSUE THREAD

**Issue by MarkTina** [kkevsekk1/AutoX#827]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型  红米K40
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
【截图逻辑优化，使截图权限在所有脚本共享】这个功能可能与其他类 auto.js 软件产生冲突；
我在使用 hamibot 也进行脚本调试以后，有所取截图权限，再回过头来使用 autox.js 时，截图功能只能截取到空图，进而导致后续 ocr 识别内容为空；
但我安装 6.5.6 以后，每次授权的情况下，截图函数 captureScreen() 可以正常范围结果

**Comment by aiselp** [comment]
其他软件占用截图权限后再调用captureScreen()函数会抛出错误，需要重新请求截图权限

**Comment by MarkTina** [comment]
OK. your email has been received.

**Comment by MarkTina** [comment]
OK. your email has been received.
