### ISSUE TITLE
怎么最新的APK没有提供下载地址啊

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#83]
老大，最新的5.3.1的apk没有提供下载地址啊

**Comment by kkevsekk1** [comment]
忘了，直接升级啊



发送自我的盖乐世



-------- 原始信息 --------
发件人： lnxcyq ***@***.***>
日期: 2021/7/15 08:21 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 怎么最新的APK没有提供下载地址啊 (#83)


老大，最新的5.3.1的apk没有提供下载地址啊

―

**Comment by lnxcyq** [comment]
编辑器出错，崩溃。我直接删除了，没办法直接升级了。

**Comment by kkevsekk1** [comment]
加了

**Comment by lnxcyq** [comment]
刚下载安装了，查看一下，怎么是Version 5.3.0，不是说是5.3.1版本么

**Comment by kkevsekk1** [comment]
可能只是 一个 修订版，发布忘记了生实际版本名称

**Comment by lnxcyq** [comment]
哦，也就是说提供下载的实际是5.3.1罗

**Comment by lnxcyq** [comment]
谢谢，辛苦了。
