### ISSUE TITLE
6.5.8多线程无法停止

### ISSUE THREAD

**Issue by Gosiu** [kkevsekk1/AutoX#830]
1. Autox.js 版本：628
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：iQOO
5. Android 系统类别：originos
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：其他issue给的很详细了。所有已知的正常停止操作后。此脚本启动的线程并没有中断。继续工作。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by Kiritocyz** [comment]
还有，setTimeout函数也是，在设定的延时内，停止脚本也是接着运行。

**Comment by LYS86** [comment]
示例代码中的监听示例无法通过管理页面的关闭按钮关闭脚本
![Screenshot_2024-02-17-09-16-56-895_org autojs autoxjs v6-edit](https://github.com/kkevsekk1/AutoX/assets/106499400/e6efd4e7-105f-459d-9d9b-fca3632997bc)

**Comment by Kiritocyz** [comment]
> 示例代码中的监听示例无法通过管理页面的关闭按钮关闭脚本 ![Screenshot_2024-02-17-09-16-56-895_org autojs autoxjs v6-edit](https://private-user-images.githubusercontent.com/106499400/305588393-e6efd4e7-105f-459d-9d9b-fca3632997bc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNDQzNzYsIm5iZiI6MTcwODE0NDA3NiwicGF0aCI6Ii8xMDY0OTk0MDAvMzA1NTg4MzkzLWU2ZWZkNGU3LTEwNWYtNDU5ZC05ZDliLWZjYTM2MzI5OTdiYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QwNDI3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTNiMTAyZmJlZjU5NmI3MDhjZDViMzE5NTJhMDZkNzY0MjE0MmU5NjY2ZjI5NjY2ODNhNGNkYTkxZDYwOTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QZOAnctLnvDSXR18XPHEr8r465brTqnsEkDZiKVf_3Q) 监听示例-通知监听报错
> 
> ```
> 09:20:31.480/E: Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? (/data/user/0/org.autojs.autoxjs.v6/files/sample/事件与按键、触摸监听/通知监听.js#2)
> Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
>     at /data/user/0/org.autojs.autoxjs.v6/files/sample/事件与按键、触摸监听/通知监听.js:2:0
> ```
> 
> 多线程无法关闭，示例参考#829

你也是所有的X都点了，结果半天都停止不了吧。感觉就像所有的停止脚本被什么东西阻塞了。

**Comment by aiselp** [comment]
这个版本的强制停止脚本是有点问题，后续会优化

**Comment by Tsyshiu** [comment]
我的华为上是：点停止脚本以后，并不会立刻停止，直到手机关屏后，events才会接收到exit事件，然后退出脚本
