### ISSUE TITLE
是否有考虑增加断点调试功能？

### ISSUE THREAD

**Issue by jim19770812** [kkevsekk1/AutoX#832]
没有断点调试功能开发起来有点痛苦，特别是调试问题的时候，如果增加上就会很方便呢

**Comment by LYS86** [comment]
手机上长按运行，有个简单的断点调试

**Comment by jim19770812** [comment]
> 手机上长按运行，有个简单的断点调试

谢谢

**Comment by jim19770812** [comment]
> 手机上长按运行，有个简单的断点调试

谢谢，哪个版本有这个功能？我在android11下试了下最新的Autox-v6-arm64-v8a-release-6.5.9.apk，长按运行后没啥反应呢。

**Comment by LYS86** [comment]
![Screenshot_2024-04-15-12-34-00-273_org autojs autoxjs v6](https://github.com/kkevsekk1/AutoX/assets/106499400/76cadc1a-0623-43e0-a5f1-dc6eb52023f3)

**Comment by jim19770812** [comment]
请问你用的是哪个版本的apk？我下载了最新的Autox-v6-arm64-v8a-release-6.6.0.apk 没有看到这个调试按钮
![图片](https://github.com/kkevsekk1/AutoX/assets/3992187/20e0c942-6d06-4000-8f15-595a128ce993)

**Comment by jim19770812** [comment]
哦，原来是用的老版本编辑器，找到了，谢了
