### ISSUE TITLE
ocr的识别度有点低啊，老是识别错误，是不是要升级一下ocr包啊

### ISSUE THREAD

**Issue by erdong01** [kkevsekk1/AutoX#833]
1. Autox.js version: 6.5.8

google  百度 ocr都用了 效果都不理想

**Comment by LYS86** [comment]
ML Kit目前不支持自定义模型，你可以去看下Paddle和Tessract的模型训练，用自己的数据训练一个模型，

**Comment by erdong01** [comment]
> ML Kit目前不支持自定义模型，你可以去看下Paddle和Tessract的模型训练，用自己的数据训练一个模型，

感谢老哥，Paddle和Tessract的模型训练没搞过，不知道怎么搞，有没有技术文章和文档啊，autox.js要怎么引入Paddle模型

**Comment by erdong01** [comment]
还是希望作者能帮我们解决一下，感谢

**Comment by qiyaozu** [comment]
paddle 使用精准模型，文字的位置偶尔会出错
