### ISSUE TITLE
images.requestScreenCapture(0) 请求竖屏截图，还是自适应横屏截图，有时竖屏也会截图成横屏，请求解决

### ISSUE THREAD

**Issue by kaixin88** [kkevsekk1/AutoX#834]
1. Autox.js 版本：6.5.6
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米note9
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：images.requestScreenCapture(0) 请求竖屏截图，还是自适应横屏截图，有时竖屏也会截图成横屏，因为申请截屏权限是一次的，可否在截屏时再次给与参数以截屏是否为横屏
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by LYS86** [comment]
https://github.com/kkevsekk1/AutoX/blob/8b5ef2e9482d1b404eb02aa5537f8a9431900b92/autojs/src/main/assets/modules/__images__.js#L159

函数内部使用===判断，输入0视为无效输入，使用默认参数
