### ISSUE TITLE
无法新建文件文件夹

### ISSUE THREAD

**Issue by superen7527** [kkevsekk1/AutoX#835]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：小米10
5. Android 系统类别：MIUI

7. 问题描述：

没有任何报错 没有任何日志 百思不得其解搞了两个小时了，只好发issue 也没找到一样的问题。

就是新建文件或者文件夹的时候文件还在列表，刷新列表或者重启就不见了。新建文件夹也不行。看了一下一直写在data私有目录的simple里面，也不能指定路径。设置里面改了会黑屏一下然后文件没变化。给了文件使用权限了。消失的问题可能是自动生成的文件没有权限，一直显示默认的几个示例。感觉文件交互这里很不友好。。

另外有一个逻辑，使用过程才发现 文件夹点进去会改文件列表变成相应的。这种逻辑好奇怪，能不能改成文件树，或者直接文件夹文件在一起显示优先文件夹这样？不过习惯一下也还好。

**Comment by qwe317149766** [comment]
一样的问题
