### ISSUE TITLE
無法透過id找到物件

### ISSUE THREAD

**Issue by aaa71541367** [kkevsekk1/AutoX#838]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：realme XT
5. Android 系统类别：realme UI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：v1.110.0
7. 问题描述：透過布局範圍分析確定該物件確實有在螢幕上，但是程式碼無法透過id找到該物件
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![79446](https://github.com/kkevsekk1/AutoX/assets/69131671/27dcadc9-3fef-44e6-aa82-dc5d8901b41e)
![429092183_1229388455132529_8703830071339114199_n](https://github.com/kkevsekk1/AutoX/assets/69131671/20eb4b53-da09-42a7-a7ec-9d80dff53348)

**Comment by System233** [comment]
类似问题，同一个控件，有时能找到有时不行，布局分析里也是一样的情况。

**Comment by jilangyangbo** [comment]
我这有的时候使用哪个fullid 的内容能够找到 id(fullId)

**Comment by sindon123** [comment]
用idEndsWith就行，id别带包名
