### ISSUE TITLE
需求，需要给脚本里的ui列表，添加启动按钮和桌面快捷

### ISSUE THREAD

**Issue by aogg** [kkevsekk1/AutoX#840]
特别是桌面快捷，这个没有，一个脚本多个桌面快捷这样

**Comment by kkevsekk1** [comment]
带参数实现



发送自我的盖乐世



-------- 原始信息 --------
发件人： aogg ***@***.***>
日期: 2024/2/25 23:18 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 需求，需要给脚本里的ui列表，添加启动按钮和桌面快捷 (Issue #840)


特别是桌面快捷，这个没有，一个脚本多个桌面快捷这样

―

**Comment by aogg** [comment]
啥，没看懂，就因为没有添加桌面快捷我都得想如何自己写安卓代码了
