### ISSUE TITLE
loadDex不能用了吗？不用这个怎么实现热更新呢？

### ISSUE THREAD

**Issue by DreamerLS1994** [kkevsekk1/AutoX#841]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
loadDex不能用了吗？不用这个怎么实现热更新呢？

**Comment by sindon123** [comment]
直接更新apk或者js文件
