### ISSUE TITLE
如何检测当前 处于前台的APP是哪个APP？ 有API吗？

### ISSUE THREAD

**Issue by ZJRui** [kkevsekk1/AutoX#843]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

定时任务 启动某一个APP 在这个APP内做一个 while循环。 有的时候虽然启动APP成功了，但是可能用户手动切换到了其他APP，
问题： 如何检测当前 处于前台的APP是哪个APP？ 有API吗？

一种思路： 随便抓个View看下其应用名称。

**Comment by pharaoh2012** [comment]
当前包名[currentPackage()](http://doc.autoxjs.com/#/globals?id=currentpackage)
当前视图: [currentActivity()](http://doc.autoxjs.com/#/globals?id=currentactivity)

**Comment by zls3201** [comment]
小米手机  获取的是这玩意

currentPackage: com.miui.securitycenter
currentActivity: android.widget.ImageView

**Comment by asd666q9** [comment]
> 小米手机  有的应用正确，有的不对获取的是这玩意
> 
> currentPackage: com.miui.securitycenter
> currentActivity: android.widget.ImageView
> 
> 怎么破？

澎湃系统碰到同样问题
开始显示实际包名
随后显示miui安全中心
```
日志
11.24.22.099/D: com.miui.nome 11:24:22.100/D: com.miui.home 11:24:23.104/D: com.miui.home 11:24:23.105/D: com.miui.home 11:24:24.108/D: com.miui.home 11:24:24.110/D: com.miui.home 11:24:25.116/D: com.miui.home 11:24:25.117/D: com.miui.home 11:24:26.125/D: com.miui.home 11:24:26.126/D: com.miui.home 11:24:27.127/D: com.miui.home 11:24:27.128/D: com.miui.home 11:24:28.143/D: com.miui.home 11:24:28.146/D: com.miui.home 11:24:29.148/D: com.miui.home 11:24:29.154/D: com.miui.home 11:24:30.155/D: com.miui.home 11:24:30.158/D: com.miui.home 11:24:31.162/D: com.miui.home 11:24:31.163/D: com.miui.home
11:24:32.377/D: com.hypergryph.arknights 11:24:32.380/D: com.hypergryph.arknights 11:24:33.382/D: com.miui.home
11:24:33.383/D: com.miui.home
11:24:34.384/D: com.miui.securitycenter 11:24:34.385/D: com.miui.securitycenter 11:24:40.004/D: com.miui.securitycenter 11:24:40.056/D: com.miui.securitycenter 11:24:41.059/D: com.miui.home
11:24:41.060/D: com.miui.home
11:24:42.061/D: com.android.systemui 11:24:42.061/D: com.android.systemui 11:24:43.063/D: com.miui.home
11:24:43.063/D: com.miui.home 11:24:44.065/D: com.miui.home 11:24:44.066/D: com.miui.home 11:24:45.068/D: com.miui.home 11:24:45.069/D: com.miui.home 11:74:46 071/D· com miui home
×
```

**Comment by pharaoh2012** [comment]
> 小米手机 有的应用正确，有的不对获取的是这玩意
> 
> currentPackage: com.miui.securitycenter currentActivity: android.widget.ImageView
> 
> 怎么破？
根据控件属性获取包名:
```js
function getPackageName() {
    let root = auto.root;
    if (root) return root.packageName();
    return "";
}
```

**Comment by asd666q9** [comment]
> > 小米手机 有的应用正确，有的不对获取的是这玩意
> > 
> > currentPackage: com.miui.securitycenter currentActivity: android.widget.ImageView
> > 
> > 怎么破？
> 
> 
> 根据控件属性获取包名:
> ```js
> function getPackageName() {
>     let root = auto.root;
>     if (root) return root.packageName();
>     return "";
> }
> ```

十分感谢，亲测有效
