### ISSUE TITLE
源码toJsArrary()函数有个未定义的值javaArrary，导致multi型dialog的item_select回调函数会报错

### ISSUE THREAD

**Issue by 112sb** [kkevsekk1/AutoX#844]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
7. 问题描述：multi型dialog的item_select回调函数源码有问题，报错："javaArray" is not defined
8. 报错日志（可选）：ReferenceError: "javaArray" is not defined. (/android_asset/modules/__dialogs__.js#225)
9. 屏幕截图（可选）：
![image](https://github.com/kkevsekk1/AutoX/assets/39861050/e5ab421a-9aad-4956-8416-29ae4d7e8dfb)

**Comment by LYS86** [comment]
#848 你试下看看还报错吗
