### ISSUE TITLE
小黄车自动抢购秒杀脚本

### ISSUE THREAD

**Issue by jilindandan** [kkevsekk1/AutoX#845]
抖音小黄车自动抢购脚本 抖音版本号:28.9.0
抖音小黄车抢购和秒杀脚本
工作室干倒闭了,准备去开个快递驿站去了.
3500软妹币在猪八戒找人写的脚本免费送给你们了,江湖再见~
[抖音小黄车抢购秒杀.txt](https://github.com/kkevsekk1/AutoX/files/14508098/default.txt)

下载后自己把扩展名改成 .js

**Comment by emeiziying** [comment]
这居然能卖到3500

**Comment by Liberations** [comment]
30不能再多了

**Comment by ZzzMiles** [comment]
我出5毛
