### ISSUE TITLE
奇怪，用稳5.3.1突然今天中午编辑器出错，编辑东西后最后一行出现乱码

### ISSUE THREAD

**Issue by lnxcyq** [kkevsekk1/AutoX#85]
奇怪，用稳5.3.1突然今天中午编辑器出错，编辑东西后最后一行出现乱码

**Comment by lnxcyq** [comment]
唉，现在都不知道用哪个版本的好

**Comment by kkevsekk1** [comment]
5.3.0呢？



发送自我的盖乐世



-------- 原始信息 --------
发件人： lnxcyq ***@***.***>
日期: 2021/7/21 15:52 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 奇怪，用稳5.3.1突然今天中午编辑器出错，编辑东西后最后一行出现乱码 (#85)


唉，现在都不知道用哪个版本的好

―

**Comment by lnxcyq** [comment]
5.3.0好象不会吧，我再安装回去试试
