### ISSUE TITLE
打包后启动app使用立马崩溃

### ISSUE THREAD

**Issue by pengjiangguo** [kkevsekk1/AutoX#851]
1. Autox.js version: 6.5.8
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 9
4. Android model: vivo x21
5. Android system category: Funtouch OS
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:
8. Error log (optional): 打包后运行崩溃
9. Screenshot (optional):

**Comment by onlyWYY** [comment]
同样的问题，导致又回去使用 6.5.6 版本了。
