### ISSUE TITLE
bug，打包后启动软件，再关闭软件，开启其他APP的时候，调节音量会有很大的延迟，但代码里面没有任何控制音量的代码。

### ISSUE THREAD

**Issue by wjcom9** [kkevsekk1/AutoX#858]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：红米turbo12
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
我用的手机是红米turbo12，然后我的脚本是一个下载保存HTTP图片，然后模拟点击去发微信朋友圈的脚本。其中用到了一些悬浮框，按钮，ontouch事件。

描述：
我打包之后的应用，我启动的时候，我调到其他APP，控制音量按键的时候（上键或者下键都一样），会有1秒多的延迟响应。且你按下一个手机音量大键，平常音量是+5%，但是只要是我这个应用启动期间，按一下就是增加15%，且会有延迟。音量小键也是同理。
但你直接运行我的脚本代码是不会有我上面出现这种问题的，仅打包的时候出现。

环境/配置：
我打包的时候，没有勾选音量上键关闭脚本，而且也尝试过关掉应用控制媒体音量的权限，但依然有这种问题。

需求：
24年3月25日前，能解决这样的问题的可以+Q 2380024671 ，有偿。 论坛信息可能一天才看一次。
8. 报错日志（可选）：没有报错，日志一切正常。
9. 屏幕截图（可选）：截图展现不了报错，其他人也有遇到跟我一样的问题
![74123363CDD9F358C27699F00536EDBA](https://github.com/kkevsekk1/AutoX/assets/76757657/cff17844-5427-462e-9418-ac70aa07c7e6)

**Comment by wjcom9** [comment]
杀死系统进程会导致下次打开的时候，还要授权一次无障碍权限，小米都需要等待10s才能授权，对用户很不友好，所有希望有其他结局办法。

**Comment by kkevsekk1** [comment]
监听，自己处理


发送自我的盖乐世



-------- 原始信息 --------
发件人： wjcom9 ***@***.***>
日期: 2024/3/18 11:33 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] bug，打包后启动软件，再关闭软件，开启其他APP的时候，调节音量会有很大的延迟，但代码里面没有任何控制音量的代码。 (Issue #858)


杀死系统进程会导致下次打开的时候，还要授权一次无障碍权限，小米都需要等待10s才能授权，对用户很不友好，所有希望有其他结局办法。

―

**Comment by wjcom9** [comment]
您好，能否说详细一点？我监听了音量键的事件，不做任何处理，依然没有解决这个问题，而且只出现在小米系列手机上，HUAWEI，samsung均没有这个问题。
