### ISSUE TITLE
5.3.1版本运行自带的例子出错

### ISSUE THREAD

**Issue by wsepr** [kkevsekk1/AutoX#86]
运行复杂界面->音乐浏览器出错，用的是雷电模拟器

![Snipaste_2021-07-21_17-43-25](https://user-images.githubusercontent.com/221005/126470889-0b355443-1034-4c38-ad2e-386ec747a31f.png)

**Comment by kkevsekk1** [comment]
files,就可以



发送自我的盖乐世



-------- 原始信息 --------
发件人： wsepr ***@***.***>
日期: 2021/7/21 18:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 5.3.1版本运行自带的例子出错 (#86)


运行复杂界面->音乐浏览器出错，用的是雷电模拟器

[Snipaste_2021-07-21_17-43-25]<https://user-images.githubusercontent.com/221005/126470889-0b355443-1034-4c38-ad2e-386ec747a31f.png>

―

**Comment by Aioure** [comment]
已经修正，并重命名为“音乐播放器”放在“多媒体”目录下
