### ISSUE TITLE
选择器使用ID节点无法找到控件

### ISSUE THREAD

**Issue by ChinaDebug** [kkevsekk1/AutoX#862]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases

最新几个版本使用ID作为选择器时有时会无法找到控件，控件是可以肯定存在的，因为相同的代码在旧版本却没有这个问题。

另外建议在github上留个TG群，方便各位大神有地方交流维护，现在项目上没有任何可以交流的入口，没法吸引大神一起维护，目前单靠一人维护不累吗？

**Comment by sindon123** [comment]
使用全id可以，包名不要省略

**Comment by imeepos** [comment]
试下idEndWidths或者idContains或者idMatch
