### ISSUE TITLE
控制台悬浮窗被手动关闭后无法再次显示

### ISSUE THREAD

**Issue by telppa** [kkevsekk1/AutoX#868]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：realme系列手机
5. Android 系统类别：realme UI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：

问题复现代码

```
console.show()
sleep(3000) //此时手动关闭控制台悬浮窗
console.show() //此时控制台悬浮窗无法显示
log("退出")
exit()
```

变通解决问题的代码

```
console.show()
sleep(3000) //此时手动关闭控制台悬浮窗 若想再次显示悬浮窗 必须先hide()且加一个延时才能再次显示
console.hide()
sleep(30)
console.show()
log("退出")
exit()
```

9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by imeepos** [comment]
重新调用floaty.window(``)
