### ISSUE TITLE
findOne 设置阻塞时间无效

### ISSUE THREAD

**Issue by songsong1994** [kkevsekk1/AutoX#870]
1. Autox.js 版本：628
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：华为nova 7
5. Android 系统类别：HarmonyOS 4.0 （其实还是android）
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：设置findOne(time)无效，比如time设置1000，但是会阻塞将近30-60秒不等才进行下一步

**Comment by imeepos** [comment]
time不是准确的 java里的Thread是这个特性 看手机性能 手机估计卡了或者内存爆了
