### ISSUE TITLE
id查询bug

### ISSUE THREAD

**Issue by misyqi** [kkevsekk1/AutoX#872]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![145daf5f937a780bd16dca69be0bd08](https://github.com/kkevsekk1/AutoX/assets/80199842/f5574bc5-0d79-4919-8c1e-ab1c549f492e)

**Comment by imeepos** [comment]
id()默认返回第一条
