### ISSUE TITLE
6.5.8截图bug

### ISSUE THREAD

**Issue by rq1996** [kkevsekk1/AutoX#874]
版本：6.5.8  
源码    AutoX/autojs/src/main/java/com/stardust/autojs/core/image/capture/ScreenCapturer.kt
119行是否存在图片资源未回收的情况？

以下是我修改后的内容
mCachedImageWrapper.getAndSet(newImageWrapper)?.recycle();
图片可以正确的回收
谢谢！

**Comment by aiselp** [comment]
截图失去引用即自动回收，而且这样改了后会造成多张截图同时只有一张可用

**Comment by rq1996** [comment]
> 截图失去引用即自动回收，而且这样改了后会造成多张截图同时只有一张可用

在我高频率截图的时候，这段代码20秒就撑爆了我8g内存，自动回收并没有启到作用。目前来说修改之后我的脚本运行是正常的，满足我的预期。也许是因为我的脚本同时只需要一张截图的原因吧。
