### ISSUE TITLE
悬浮窗的触摸穿透在mumu模拟器12和红米k60兼容性问题

### ISSUE THREAD

**Issue by 40020463** [kkevsekk1/AutoX#875]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12,Android 14
4. Android 机型：mumu模拟器12 ,红米k60
5. Android 系统类别：mumu模拟器12,xiaomihyperos(1.0.6.0.umncnxm)
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：在mumu模拟器12和红米k60下 [window.setTouchable(touchable)](http://doc.autoxjs.com/#/floaty?id=windowsettouchabletouchable) 悬浮窗的触摸穿透失效
8. 报错日志（可选）：
9. 屏幕截图（可选）：

测试代码
if (!floaty.checkPermission()) {
    // 没有悬浮窗权限，提示用户并跳转请求
    toast("本脚本需要悬浮窗权限来显示悬浮窗，请在随后的界面中允许并重新运行本脚本。");
    floaty.requestPermission();
    exit();
} else {
    toastLog('已有悬浮窗权限');
}
var w = floaty.rawWindow(
    <frame gravity="center" bg="#44ffcc00" />
);
w.setSize(-1, -1);
w.setTouchable(false);
setTimeout(() => {
    w.close();
}, 10000);

个人测试在雷电和夜神的安卓9下正常 
红米k60下用autox运行脚本时 autox界面下正常穿透(autox已经开启了悬浮窗 前台服务 无障碍服务) 切到桌面或其他app触摸穿透失效 手势操作等正常 
打包时 勾选悬浮窗和无障碍后运行正常穿透

mumu模拟器12下用autox运行脚本时 autox界面下正常穿透(autox已经开启了悬浮窗 前台服务 无障碍服务) 切到桌面或其他app触摸穿透失效 back home等按键功能正常 
打包时 勾选悬浮窗和无障碍后运行在主界面下(就是会显示日志那个界面)正常 切到桌面或其他app触摸穿透失效 back home等按键功能正常
开发者模式下开启点按操作反馈和指针位置后 在失效情况下没有任何点击显示和坐标显示

**Comment by sindon123** [comment]
安卓12系统以上会限制穿透事件导致的
