### ISSUE TITLE
6.5.9删除了 RunIntentActivity 导致不能直接通过意图运行脚本

### ISSUE THREAD

**Issue by bukkumaaku** [kkevsekk1/AutoX#877]
1. Autox.js 版本：6.5.9
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：IQOO 11S
5. Android 系统类别：Origin OS 4
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：6.5.9删除了 RunIntentActivity 导致不能用意图运行脚本，有没有其他方法可以调用？如果使用OpenIntentActivity会自动跳转到autoxjs界面，导致无法实时获取当前界面内容
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by aiselp** [comment]
之后版本在设置中加入开关可以使用之前的RunIntentActivity运行脚本

**Comment by kkevsekk1** [comment]
这个加回来了吧？



发送自我的盖乐世



-------- 原始信息 --------
发件人： bukkumaaku ***@***.***>
日期: 2024/6/26 19:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 6.5.9删除了 RunIntentActivity 导致不能直接通过意图运行脚本 (Issue #877)


Closed #877<https://github.com/kkevsekk1/AutoX/issues/877> as completed.

―

**Comment by aiselp** [comment]
加了

aaron ***@***.***> 于 2024年6月26日周三 21:10写道：
