### ISSUE TITLE
一年没用重新下载使用，发现log不出来信息

### ISSUE THREAD

**Issue by Pikarziur** [kkevsekk1/AutoX#879]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：realme X（RMX1901）
5. Android 系统类别：ColorOS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用console.log/log等方法，但是无法打印object的具体信息，只log出一个空的{}，但是用log(object.text())之类的命令可以log出具体信息
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by Pikarziur** [comment]
换了另外一个手机也不行，后来退回6.5.8就解决了

**Comment by aiselp** [comment]
可以调用object.toString()打印原来的信息

**Comment by kkevsekk1** [comment]
版本号不兼容？



发送自我的盖乐世



-------- 原始信息 --------
发件人： aiselp ***@***.***>
日期: 2024/4/18 23:13 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 一年没用重新下载使用，发现log不出来信息 (Issue #879)


可以调用object.toString()打印原来的信息

―
