### ISSUE TITLE
能不能重新编译一个换过名字的版本？

### ISSUE THREAD

**Issue by wanababy** [kkevsekk1/AutoX#88]
现在很多软件都会检测autojs，我装了这个autoxjs，淘宝还会检测出来。能不能把源代码里所有相关的autojs都替换一下成别的名字，然后重新编译一版，这样是不是就不能被检测到了，谢谢！

**Comment by kkevsekk1** [comment]
不要去淘宝N种方法检测你，改名字也没有

**Comment by wanababy** [comment]
是有办法的，下面这个能做到，但是具体方法他没透露。
https://github.com/MonsterNone/tmall-miao
