### ISSUE TITLE
6.5.9 最新版无法使用按键事件监听

### ISSUE THREAD

**Issue by zwc456baby** [kkevsekk1/AutoX#881]
1. Autox.js 版本：6.5.9
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米14
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：

[这一段代码使用无效：](http://doc.autoxjs.com/#/events?id=%e4%ba%8b%e4%bb%b6-39key39)
```
auto();
events.observeKey();
events.on("key", function(keyCode, event){
    //处理按键事件
});
```

看上去是没有进入轮询。直接结束了脚本，后附日志

9. 报错日志（可选）：
10. 屏幕截图（可选）：![175615](https://images.zwc365.com/i/2024/04/11/175615.jpg)

**Comment by zwc456baby** [comment]
**撤回到 6.5.8 功能正常**

**Comment by kkevsekk1** [comment]
有时间看一下，重新搞一个



发送自我的盖乐世



-------- 原始信息 --------
发件人： zwc ***@***.***>
日期: 2024/4/11 18:00 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 6.5.9 最新版无法使用按键事件监听 (Issue #881)


撤回到 6.5.8 功能正常

―

**Comment by zwc456baby** [comment]
首先感谢作者的持续维护。目前发现另外一个问题。使用最新版的 6.5.9 ，打包的 PaddleOCR 识别不出文字。，撤回到 6.5.7 版本后，打包出来的app。可以正常识别。，

我附加的两张图片是正常识别的。如果使用最新版打包。识别到的数量为：0 ，看日志升级 targetSDK 到 28 了。应该是升级过程中某些文件权限之类的问题吧。

![150113.jpg](https://images.zwc365.com/i/2024/04/15/150113.jpg)

![150118.jpg](https://images.zwc365.com/i/2024/04/15/150118.jpg)

**Comment by zwc456baby** [comment]
```
//log("尝试本地paddle识别ocr")
                var img = images.fromBytes(images.toBytes(captureScreen(), format = "jpeg", quality = 10));
                var paddinfo = paddle.ocr(img, cpuThreadNum=2, useSlim=true);
                if(paddinfo){
                    var paddjson = JSON.parse(JSON.stringify(paddinfo));
                    var retlist = [];
                    paddjson.forEach(e => {
                        // 转换成通用的格式
                        retlist.push({
                            bounds: [e.bounds["left"], e.bounds["top"], e.bounds["right"], e.bounds["bottom"]],
                            text: e.text,
                            truse: e.confidence
                        })
                    })
                    //log("本地ocr识别完成")
                    return retlist;
                }
```

**Comment by kkevsekk1** [comment]
收到，好看要回退一下才行，这个版本问题有点多



发送自我的盖乐世



-------- 原始信息 --------
发件人： zwc ***@***.***>
日期: 2024/4/15 15:04 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 6.5.9 最新版无法使用按键事件监听 (Issue #881)


首先感谢作者的持续维护。目前发现另外一个问题。使用最新版的 6.5.9 ，打包的 PaddleOCR 识别不出文字。，撤回到 6.5.7 版本后，打包出来的app。可以正常识别。，

我附加的两张图片是正常识别的。如果使用最新版打包。识别到的数量为：0 ，看日志升级 targetSDK 到 28 了。应该是升级过程中某些文件权限之类的问题吧。

[150113.jpg]<https://camo.githubusercontent.com/81b4df5060d637f37598a8607f9ff9b7efe3b22cec664c859af016507af2a793/68747470733a2f2f696d616765732e7a77633336352e636f6d2f692f323032342f30342f31352f3135303131332e6a7067>

[150118.jpg]<https://camo.githubusercontent.com/c0a494125e8910b4f2478c151276f02b4901c88f5df1fb79e5575b39c0a6168e/68747470733a2f2f696d616765732e7a77633336352e636f6d2f692f323032342f30342f31352f3135303131382e6a7067>

―

**Comment by zyjStart** [comment]
658也无法使用按键监听
