### ISSUE TITLE
requestScreenCapture申请完权限后，后续不需要了怎么才能关闭授权。

### ISSUE THREAD

**Issue by NOWorEVER** [kkevsekk1/AutoX#882]
1. Autox.js 版本：6.5.9
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米12SU
5. Android 系统类别：hyperos
7. 问题描述：requestScreenCapture申请完权限后，后续不需要了怎么才能关闭授权。
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by Zebartin** [comment]
`images.stopScreenCapturer()`

**Comment by NOWorEVER** [comment]
> `images.stopScreenCapturer()`

好的，感谢。等下试试看
