### ISSUE TITLE
布局分析卡死，只能重启解决

### ISSUE THREAD

**Issue by ygr2333** [kkevsekk1/AutoX#883]
Autox.js 版本：6.5.9
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 13
Android 机型：Redmi K50 Gaming
Android 系统类别：MIUI
问题描述：在 Autox.js v6 的悬浮窗中点击布局分析 - 布局范围分析 中任意点击一个控件，再点击 “生成代码”，点击生成后无法返回（点击生成后不知是卡死与否），系统并未停止运行，只能重启解决。
报错日志（可选）：无
屏幕截图（可选）：有视频，请提供您的邮箱以便于给您提供
运行方式：Root 运行

**Comment by aishuaikang** [comment]
设备信息: 
App version: 6.5.9
App version code: 659
Android build version: 7.1.0.214C00E202R1P3
Android release version: 13
Android SDK version: 33
Android build ID: ANY-AN00 7.0.0.214(C00E202R1P3)
Device brand: HONOR
Device manufacturer: HONOR
Device name: HNANY-Q
Device model: ANY-AN00
Device product name: ANY-AN00
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
java.lang.NullPointerException: Parameter specified as non-null is null: method com.stardust.automator.UiObject.<init>, parameter info
com.stardust.automator.UiObject.<init>(Unknown Source:2)
com.stardust.autojs.codegeneration.ReadOnlyUiObject.<init>(ReadOnlyUiObject.java:20)
com.stardust.autojs.codegeneration.CodeGenerator.<init>(CodeGenerator.java:29)
org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.generateCode(CodeGenerateDialog.java:92)
org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.generateCodeAndShow(CodeGenerateDialog.java:77)
org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.lambda$new$0(CodeGenerateDialog.java:72)
org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.$r8$lambda$1jfPgYDpVppHmrGoSeYgRENNAy4(Unknown Source:0)
org.autojs.autojs.ui.codegeneration.CodeGenerateDialog$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:361)
android.view.View.performClick(View.java:7738)
android.view.View.performClickInternal(View.java:7712)
android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
android.view.View$PerformClick.run(View.java:30495)
android.os.Handler.handleCallback(Handler.java:971)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loopOnce(Looper.java:206)
android.os.Looper.loop(Looper.java:296)
android.app.ActivityThread.main(ActivityThread.java:9205)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)

**Comment by aiselp** [comment]
之后修复
