### ISSUE TITLE
找图找色区域值top超过500就会报错

### ISSUE THREAD

**Issue by 112sb** [kkevsekk1/AutoX#886]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：大概超过这个值就会报错，改成300就没问题，不知道为啥
8. 报错日志（可选）：
Error: out of region: region = [156,500,912,2000], image.size = [1080,2400] (/android_asset/modules/__images__.js#523)
Error: out of region: region = [156,500,912,2000], image.size = [1080,2400]
9. 屏幕截图（可选）：

**Comment by aiselp** [comment]
500+2000=2500
