### ISSUE TITLE
find()

### ISSUE THREAD

**Issue by jyxinye** [kkevsekk1/AutoX#891]
1. Autox.js 版本：659
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K30PRO
6. Android 系统类别：MIUI
7. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
8. 问题描述： find() 最新版本报错，使用6.2.7的版本没有问题，
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by fanlushuai** [comment]
find（）函数有问题，
