### ISSUE TITLE
新建项目的UI中，“项目路径”输入框应当为文本框，而软件中将其错误的设置为了数字框

### ISSUE THREAD

**Issue by cnbilinyj** [kkevsekk1/AutoX#893]
1. Autox.js 版本：6.5.9
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
（由于该bug为软件包内错误，原软件Auto.js Pro中也包含同样的错误，这个属于布局元素属性设置错误，与机型安卓版本等无关，根据更新日志，最新版本似乎仍未解决这个问题，或许甚至到目前来说都没有人发现这个问题）

在activity`org.autojs.autojs.ui.build.ProjectConfigActivity_`[Layout XML文件路径：`APK FILE/res/St1.xml`]（进入软件后点击右上角加号点击项目后进入的页面）中的“项目路径”输入框应当是文本框，而软件中是数字框

**问题XML元素标签完整内容**
**这个XML是构建后的安装包中的文件**
```xml
<androidx.appcompat.widget.AppCompatEditText
    android:id="@7F090265"
    android:layout_width="-1"
    android:layout_height="-2"
    android:inputType="0x00000002" />
```
可以直接在反编译后的xml文件中搜索内容：`android:id="@7F090265"`
然后将该元素的`android:inputType`属性值更改为`0x00000000`

在github源码中的[`app/src/main/res/layout/activity_project_config.xml`:`160:52(6)`](/kkevsekk1/AutoX/blob/eccbb15d864f3eac09efbf3c6e24d4c423947ec5/app/src/main/res/layout/activity_project_config.xml#L160)应当更改为：`0x00000000`或`text`

**在github中的内容**
```xml
<androidx.appcompat.widget.AppCompatEditText
    android:id="@+id/project_location"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:inputType="number"/>
```

[视频](https://pan.beecld.com/s/1VPtW)

![Screenshot_20240421_102725](https://github.com/kkevsekk1/AutoX/assets/99505726/99a458d8-ba7e-403f-b463-08a78729be4c)
![Screenshot_20240421_102850](https://github.com/kkevsekk1/AutoX/assets/99505726/a49c46af-4318-4622-99bd-9273987e043a)

**Comment by cnbilinyj** [comment]
错误位置我都给你定位的清清楚楚，甚至你别说错误位置了，我甚至都告诉你怎么改了，你别又过去好几个版本不改

**Comment by LYS86** [comment]
你都查到具体位置了，为啥不直接改了呢

**Comment by cnbilinyj** [comment]
> 回复 @LYS86 的[评论](https://github.com/kkevsekk1/AutoX/issues/893#issuecomment-2068022077)：
> 
> 你都查到具体位置了，为啥不直接改了呢

……
这个项目的所有者是 @AutoX 又不是我，我又没有办法直接对项目内容进行更改
我可以直接改安装包啊，但是改过安装包之后，安装包还是要重新签名的，我又没有项目所有者的签名文件，那我就只能用自己的签名了，那到时候更新的话，我还要自己手动再重新签名，那很麻烦诶
那我还不如让项目所有者直接改项目呢

**Comment by LYS86** [comment]
源码不是开放的么，你复制一份源码修正错误，测试完进行回传，进行合并申请就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月4日(周六) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] 新建项目的UI中，“项目路径”输入框应当为文本框，而软件中将其错误的设置为了数字框 (Issue #893)




  
回复 @LYS86 的评论：
 
你都查到具体位置了，为啥不直接改了呢
  
……
 这个项目的所有者是 @AutoX 又不是我，我又没有办法直接对项目内容进行更改
 我可以直接改安装包啊，但是改过安装包之后，安装包还是要重新签名的，我又没有项目所有者的签名文件，那我就只能用自己的签名了，那到时候更新的话，我还要自己手动再重新签名，那很麻烦诶
 那我还不如让项目所有者直接改项目呢

**Comment by cnbilinyj** [comment]
@LYS86 搞好了#916 
@kkevsekk1
