### ISSUE TITLE
脚本编辑器无法正常进入

### ISSUE THREAD

**Issue by cnbilinyj** [kkevsekk1/AutoX#895]
1. Autox.js 版本：6.5.9
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 8.1.0
4. Android 机型：vivo vivo X20A
5. Android 系统类别：FunTouch OS
7. 问题描述：脚本编辑器无法正常进入，进入后持续白屏，无法正常使用
8. 报错日志（可选）：
9. 屏幕截图（可选）：
无屏幕截图，但有屏幕录制视频

[屏幕录制](https://github.com/kkevsekk1/AutoX/assets/99505726/85db8451-725d-4920-8520-830315940760)

**Comment by aiselp** [comment]
目前只能支持比较新的机型

**Comment by DuuiG** [comment]
我也是这样，手机型号:中兴天机A31
![Screenshot_20240427_032407](https://github.com/kkevsekk1/AutoX/assets/94788510/e63f9b06-3477-4913-81ab-c4cf11446c4a)
![Screenshot_20240427_032356](https://github.com/kkevsekk1/AutoX/assets/94788510/5beb7853-97fd-4cf0-a6ef-248c122f8f22)

**Comment by DuuiG** [comment]
中兴系统 Myos   型号 ZTE A2122H   安卓11  跟楼上一样，进不去编译器

**Comment by JohnHubcr** [comment]
> 目前只能支持比较新的机型

启用新版编辑器，选择脚本编辑时，首次进入不显示代码，再次进入才显示。

**Comment by cnbilinyj** [comment]
回复@kkevsekk1 的[评论](https://github.com/kkevsekk1/AutoX/issues/895#issuecomment-2081301303)
> > 目前只能支持比较新的机型
>
> 启用新版编辑器，选择脚本编辑时，首次进入不显示代码，再次进入才显示。

我重进无数遍都是白屏，只要是新版本的编辑器，无论怎样重建都是白屏
