### ISSUE TITLE
axios post请求输入流问题请教

### ISSUE THREAD

**Issue by iamqiqi1017** [kkevsekk1/AutoX#897]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
请问axios 如何正确发送文件流呀
这里是我的代码，但是传输貌似不对，传给服务端，服务端貌似无法解析成文件，我看axios是不支持arrayBuffer的格式，支持input输入流的
var file = new java.io.File(filePath);
  var fis = new FileInputStream(file);
  axios.post(url, fis).then((res) => {
    console.log(res);
  });
  
8. 报错日志（可选）：
![image](https://github.com/kkevsekk1/AutoX/assets/78333511/f7c20431-95fd-4508-b58b-126fcd9b6611)

9. 屏幕截图（可选）：

**Comment by iamqiqi1017** [comment]
我使用 http.request， 似乎也不能传二进制文件数据，body会报错TypeError: writeTo is not a function, it is object.
    at /android_asset/modules/__http__.js:49:0 我最终想实现的还是在body里面传输二进制数据
  const res = http.request(url, {
    headers: {
      "Content-Type": "application/octet-stream",
    },
    body: files.readBytes(filePath),
  });
  const result = res.body.json();
  console.log(result);

**Comment by exculibar** [comment]
> 我使用 http.request， 似乎也不能传二进制文件数据，body会报错TypeError: writeTo is not a function, it is object. at /android_asset/modules/**http**.js:49:0 我最终想实现的还是在body里面传输二进制数据 const res = http.request(url, { headers: { "Content-Type": "application/octet-stream", }, body: files.readBytes(filePath), }); const result = res.body.json(); console.log(result);

@iamqiqi1017 
我尝试的可以正常的用法是这样的
```js
const res = http.request(url, {
    headers: {
        "Content-Type": "application/octet-stream",
    },
    body: (bufferedSink) =>{ 
        // console.log(bufferedSink)
        bufferedSink.write(files.readBytes(filePath))
        return bufferedSink
    }
});
const result = res.body.json();
console.log(result);
```
