### ISSUE TITLE
执行脚本后cpu占用异常

### ISSUE THREAD

**Issue by eddiechen2011** [kkevsekk1/AutoX#898]
1. Autox.js 版本：660
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型: 一加11
5. Android 系统类别：ColorOS 14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
    脚本执行完成后，cpu占用异常
9. 报错日志（可选）：
10. 屏幕截图（可选）：
![Screenshot_2024-04-23-07-47-08-94_da1609eef9f7e3f5e1ae7ca4f8388be1](https://github.com/kkevsekk1/AutoX/assets/63313670/e294e5b6-0dc5-4e1b-910a-1c53b983e092)
![Screenshot_2024-04-23-07-47-39-83_7d78ecc499fd92ab4cb74ff1355f98d5](https://github.com/kkevsekk1/AutoX/assets/63313670/fd98ad20-6c83-4d34-aea4-93efa4afef8f)
![Screenshot_2024-04-23-07-47-54-70_7d78ecc499fd92ab4cb74ff1355f98d5](https://github.com/kkevsekk1/AutoX/assets/63313670/6e7e5848-f571-4800-a5c2-b3f6b876eb9f)

**Comment by fanlushuai** [comment]
这个cpu信息的是什么软件？
