### ISSUE TITLE
UI+websocket+ engines.execScript情况下， getEngine拿到空值

### ISSUE THREAD

**Issue by epiphyllum** [kkevsekk1/AutoX#899]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：雷电模拟器9
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
    获取脚本执行的引擎， 得到空值
    let lastEngine = engines.execScript("scriptName",  scriptContent).getEngine()

简单情况下这个可以拿到engine
```javascript


function exec(action, args){
    args = args || {};
    return engines.execScript(action.name, action + "(" + JSON.stringify(args) + ");\n" + action.toString());
}

//要执行的函数，是一个简单的加法
function add(args){
    while(true) {
        toast(args.a + args.b);
    }
}

//在新的脚本环境中执行 1 + 2
let execution = exec(add, {a: 1, b:2});

for(let i = 0; i < 10; ++i) {
    log(execution.getEngine())
    sleep(1000)
}

let engine = execution.getEngine()
log("engine is:", engine)
engine.forceStop()
```

我这里情况复杂写， 大致是这样。 有个UI线程，   UI上接收到参数后， UI线程启动一个线程， 线程内去连接okhttp3的websocket
websocket的连接上后， 连接所在的是单独的线程(这个好像是okhttp3的特点?)。  然后websocket连接收到消息后， 启动脚本， 从而返回脚本引擎， 此时返回的脚本引擎是空的。 日志如下：

  
9. 报错日志（可选）：
09:04:26.476/D: <debug>[136] - 登录成功: { code: 0, msg: 'success', data: '1781914024397651969' }
09:04:26.479/D: <debug>[137] - 启动websocket...
09:04:26.600/D: [140] - 连接服务器成功 Response{protocol=http/1.1, code=101, message=, url=http://192.168.0.21:8082/sys/spider/ss/18899999993}
09:04:35.923/D: <debug>[140] - 收到消息: { data: 
   { application: {},
     id: '8888',
     script: 'http://192.168.0.21:8989/tick-scripts/event.test.js' },
  command: 'script' }
09:04:35.938/D: <debug>[140] - 脚本启动, engine = null
09:04:36.016/V: 开始运行[script.js]
09:04:41.050/D: <debug>[147] - i am running
09:04:46.087/D: <debug>[147] - i am running
09:04:51.095/D: <debug>[147] - i am running
09:04:56.110/D: <debug>[147] - i am running

11. 屏幕截图（可选）：

日志说明:
<debug>[136] 里的136是UI 线程ID
<debug>[137] 里的137是启动okhttp3的线程
<debug>[140] 里的140是websocket连接处理所在线程
<debug>[147] 里的147是被启动脚本执行所在的现场

这里的问题在于:  09:04:35.938/D: <debug>[140] - 脚本启动, engine = null
刚启动， 拿到的引擎就是空的。 
```javascript
 let lastExecution = engines.execScript("script", content)
 tlog("脚本启动, engine =", lastExecution.getEngine())
```

**Comment by epiphyllum** [comment]
09:26:38.211/V: 开始运行[/storage/emulated/0/脚本/ticktaker/ticktaker.js]
09:26:52.429/D: <debug>[135] - 登录成功: { code: 0, msg: 'success', data: '1781914024397651969' }
09:26:52.432/D: <debug>[136] - 启动websocket...
09:26:52.668/D: [139] - 连接服务器成功 Response{protocol=http/1.1, code=101, message=, url=http://192.168.0.21:8082/sys/spider/ss/18899999993}
09:27:09.392/D: <debug>[139] - 收到消息: { data: 
   { application: {},
     id: '8888',
     script: 'http://192.168.0.21:8989/tick-scripts/event.test.js' },
  command: 'script' }
09:27:09.403/D: <debug>[139] - lastExecution: com.stardust.autojs.execution.LoopedBasedJavaScriptExecution@1
09:27:09.404/D: <debug>[139] - 脚本启动, engine = null
09:27:09.480/V: 开始运行[script.js]
09:27:14.534/D: <debug>[142] - i am running
09:27:19.550/D: <debug>[142] - i am running
09:27:24.555/D: <debug>[142] - i am running
09:27:29.562/D: <debug>[142] - i am running
09:27:34.564/D: <debug>[142] - i am running


拿到执行对象， 立马就拿不到engine

**Comment by aiselp** [comment]
开个新线程或使用定时器api，从各种奇怪的线程切换到与脚本关联的线程执行大概可以解决

**Comment by kkevsekk1** [comment]
默认有类似功能，连接编辑器那个，不用自己再实现一次



发送自我的盖乐世



-------- 原始信息 --------
发件人： hary ***@***.***>
日期: 2024/4/24 09:28 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] UI+websocket+ engines.execScript情况下， getEngine拿到空值 (Issue #899)


09:26:38.211/V: 开始运行[/storage/emulated/0/脚本/ticktaker/ticktaker.js]
09:26:52.429/D: [135] - 登录成功: { code: 0, msg: 'success', data: '1781914024397651969' }
09:26:52.432/D: [136] - 启动websocket...
09:26:52.668/D: [139] - 连接服务器成功 Response{protocol=http/1.1, code=101, message=, url=http://192.168.0.21:8082/sys/spider/ss/18899999993}<http://192.168.0.21:8082/sys/spider/ss/18899999993%7D>
09:27:09.392/D: [139] - 收到消息: { data:
{ application: {},
id: '8888',
script: 'http://192.168.0.21:8989/tick-scripts/event.test.js' },
command: 'script' }
09:27:09.403/D: [139] - lastExecution: ***@***.***
09:27:09.404/D: [139] - 脚本启动, engine = null
09:27:09.480/V: 开始运行[script.js]
09:27:14.534/D: [142] - i am running
09:27:19.550/D: [142] - i am running
09:27:24.555/D: [142] - i am running
09:27:29.562/D: [142] - i am running
09:27:34.564/D: [142] - i am running

拿到执行对象， 立马就拿不到engine

―
