### ISSUE TITLE
更改脚本文件夹路径之后。主页面加载不出来文件，还不必须重启一下，才行

### ISSUE THREAD

**Issue by fanlushuai** [kkevsekk1/AutoX#901]
![image](https://github.com/kkevsekk1/AutoX/assets/21078607/f74f3d2f-4a07-45a4-a185-a3fcacd854d4)
![image](https://github.com/kkevsekk1/AutoX/assets/21078607/ef1e137e-db28-4ea9-8fbf-7b6f2488bd09)

**Comment by cnbilinyj** [comment]
很正常，历史遗留问题嘛，毕竟是
这个软件是从Auto.js Pro改过来的，而原本的软件就有这个问题，其实吧就连最最基础的布局问题他都没有把原版软件的历史遗留给改正，比如我提出的这个问题： [ #893 ：新建项目的UI中，“项目路径”输入框应当为文本框，而软件中将其错误的设置为了数字框](https://github.com/kkevsekk1/AutoX/issues/893)
