### ISSUE TITLE
events.observeNotification();功能，在调试环境正常运行，打包后下载安装，运行报错

### ISSUE THREAD

**Issue by ZhongXiangXiang** [kkevsekk1/AutoX#903]
1. Autox.js 版本：6.6.0
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：一加10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用events.observeNotification();功能，在调试环境正常运行，打包后下载安装，运行报错
代码：
events.observeNotification();
events.onNotification(n => {
  const message = n.getText();
  log(111, message);

  setClip(message);
  toast(`已发送至剪切板`);
});

9. 报错日志（可选）：android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

10. 屏幕截图（可选）：
![f86a6f1ef2c82c0a36a1c01ac435be2](https://github.com/kkevsekk1/AutoX/assets/59525266/3a51314e-3499-4d27-b823-6e61e6cb0066)

**Comment by epiphyllum** [comment]
vivo x27 我也遇到这个问题。 
有知道是什么原因的不？

**Comment by epiphyllum** [comment]
我的是测试环境都无法observeNotification

**Comment by ZhongXiangXiang** [comment]
> 我的是测试环境都无法observeNotification

auto.js里的设置，点击允许读取通知，会看到auto.js和你打包安装的apk，打开允许就可以了

**Comment by zhuluquan** [comment]
> > 我的是测试环境都无法observeNotification
> 
> auto.js里的设置，点击允许读取通知，会看到auto.js和你打包安装的apk，打开允许就可以了

我也报错，请问老师，怎么解决
