### ISSUE TITLE
thread.start期的线程，程序退出都没结束，新写脚本使用threads.shutDownAll也还在运行。

### ISSUE THREAD

**Issue by JohnHubcr** [kkevsekk1/AutoX#904]
1. Autox.js 版本：6.6.0
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Harmony OS 4
4. Android 机型：华为noval 9
5. Android 系统类别：Harmony OS
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
thread.start的线程，程序退出都没结束，使用threads.shutDownAll,也还在运行。
重启手机才结束。

**Comment by aiselp** [comment]
提供一下能复现问题的代码

**Comment by qwweeapk** [comment]
"ui";
//代码过长就不展示
ui.开始按钮.on("click", () => {
    events.setKeyInterceptionEnabled("volume_up", true)
    events.observeKey();
    events.onKeyDown("volume_up", function (event) {
        threads.shutDownAll()
        floaty.closeAll()
        engines.stopAll()   
    });
    threads.start(function () {
        KONGZHITAI();
        threads.start(function () {
            ZTquanx()
        });
        gfwsg()   
        sleep(random(500, 1000))
        console.error("运行完成！！！！！！")
        console.clear()
        sleep(3000)
        threads.shutDownAll()
        floaty.closeAll()
    });
});

function gfwsg(){
    let 检测app = threads.start(function () {
        while (true) {
            FNAPP("米多剧点")
        }
    });
    let 检测广告 = threads.start(function () {
        while (true) {
            GBgb()
        }
    });
    sleep(10000)
    检测app.interrupt();
    检测广告.interrupt();
}
//代码过长举例
问题： 监听上键有时候能关闭主程序，有时不能，子线程是关不了的
      在函数gfwsg()中，检测app.interrupt()也停止不了子线程，

**Comment by aiselp** [comment]
你尝试一下示例代码中的线程启动和停止，并没有发现异常

**Comment by qwweeapk** [comment]
经过测试 ：示例代码中的线程启动和停止，没有异常
自己写的代码，在UI线程，有时正常，有时停止不了线程（正常运行没有问题，出问题的是上键停止）
6.5.8是没问题的 、       
上键停止使用的是        threads.shutDownAll()
                                     floaty.closeAll()
                                     engines.stopAll()
如果没有报错就可以停止掉   ，   出错会报     
{ JavaException: com.stardust.autojs.runtime.exception.ScriptInterruptedException: null
at /android_asset/modules/__globals__.js:16
at [remote]控制台:3670 (JDNB)
at [remote]控制台:838 (友邻剧场操作)
at [remote]控制台:562
﻿
fileName: '/android_asset/modules/__globals__.js',
lineNumber: 16 }           
报错就会出现， 继续运行（但是其中的一些子线程会被停止）

**Comment by qwweeapk** [comment]
另外还有一种情况
    let 检测app = threads.start(function () {
        while (true) {
            FNAPP("米多剧点")
        }
    });
    let 检测广告 = threads.start(function () {
        while (true) {
            GBgb()
        }
    });
    多个子程序使用
    检测app.interrupt();
    检测广告.interrupt();
    会出现只能关闭第一个线程，后面一个继续运行的BUG（和上面的一样，有时能关闭有时不能，一半一半）

**Comment by qwweeapk** [comment]
多次测试  发现了问题   函数中    sleep(random(zdsa, zxsa)) 不能使用，清楚后正常  6.5.6是没问题的 
function JDNB(kobp, komb, shux, koms, zdsa, zxsa, kond) {//文本点击
    try {
        if (kobp == 1) {
            let a = komb(shux).boundsInside(0, 0, device.width, device.height).visibleToUser().findOnce();
            if (a != null) {
                if (a.clickable() == true) {
                    a.click();
                } else {
                    let x11 = a.bounds().left;
                    let x22 = a.bounds().right;
                    let y11 = a.bounds().top;
                    let y22 = a.bounds().bottom;
                    let x = random(Math.floor(x11 + 3), Math.floor(x22 - 3));
                    let y = random(Math.floor(y11 + 3), Math.floor(y22 - 3));
                    let timedelay = random(50, 150);
                    press(x, y, timedelay);
                }
                console.log(SHIJIAN() + " " + koms);
                sleep(random(zdsa, zxsa))
                return true;
            }
        }
        if (kobp == 2) {
            let pukw = kond
            if (pukw) {
                let a = komb(shux).boundsInside(0, 0, device.width, device.height).visibleToUser().findOnce();
                if (a != null) {
                    if (a.clickable() == true) {
                        a.click();
                    } else {
                        let x11 = a.bounds().left;
                        let x22 = a.bounds().right;
                        let y11 = a.bounds().top;
                        let y22 = a.bounds().bottom;
                        let x = random(Math.floor(x11 + 3), Math.floor(x22 - 3));
                        let y = random(Math.floor(y11 + 3), Math.floor(y22 - 3));
                        let timedelay = random(50, 150);
                        press(x, y, timedelay);
                    }
                    console.log(SHIJIAN() + " " + koms);
                    sleep(random(zdsa, zxsa))
                    return true;
                }
            }
        }
    } catch (err) {
        log(err)
    }
}

**Comment by hinoTare** [comment]
我也遇到同样的问题，我在子线程中有一个死循环，当手动终止程序或、主线程异常或其他线程异常导致脚本停止，子线程有时候没有跟随主线程消亡，threads.shutDownAll() 和 Thread.interrupt()都无法结束子线程。我用了个笨办法，就是用Storages同步消息，一旦主线程停止，就会往Storages写入一条主线程停止的消息，子线程收到停止的消息时，就跳出循环，子线程无法终止的问题解决了。

**Comment by api-invoker** [comment]
我也有这个问题  子线程是个死循环   主线程exit()   threads.shutDownAll()  都调用了  子线程还在后台偷偷的运行着

**Comment by api-invoker** [comment]
> 我也遇到同样的问题，我在子线程中有一个死循环，当手动终止程序或、主线程异常或其他线程异常导致脚本停止，子线程有时候没有跟随主线程消亡，threads.shutDownAll() 和 Thread.interrupt()都无法结束子线程。我用了个笨办法，就是用Storages同步消息，一旦主线程停止，就会往Storages写入一条主线程停止的消息，子线程收到停止的消息时，就跳出循环，子线程无法终止的问题解决了。

是的  我也用类似的方式凑活着解决了

**Comment by yz1305777633** [comment]
我也遇到这个了，建议实例化对象，在里面做一成设计保证 能够停止掉

**Comment by fanlushuai** [comment]
真恶心

**Comment by Ryushane** [comment]
同遇到这个问题，脚本已经停止运行了，子线程依然在继续。
