### ISSUE TITLE
require导入网络文件问题

### ISSUE THREAD

**Issue by iamqiqi1017** [kkevsekk1/AutoX#907]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：require不支持直接请求网络文件吗？我看文档里面写的是支持请求网络文件的，实际上会报错module找不到，如果不支持网络文件的话，那么我应该怎么设计呢？我试过了在require的文件里面请求网络文件内容，然后再module.export出去，但是貌似不行
const fetchLatestUtils = () => {
    // 使用fetch或其他适合的方式从服务器上获取文件
   const result = http.get('http://******/jscode/logger.js')
  const script = result.body.string()
  eval(script)
  console.log('加载完毕')
}

fetchLatestUtils();

module.exports = {
  // 默认导出，可以在本地调用
  log(message) {
    console.log(message);
  },
};
8. 报错日志（可选）：

9. 屏幕截图（可选）：

**Comment by cnbilinyj** [comment]
`require`似乎并不支持请求网络文件，这边建议你是使用HTTP模块，进行网络请求，并且将网络模块文件下载至本地，然后导入

比较好的方法是这样：
``` JavaScript
files.write("modules/module.js", http.get("http://www.domain.com/modules/module.js").body.string());
requirt("modules/module")
```
