### ISSUE TITLE
runtime.loadDex  Function importClass must be called with a class; had "[JavaPackage xxx]" instead

### ISSUE THREAD

**Issue by DspringL** [kkevsekk1/AutoX#908]
1. Autox.js 版本：653
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米11
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：runtime.loadDex  Function importClass must be called with a class; had "[JavaPackage xxx]" instead
8. 报错日志（可选）：
9. 屏幕截图（可选）：

请问哪个版本可以动态加载dex，并调用类函数呢

**Comment by DspringL** [comment]
let dexPath = files.path('./core-3.3.0.dex')
console.log(dexPath)
runtime.loadDex(dexPath);
importPackage(com.google.zxing)
let fe = new Packages.ResultPoint(1,2)

TypeError: [JavaPackage ResultPoint] is not a function, it is object. ([remote]test2#6)
TypeError: [JavaPackage ResultPoint] is not a function, it is object.
    at [remote]test2:6:0

**Comment by DspringL** [comment]
let dexPath = files.path('./core-3.3.0.dex')
console.log(dexPath)
runtime.loadDex(dexPath);
//importPackage(com.google.zxing)
let fe = new com.google.zxing.ResultPoint(1,2)
//console.log(fe)
TypeError: [JavaPackage com.google.zxing.ResultPoint] is not a function, it is object. ([remote]test2#5)
TypeError: [JavaPackage com.google.zxing.ResultPoint] is not a function, it is object.

**Comment by DspringL** [comment]
let devPath = files.path('./core.dex')
let targetPath = '/storage/emulated/0/Download/core.dex'
files.copy(devPath,targetPath)
runtime.loadDex(targetPath);
importPackage(com.google.zxing);
importPackage(com.google.zxing.common);
console.log(StringUtils().ASSUME_SHIFT_JIS)

ReferenceError: "StringUtils" is not defined. ([remote]test2#7)
ReferenceError: "StringUtils" is not defined.
    at [remote]test2:7:0

**Comment by kkevsekk1** [comment]
这个包有别的依赖导致



发送自我的盖乐世



-------- 原始信息 --------
发件人： DspringL ***@***.***>
日期: 2024/5/7 19:38 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] runtime.loadDex Function importClass must be called with a class; had "[JavaPackage xxx]" instead (Issue #908)


let devPath = files.path('./core.dex')
let targetPath = '/storage/emulated/0/Download/core.dex'
files.copy(devPath,targetPath)
runtime.loadDex(targetPath);
importPackage(com.google.zxing);
importPackage(com.google.zxing.common);
console.log(StringUtils().ASSUME_SHIFT_JIS)

ReferenceError: "StringUtils" is not defined. ([remote]test2#7)
ReferenceError: "StringUtils" is not defined.
at [remote]test2:7:0

―

**Comment by DspringL** [comment]
都编译为jar包了，后转的dex了，有别的依赖那是在未编译阶段，都编译为.class文件了，下面为dex反编译的jar
![Uploading image.png…]()

**Comment by DspringL** [comment]
![image](https://github.com/kkevsekk1/AutoX/assets/29829184/03733201-ebea-4864-9c1c-7a2d295b9f29)
