### ISSUE TITLE
vscode连接手机如何debug 卡断点 单步调试

### ISSUE THREAD

**Issue by yuhengShii** [kkevsekk1/AutoX#909]
各位大佬们 ，想请教一下用vscode autox插件连接手机时，怎么卡断点 单步调试？

1. Autox.js 版本：660
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：鸿蒙4.2
4. Android 机型：小米10
5. Android 系统类别：鸿蒙
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by LiStone30** [comment]
同求！！！
