### ISSUE TITLE
device.getIMEI有BUG,下个版本更新时，请修改下！！！

### ISSUE THREAD

**Issue by helloworld8686** [kkevsekk1/AutoX#91]
device.java中修改内容如下
    @SuppressLint({"HardwareIds", "MissingPermission"})
    @Nullable
    public String getIMEI() {
        checkReadPhoneStatePermission();
//        try {
//            return ((TelephonyManager) mContext.getSystemService(Context.TELEPHONY_SERVICE)).getDeviceId();
//        } catch (SecurityException e) {
//            return null;
//        }
        String deviceId = null;
        TelephonyManager tm = (TelephonyManager) mContext.getSystemService(TELEPHONY_SERVICE);
        deviceId = tm.getDeviceId();
        if (TextUtils.isEmpty(deviceId)) {
            deviceId = Settings.System.getString(mContext.getContentResolver(), Settings.Secure.ANDROID_ID);
        }
        return deviceId;
    }

**Comment by kkevsekk1** [comment]
deviceId 有单独的接口 可以获取

**Comment by lnxcyq** [comment]
@kkevsekk1 老大，pro 7原作者已经停更了，能不能考虑把pro 7里面的一些功能移植一些过来呢，毕竟pro 7 有些功能很好

**Comment by kkevsekk1** [comment]
没看过 7  不知道 有些啥功能

**Comment by kkevsekk1** [comment]
你 觉得合适的可以直接 pr 上来 我们看看，合适 就合并

**Comment by helloworld8686** [comment]
@kkevsekk1 
js文件中
小米MIX2 device.getIMEI() 可以正常获取
华为P10 device.getIMEI() 取到的是null

**Comment by kkevsekk1** [comment]
android 10 以上版本 无法获取imei 只用用deviceid 代替，这是两个不同的东西

**Comment by helloworld8686** [comment]
@kkevsekk1 
android 10 以上版本 ，连接电脑的时候获取imei做了兼容，但是，device.getIMEI()   没做兼容！是否可以加兼容？
