### ISSUE TITLE
自动任务到时间后会一直重复创建
怀疑是使用过定时任务调度器，现在设置默认也没有用

### ISSUE THREAD

**Issue by NOWorEVER** [kkevsekk1/AutoX#911]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by LYS86** [comment]
AndroidJob会执行两次，用别的 #681
