### ISSUE TITLE
把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。

### ISSUE THREAD

**Issue by AlexanderDash** [kkevsekk1/AutoX#920]
1. Autox.js 版本：6.6.0
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米Civi3
5. Android 系统类别：MIUI14
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。除此之外，屏幕截图权限弹出的那个框弹出也会让autojs的悬浮图标消失
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
在电脑上搞，



发送自我的盖乐世



-------- 原始信息 --------
发件人： QwQ233 ***@***.***>
日期: 2024/5/14 02:23 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。 (Issue #920)


  1.  Autox.js 版本：6.6.0
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13
  4.  Android 机型：小米Civi3
  5.  Android 系统类别：MIUI14
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。除此之外，屏幕截图权限弹出的那个框弹出也会让autojs的悬浮图标消失
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by kkevsekk1** [comment]
用Python的那个分析布局的搞



发送自我的盖乐世



-------- 原始信息 --------
发件人： QwQ233 ***@***.***>
日期: 2024/5/14 02:23 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。 (Issue #920)


  1.  Autox.js 版本：6.6.0
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13
  4.  Android 机型：小米Civi3
  5.  Android 系统类别：MIUI14
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：把某个文件分享，然后系统级弹窗“分享给”出现，autojs的靠左边的悬浮图标直接消失了，怎么办？不能用布局分析我哭了。除此之外，屏幕截图权限弹出的那个框弹出也会让autojs的悬浮图标消失
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

―

**Comment by DspringL** [comment]
同问分析布局，python 使用什么分析呀

**Comment by DspringL** [comment]
谢谢老板
