### ISSUE TITLE
红米k70用不了，黑白闪屏

### ISSUE THREAD

**Issue by czh002** [kkevsekk1/AutoX#923]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：红米k70
5. Android 系统类别：澎湃
6. VSCODE Autox.js 扩展版本可选，如果是连接电脑的问题需要填）：
7. 问题描述：打开后，在应用内黑白来回闪
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by flymeqy** [comment]
是的，我也是

**Comment by flymeqy** [comment]
6.6.1的问题，6.6.0就没问题了

**Comment by czh002** [comment]
可以了
