### ISSUE TITLE
Releases 6.6.1发布错误

### ISSUE THREAD

**Issue by cyo57** [kkevsekk1/AutoX#924]
1. Autox.js 版本：661
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
7. 问题描述：releases中的apk为低版本且闪退无法运行

**Comment by paulrenfik** [comment]
crashes on Android 11

**Comment by HaoToo** [comment]
先用老版本 https://objects.githubusercontent.com/github-production-release-asset-2e65be/281414496/2820fe29-4117-412e-bbf6-2467d7c2bdb5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240517%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240517T091713Z&X-Amz-Expires=300&X-Amz-Signature=e525c0cef5b238d251a486d462abf91c61e98c37302a4615559724bc0a241468&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=281414496&response-content-disposition=attachment%3B%20filename%3DAutox-v6-universal-release-6.6.0.apk&response-content-type=application%2Fvnd.android.package-archive
