### ISSUE TITLE
setText和input不会触发App的input事件，希望增加脚本输入法，这个功能用的还是挺多的

### ISSUE THREAD

**Issue by qwe317149766** [kkevsekk1/AutoX#925]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by HaoToo** [comment]
加我微信 我送个脚本 输入 法你

**Comment by HaoToo** [comment]
HNCJTV
