### ISSUE TITLE
定时任务概率不自动执行，需要手动解锁

### ISSUE THREAD

**Issue by NOWorEVER** [kkevsekk1/AutoX#926]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米12
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

设置了定时任务，但是时间到了有概率不触发，需要手动解锁触发。

**Comment by Kiritocyz** [comment]
> 1. Autox.js 版本：629
> 2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
> 3. Android 版本：Android 13
> 4. Android 机型：小米12
> 5. Android 系统类别：MIUI
> 6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
> 7. 问题描述：
> 8. 报错日志（可选）：
> 9. 屏幕截图（可选）：
> 
> 设置了定时任务，但是时间到了有概率不触发，需要手动解锁触发。

这个怕是和系统的后台保活有关🤔

**Comment by NOWorEVER** [comment]
> 🤔

有点烦，所有清理后台都关了，睡眠学习也关了，自启动和电量不限制也开了，还是一样的情况，真的很崩溃

**Comment by wuxiemian** [comment]
可以提前一分钟定个闹铃，闹铃会亮屏，然后脚本里面关闭闹铃就行了

**Comment by songjiang951130** [comment]
> > 🤔
> 
> 有点烦，所有清理后台都关了，睡眠学习也关了，自启动和电量不限制也开了，还是一样的情况，真的很崩溃

我也遇到了，只有我手动解锁才执行脚本
