### ISSUE TITLE
无法启动，直接报错

### ISSUE THREAD

**Issue by haifding** [kkevsekk1/AutoX#927]
1. Autox.js 版本：661
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：鸿蒙4.0
4. Android 机型：华为M20X
5. Android 系统类别：鸿蒙
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：无法启动，直接报错

![微信图片_20240518202610](https://github.com/kkevsekk1/AutoX/assets/12177660/cbafac11-1887-4237-bc28-027f9831acbe)

[Log_20240518_201912.txt](https://github.com/kkevsekk1/AutoX/files/15363270/Log_20240518_201912.txt)

**Comment by bimo12138** [comment]
我是用 6.6.1 也报错了，退级到 6.6.0 即可
