### ISSUE TITLE
6.5.8版本，images.findMultiColors 方法报错

### ISSUE THREAD

**Issue by xiexiedaima** [kkevsekk1/AutoX#944]
1. Autox.js 版本：Autox-v6-universal-release-6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases/tag/6.5.8
3. Android 版本：鸿蒙4.0.0
4. Android 机型：华为 P30
5. Android 系统类别：鸿蒙 4.0.0
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：如果图片经过images.grayscale灰度处理，或者images.threshold二值化处理后，对处理过后的图片使用images.findMultiColors方法时，就会报错.
8. 报错日志：
```
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=3 (/android_asset/modules/__images__.js#397)
Wrapped java.lang.ArrayIndexOutOfBoundsException: length=1; index=3
    at /android_asset/modules/__images__.js:397:0
```
9. 我的代码
```
if(!requestScreenCapture()) {
    alert("请求截图失败");
    exit();
}
// 这里如果是把img传给images.findMultiColors就正常，把grayImg或者blackWhiteImg就报数组越界的错误
let  img = captureScreen();
let grayImg = images.grayscale(img);
let blackWhiteImg = images.threshold(grayImg, 128, 255);
images.findMultiColors(blackWhiteImg, '#ffffff', [
            [33, 0, "#f9f9f9"],
            [50, -1, "#f9f9f9"]
 ]);
```

**Comment by xiexiedaima** [comment]
翻了历史issue里有遇到和我一样的报错的，不过因为无活动已被机器人自动关闭，https://github.com/kkevsekk1/AutoX/issues/610

**Comment by LYS86** [comment]
好像是因为阀值后的图片是单通道。可以先保存到本地再读出来。
```
blackWhiteImg.saveTo(path)
blackWhiteImg=images.read(path)
```

**Comment by xiexiedaima** [comment]
> 好像是因为阀值后的图片是单通道。可以先保存到本地再读出来。
> 
> ```
> blackWhiteImg.saveTo(path)
> blackWhiteImg=images.read(path)
> ```

已解决，多谢
