### ISSUE TITLE
监测某个值的过程中会突然停止运行代码

### ISSUE THREAD

**Issue by wanqian-windrunner** [kkevsekk1/AutoX#945]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米12X
5. Android 系统类别：HyperOS 官改包
7. 问题描述：我写了一个脚本，其中有一个环节是停在一个页面，一直监测某个元素的数值直到到达某个上限然后执行下一段代码，我遇到的问题是在这个监测环节有的时候会突然停止运行代码，需要切到其他页面如桌面再切回来，然后才会立即继续执行代码。
8. 已经进行过的尝试：在代码停止后点击并滑动屏幕无法唤醒代码。
9. 执行的代码：
```Autoxjs
function 结束(距离){
  while (parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText()) <= (距离)) {
    log("还差："+(距离-parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText())).toFixed(2))
  }
  toast('结束');
  id("btn_finish").findOne().click();
  id("btn_confirm").findOne().click();
  sleep(10000)
}
```

**Comment by kkevsekk1** [comment]
是一直没找到，切出去回来才找到了



发送自我的盖乐世



-------- 原始信息 --------
发件人： wanqian-windrunner ***@***.***>
日期: 2024/5/22 20:58 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 监测某个值的过程中会突然停止运行代码 (Issue #945)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 14
  4.  Android 机型：小米12X
  5.  Android 系统类别：HyperOS 官改包
  6.  问题描述：我写了一个脚本，其中有一个环节是停在一个页面，一直监测某个元素的数值直到到达某个上限然后执行下一段代码，我遇到的问题是在这个监测环节有的时候会突然停止运行代码，需要切到其他页面如桌面再切回来，然后才会立即继续执行代码。
  7.  已经进行过的尝试：在代码停止后点击并滑动屏幕无法唤醒代码。
  8.  执行的代码：

function 结束(距离){
  while (parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText()) <= (距离)) {
    log("还差："+(距离-parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText())).toFixed(2))
  }
  toast('结束');
  id("btn_finish").findOne().click();
  id("btn_confirm").findOne().click();
  sleep(10000)
}


―

**Comment by kkevsekk1** [comment]
发送自我的盖乐世



-------- 原始信息 --------
发件人： wanqian-windrunner ***@***.***>
日期: 2024/5/22 20:58 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 监测某个值的过程中会突然停止运行代码 (Issue #945)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 14
  4.  Android 机型：小米12X
  5.  Android 系统类别：HyperOS 官改包
  6.  问题描述：我写了一个脚本，其中有一个环节是停在一个页面，一直监测某个元素的数值直到到达某个上限然后执行下一段代码，我遇到的问题是在这个监测环节有的时候会突然停止运行代码，需要切到其他页面如桌面再切回来，然后才会立即继续执行代码。
  7.  已经进行过的尝试：在代码停止后点击并滑动屏幕无法唤醒代码。
  8.  执行的代码：

function 结束(距离){
  while (parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText()) <= (距离)) {
    log("还差："+(距离-parseFloat(id("tv_distance").className("android.widget.TextView").depth(10).findOne().getText())).toFixed(2))
  }
  toast('结束');
  id("btn_finish").findOne().click();
  id("btn_confirm").findOne().click();
  sleep(10000)
}


―

**Comment by wanqian-windrunner** [comment]
感谢，核实了一下原来是这个原因，我试试OCR能不能解决这个问题
