### ISSUE TITLE
能不能升级一下 Rhino 版本

### ISSUE THREAD

**Issue by tang-butian** [kkevsekk1/AutoX#95]
升级Rhino 为最新版，支持更多的es6 语法

**Comment by kkevsekk1** [comment]
这个基础库很久没有更新了，最新版本 向下兼容 不？

**Comment by tang-butian** [comment]
这个不太清楚，但是可以试一下

**Comment by kkevsekk1** [comment]
你可以 fork 一个最新代码，升级一下这个包，先测试,没问题再 发个pr 上来，可以发布已 dev 版本

**Comment by ag2s20150909** [comment]
或者用quic js

**Comment by Aioure** [comment]
> 升级Rhino 为最新版，支持更多的es6 语法

已经升级，欢迎测试
