### ISSUE TITLE
官网打不开了，文档也看不了，希望作者大佬解决下💖

### ISSUE THREAD

**Issue by fanpeii** [kkevsekk1/AutoX#951]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：红米k40
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
莫慌



发送自我的盖乐世



-------- 原始信息 --------
发件人： fanpeii ***@***.***>
日期: 2024/5/26 20:49 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 官网打不开了，文档也看不了，希望作者大佬解决下💖 (Issue #951)


  1.  Autox.js 版本：629
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：红米k40
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  报错日志（可选）：
  9.  屏幕截图（可选）：

**Comment by xiaozhi-xmu** [comment]
文档打不开了，大佬麻烦看看

**Comment by EaxMov** [comment]
文档打不开了+1

**Comment by kkevsekk1** [comment]
好了吧



发送自我的盖乐世



-------- 原始信息 --------
发件人： Eax ***@***.***>
日期: 2024/5/27 00:08 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] 官网打不开了，文档也看不了，希望作者大佬解决下💖 (Issue #951)


文档打不开了+1

**Comment by fanpeii** [comment]
好了！大佬牛逼！
