### ISSUE TITLE
Thread can NOT be inuterrupted

### ISSUE THREAD

**Issue by MichaelLin0713** [kkevsekk1/AutoX#954]
1. Autox.js 版本：6.6.0
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 11
4. Android 机型：Samsung S22U
5. Android 系统类别：Stock ROM
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
    原本 threads.start後，可以使用threads.interrupt中斷thread.
但在目前6.6.0及更早的版本無法中斷thread.
6.3.7以前的版本一直都可以使用

**Comment by kkevsekk1** [comment]
天天加班，研究不了啊



发送自我的盖乐世



-------- 原始信息 --------
发件人： MichaelLin0713 ***@***.***>
日期: 2024/5/28 19:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] Thread can NOT be inuterrupted (Issue #954)


  1.  Autox.js 版本：6.6.0
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 11
  4.  Android 机型：Samsung S22U
  5.  Android 系统类别：Stock ROM
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
原本 threads.start後，可以使用threads.interrupt中thread.
但在目前6.6.0及更早的版本o法中thread.
6.3.7以前的版本一直都可以使用

―

**Comment by kkevsekk1** [comment]
刚刚测试了一下中断是有效果的啊，你是怎么处理的？



发送自我的盖乐世



-------- 原始信息 --------
发件人： MichaelLin0713 ***@***.***>
日期: 2024/5/28 19:32 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] Thread can NOT be inuterrupted (Issue #954)


  1.  Autox.js 版本：6.6.0
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 11
  4.  Android 机型：Samsung S22U
  5.  Android 系统类别：Stock ROM
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
原本 threads.start後，可以使用threads.interrupt中thread.
但在目前6.6.0及更早的版本o法中thread.
6.3.7以前的版本一直都可以使用

―

**Comment by MichaelLin0713** [comment]
在要畫floaty.rawWindows前
var ScriptName;

 在floaty.rawWindows裡 畫了一個button1
 w.btn1.click( () =>
 {
               ScriptName = threads.start( function()
                {
                    TestThread();
                });
 });

在floaty.rawWindows裡 畫了一個button2
w.btn2.click( () =>
{
               GlobalEvent.emit('exitScript', 0);
});

在floaty.rawWindows裡, 設了一個event去收
GlobalEvent.on('exitScript', function (Task)
{
               ScriptName.interrupt();                         //// <== 這裡不會報錯，但thread無法中斷，thead繼續跑
}

**Comment by MichaelLin0713** [comment]
在要畫floaty.rawWindows前
var ScriptName;

 在floaty.rawWindows裡 畫了一個button1
 w.btn1.click( () =>
 {
               ScriptName = threads.start( function()
                {
                    TestThread();
                });
 });

在floaty.rawWindows裡 畫了一個button2
w.btn2.click( () =>
{
               GlobalEvent.emit('exitScript', 0);
});

在floaty.rawWindows裡, 設了一個event去收
GlobalEvent.on('exitScript', function (Task)
{
               ScriptName.interrupt();                         //// <== 這裡不會報錯，但thread無法中斷，thead繼續跑
}

**Comment by MichaelLin0713** [comment]
經過一版版測試 6.5.6 都還正常

6.5.7 修复"emit"报错

但我原本script 用在UI上按下button 會使用GlobalEvent.emit, 然後GlobalEvent 就無法中斷thread

**Comment by kkevsekk1** [comment]
我感觉这是正常的哦，中断不会影响正在运行的线程。除非run方法中有识别中断。



发送自我的盖乐世



-------- 原始信息 --------
发件人： MichaelLin0713 ***@***.***>
日期: 2024/5/28 20:54 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： aaron ***@***.***>, Comment ***@***.***>
主题： Re: [kkevsekk1/AutoX] Thread can NOT be inuterrupted (Issue #954)


在要floaty.rawWindows前
var ScriptName;

在floaty.rawWindowse 了一button1
w.btn1.click( () =>
{
ScriptName = threads.start( function()
{
TestThread();
});
});

在floaty.rawWindowse 了一button2
w.btn2.click( () =>
{
GlobalEvent.emit('exitScript', 0);
});

在floaty.rawWindowse, O了一event去收
GlobalEvent.on('exitScript', function (Task)
{
ScriptName.interrupt(); //// <== @e不箦e，但threado法中啵thead^m跑
}

―
