### ISSUE TITLE
[error] can not use setTimeout function with websocket

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#96]
when using websocket, setTimeout function did not work.
for example:
```
...
myListener = {
    onOpen: function (webSocket, response) {
        console.log('run?'); // run ok!
        setTimeout(function () {console.log('run2?');} , 1000) ; // <--- never run, maybe some error here
        console.log('run again?'); // <-- not run!
    },
...
```

**Comment by anhnhoktvn** [comment]
I got an error:
```
JavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.stardust.autojs.core.looper.Timer.setTimeout(java.lang.Object, long, java.lang.Object[])' on a null object reference]
```

**Comment by kkevsekk1** [comment]
this is callback ，so can not use it as this!  and the setTimeOut is not same the setTimeOut of JavaScript，  you can do it like 
 interface of java

**Comment by anhnhoktvn** [comment]
Thank you for you reply. I don't have much experience with Java language. Most of my code can run in the websocket callback. Only the setTimeout and some floaty window functions can not run. It's much easier for me to run javascript code in the callback. Therefore, could I have a way to use javascript code in the websocket callback?
